In [1]:
import pandas as pd
train=pd.read_csv('/kaggle/input/icr-identify-age-related-conditions/train.csv')
train.head()

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
0,000ff2bfdfe9,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,...,7.298162,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1
1,007255e47698,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,...,0.173229,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0
2,013f2bd269f5,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,...,7.709560,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0
3,043ac50845d5,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,...,6.122162,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0
4,044fb8a146ec,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,...,8.153058,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1

In [2]:
test=pd.read_csv('/kaggle/input/icr-identify-age-related-conditions/test.csv')
test.head()

,Id,AB,AF,AH,AM,AR,AX,AY,AZ,BC,...,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL
0,00eed32682bb,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,010ebe33f668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,02fa521e1838,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,040e15f562a2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,046e85c7cc7f,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
train=train.drop(['Id'],axis=1)
train.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FL,FR,FS,GB,GE,GF,GH,GI,GL,Class
0,0.209377,3109.03329,85.200147,22.394407,8.138688,0.699861,0.025578,9.812214,5.555634,4126.58731,...,7.298162,1.73855,0.094822,11.339138,72.611063,2003.810319,22.136229,69.834944,0.120343,1
1,0.145282,978.76416,85.200147,36.968889,8.138688,3.632190,0.025578,13.517790,1.229900,5496.92824,...,0.173229,0.49706,0.568932,9.292698,72.611063,27981.562750,29.135430,32.131996,21.978000,0
2,0.470030,2635.10654,85.200147,32.360553,8.138688,6.732840,0.025578,12.824570,1.229900,5135.78024,...,7.709560,0.97556,1.198821,37.077772,88.609437,13676.957810,28.022851,35.192676,0.196941,0
3,0.252107,3819.65177,120.201618,77.112203,8.138688,3.685344,0.025578,11.053708,1.229900,4169.67738,...,6.122162,0.49706,0.284466,18.529584,82.416803,2094.262452,39.948656,90.493248,0.155829,0
4,0.380297,3733.04844,85.200147,14.103738,8.138688,3.942255,0.054810,3.396778,102.151980,5728.73412,...,8.153058,48.50134,0.121914,16.408728,146.109943,8524.370502,45.381316,36.262628,0.096614,1

In [4]:
test=test.drop(['Id'],axis=1)
test.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
def reduce_mem_usage(df):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.        
    """
    start_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            df[col] = df[col].astype('object')

    end_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

In [6]:
import numpy as np
train = reduce_mem_usage(train)
train.info()

Memory usage of dataframe is 0.27 MB
Memory usage after optimization is: 0.07 MB
Decreased by 72.6%
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 617 entries, 0 to 616
Data columns (total 57 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AB      617 non-null    float16
 1   AF      617 non-null    float16
 2   AH      617 non-null    float16
 3   AM      617 non-null    float16
 4   AR      617 non-null    float16
 5   AX      617 non-null    float16
 6   AY      617 non-null    float16
 7   AZ      617 non-null    float16
 8   BC      617 non-null    float16
 9   BD      617 non-null    float16
 10  BN      617 non-null    float16
 11  BP      617 non-null    float16
 12  BQ      557 non-null    float16
 13  BR      617 non-null    float32
 14  BZ      617 non-null    float16
 15  CB      615 non-null    float16
 16  CC      614 non-null    float16
 17  CD      617 non-null    float16
 18  CF      617 non-null    float16
 19  CH      617 non-null    float16
 20  CL      617 non-null    float16
 21  CR      617 non-null    float16
 22  CS      617 non-null    float16
 23  CU      617 non-null    float16
 24  CW      617 non-null    float16
 25  DA      617 non-null    float16
 26  DE      617 non-null    float16
 27  DF      617 non-null    float16
 28  DH      617 non-null    float16
 29  DI      617 non-null    float16
 30  DL      617 non-null    float16
 31  DN      617 non-null    float16
 32  DU      616 non-null    float16
 33  DV      617 non-null    float16
 34  DY      617 non-null    float16
 35  EB      617 non-null    float16
 36  EE      617 non-null    float16
 37  EG      617 non-null    float16
 38  EH      617 non-null    float16
 39  EJ      617 non-null    object
 40  EL      557 non-null    float16
 41  EP      617 non-null    float16
 42  EU      617 non-null    float16
 43  FC      616 non-null    float16
 44  FD      617 non-null    float16
 45  FE      617 non-null    float32
 46  FI      617 non-null    float16
 47  FL      616 non-null    float16
 48  FR      617 non-null    float16
 49  FS      615 non-null    float16
 50  GB      617 non-null    float16
 51  GE      617 non-null    float16
 52  GF      617 non-null    float32
 53  GH      617 non-null    float16
 54  GI      617 non-null    float16
 55  GL      616 non-null    float16
 56  Class   617 non-null    int8
dtypes: float16(52), float32(3), int8(1), object(1)
memory usage: 75.4+ KB

In [7]:
test = reduce_mem_usage(test)
test.info()

Memory usage of dataframe is 0.00 MB
Memory usage after optimization is: 0.00 MB
Decreased by 69.7%
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AB      5 non-null      float16
 1   AF      5 non-null      float16
 2   AH      5 non-null      float16
 3   AM      5 non-null      float16
 4   AR      5 non-null      float16
 5   AX      5 non-null      float16
 6   AY      5 non-null      float16
 7   AZ      5 non-null      float16
 8   BC      5 non-null      float16
 9   BD      5 non-null      float16
 10  BN      5 non-null      float16
 11  BP      5 non-null      float16
 12  BQ      5 non-null      float16
 13  BR      5 non-null      float16
 14  BZ      5 non-null      float16
 15  CB      5 non-null      float16
 16  CC      5 non-null      float16
 17  CD      5 non-null      float16
 18  CF      5 non-null      float16
 19  CH      5 non-null      float16
 20  CL      5 non-null      float16
 21  CR      5 non-null      float16
 22  CS      5 non-null      float16
 23  CU      5 non-null      float16
 24  CW      5 non-null      float16
 25  DA      5 non-null      float16
 26  DE      5 non-null      float16
 27  DF      5 non-null      float16
 28  DH      5 non-null      float16
 29  DI      5 non-null      float16
 30  DL      5 non-null      float16
 31  DN      5 non-null      float16
 32  DU      5 non-null      float16
 33  DV      5 non-null      float16
 34  DY      5 non-null      float16
 35  EB      5 non-null      float16
 36  EE      5 non-null      float16
 37  EG      5 non-null      float16
 38  EH      5 non-null      float16
 39  EJ      5 non-null      object
 40  EL      5 non-null      float16
 41  EP      5 non-null      float16
 42  EU      5 non-null      float16
 43  FC      5 non-null      float16
 44  FD      5 non-null      float16
 45  FE      5 non-null      float16
 46  FI      5 non-null      float16
 47  FL      5 non-null      float16
 48  FR      5 non-null      float16
 49  FS      5 non-null      float16
 50  GB      5 non-null      float16
 51  GE      5 non-null      float16
 52  GF      5 non-null      float16
 53  GH      5 non-null      float16
 54  GI      5 non-null      float16
 55  GL      5 non-null      float16
dtypes: float16(55), object(1)
memory usage: 718.0+ bytes

In [8]:
col=train.columns.tolist()
col.remove('Class')
col[:5]

['AB', 'AF', 'AH', 'AM', 'AR']

In [9]:
y = train[['Class']]
X = train[col]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42,shuffle=True, stratify=y)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [11]:
params={'n_estimators': 97, 'num_leaves': 33, 'min_child_samples': 8, 
        'learning_rate': 0.3848454051107216, 'log_max_bin': 9, 'colsample_bytree': 1.0,
        'reg_alpha': 0.002010966076190542, 'reg_lambda': 0.3138652985500363}

In [12]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [13]:
X_train['EJ'] = label_encoder.fit_transform(X_train['EJ'])
X_train.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL
99,0.170898,1549.0,85.1875,14.484375,8.140625,5.765625,0.049927,9.562500,5.898438,5488.0,...,10.546875,0.173218,2.009766,0.717773,19.890625,281.5000,14301.991211,26.812500,101.937500,21.984375
256,0.538574,4888.0,108.5625,7.003906,8.140625,5.933594,0.073059,8.898438,14.257812,2706.0,...,9.851562,0.173218,0.497070,0.169312,15.671875,72.6250,1180.078979,23.671875,9.445312,21.984375
577,0.217896,2498.0,85.1875,19.125000,8.140625,3.560547,0.109619,7.746094,3.542969,3972.0,...,10.976562,0.173218,0.497070,0.067749,11.617188,72.6250,11234.645508,35.656250,26.250000,21.984375
76,0.645020,5652.0,100.5625,269.000000,30.609375,4.289062,0.025574,11.281250,1.229492,4996.0,...,7.992188,18.640625,0.815430,0.128662,16.453125,108.6875,690.313416,29.171875,151.375000,0.002405
599,1.106445,3280.0,118.7500,48.656250,8.140625,8.210938,0.025574,9.992188,1.229492,6704.0,...,16.687500,0.434326,1.140625,1.713867,20.859375,72.6250,13738.932617,43.187500,21.656250,1.566406

In [14]:
X_test['EJ'] = label_encoder.transform(X_test['EJ'])
X_test.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL
569,0.136719,2688.0,85.1875,8.156250,8.140625,4.328125,0.030457,7.058594,1.229492,3482.0,...,14.601562,1.801758,0.497070,0.860352,11.093750,72.6250,18119.689453,23.703125,96.12500,10.101562
67,0.375977,3354.0,85.1875,14.984375,8.140625,6.832031,0.025574,15.109375,4.925781,6480.0,...,11.171875,6.511719,2.119141,0.067749,32.000000,90.9375,14322.419922,39.812500,16.37500,0.143555
566,0.337646,2176.0,399.2500,9.000000,8.367188,3.507812,0.025574,15.531250,1.229492,4968.0,...,9.671875,0.173218,0.497070,0.176147,34.843750,72.6250,17344.292969,35.593750,80.81250,21.984375
229,1.042969,2808.0,94.6875,36.468750,38.000000,6.953125,0.025574,13.835938,4.425781,3820.0,...,7.492188,0.173218,3.248047,0.067749,44.562500,116.4375,134409.531250,35.187500,128.62500,21.984375
121,1.140625,1649.0,170.3750,59.562500,10.546875,8.718750,0.151001,10.273438,8.351562,8128.0,...,10.703125,14.281250,1.526367,0.568848,20.703125,72.6250,14796.294922,44.125000,33.71875,0.079590

In [15]:
test['EJ'] = label_encoder.transform(test['EJ'])
test.head()

,AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD,...,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
import lightgbm as lgbm
model = lgbm.LGBMClassifier(learning_rate=0.3848454051107216, max_bin=511,
               min_child_samples=8, n_estimators=97, num_leaves=33,
               reg_alpha=0.002010966076190542, reg_lambda=0.3138652985500363,
               verbose=-1)
model.fit(X_train, y_train)

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

LGBMClassifier(learning_rate=0.3848454051107216, max_bin=511,
               min_child_samples=8, n_estimators=97, num_leaves=33,
               reg_alpha=0.002010966076190542, reg_lambda=0.3138652985500363,
               verbose=-1)

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_train, model.predict(X_train)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       407
           1       1.00      1.00      1.00        86

    accuracy                           1.00       493
   macro avg       1.00      1.00      1.00       493
weighted avg       1.00      1.00      1.00       493

In [18]:
print(classification_report(y_test, model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95       102
           1       0.83      0.68      0.75        22

    accuracy                           0.92       124
   macro avg       0.88      0.83      0.85       124
weighted avg       0.92      0.92      0.92       124

In [19]:
sample_submission = pd.read_csv('/kaggle/input/icr-identify-age-related-conditions/sample_submission.csv')
sample_submission.head()

             Id  class_0  class_1
0  00eed32682bb      0.5      0.5
1  010ebe33f668      0.5      0.5
2  02fa521e1838      0.5      0.5
3  040e15f562a2      0.5      0.5
4  046e85c7cc7f      0.5      0.5

In [20]:
model.predict_proba(test)

array([[0.91067741, 0.08932259],
       [0.91067741, 0.08932259],
       [0.91067741, 0.08932259],
       [0.91067741, 0.08932259],
       [0.91067741, 0.08932259]])

In [21]:
sample_submission['class_1'] = model.predict_proba(test)[:,1]
sample_submission['class_0'] = 1-model.predict_proba(test)[:,1]
sample_submission.to_csv("./submission.csv", index=False)
sample_submission.head()

             Id   class_0   class_1
0  00eed32682bb  0.910677  0.089323
1  010ebe33f668  0.910677  0.089323
2  02fa521e1838  0.910677  0.089323
3  040e15f562a2  0.910677  0.089323
4  046e85c7cc7f  0.910677  0.089323