# **Setup**

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor

# **Import Data**

In [2]:
iowa_file_path_train = '../input/home-data-for-ml-course/train.csv'
iowa_file_path_test = '../input/home-data-for-ml-course/test.csv'

home_data_train = pd.read_csv(iowa_file_path_train)
home_data_test = pd.read_csv(iowa_file_path_test)

# **Feature Selection**

* First score 29114.34659
* Used Feature MSSubClass - Score Improved by 320.83265 to 28793.51394
* Used Feature MSZoning - Score Improved by 1101.71879 to 27691.79515
* Used Feature LotFrontage - Scrore Reduced by -2101.89712 - Feature Removed
* Removed Feature LotArea - Score Reduced by -760.82762 - Feature Added
* Used Features OverallCond, OverallQual - Score Improved by 1302.89712 to 26388.89803
* Used Features LowQualFinSF, GrLivArea, HalfBath - Scrore Improved by 879.31825 to 25509.57978
* Used Features OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, MoSold, YrSold - Score Improved by 224.73891 to 25284.84087
* Used Feature TotalBsmtSF - Score Improved by 403.27846 to 24881.56241
* Used Feature BldgType - Score Reduced by -897.42524 - Feature Removed

* Used RandomForestRegressor instead of DecisionTreeRegressor
* Used Features YearRemodAdd,KitchenAbvGr,Fireplaces,WoodDeckSF,PoolArea,MiscVal - Improved Score by 245.78811 to 17469.0593

In [3]:
feature_names = ["MSSubClass", "MSZoning", "LotArea", "OverallQual", "OverallCond", "YearBuilt","1stFlrSF","2ndFlrSF"
                 ,"LowQualFinSF", "TotalBsmtSF", "GrLivArea","FullBath", "HalfBath","BedroomAbvGr","TotRmsAbvGrd"
                 ,"OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch","MoSold", "YrSold",'YearRemodAdd'
                 ,'KitchenAbvGr','Fireplaces','WoodDeckSF','PoolArea','MiscVal','LotFrontage','Street','LandContour'
                 ,'Alley','Neighborhood']

# **Feature Engineering**

In [4]:
def fill_missing_ex(df):
    for column in df:
        if df[column].dtype == 'int64':
            df[column].fillna(0, inplace = True)
        elif df[column].dtype == 'float64':
            df[column].fillna(0.0, inplace = True)
        else:
            df[column].fillna('U', inplace = True)
    return df

fill_missing_ex(home_data_train)
fill_missing_ex(home_data_test)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,U,Reg,Lvl,AllPub,...,120,0,U,MnPrv,U,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,U,IR1,Lvl,AllPub,...,0,0,U,U,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,U,IR1,Lvl,AllPub,...,0,0,U,MnPrv,U,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,U,IR1,Lvl,AllPub,...,0,0,U,U,U,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,U,IR1,HLS,AllPub,...,144,0,U,U,U,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,U,Reg,Lvl,AllPub,...,0,0,U,U,U,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,U,Reg,Lvl,AllPub,...,0,0,U,U,U,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,U,Reg,Lvl,AllPub,...,0,0,U,U,U,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,U,Reg,Lvl,AllPub,...,0,0,U,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,U,Reg,Lvl,AllPub,...,0,0,U,U,U,0,11,2006,WD,Normal

In [5]:
from sklearn import preprocessing

def encode_features(df):
    le = preprocessing.LabelEncoder()
    for column in df:
        if df[column].dtype == 'object':
            le.fit(df[column])
            df[column] = le.transform(df[column])
    return df

encode_features(home_data_train)
encode_features(home_data_test)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,80.0,11622,1,2,3,3,0,...,120,0,2,2,3,0,6,2010,9,4
1,1462,20,3,81.0,14267,1,2,0,3,0,...,0,0,2,4,0,12500,6,2010,9,4
2,1463,60,3,74.0,13830,1,2,0,3,0,...,0,0,2,2,3,0,3,2010,9,4
3,1464,60,3,78.0,9978,1,2,0,3,0,...,0,0,2,4,3,0,6,2010,9,4
4,1465,120,3,43.0,5005,1,2,0,1,0,...,144,0,2,4,3,0,1,2010,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,4,21.0,1936,1,2,3,3,0,...,0,0,2,4,3,0,6,2006,9,4
1455,2916,160,4,21.0,1894,1,2,3,3,0,...,0,0,2,4,3,0,4,2006,9,0
1456,2917,20,3,160.0,20000,1,2,3,3,0,...,0,0,2,4,3,0,9,2006,9,0
1457,2918,85,3,62.0,10441,1,2,3,3,0,...,0,0,2,2,2,700,7,2006,9,4
1458,2919,60,3,74.0,9627,1,2,3,3,0,...,0,0,2,4,3,0,11,2006,9,4

# **Build Model**

In [6]:
X = home_data_train[feature_names]
X_test = home_data_test[feature_names]

In [7]:
y = home_data_train.SalePrice

In [8]:
iowa_model = GradientBoostingRegressor(random_state = 1)

iowa_model.fit(X,y)

GradientBoostingRegressor(random_state=1)

# **Model Validation**

In [9]:
predictions = iowa_model.predict(X)
y_train = np.array(predictions).tolist()
y_train = pd.DataFrame(y_train)
y_train.columns = ['SalePrice']

In [10]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(y, y_train)

12590.663031047465

# **Predict Target Sale Price**

In [11]:
predictions = iowa_model.predict(X_test)

In [12]:
df = home_data_test[['Id']]

y_test = np.array(predictions).tolist()
y_test = pd.DataFrame(y_test)
y_test.columns = ['SalePrice']

final_prediction = pd.concat([df, pd.DataFrame(y_test)], axis=1)

# **Submit Entry**

In [13]:
final_prediction.to_csv("./submission.csv",index=False)