In [1]:
import numpy as np
import os
import pandas as pd

In [2]:
train_data = pd.read_csv("/kaggle/input/titanic/train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
test_data = pd.read_csv("/kaggle/input/titanic/test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
train_data.info()
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [5]:
train_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
combine = [train_data, test_data]
print(train_data.columns.values)

#categorical -  Survived, Sex, and Embarked
#ordinal - Pclass
#continuous -  Age, Fare. 
#discrete: SibSp, Parch.

['PassengerId' 'Survived' 'Pclass' 'Name' 'Sex' 'Age' 'SibSp' 'Parch'
 'Ticket' 'Fare' 'Cabin' 'Embarked']

In [7]:
#can drop this column - many missing values
train_data['Cabin'].isna(). sum() 
# dont need name, ticket,

687

In [8]:
train_data['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

Correlate. Complete. Correct.

In [9]:

train_data.corr()['Survived']
#drop passengerID - not needed

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Age           -0.077221
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Name: Survived, dtype: float64

In [10]:
train_data[['Pclass', 'Survived']].groupby(['Pclass'], as_index=False).mean().sort_values(by='Survived', ascending=False)

#keep as better class = more survival rate

   Pclass  Survived
0       1  0.629630
1       2  0.472826
2       3  0.242363

In [11]:
train_data['age_group'] = pd.cut(train_data['Age'], 4)

train_data[['age_group', 'Survived']].groupby(['age_group'], as_index=False).count().sort_values(by='Survived', ascending=True)

         age_group  Survived
3   (60.105, 80.0]        22
2  (40.21, 60.105]       128
0   (0.34, 20.315]       179
1  (20.315, 40.21]       385

In [12]:
for dataset in combine:
    dataset.loc[ dataset['Age'].isna(), 'Age'] = 0
    dataset.loc[ dataset['Age'] <= 20, 'Age'] = 0
    dataset.loc[(dataset['Age'] > 20) & (dataset['Age'] <= 40), 'Age'] = 1
    dataset.loc[(dataset['Age'] > 40) & (dataset['Age'] <= 60), 'Age']   = 2
    dataset.loc[ dataset['Age'] > 60, 'Age'] = 3
    dataset['Age'] = dataset['Age'].astype(int)

In [13]:
train_data['FareBand'] = pd.qcut(train_data['Fare'], 4)
train_data[['FareBand', 'Survived']].groupby(['FareBand'], as_index=False).count().sort_values(by='FareBand', ascending=True)

          FareBand  Survived
0   (-0.001, 7.91]       223
1   (7.91, 14.454]       224
2   (14.454, 31.0]       222
3  (31.0, 512.329]       222

In [14]:
for dataset in combine:
    dataset.loc[ dataset['Fare'].isna(), 'Fare'] = 0
    dataset.loc[ dataset['Fare'] <= 7.91, 'Fare'] = 0
    dataset.loc[(dataset['Fare'] > 7.91) & (dataset['Fare'] <= 14.454), 'Fare'] = 1
    dataset.loc[(dataset['Fare'] > 14.454) & (dataset['Fare'] <= 31), 'Fare']   = 2
    dataset.loc[ dataset['Fare'] > 31, 'Fare'] = 3
    dataset['Fare'] = dataset['Fare'].astype(int)

In [15]:
train_data[['Sex', 'Survived']].groupby(['Sex'], as_index=False).mean().sort_values(by='Survived', ascending=False)

      Sex  Survived
0  female  0.742038
1    male  0.188908

In [16]:
#siblings/spouse aboard

train_data[["SibSp", "Survived"]].groupby(['SibSp'], as_index=False).mean().sort_values(by='Survived', ascending=False)

   SibSp  Survived
1      1  0.535885
2      2  0.464286
0      0  0.345395
3      3  0.250000
4      4  0.166667
5      5  0.000000
6      8  0.000000

In [17]:
# parents / children

train_data[["Parch", "Survived"]].groupby(['Parch'], as_index=False).mean().sort_values(by='Survived', ascending=False)

   Parch  Survived
3      3  0.600000
1      1  0.550847
2      2  0.500000
0      0  0.343658
5      5  0.200000
4      4  0.000000
6      6  0.000000

In [18]:
train_data = train_data.drop(['Name','Ticket', 'Cabin'], axis=1)
test_data = test_data.drop(['Name','Ticket', 'Cabin'], axis=1)
combine = [train_data, test_data]

In [19]:
for dataset in combine:
    dataset['Sex'] = dataset['Sex'].map( {'female': 1, 'male': 0} ).astype(int)

In [20]:
freq_port = train_data.Embarked.dropna().mode()[0]
freq_port

for dataset in combine:
    dataset['Embarked'] = dataset['Embarked'].fillna(freq_port)
    
train_data[['Embarked', 'Survived']].groupby(['Embarked'], as_index=False).mean().sort_values(by='Survived', ascending=False)

  Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.339009

In [21]:
for dataset in combine:
    dataset['Embarked'] = dataset['Embarked'].map( {'S': 0, 'C': 1, 'Q': 2} ).astype(int)

In [22]:
train_data.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,age_group,FareBand
0,1,0,3,0,1,1,0,0,0,"(20.315, 40.21]","(-0.001, 7.91]"
1,2,1,1,1,1,1,0,3,1,"(20.315, 40.21]","(31.0, 512.329]"
2,3,1,3,1,1,0,0,1,0,"(20.315, 40.21]","(7.91, 14.454]"
3,4,1,1,1,1,1,0,3,0,"(20.315, 40.21]","(31.0, 512.329]"
4,5,0,3,0,1,0,0,1,0,"(20.315, 40.21]","(7.91, 14.454]"

In [23]:
test_data.head()

   PassengerId  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0          892       3    0    1      0      0     0         2
1          893       3    1    2      1      0     0         0
2          894       2    0    3      0      0     1         2
3          895       3    0    1      0      0     1         0
4          896       3    1    1      1      1     1         0

In [24]:
x_test = test_data.drop(['PassengerId'],axis = 1)
x_test.head()

   Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0       3    0    1      0      0     0         2
1       3    1    2      1      0     0         0
2       2    0    3      0      0     1         2
3       3    0    1      0      0     1         0
4       3    1    1      1      1     1         0

In [25]:
train_data = train_data.drop(['age_group','FareBand'], axis=1)

In [26]:
train_data.head()

   PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0            1         0       3    0    1      1      0     0         0
1            2         1       1    1    1      1      0     3         1
2            3         1       3    1    1      0      0     1         0
3            4         1       1    1    1      1      0     3         0
4            5         0       3    0    1      0      0     1         0

In [27]:
x_train = train_data.drop(['Survived', 'PassengerId'], axis = 1)
x_train

     Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0         3    0    1      1      0     0         0
1         1    1    1      1      0     3         1
2         3    1    1      0      0     1         0
3         1    1    1      1      0     3         0
4         3    0    1      0      0     1         0
..      ...  ...  ...    ...    ...   ...       ...
886       2    0    1      0      0     1         0
887       1    1    0      0      0     2         0
888       3    1    0      1      2     2         0
889       1    0    1      0      0     2         1
890       3    0    1      0      0     0         2

[891 rows x 7 columns]

In [28]:
y_train = train_data['Survived']
y_train

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [29]:
x_train.shape, y_train.shape, x_test.shape

((891, 7), (891,), (418, 7))

In [30]:
#Random forest
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators = 100)

random_forest.fit(x_train,y_train)
y_pred1 = random_forest.predict(x_test)

acc_random_forest = round(random_forest.score(x_train, y_train) * 100, 2)
acc_random_forest

88.44

In [31]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train,y_train)

y_pred2 = decision_tree.predict(x_test)
acc_decision_tree = round(decision_tree.score(x_train,y_train) * 100, 2)
acc_decision_tree

88.44

In [32]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train,y_train)

y_pred3 = svc.predict(x_test)
acc_svc = round(svc.score(x_train,y_train)*100,2)
acc_svc

82.15

In [33]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': y_pred1})
output.to_csv('submission_final.csv', index=False)