In [1]:
## libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import os
from copy import deepcopy
from functools import partial
import random
import gc

# Import sklearn classes for model selection, cross validation, and performance evaluation
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.metrics import roc_auc_score, accuracy_score, log_loss
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import seaborn as sns
from category_encoders import OneHotEncoder, OrdinalEncoder, CountEncoder
from imblearn.under_sampling import RandomUnderSampler

# Import libraries for Hypertuning
import optuna

# Import libraries for gradient boosting
import xgboost as xgb
import lightgbm as lgb
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier, GradientBoostingClassifier, AdaBoostClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.impute import KNNImputer
from sklearn.pipeline import Pipeline
from sklearn.svm import NuSVC, SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from catboost import CatBoost, CatBoostRegressor, CatBoostClassifier
from catboost import Pool

# Suppress warnings
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

## EDA

In [3]:
filepath = '/kaggle/input/icr-identify-age-related-conditions/'
df_train = pd.read_csv(os.path.join(filepath, 'train.csv'), index_col=[0])
df_test = pd.read_csv(os.path.join(filepath, 'test.csv'), index_col=[0])
greeks = pd.read_csv(f'{filepath}greeks.csv')

df_train['EJ'] = df_train['EJ'].replace({'A': 0, 'B': 1})
df_test['EJ']  = df_test['EJ'].replace({'A': 0, 'B': 1})

data = pd.concat([df_train, greeks.set_index('Id')], axis=1)
target_col = 'Class'

## Prepare train and test sets

In [4]:
df_train = pd.read_csv(os.path.join(filepath, 'train.csv'), index_col=[0])
df_test = pd.read_csv(os.path.join(filepath, 'test.csv'), index_col=[0])
df_train['EJ'] = df_train['EJ'].replace({'A': 0, 'B': 1})
df_test['EJ']  = df_test['EJ'].replace({'A': 0, 'B': 1})
target_col = 'Class'

X_train = df_train.drop([f'{target_col}'],axis=1).reset_index(drop=True)
y_train = df_train[f'{target_col}'].reset_index(drop=True)
X_test = df_test.reset_index(drop=True)

drop_cols = ['BC', 'CL']
X_train.drop(drop_cols, axis=1, inplace=True)
X_test.drop(drop_cols, axis=1, inplace=True)

numeric_columns = [_ for _ in X_train.columns if _ not in ['EJ']]
sc = StandardScaler() # MinMaxScaler or StandardScaler
X_train[numeric_columns] = sc.fit_transform(X_train[numeric_columns])
X_test[numeric_columns] = sc.transform(X_test[numeric_columns])

print(f"X_train shape :{X_train.shape} , y_train shape :{y_train.shape}")
print(f"X_test shape :{X_test.shape}")

# Delete the train and test dataframes to free up memory
del df_train, df_test

X_train.head(5)

X_train shape :(617, 54) , y_train shape :(617,)
X_test shape :(5, 54)

,AB,AF,AH,AM,AR,AX,AY,AZ,BD,BN,...,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL
0,-0.572153,-0.170975,-0.261669,-0.237889,-0.189295,-1.900558,-0.083417,-0.173502,-0.405383,0.339209,...,-2.226608,0.162355,-0.035806,-0.250462,-0.940094,-0.410260,-0.655511,-0.948991,0.531241,-0.815091
1,-0.709105,-1.097801,-0.261669,-0.028701,-0.189295,-0.750457,-0.083417,0.678919,0.048541,-0.575174,...,0.084542,-0.457909,-0.060566,0.113034,-1.145070,-0.410260,0.687893,-0.238862,-0.509218,1.303181
2,-0.015212,-0.377169,-0.261669,-0.094845,-0.189295,0.465662,-0.083417,0.519453,-0.071089,1.456789,...,0.517060,0.198170,-0.051023,0.595966,1.637944,-0.299210,-0.051850,-0.351743,-0.424754,-0.807668
3,-0.480851,0.138196,0.012347,0.547477,-0.189295,-0.729610,-0.083417,0.112088,-0.391109,0.644004,...,1.617160,0.059978,-0.060566,-0.105064,-0.219883,-0.342195,-0.650833,0.858232,1.101332,-0.811652
4,-0.206946,0.100517,-0.261669,-0.356885,-0.189295,-0.628845,-0.013229,-1.649292,0.125327,0.745602,...,1.212850,0.236779,0.896815,-0.229691,-0.432313,0.099920,-0.318309,1.409422,-0.395228,-0.817391

## Define Model

In [5]:
class Splitter:
    def __init__(self, kfold=True, n_splits=5, greeks=pd.DataFrame()):
        self.n_splits = n_splits
        self.kfold = kfold
        self.greeks = greeks

    def split_data(self, X, y, random_state_list):
        if self.kfold == 'skf':
            for random_state in random_state_list:
                kf = StratifiedKFold(n_splits=self.n_splits, random_state=random_state, shuffle=True)
                for train_index, val_index in kf.split(X, y):
                    if type(X) is np.ndarray:
                        X_train, X_val = X[train_index], X[val_index]
                        y_train, y_val = y[train_index], y[val_index]
                    else:
                        X_train, X_val = X.iloc[train_index], X.iloc[val_index]
                        y_train, y_val = y.iloc[train_index], y.iloc[val_index]
                    yield X_train, X_val, y_train, y_val
        else:
            raise ValueError(f"Invalid kfold: Must be True")

class Classifier:
    def __init__(self, n_estimators=100, device="cpu", random_state=0):
        self.n_estimators = n_estimators
        self.device = device
        self.random_state = random_state
        self.models = self._define_model()
        self.models_name = list(self._define_model().keys())
        self.len_models = len(self.models)
        
    def _define_model(self):
        
        xgb_params = {
            'n_estimators': self.n_estimators,
            'learning_rate': 0.413327571405248,
            'booster': 'gbtree',
            'lambda': 0.0000263894617720096,
            'alpha': 0.000463768723479341,
            'subsample': 0.237467672874133,
            'colsample_bytree': 0.618829300507829,
            'max_depth': 5,
            'min_child_weight': 9,
            'eta': 2.09477807126539E-06,
            'gamma': 0.000847289463422307,
            'grow_policy': 'depthwise',
            'n_jobs': -1,
            'objective': 'binary:logistic',
            'eval_metric': 'logloss',
            'verbosity': 0,
            'random_state': self.random_state,
        }
        if self.device == 'gpu':
            xgb_params['tree_method'] = 'gpu_hist'
            xgb_params['predictor'] = 'gpu_predictor'
        
        lgb_params = {
            'n_estimators': self.n_estimators,
            'objective': 'binary',
            'boosting_type': 'gbdt',
            'learning_rate': 0.005,
            'num_leaves': 5,
            'colsample_bytree': 0.50,
            'subsample': 0.80,
            'reg_alpha': 2, 
            'reg_lambda': 4,
            'n_jobs': -1,
            'is_unbalance':True,
            'device': self.device,
            'random_state': self.random_state
        }
        lgb1_params = {
            'n_estimators': self.n_estimators,
            'learning_rate': 0.190197487721534,
            'reg_alpha': 0.00749112221417973,
            'reg_lambda': 0.000548118227209224,
            'num_leaves': 17,
            'colsample_bytree': 0.547257860506146,
            'subsample': 0.592628085686409,
            'subsample_freq': 2,
            'min_child_samples': 64,
            'objective': 'binary',
            #'metric': 'binary_error',
            'boosting_type': 'gbdt',
            'is_unbalance':True,
            'device': self.device,
            'random_state': self.random_state
        } 
        lgb2_params = {
            'n_estimators': self.n_estimators,
            'learning_rate': 0.181326407627473,
            'reg_alpha': 0.000030864084239014,
            'reg_lambda': 0.0000395714763869486,
            'num_leaves': 122,
            'colsample_bytree': 0.75076596295323,
            'subsample': 0.6303245788342,
            'subsample_freq': 3,
            'min_child_samples': 72,
            'objective': 'binary',
            #'metric': 'binary_error',
            'boosting_type': 'gbdt',
            'is_unbalance':True,
            'device': self.device,
            'random_state': self.random_state
        } 
        cat_params = {
            'iterations': self.n_estimators,
            'colsample_bylevel': 0.0513276895988184,
            'depth': 2,
            'learning_rate': 0.0256579773375401,
            'l2_leaf_reg': 8.22319805476255,
            'random_strength': 0.11327724457066,
            'od_type': "Iter", 
            'od_wait': 72,
            'bootstrap_type': "Bayesian",
            'grow_policy': 'SymmetricTree',
            'bagging_temperature': 9.58737431845122,
            #'eval_metric': 'Logloss',
            #'loss_function': 'Logloss',
            'auto_class_weights': 'Balanced',
            'task_type': self.device.upper(),
            'random_state': self.random_state
        }
        hist_params = {
            'l2_regularization': 0.01,
            'early_stopping': True,
            'learning_rate': 0.01,
            'max_iter': self.n_estimators,
            'max_depth': 4,
            'max_bins': 255,
            'min_samples_leaf': 10,
            'max_leaf_nodes':10,
            'class_weight':'balanced',
            'random_state': self.random_state
        }
        models = {
            'xgb': xgb.XGBClassifier(**xgb_params),
            'lgb': lgb.LGBMClassifier(**lgb_params),
            'lgb1': lgb.LGBMClassifier(**lgb1_params),
            'lgb2': lgb.LGBMClassifier(**lgb2_params),
            'hgb': HistGradientBoostingClassifier(**hist_params),
            'cat': CatBoostClassifier(**cat_params),
        }
        
        return models

## Metrics

In [6]:
def calc_log_loss_weight(y_true):
    nc = np.bincount(y_true)
    w0, w1 = 1/(nc[0]/y_true.shape[0]), 1/(nc[1]/y_true.shape[0])
    return w0, w1

def balanced_log_loss(y_true, y_pred):
    y_pred = np.clip(y_pred, 1e-15, 1-1e-15)
    nc = np.bincount(y_true)
    w0, w1 = 1/(nc[0]/y_true.shape[0]), 1/(nc[1]/y_true.shape[0])
    balanced_log_loss_score = (-w0/nc[0]*(np.sum(np.where(y_true==0,1,0) * np.log(1-y_pred))) - w1/nc[1]*(np.sum(np.where(y_true!=0,1,0) * np.log(y_pred)))) / (w0+w1)
    return balanced_log_loss_score

## Optimizer (--> Optimize balanced_log_loss)

In [7]:
class OptunaWeights:
    def __init__(self, random_state, n_trials=3000):
        self.study = None
        self.weights = None
        self.random_state = random_state
        self.n_trials = n_trials

    def _objective(self, trial, y_true, y_preds):
        # Define the weights for the predictions from each model
        weights = [trial.suggest_float(f"weight{n}", 1e-14, 1) for n in range(len(y_preds))]

        # Calculate the weighted prediction
        weighted_pred = np.average(np.array(y_preds).T, axis=1, weights=weights)

        # Calculate the score for the weighted prediction
        # score = log_loss(y_true, weighted_pred)
        score = balanced_log_loss(y_true, weighted_pred)
        return score

    def fit(self, y_true, y_preds):
        optuna.logging.set_verbosity(optuna.logging.ERROR)
        sampler = optuna.samplers.CmaEsSampler(seed=self.random_state)
        pruner = optuna.pruners.HyperbandPruner()
        self.study = optuna.create_study(sampler=sampler, pruner=pruner, study_name="OptunaWeights", direction='minimize')
        objective_partial = partial(self._objective, y_true=y_true, y_preds=y_preds)
        self.study.optimize(objective_partial, n_trials=self.n_trials)
        self.weights = [self.study.best_params[f"weight{n}"] for n in range(len(y_preds))]

    def predict(self, y_preds):
        assert self.weights is not None, 'OptunaWeights error, must be fitted before predict'
        weighted_pred = np.average(np.array(y_preds).T, axis=1, weights=self.weights)
        return weighted_pred

    def fit_predict(self, y_true, y_preds):
        self.fit(y_true, y_preds)
        return self.predict(y_preds)
    
    def weights(self):
        return self.weights

## Base Model

In [8]:
%%time

kfold = 'skf'
n_splits = 5
n_reapts = 5
random_state = 71
n_estimators = 99999
early_stopping_rounds = 1000
verbose = False
device = 'cpu'

# Fix seed
random.seed(random_state)
random_state_list = random.sample(range(9999), n_reapts)

# Initialize an array for storing test predictions
classifier = Classifier(n_estimators, device, random_state)
test_predss = np.zeros((X_test.shape[0]))
oof_predss = np.zeros((X_train.shape[0], n_reapts))
ensemble_score, ensemble_score_ = [], []
weights = []
oof_each_predss = []
oof_each_preds = np.zeros((X_train.shape[0], classifier.len_models))
test_each_predss = []
test_each_preds = np.zeros((X_test.shape[0], classifier.len_models))
trained_models = {'xgb':[], 'cat':[]}
score_dict = dict(zip(classifier.models_name, [[] for _ in range(classifier.len_models)]))

splitter = Splitter(kfold=kfold, n_splits=n_splits, greeks=greeks.iloc[:,1:-1])
for i, (X_train_, X_val, y_train_, y_val) in enumerate(splitter.split_data(X_train, y_train, random_state_list=random_state_list)):
    n = i % n_splits
    m = i // n_splits
            
    # Get a set of classifier models
    classifier = Classifier(n_estimators, device, random_state_list[m])
    models = classifier.models
    
    # Initialize lists to store oof and test predictions for each base model
    oof_preds = []
    test_preds = []
    
    # Loop over each base model and fit it to the training data, evaluate on validation data, and store predictions
    for name, model in models.items():
        if ('xgb' in name) or ('lgb' in name) or ('cat' in name):
            train_w0, train_w1 = calc_log_loss_weight(y_train_)
            valid_w0, valid_w1 = calc_log_loss_weight(y_val)
            if 'xgb' in name:
                model.fit(
                    X_train_, y_train_, sample_weight=y_train_.map({0: train_w0, 1: train_w1}), 
                    eval_set=[(X_val, y_val)], sample_weight_eval_set=[y_val.map({0: valid_w0, 1: valid_w1})],
                    early_stopping_rounds=early_stopping_rounds, verbose=verbose)
            elif 'lgb' in name:
                model.fit(
                    X_train_, y_train_, sample_weight=y_train_.map({0: train_w0, 1: train_w1}), 
                    eval_set=[(X_val, y_val)], eval_sample_weight=[y_val.map({0: valid_w0, 1: valid_w1})],
                    early_stopping_rounds=early_stopping_rounds, verbose=verbose)
            elif 'cat' in name:
                model.fit(
                    Pool(X_train_, y_train_, weight=y_train_.map({0: train_w0, 1: train_w1})), 
                    eval_set=Pool(X_val, y_val, weight=y_val.map({0: valid_w0, 1: valid_w1})), 
                    early_stopping_rounds=early_stopping_rounds, verbose=verbose)
        else:
            model.fit(X_train_, y_train_)
            
        if name in trained_models.keys():
            trained_models[f'{name}'].append(deepcopy(model))
        
        test_pred = model.predict_proba(X_test)[:, 1].reshape(-1)
        y_val_pred = model.predict_proba(X_val)[:, 1].reshape(-1)
        
        score = balanced_log_loss(y_val, y_val_pred)
        score_dict[name].append(score)
        print(f'{name} [FOLD-{n} SEED-{random_state_list[m]}] BalancedLogLoss score: {score:.5f}')
        
        oof_preds.append(y_val_pred)
        test_preds.append(test_pred)
    
    # Use Optuna to find the best ensemble weights
    optweights = OptunaWeights(random_state=random_state_list[m])
    y_val_pred = optweights.fit_predict(y_val.values, oof_preds)
    
    score = balanced_log_loss(y_val, y_val_pred)
    score_ = roc_auc_score(y_val, y_val_pred)
    print(f'--> Ensemble [FOLD-{n} SEED-{random_state_list[m]}] BalancedLogLoss score {score:.5f}')
    ensemble_score.append(score)
    ensemble_score_.append(score_)
    weights.append(optweights.weights)
    
    # Predict to X_test by the best ensemble weights
    test_predss += optweights.predict(test_preds) / (n_splits * len(random_state_list))
    oof_predss[X_val.index, m] += optweights.predict(oof_preds)
    oof_each_preds[X_val.index] = np.stack(oof_preds).T
    test_each_preds += np.array(test_preds).T / n_splits
    if n == (n_splits - 1):
        oof_each_predss.append(oof_each_preds)
        oof_each_preds = np.zeros((X_train.shape[0], classifier.len_models))
        test_each_predss.append(test_each_preds)
        test_each_preds = np.zeros((X_test.shape[0], classifier.len_models))
    
    gc.collect()
    
oof_each_predss = np.mean(np.array(oof_each_predss), axis=0)
test_each_predss = np.mean(np.array(test_each_predss), axis=0)
oof_each_predss = np.concatenate([oof_each_predss, np.mean(oof_predss, axis=1).reshape(-1, 1)], axis=1)
test_each_predss = np.concatenate([test_each_predss, test_predss.reshape(-1, 1)], axis=1)

xgb [FOLD-0 SEED-5304] BalancedLogLoss score: 0.17309
lgb [FOLD-0 SEED-5304] BalancedLogLoss score: 0.08824
lgb1 [FOLD-0 SEED-5304] BalancedLogLoss score: 0.09791
lgb2 [FOLD-0 SEED-5304] BalancedLogLoss score: 0.12440
hgb [FOLD-0 SEED-5304] BalancedLogLoss score: 0.42115
cat [FOLD-0 SEED-5304] BalancedLogLoss score: 0.08493
--> Ensemble [FOLD-0 SEED-5304] BalancedLogLoss score 0.08449
xgb [FOLD-1 SEED-5304] BalancedLogLoss score: 0.50279
lgb [FOLD-1 SEED-5304] BalancedLogLoss score: 0.33739
lgb1 [FOLD-1 SEED-5304] BalancedLogLoss score: 0.30729
lgb2 [FOLD-1 SEED-5304] BalancedLogLoss score: 0.28585
hgb [FOLD-1 SEED-5304] BalancedLogLoss score: 0.63976
cat [FOLD-1 SEED-5304] BalancedLogLoss score: 0.53331
--> Ensemble [FOLD-1 SEED-5304] BalancedLogLoss score 0.28648
xgb [FOLD-2 SEED-5304] BalancedLogLoss score: 0.17713
lgb [FOLD-2 SEED-5304] BalancedLogLoss score: 0.13871
lgb1 [FOLD-2 SEED-5304] BalancedLogLoss score: 0.08841
lgb2 [FOLD-2 SEED-5304] BalancedLogLoss score: 0.09249
hgb [FOLD-2 SEED-5304] BalancedLogLoss score: 0.37466
cat [FOLD-2 SEED-5304] BalancedLogLoss score: 0.12718
--> Ensemble [FOLD-2 SEED-5304] BalancedLogLoss score 0.08519
xgb [FOLD-3 SEED-5304] BalancedLogLoss score: 0.61270
lgb [FOLD-3 SEED-5304] BalancedLogLoss score: 0.28471
lgb1 [FOLD-3 SEED-5304] BalancedLogLoss score: 0.34034
lgb2 [FOLD-3 SEED-5304] BalancedLogLoss score: 0.33433
hgb [FOLD-3 SEED-5304] BalancedLogLoss score: 0.49102
cat [FOLD-3 SEED-5304] BalancedLogLoss score: 0.44200
--> Ensemble [FOLD-3 SEED-5304] BalancedLogLoss score 0.28974
xgb [FOLD-4 SEED-5304] BalancedLogLoss score: 0.51391
lgb [FOLD-4 SEED-5304] BalancedLogLoss score: 0.38990
lgb1 [FOLD-4 SEED-5304] BalancedLogLoss score: 0.25258
lgb2 [FOLD-4 SEED-5304] BalancedLogLoss score: 0.32865
hgb [FOLD-4 SEED-5304] BalancedLogLoss score: 0.55431
cat [FOLD-4 SEED-5304] BalancedLogLoss score: 0.40776
--> Ensemble [FOLD-4 SEED-5304] BalancedLogLoss score 0.25274
xgb [FOLD-0 SEED-8330] BalancedLogLoss score: 0.58371
lgb [FOLD-0 SEED-8330] BalancedLogLoss score: 0.42834
lgb1 [FOLD-0 SEED-8330] BalancedLogLoss score: 0.41232
lgb2 [FOLD-0 SEED-8330] BalancedLogLoss score: 0.45201
hgb [FOLD-0 SEED-8330] BalancedLogLoss score: 0.62180
cat [FOLD-0 SEED-8330] BalancedLogLoss score: 0.46472
--> Ensemble [FOLD-0 SEED-8330] BalancedLogLoss score 0.38219
xgb [FOLD-1 SEED-8330] BalancedLogLoss score: 0.54027
lgb [FOLD-1 SEED-8330] BalancedLogLoss score: 0.34974
lgb1 [FOLD-1 SEED-8330] BalancedLogLoss score: 0.31039
lgb2 [FOLD-1 SEED-8330] BalancedLogLoss score: 0.42327
hgb [FOLD-1 SEED-8330] BalancedLogLoss score: 0.55722
cat [FOLD-1 SEED-8330] BalancedLogLoss score: 0.44036
--> Ensemble [FOLD-1 SEED-8330] BalancedLogLoss score 0.31106
xgb [FOLD-2 SEED-8330] BalancedLogLoss score: 0.21352
lgb [FOLD-2 SEED-8330] BalancedLogLoss score: 0.12412
lgb1 [FOLD-2 SEED-8330] BalancedLogLoss score: 0.20023
lgb2 [FOLD-2 SEED-8330] BalancedLogLoss score: 0.14138
hgb [FOLD-2 SEED-8330] BalancedLogLoss score: 0.34210
cat [FOLD-2 SEED-8330] BalancedLogLoss score: 0.21083
--> Ensemble [FOLD-2 SEED-8330] BalancedLogLoss score 0.12419
xgb [FOLD-3 SEED-8330] BalancedLogLoss score: 0.17908
lgb [FOLD-3 SEED-8330] BalancedLogLoss score: 0.18843
lgb1 [FOLD-3 SEED-8330] BalancedLogLoss score: 0.20598
lgb2 [FOLD-3 SEED-8330] BalancedLogLoss score: 0.20684
hgb [FOLD-3 SEED-8330] BalancedLogLoss score: 0.47816
cat [FOLD-3 SEED-8330] BalancedLogLoss score: 0.22935
--> Ensemble [FOLD-3 SEED-8330] BalancedLogLoss score 0.15817
xgb [FOLD-4 SEED-8330] BalancedLogLoss score: 0.22442
lgb [FOLD-4 SEED-8330] BalancedLogLoss score: 0.20211
lgb1 [FOLD-4 SEED-8330] BalancedLogLoss score: 0.20222
lgb2 [FOLD-4 SEED-8330] BalancedLogLoss score: 0.23190
hgb [FOLD-4 SEED-8330] BalancedLogLoss score: 0.43655
cat [FOLD-4 SEED-8330] BalancedLogLoss score: 0.27374
--> Ensemble [FOLD-4 SEED-8330] BalancedLogLoss score 0.18014
xgb [FOLD-0 SEED-138] BalancedLogLoss score: 0.32164
lgb [FOLD-0 SEED-138] BalancedLogLoss score: 0.27978
lgb1 [FOLD-0 SEED-138] BalancedLogLoss score: 0.26162
lgb2 [FOLD-0 SEED-138] BalancedLogLoss score: 0.22437
hgb [FOLD-0 SEED-138] BalancedLogLoss score: 0.42541
cat [FOLD-0 SEED-138] BalancedLogLoss score: 0.31871
--> Ensemble [FOLD-0 SEED-138] BalancedLogLoss score 0.22465
xgb [FOLD-1 SEED-138] BalancedLogLoss score: 0.40507
lgb [FOLD-1 SEED-138] BalancedLogLoss score: 0.12766
lgb1 [FOLD-1 SEED-138] BalancedLogLoss score: 0.14253
lgb2 [FOLD-1 SEED-138] BalancedLogLoss score: 0.13801
hgb [FOLD-1 SEED-138] BalancedLogLoss score: 0.34056
cat [FOLD-1 SEED-138] BalancedLogLoss score: 0.17357
--> Ensemble [FOLD-1 SEED-138] BalancedLogLoss score 0.12713
xgb [FOLD-2 SEED-138] BalancedLogLoss score: 0.48783
lgb [FOLD-2 SEED-138] BalancedLogLoss score: 0.31658
lgb1 [FOLD-2 SEED-138] BalancedLogLoss score: 0.35647
lgb2 [FOLD-2 SEED-138] BalancedLogLoss score: 0.28975
hgb [FOLD-2 SEED-138] BalancedLogLoss score: 0.54371
cat [FOLD-2 SEED-138] BalancedLogLoss score: 0.39538
--> Ensemble [FOLD-2 SEED-138] BalancedLogLoss score 0.28990
xgb [FOLD-3 SEED-138] BalancedLogLoss score: 0.29618
lgb [FOLD-3 SEED-138] BalancedLogLoss score: 0.19571
lgb1 [FOLD-3 SEED-138] BalancedLogLoss score: 0.22858
lgb2 [FOLD-3 SEED-138] BalancedLogLoss score: 0.26969
hgb [FOLD-3 SEED-138] BalancedLogLoss score: 0.48728
cat [FOLD-3 SEED-138] BalancedLogLoss score: 0.33292
--> Ensemble [FOLD-3 SEED-138] BalancedLogLoss score 0.19644
xgb [FOLD-4 SEED-138] BalancedLogLoss score: 0.54632
lgb [FOLD-4 SEED-138] BalancedLogLoss score: 0.30524
lgb1 [FOLD-4 SEED-138] BalancedLogLoss score: 0.28157
lgb2 [FOLD-4 SEED-138] BalancedLogLoss score: 0.27418
hgb [FOLD-4 SEED-138] BalancedLogLoss score: 0.38402
cat [FOLD-4 SEED-138] BalancedLogLoss score: 0.43499
--> Ensemble [FOLD-4 SEED-138] BalancedLogLoss score 0.25380
xgb [FOLD-0 SEED-4340] BalancedLogLoss score: 0.59297
lgb [FOLD-0 SEED-4340] BalancedLogLoss score: 0.22192
lgb1 [FOLD-0 SEED-4340] BalancedLogLoss score: 0.22839
lgb2 [FOLD-0 SEED-4340] BalancedLogLoss score: 0.35702
hgb [FOLD-0 SEED-4340] BalancedLogLoss score: 0.54011
cat [FOLD-0 SEED-4340] BalancedLogLoss score: 0.38571
--> Ensemble [FOLD-0 SEED-4340] BalancedLogLoss score 0.21415
xgb [FOLD-1 SEED-4340] BalancedLogLoss score: 0.42244
lgb [FOLD-1 SEED-4340] BalancedLogLoss score: 0.35092
lgb1 [FOLD-1 SEED-4340] BalancedLogLoss score: 0.30309
lgb2 [FOLD-1 SEED-4340] BalancedLogLoss score: 0.24436
hgb [FOLD-1 SEED-4340] BalancedLogLoss score: 0.53648
cat [FOLD-1 SEED-4340] BalancedLogLoss score: 0.35708
--> Ensemble [FOLD-1 SEED-4340] BalancedLogLoss score 0.24543
xgb [FOLD-2 SEED-4340] BalancedLogLoss score: 0.30044
lgb [FOLD-2 SEED-4340] BalancedLogLoss score: 0.28813
lgb1 [FOLD-2 SEED-4340] BalancedLogLoss score: 0.18689
lgb2 [FOLD-2 SEED-4340] BalancedLogLoss score: 0.29567
hgb [FOLD-2 SEED-4340] BalancedLogLoss score: 0.41775
cat [FOLD-2 SEED-4340] BalancedLogLoss score: 0.33930
--> Ensemble [FOLD-2 SEED-4340] BalancedLogLoss score 0.18727
xgb [FOLD-3 SEED-4340] BalancedLogLoss score: 0.14182
lgb [FOLD-3 SEED-4340] BalancedLogLoss score: 0.14126
lgb1 [FOLD-3 SEED-4340] BalancedLogLoss score: 0.23743
lgb2 [FOLD-3 SEED-4340] BalancedLogLoss score: 0.11868
hgb [FOLD-3 SEED-4340] BalancedLogLoss score: 0.44711
cat [FOLD-3 SEED-4340] BalancedLogLoss score: 0.16673
--> Ensemble [FOLD-3 SEED-4340] BalancedLogLoss score 0.11901
xgb [FOLD-4 SEED-4340] BalancedLogLoss score: 0.32776
lgb [FOLD-4 SEED-4340] BalancedLogLoss score: 0.22523
lgb1 [FOLD-4 SEED-4340] BalancedLogLoss score: 0.28084
lgb2 [FOLD-4 SEED-4340] BalancedLogLoss score: 0.27119
hgb [FOLD-4 SEED-4340] BalancedLogLoss score: 0.41117
cat [FOLD-4 SEED-4340] BalancedLogLoss score: 0.37025
--> Ensemble [FOLD-4 SEED-4340] BalancedLogLoss score 0.22568
xgb [FOLD-0 SEED-2536] BalancedLogLoss score: 0.20898
lgb [FOLD-0 SEED-2536] BalancedLogLoss score: 0.15434
lgb1 [FOLD-0 SEED-2536] BalancedLogLoss score: 0.20923
lgb2 [FOLD-0 SEED-2536] BalancedLogLoss score: 0.22466
hgb [FOLD-0 SEED-2536] BalancedLogLoss score: 0.39042
cat [FOLD-0 SEED-2536] BalancedLogLoss score: 0.25663
--> Ensemble [FOLD-0 SEED-2536] BalancedLogLoss score 0.15463
xgb [FOLD-1 SEED-2536] BalancedLogLoss score: 0.40129
lgb [FOLD-1 SEED-2536] BalancedLogLoss score: 0.28308
lgb1 [FOLD-1 SEED-2536] BalancedLogLoss score: 0.26374
lgb2 [FOLD-1 SEED-2536] BalancedLogLoss score: 0.28395
hgb [FOLD-1 SEED-2536] BalancedLogLoss score: 0.42373
cat [FOLD-1 SEED-2536] BalancedLogLoss score: 0.31710
--> Ensemble [FOLD-1 SEED-2536] BalancedLogLoss score 0.25521
xgb [FOLD-2 SEED-2536] BalancedLogLoss score: 0.25619
lgb [FOLD-2 SEED-2536] BalancedLogLoss score: 0.18609
lgb1 [FOLD-2 SEED-2536] BalancedLogLoss score: 0.17724
lgb2 [FOLD-2 SEED-2536] BalancedLogLoss score: 0.17737
hgb [FOLD-2 SEED-2536] BalancedLogLoss score: 0.45415
cat [FOLD-2 SEED-2536] BalancedLogLoss score: 0.28189
--> Ensemble [FOLD-2 SEED-2536] BalancedLogLoss score 0.16877
xgb [FOLD-3 SEED-2536] BalancedLogLoss score: 0.47816
lgb [FOLD-3 SEED-2536] BalancedLogLoss score: 0.28425
lgb1 [FOLD-3 SEED-2536] BalancedLogLoss score: 0.33294
lgb2 [FOLD-3 SEED-2536] BalancedLogLoss score: 0.34093
hgb [FOLD-3 SEED-2536] BalancedLogLoss score: 0.53569
cat [FOLD-3 SEED-2536] BalancedLogLoss score: 0.41561
--> Ensemble [FOLD-3 SEED-2536] BalancedLogLoss score 0.27996
xgb [FOLD-4 SEED-2536] BalancedLogLoss score: 0.20476
lgb [FOLD-4 SEED-2536] BalancedLogLoss score: 0.37191
lgb1 [FOLD-4 SEED-2536] BalancedLogLoss score: 0.36659
lgb2 [FOLD-4 SEED-2536] BalancedLogLoss score: 0.31421
hgb [FOLD-4 SEED-2536] BalancedLogLoss score: 0.54991
cat [FOLD-4 SEED-2536] BalancedLogLoss score: 0.35642
--> Ensemble [FOLD-4 SEED-2536] BalancedLogLoss score 0.20353
CPU times: user 29min 25s, sys: 11min 39s, total: 41min 5s
Wall time: 21min 15s

## Stacking Model (LightGBM)

In [9]:
%%time

stack_test_predss = np.zeros((X_test.shape[0]))
stack_scores = []
stack_models = []
splitter = Splitter(kfold=kfold, n_splits=n_splits, greeks=greeks.iloc[:,1:-1])
for i, (X_train_, X_val, y_train_, y_val) in enumerate(splitter.split_data(oof_each_predss, y_train, random_state_list=random_state_list)):
    n = i % n_splits
    m = i // n_splits
    
    classifier = Classifier(n_estimators, device, random_state_list[m])
    models = classifier.models
    model = models['lgb1']
    
    train_w0, train_w1 = calc_log_loss_weight(y_train_)
    valid_w0, valid_w1 = calc_log_loss_weight(y_val)
    
    model.fit(
        X_train_, y_train_, sample_weight=y_train_.map({0: train_w0, 1: train_w1}), 
        eval_set=[(X_val, y_val)], eval_sample_weight=[y_val.map({0: valid_w0, 1: valid_w1})],
        early_stopping_rounds=early_stopping_rounds, verbose=verbose)
    
    test_pred = model.predict_proba(test_each_predss)[:, 1].reshape(-1)
    y_val_pred = model.predict_proba(X_val)[:, 1].reshape(-1)

    score = balanced_log_loss(y_val, y_val_pred)
    stack_scores.append(score)
    stack_models.append(deepcopy(model))
    
    stack_test_predss += test_pred / (n_splits * len(random_state_list))

CPU times: user 24.2 s, sys: 21.5 s, total: 45.7 s
Wall time: 35.5 s

## Make Submission

In [10]:
sub = pd.read_csv(os.path.join(filepath, 'sample_submission.csv'))

sub['class_1'] = stack_test_predss
sub['class_0'] = 1 - stack_test_predss
# sub.to_csv('submission.csv', index=False)
sub

             Id   class_0   class_1
0  00eed32682bb  0.238332  0.761668
1  010ebe33f668  0.238332  0.761668
2  02fa521e1838  0.238332  0.761668
3  040e15f562a2  0.238332  0.761668
4  046e85c7cc7f  0.238332  0.761668

In [11]:
import numpy as np
import pandas as pd
import lightgbm as lgb
from imblearn.under_sampling import RandomUnderSampler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
import warnings
warnings.filterwarnings('ignore')

# Load the data
train_df = pd.read_csv(f'{filepath}train.csv')
test_df = pd.read_csv(f'{filepath}test.csv')
greeks_df = pd.read_csv(f'{filepath}greeks.csv')
sample_submission_df = pd.read_csv(f'{filepath}sample_submission.csv')


numerical_features = ['AB', 'AF', 'AH', 'AM', 'AR', 'AX', 'AY', 'AZ',#'BC',
                      'BD', 'BN', 'BP', 'BQ', 'BR', 'BZ',
                      'CB', 'CC', 'CD', 'CF', 'CH',  'CR', 'CS', 'CU', 'CW', #'CL',
                      'DA', 'DE', 'DF', 'DH', 'DI', 'DL', 'DN', 'DU', 'DV', 'DY',
                      'EB', 'EE', 'EG', 'EH', 'EL', 'EP', 'EU',
                      'FC', 'FD', 'FE', 'FI', 'FL', 'FR', 'FS',
                      'GB', 'GE', 'GF', 'GH', 'GI', 'GL']
categorical_features = ['EJ']
features = numerical_features + categorical_features


train_df['EJ'] = train_df['EJ'].replace({'A': 0, 'B': 1})
test_df['EJ'] = test_df['EJ'].replace({'A': 0, 'B': 1})

X=train_df.drop("Class",axis=1)
y=train_df["Class"]

X_test=test_df.copy()

params = {
    'boosting_type': 'GBDT',
    'objective':"binary",
    'metric':'binary_logloss',
    'random_state': 42,
    'verbose': -1,
}

for i in range(20):
    
    positive_count_train = y.value_counts()[1]
    sampler = RandomUnderSampler(sampling_strategy={0: positive_count_train, 1: positive_count_train},random_state=i, replacement=True)
    X_re, y_re = sampler.fit_resample(X, y)

    (X_train, X_val , y_train , y_val) = train_test_split(X_re, y_re , test_size = 0.2,random_state=42)

    lgb_eval = lgb.Dataset(X_val.drop("Id",axis=1), y_val,free_raw_data=False) 
    lgb_train = lgb.Dataset(X_re.drop("Id",axis=1), y_re,free_raw_data=False) 
    
    
    model = lgb.train(params, lgb_train, valid_sets=lgb_eval,
                      categorical_feature = categorical_features,
                      num_boost_round=1000,
                      early_stopping_rounds=20,
                      verbose_eval=200)
    
    pred = model.predict(X_test.drop("Id",axis=1),num_iteration=model.best_iteration)

    if i == 0:
        output = pd.DataFrame(pred, columns=['pred' + str(i + 1)])
        output2 = output
    else:
        output = pd.DataFrame(pred, columns=['pred' + str(i + 1)])
        output2 = pd.concat([output2, output], axis=1)


pred = output2.mean(axis='columns')

Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 3.28977e-05
[400]	valid_0's binary_logloss: 9.593e-06
Early stopping, best iteration is:
[411]	valid_0's binary_logloss: 9.49307e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 3.05692e-05
[400]	valid_0's binary_logloss: 1.01045e-05
Early stopping, best iteration is:
[508]	valid_0's binary_logloss: 9.15561e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.46043e-05
Early stopping, best iteration is:
[358]	valid_0's binary_logloss: 9.0998e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 1.55326e-05
[400]	valid_0's binary_logloss: 7.37785e-06
Early stopping, best iteration is:
[424]	valid_0's binary_logloss: 7.16289e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 1.92501e-05
Early stopping, best iteration is:
[329]	valid_0's binary_logloss: 8.7209e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.70547e-05
[400]	valid_0's binary_logloss: 1.11026e-05
Early stopping, best iteration is:
[383]	valid_0's binary_logloss: 1.10998e-05
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 1.8849e-05
Early stopping, best iteration is:
[364]	valid_0's binary_logloss: 7.87075e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.23201e-05
[400]	valid_0's binary_logloss: 9.66193e-06
Early stopping, best iteration is:
[404]	valid_0's binary_logloss: 9.65889e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.4855e-05
[400]	valid_0's binary_logloss: 8.64135e-06
Early stopping, best iteration is:
[479]	valid_0's binary_logloss: 8.21563e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.08135e-05
[400]	valid_0's binary_logloss: 8.42994e-06
Early stopping, best iteration is:
[462]	valid_0's binary_logloss: 8.02136e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 1.73157e-05
Early stopping, best iteration is:
[350]	valid_0's binary_logloss: 9.76251e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 1.6772e-05
Early stopping, best iteration is:
[348]	valid_0's binary_logloss: 8.15972e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.03768e-05
[400]	valid_0's binary_logloss: 8.35831e-06
Early stopping, best iteration is:
[434]	valid_0's binary_logloss: 7.98573e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 4.2183e-05
[400]	valid_0's binary_logloss: 9.77276e-06
Early stopping, best iteration is:
[473]	valid_0's binary_logloss: 8.63498e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 4.97647e-05
[400]	valid_0's binary_logloss: 1.19152e-05
Early stopping, best iteration is:
[480]	valid_0's binary_logloss: 1.12043e-05
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 1.91964e-05
[400]	valid_0's binary_logloss: 8.52008e-06
Early stopping, best iteration is:
[428]	valid_0's binary_logloss: 8.41325e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 3.30115e-05
[400]	valid_0's binary_logloss: 1.00521e-05
Early stopping, best iteration is:
[426]	valid_0's binary_logloss: 9.80349e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.96553e-05
[400]	valid_0's binary_logloss: 7.30995e-06
Early stopping, best iteration is:
[458]	valid_0's binary_logloss: 6.68593e-06
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 2.93224e-05
[400]	valid_0's binary_logloss: 1.11595e-05
Early stopping, best iteration is:
[398]	valid_0's binary_logloss: 1.1156e-05
Training until validation scores don't improve for 20 rounds
[200]	valid_0's binary_logloss: 3.65849e-05
[400]	valid_0's binary_logloss: 8.87596e-06
Early stopping, best iteration is:
[461]	valid_0's binary_logloss: 8.05463e-06

In [12]:
pred

0    0.31672
1    0.31672
2    0.31672
3    0.31672
4    0.31672
dtype: float64

In [13]:
# !pip download autogluon.tabular[all] -d autogluon

# !zip -r autogluon.zip autogluon

In [14]:
# import shutil
# shutil.make_archive("autogluon", 'zip', "kaggle/working/autogluon/")

In [15]:
# !pip install autogluon --no-index --find-links=file:///kaggle/input/tabpfn/

In [16]:
# !zip -r autogluon.zip autogluon

In [17]:
# !pip download tabpfn --no-deps -d pip-packages

# from tabpfn import TabPFNClassifier
# TabPFNClassifier(N_ensemble_configurations=64,device='cpu')

# !mv /opt/conda/lib/python3.10/site-packages/tabpfn/models_diff/prior_diff_real_checkpoint_n_0_epoch_100.cpkt pip-packages/
# !zip -r pip-packages.zip pip-packages

In [18]:
!pip install tabpfn --no-index --find-links=file:///kaggle/input/tabpfn/pip-packages/pip-packages

!mkdir -p /opt/conda/lib/python3.10/site-packages/tabpfn/models_diff
!cp /kaggle/input/tabpfn/prior_diff_real_checkpoint_n_0_epoch_100.cpkt /opt/conda/lib/python3.10/site-packages/tabpfn/models_diff/

Looking in links: file:///kaggle/input/tabpfn/pip-packages/pip-packages
Processing /kaggle/input/tabpfn/pip-packages/pip-packages/tabpfn-0.1.9-py3-none-any.whl
Requirement already satisfied: numpy>=1.21.2 in /opt/conda/lib/python3.10/site-packages (from tabpfn) (1.23.5)
Requirement already satisfied: pyyaml>=5.4.1 in /opt/conda/lib/python3.10/site-packages (from tabpfn) (5.4.1)
Requirement already satisfied: requests>=2.23.0 in /opt/conda/lib/python3.10/site-packages (from tabpfn) (2.28.2)
Requirement already satisfied: scikit-learn>=0.24.2 in /opt/conda/lib/python3.10/site-packages (from tabpfn) (1.2.2)
Requirement already satisfied: torch>=1.9.0 in /opt/conda/lib/python3.10/site-packages (from tabpfn) (2.0.0+cpu)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->tabpfn) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->tabpfn) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->tabpfn) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests>=2.23.0->tabpfn) (2023.5.7)
Requirement already satisfied: scipy>=1.3.2 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.24.2->tabpfn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.24.2->tabpfn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn>=0.24.2->tabpfn) (3.1.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from torch>=1.9.0->tabpfn) (3.12.0)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.10/site-packages (from torch>=1.9.0->tabpfn) (4.5.0)
Requirement already satisfied: sympy in /opt/conda/lib/python3.10/site-packages (from torch>=1.9.0->tabpfn) (1.12)
Requirement already satisfied: networkx in /opt/conda/lib/python3.10/site-packages (from torch>=1.9.0->tabpfn) (3.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.10/site-packages (from torch>=1.9.0->tabpfn) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from jinja2->torch>=1.9.0->tabpfn) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/lib/python3.10/site-packages (from sympy->torch>=1.9.0->tabpfn) (1.3.0)
Installing collected packages: tabpfn
Successfully installed tabpfn-0.1.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [19]:
import numpy as np
import pandas as pd
import json



pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import warnings
warnings.filterwarnings("ignore")

# LOAD THE DATA

# Import data directly as H2O frame
maindf = pd.read_csv(f'{filepath}/train.csv')
greeksdf = pd.read_csv(f'{filepath}/greeks.csv')
testdf = pd.read_csv(f'{filepath}/test.csv')

print(maindf.EJ.unique())
first_cat = maindf.EJ.unique()[0]
maindf.EJ = maindf.EJ.eq(first_cat).astype('int')
testdf.EJ = testdf.EJ.eq(first_cat).astype('int')

# Greeks contains time information that we can use, we just need to parse it to int / nan.

from datetime import date, datetime
times = greeksdf.Epsilon.copy()
times[greeksdf.Epsilon != 'Unknown'] = greeksdf.Epsilon[greeksdf.Epsilon != 'Unknown'].map(lambda x: datetime.strptime(x,'%m/%d/%Y').toordinal())
times[greeksdf.Epsilon == 'Unknown'] = np.nan

device = 'cpu' 

# Set predictor and target columns
target = 'Class'
predictors = [n for n in maindf.columns if n != target and n != 'Id']

from sklearn.base import BaseEstimator
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.impute import SimpleImputer
from catboost import Pool, CatBoostClassifier
import xgboost
from tabpfn import TabPFNClassifier


class WeightedEns(BaseEstimator):
    def __init__(self):
        self.classifiers = [xgboost.XGBClassifier(),TabPFNClassifier(N_ensemble_configurations=64,device=device)]
        self.imp = SimpleImputer(missing_values=np.nan, strategy='median')
    
    def fit(self, X, y):
        cls, y = np.unique(y, return_inverse=True)
        self.classes_ = cls
        X = self.imp.fit_transform(X)
        for cl in self.classifiers:
            cl.fit(X,y)
    
    def predict_proba(self, X):
        X = self.imp.transform(X)
        ps = np.stack([cl.predict_proba(X) for cl in self.classifiers])
        p = np.mean(ps,axis=0)
        class_0_est_instances = p[:,0].sum()
        others_est_instances = p[:,1:].sum()
        # we reweight the probs, since the loss is also balanced like this
        # our models out of the box optimize CE
        # with these changes they optimize balanced CE
        new_p = p * np.array([[1/(class_0_est_instances if i==0 else others_est_instances) for i in range(p.shape[1])]])
        return new_p / np.sum(new_p,axis=1,keepdims=1)

pred_and_time = pd.concat([maindf[predictors], times], axis=1)

test_predictors = np.array(testdf[predictors])
test_pred_and_time = np.concatenate((test_predictors, np.zeros((len(test_predictors),1)) + pred_and_time.Epsilon.max()+1),1)

m = WeightedEns()
m.fit(np.array(pred_and_time),np.array(greeksdf['Alpha']))
p = m.predict_proba(test_pred_and_time)
assert (m.classes_[0] == 'A')
p = np.concatenate((p[:,:1],np.sum(p[:,1:],1,keepdims=True)), 1)
result_df = pd.concat((testdf['Id'],pd.DataFrame(p, columns=('class_0', 'class_1'))),axis=1)

['B' 'A']
Loading model that can be used for inference only
Using a Transformer with 25.82 M parameters

In [20]:
result_df

             Id  class_0  class_1
0  00eed32682bb      0.5      0.5
1  010ebe33f668      0.5      0.5
2  02fa521e1838      0.5      0.5
3  040e15f562a2      0.5      0.5
4  046e85c7cc7f      0.5      0.5

In [21]:
tabpfn = result_df["class_1"]
tabpfn[tabpfn > 0.86] = 1
tabpfn[tabpfn < 0.14] = 0

pred[pred > 0.93] = 1
pred[pred < 0.07] = 0

stack_test_predss[stack_test_predss > 0.93] = 1
stack_test_predss[stack_test_predss < 0.07] = 0

/tmp/ipykernel_20/1254818649.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabpfn[tabpfn > 0.86] = 1
/tmp/ipykernel_20/1254818649.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabpfn[tabpfn < 0.14] = 0

In [22]:
fin_pred = 0.1*pred + 0.2*stack_test_predss + 0.7*tabpfn

In [23]:
sub['class_1'] = fin_pred
sub['class_0'] = 1 - fin_pred
sub.to_csv('submission.csv', index=False)
sub

             Id   class_0   class_1
0  00eed32682bb  0.465994  0.534006
1  010ebe33f668  0.465994  0.534006
2  02fa521e1838  0.465994  0.534006
3  040e15f562a2  0.465994  0.534006
4  046e85c7cc7f  0.465994  0.534006