In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv

**Load the dataset**

In [2]:
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import pandas as pd
import numpy as np

# Ignore in case of warnings
import warnings
warnings.filterwarnings(action="ignore")

In [3]:
train = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/train.csv')
df_train = train.copy()

# Load df_test data
df_test = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/test.csv')

# Load sample_submission
sample_data = pd.read_csv('/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv')

In [4]:
print("--------------------Null values ratio-----------------------\n")
display(df_train.isnull().mean()*100)

--------------------Null values ratio-----------------------

Id                0.000000
MSSubClass        0.000000
MSZoning          0.000000
LotFrontage      17.739726
LotArea           0.000000
                   ...
MoSold            0.000000
YrSold            0.000000
SaleType          0.000000
SaleCondition     0.000000
SalePrice         0.000000
Length: 81, dtype: float64

In [5]:
df_train.columns[df_train.isnull().mean()*100 > 20]

Index(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], dtype='object')

In [6]:
df_train = df_train.drop(columns=['Alley','FireplaceQu','PoolQC','Fence','MiscFeature'],axis=1)

In [7]:
for column in df_train.columns:
    if df_train[column].dtype == np.object:
        df_train[column].fillna(df_train[column].mode()[0], inplace=True)
    elif df_train[column].dtype == np.float64:
        df_train[column].fillna(df_train[column].median(), inplace=True)
    elif df_train[column].dtype == np.int64:
        df_train[column].fillna(df_train[column].median(), inplace=True)

In [8]:
print("---------------Checking for the null value again-----------------\n")
display(df_train.isnull().sum())
print("The totall amount of null values:",df_train.isnull().sum().sum())
print("---------------------The final train data set-------------------\n")
display(df_train)

---------------Checking for the null value again-----------------

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 76, dtype: int64

The totall amount of null values: 0
---------------------The final train data set-------------------

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [9]:
from sklearn.preprocessing import LabelEncoder
label_encode = LabelEncoder()
for column in df_train.columns:
    if df_train[column].dtype == 'object':
        df_train[column] = label_encode.fit_transform(df_train[column])

In [10]:
df_train.drop(['Id','Street','YearRemodAdd','MiscVal'], axis=1, inplace= True)

In [11]:
df_train['MSSubClass'] = df_train['MSSubClass'].apply(str)
df_train['OverallCond'] = df_train['OverallCond'].astype(str)
df_train['YrSold'] = df_train['YrSold'].astype(str)
df_train['MoSold'] = df_train['MoSold'].astype(str)

In [12]:
print("--------------------Null values ratio-----------------------\n")
display(df_test.isnull().mean()*100)

--------------------Null values ratio-----------------------

Id                0.000000
MSSubClass        0.000000
MSZoning          0.274160
LotFrontage      15.558602
LotArea           0.000000
                   ...
MiscVal           0.000000
MoSold            0.000000
YrSold            0.000000
SaleType          0.068540
SaleCondition     0.000000
Length: 80, dtype: float64

In [13]:
df_test.columns[df_test.isnull().mean()*100 > 20]

Index(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], dtype='object')

In [14]:
df_test = df_test.drop(columns=['Alley','FireplaceQu','PoolQC','Fence','MiscFeature'],axis=1)

In [15]:
for column in df_test.columns:
    if df_test[column].dtype == np.object:
        df_test[column].fillna(df_test[column].mode()[0], inplace=True)
    elif df_test[column].dtype == np.float64:
        df_test[column].fillna(df_test[column].median(), inplace=True)
    elif df_test[column].dtype == np.int64:
        df_test[column].fillna(df_test[column].median(), inplace=True)

In [16]:
print("---------------Checking for the null value again-----------------\n")
display(df_test.isnull().sum())
print("The totall amount of null values:",df_test.isnull().sum().sum())
print("---------------------The final test data set-------------------\n")
display(df_test)

---------------Checking for the null value again-----------------

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 75, dtype: int64

The totall amount of null values: 0
---------------------The final test data set-------------------

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,...,36,0,0,0,0,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,...,34,0,0,0,0,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,IR1,Lvl,AllPub,Inside,...,36,0,0,0,0,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,IR1,HLS,AllPub,Inside,...,82,0,0,144,0,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,Reg,Lvl,AllPub,Inside,...,24,0,0,0,0,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,...,32,0,0,0,0,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,...,48,0,0,0,0,0,11,2006,WD,Normal

In [17]:
df_test.drop(['PoolArea'], axis=1, inplace=True)

In [18]:
object_features = []
for column_name in df_test.columns:
    if df_test[column_name].dtype == 'object':
        object_features.append(column_name) 

print(f"----------------Object type features name ----------> number of object features:{len(object_features)} <----------\n ")        
display(object_features)

----------------Object type features name ----------> number of object features:38 <----------

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [19]:
label_encode = LabelEncoder()
for column in df_test.columns:
    if df_test[column].dtype == 'object':
        df_test[column] = label_encode.fit_transform(df_test[column])

In [20]:
df_test.drop(['Street','YearRemodAdd','MiscVal'], axis=1, inplace= True)

In [21]:
df_test['MSSubClass'] = df_test['MSSubClass'].apply(str)
df_test['OverallCond'] = df_test['OverallCond'].astype(str)
df_test['YrSold'] = df_test['YrSold'].astype(str)
df_test['MoSold'] = df_test['MoSold'].astype(str)

In [22]:
X=df_train.drop(columns=['SalePrice'])
Y=df_train['SalePrice']
X.df_test=df_test

In [23]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=42,test_size=0.3)

In [24]:
X_train= np.asarray(X_train).astype(np.int)
Y_train= np.asarray(Y_train).astype(np.int)
X_test= np.asarray(X_test).astype(np.int)
Y_test= np.asarray(Y_test).astype(np.int)

**Build the Model**

In [25]:
tf.random.set_seed(42)
norm_layer = tf.keras.layers.Normalization(input_shape=X_train.shape[1:])
model = tf.keras.Sequential([
    norm_layer,
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    tf.keras.layers.Dense(200, activation="relu"),
    
    tf.keras.layers.Dense(1)
])

**Compile the model**

In [26]:
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
model.compile(loss="mse", optimizer=optimizer, metrics=["RootMeanSquaredError"])
norm_layer.adapt(X_train)

In [27]:
model.fit(X_train, Y_train, epochs=4500)

Epoch 1/4500
32/32 [==============================] - 2s 7ms/step - loss: 35240759296.0000 - root_mean_squared_error: 187725.2188
Epoch 2/4500
32/32 [==============================] - 0s 6ms/step - loss: 4557330944.0000 - root_mean_squared_error: 67508.0078
Epoch 3/4500
32/32 [==============================] - 0s 7ms/step - loss: 1760728448.0000 - root_mean_squared_error: 41961.0352
Epoch 4/4500
32/32 [==============================] - 0s 6ms/step - loss: 1574239616.0000 - root_mean_squared_error: 39676.6875
Epoch 5/4500
32/32 [==============================] - 0s 6ms/step - loss: 1150281216.0000 - root_mean_squared_error: 33915.7969
Epoch 6/4500
32/32 [==============================] - 0s 6ms/step - loss: 907740800.0000 - root_mean_squared_error: 30128.7363
Epoch 7/4500
32/32 [==============================] - 0s 6ms/step - loss: 888714560.0000 - root_mean_squared_error: 29811.3164
Epoch 8/4500
32/32 [==============================] - 0s 6ms/step - loss: 922868032.0000 - root_mean_squared_error: 30378.7422
Epoch 9/4500
32/32 [==============================] - 0s 6ms/step - loss: 720471488.0000 - root_mean_squared_error: 26841.5996
Epoch 10/4500
32/32 [==============================] - 0s 6ms/step - loss: 686930240.0000 - root_mean_squared_error: 26209.3535
Epoch 11/4500
32/32 [==============================] - 0s 6ms/step - loss: 653457664.0000 - root_mean_squared_error: 25562.8184
Epoch 12/4500
32/32 [==============================] - 0s 6ms/step - loss: 564945536.0000 - root_mean_squared_error: 23768.5820
Epoch 13/4500
32/32 [==============================] - 0s 6ms/step - loss: 525193152.0000 - root_mean_squared_error: 22917.0938
Epoch 14/4500
32/32 [==============================] - 0s 6ms/step - loss: 522604512.0000 - root_mean_squared_error: 22860.5449
Epoch 15/4500
32/32 [==============================] - 0s 6ms/step - loss: 674144704.0000 - root_mean_squared_error: 25964.2969
Epoch 16/4500
32/32 [==============================] - 0s 6ms/step - loss: 446255456.0000 - root_mean_squared_error: 21124.7598
Epoch 17/4500
32/32 [==============================] - 0s 6ms/step - loss: 403469472.0000 - root_mean_squared_error: 20086.5488
Epoch 18/4500
32/32 [==============================] - 0s 6ms/step - loss: 444113312.0000 - root_mean_squared_error: 21073.9961
Epoch 19/4500
32/32 [==============================] - 0s 6ms/step - loss: 349810304.0000 - root_mean_squared_error: 18703.2168
Epoch 20/4500
32/32 [==============================] - 0s 6ms/step - loss: 329020576.0000 - root_mean_squared_error: 18138.9238
Epoch 21/4500
32/32 [==============================] - 0s 6ms/step - loss: 356171904.0000 - root_mean_squared_error: 18872.5176
Epoch 22/4500
32/32 [==============================] - 0s 6ms/step - loss: 286316864.0000 - root_mean_squared_error: 16920.9004
Epoch 23/4500
32/32 [==============================] - 0s 6ms/step - loss: 250059120.0000 - root_mean_squared_error: 15813.2578
Epoch 24/4500
32/32 [==============================] - 0s 6ms/step - loss: 237114816.0000 - root_mean_squared_error: 15398.5332
Epoch 25/4500
32/32 [==============================] - 0s 6ms/step - loss: 249864768.0000 - root_mean_squared_error: 15807.1113
Epoch 26/4500
32/32 [==============================] - 0s 6ms/step - loss: 245172480.0000 - root_mean_squared_error: 15657.9844
Epoch 27/4500
32/32 [==============================] - 0s 6ms/step - loss: 221166000.0000 - root_mean_squared_error: 14871.6514
Epoch 28/4500
32/32 [==============================] - 0s 6ms/step - loss: 190340784.0000 - root_mean_squared_error: 13796.4043
Epoch 29/4500
32/32 [==============================] - 0s 6ms/step - loss: 189218656.0000 - root_mean_squared_error: 13755.6768
Epoch 30/4500
32/32 [==============================] - 0s 6ms/step - loss: 179522224.0000 - root_mean_squared_error: 13398.5908
Epoch 31/4500
32/32 [==============================] - 0s 6ms/step - loss: 150513680.0000 - root_mean_squared_error: 12268.4014
Epoch 32/4500
32/32 [==============================] - 0s 6ms/step - loss: 146501696.0000 - root_mean_squared_error: 12103.7881
Epoch 33/4500
32/32 [==============================] - 0s 6ms/step - loss: 115903920.0000 - root_mean_squared_error: 10765.8682
Epoch 34/4500
32/32 [==============================] - 0s 6ms/step - loss: 108382152.0000 - root_mean_squared_error: 10410.6748
Epoch 35/4500
32/32 [==============================] - 0s 7ms/step - loss: 106303984.0000 - root_mean_squared_error: 10310.3828
Epoch 36/4500
32/32 [==============================] - 0s 6ms/step - loss: 133447600.0000 - root_mean_squared_error: 11551.9521
Epoch 37/4500
32/32 [==============================] - 0s 6ms/step - loss: 102929768.0000 - root_mean_squared_error: 10145.4307
Epoch 38/4500
32/32 [==============================] - 0s 6ms/step - loss: 87864728.0000 - root_mean_squared_error: 9373.6191
Epoch 39/4500
32/32 [==============================] - 0s 6ms/step - loss: 69752488.0000 - root_mean_squared_error: 8351.7959
Epoch 40/4500
32/32 [==============================] - 0s 6ms/step - loss: 70137256.0000 - root_mean_squared_error: 8374.7988
Epoch 41/4500
32/32 [==============================] - 0s 6ms/step - loss: 65902456.0000 - root_mean_squared_error: 8118.0327
Epoch 42/4500
32/32 [==============================] - 0s 6ms/step - loss: 63307240.0000 - root_mean_squared_error: 7956.5845
Epoch 43/4500
32/32 [==============================] - 0s 6ms/step - loss: 61015028.0000 - root_mean_squared_error: 7811.2119
Epoch 44/4500
32/32 [==============================] - 0s 6ms/step - loss: 71662112.0000 - root_mean_squared_error: 8465.3477
Epoch 45/4500
32/32 [==============================] - 0s 7ms/step - loss: 57217856.0000 - root_mean_squared_error: 7564.2485
Epoch 46/4500
32/32 [==============================] - 0s 6ms/step - loss: 59809664.0000 - root_mean_squared_error: 7733.6709
Epoch 47/4500
32/32 [==============================] - 0s 6ms/step - loss: 43860188.0000 - root_mean_squared_error: 6622.7026
Epoch 48/4500
32/32 [==============================] - 0s 6ms/step - loss: 41809780.0000 - root_mean_squared_error: 6466.0483
Epoch 49/4500
32/32 [==============================] - 0s 6ms/step - loss: 41756184.0000 - root_mean_squared_error: 6461.9023
Epoch 50/4500
32/32 [==============================] - 0s 6ms/step - loss: 42836640.0000 - root_mean_squared_error: 6544.9707
Epoch 51/4500
32/32 [==============================] - 0s 6ms/step - loss: 33305322.0000 - root_mean_squared_error: 5771.0762
Epoch 52/4500
32/32 [==============================] - 0s 6ms/step - loss: 33033078.0000 - root_mean_squared_error: 5747.4409
Epoch 53/4500
32/32 [==============================] - 0s 6ms/step - loss: 36869480.0000 - root_mean_squared_error: 6072.0244
Epoch 54/4500
32/32 [==============================] - 0s 6ms/step - loss: 46156980.0000 - root_mean_squared_error: 6793.8931
Epoch 55/4500
32/32 [==============================] - 0s 6ms/step - loss: 71318832.0000 - root_mean_squared_error: 8445.0479
Epoch 56/4500
32/32 [==============================] - 0s 6ms/step - loss: 50496540.0000 - root_mean_squared_error: 7106.0918
Epoch 57/4500
32/32 [==============================] - 0s 6ms/step - loss: 44244584.0000 - root_mean_squared_error: 6651.6602
Epoch 58/4500
32/32 [==============================] - 0s 6ms/step - loss: 36871200.0000 - root_mean_squared_error: 6072.1660
Epoch 59/4500
32/32 [==============================] - 0s 6ms/step - loss: 23630782.0000 - root_mean_squared_error: 4861.1504
Epoch 60/4500
32/32 [==============================] - 0s 6ms/step - loss: 21330590.0000 - root_mean_squared_error: 4618.5054
Epoch 61/4500
32/32 [==============================] - 0s 6ms/step - loss: 19747510.0000 - root_mean_squared_error: 4443.8169
Epoch 62/4500
32/32 [==============================] - 0s 6ms/step - loss: 23229812.0000 - root_mean_squared_error: 4819.7314
Epoch 63/4500
32/32 [==============================] - 0s 6ms/step - loss: 30793788.0000 - root_mean_squared_error: 5549.2148
Epoch 64/4500
32/32 [==============================] - 0s 6ms/step - loss: 22537402.0000 - root_mean_squared_error: 4747.3574
Epoch 65/4500
32/32 [==============================] - 0s 6ms/step - loss: 33131842.0000 - root_mean_squared_error: 5756.0264
Epoch 66/4500
32/32 [==============================] - 0s 6ms/step - loss: 32865562.0000 - root_mean_squared_error: 5732.8496
Epoch 67/4500
32/32 [==============================] - 0s 6ms/step - loss: 21770388.0000 - root_mean_squared_error: 4665.8750
Epoch 68/4500
32/32 [==============================] - 0s 6ms/step - loss: 17013942.0000 - root_mean_squared_error: 4124.7959
Epoch 69/4500
32/32 [==============================] - 0s 6ms/step - loss: 22520976.0000 - root_mean_squared_error: 4745.6270
Epoch 70/4500
32/32 [==============================] - 0s 6ms/step - loss: 39479888.0000 - root_mean_squared_error: 6283.3022
Epoch 71/4500
32/32 [==============================] - 0s 6ms/step - loss: 32496732.0000 - root_mean_squared_error: 5700.5903
Epoch 72/4500
32/32 [==============================] - 0s 6ms/step - loss: 25784390.0000 - root_mean_squared_error: 5077.8330
Epoch 73/4500
32/32 [==============================] - 0s 6ms/step - loss: 15243373.0000 - root_mean_squared_error: 3904.2764
Epoch 74/4500
32/32 [==============================] - 0s 6ms/step - loss: 14143538.0000 - root_mean_squared_error: 3760.7896
Epoch 75/4500
32/32 [==============================] - 0s 6ms/step - loss: 17944008.0000 - root_mean_squared_error: 4236.0366
Epoch 76/4500
32/32 [==============================] - 0s 6ms/step - loss: 20906334.0000 - root_mean_squared_error: 4572.3442
Epoch 77/4500
32/32 [==============================] - 0s 6ms/step - loss: 16991788.0000 - root_mean_squared_error: 4122.1099
Epoch 78/4500
32/32 [==============================] - 0s 6ms/step - loss: 27788812.0000 - root_mean_squared_error: 5271.5093
Epoch 79/4500
32/32 [==============================] - 0s 6ms/step - loss: 60558632.0000 - root_mean_squared_error: 7781.9429
Epoch 80/4500
32/32 [==============================] - 0s 6ms/step - loss: 40491604.0000 - root_mean_squared_error: 6363.3013
Epoch 81/4500
32/32 [==============================] - 0s 7ms/step - loss: 25990586.0000 - root_mean_squared_error: 5098.0962
Epoch 82/4500
32/32 [==============================] - 0s 6ms/step - loss: 23895178.0000 - root_mean_squared_error: 4888.2695
Epoch 83/4500
32/32 [==============================] - 0s 6ms/step - loss: 20182830.0000 - root_mean_squared_error: 4492.5303
Epoch 84/4500
32/32 [==============================] - 0s 6ms/step - loss: 17016172.0000 - root_mean_squared_error: 4125.0664
Epoch 85/4500
32/32 [==============================] - 0s 6ms/step - loss: 17772936.0000 - root_mean_squared_error: 4215.7959
Epoch 86/4500
32/32 [==============================] - 0s 6ms/step - loss: 13667570.0000 - root_mean_squared_error: 3696.9678
Epoch 87/4500
32/32 [==============================] - 0s 6ms/step - loss: 11584464.0000 - root_mean_squared_error: 3403.5957
Epoch 88/4500
32/32 [==============================] - 0s 6ms/step - loss: 26659608.0000 - root_mean_squared_error: 5163.2944
Epoch 89/4500
32/32 [==============================] - 0s 6ms/step - loss: 26890288.0000 - root_mean_squared_error: 5185.5845
Epoch 90/4500
32/32 [==============================] - 0s 7ms/step - loss: 20848824.0000 - root_mean_squared_error: 4566.0513
Epoch 91/4500
32/32 [==============================] - 0s 6ms/step - loss: 16104681.0000 - root_mean_squared_error: 4013.0637
Epoch 92/4500
32/32 [==============================] - 0s 6ms/step - loss: 15318917.0000 - root_mean_squared_error: 3913.9387
Epoch 93/4500
32/32 [==============================] - 0s 6ms/step - loss: 16571877.0000 - root_mean_squared_error: 4070.8569
Epoch 94/4500
32/32 [==============================] - 0s 6ms/step - loss: 17528954.0000 - root_mean_squared_error: 4186.7593
Epoch 95/4500
32/32 [==============================] - 0s 6ms/step - loss: 17124132.0000 - root_mean_squared_error: 4138.1313
Epoch 96/4500
32/32 [==============================] - 0s 6ms/step - loss: 10996335.0000 - root_mean_squared_error: 3316.0723
Epoch 97/4500
32/32 [==============================] - 0s 6ms/step - loss: 10167064.0000 - root_mean_squared_error: 3188.5835
Epoch 98/4500
32/32 [==============================] - 0s 6ms/step - loss: 12314418.0000 - root_mean_squared_error: 3509.1904
Epoch 99/4500
32/32 [==============================] - 0s 6ms/step - loss: 15911303.0000 - root_mean_squared_error: 3988.8975
Epoch 100/4500
32/32 [==============================] - 0s 6ms/step - loss: 17093420.0000 - root_mean_squared_error: 4134.4189
Epoch 101/4500
32/32 [==============================] - 0s 7ms/step - loss: 20919940.0000 - root_mean_squared_error: 4573.8320
Epoch 102/4500
32/32 [==============================] - 0s 7ms/step - loss: 23296752.0000 - root_mean_squared_error: 4826.6709
Epoch 103/4500
32/32 [==============================] - 0s 7ms/step - loss: 43403676.0000 - root_mean_squared_error: 6588.1465
Epoch 104/4500
32/32 [==============================] - 0s 7ms/step - loss: 66431792.0000 - root_mean_squared_error: 8150.5698
Epoch 105/4500
32/32 [==============================] - 0s 6ms/step - loss: 42741892.0000 - root_mean_squared_error: 6537.7285
Epoch 106/4500
32/32 [==============================] - 0s 6ms/step - loss: 137444000.0000 - root_mean_squared_error: 11723.6514
Epoch 107/4500
32/32 [==============================] - 0s 6ms/step - loss: 320492128.0000 - root_mean_squared_error: 17902.2930
Epoch 108/4500
32/32 [==============================] - 0s 6ms/step - loss: 255453072.0000 - root_mean_squared_error: 15982.8994
Epoch 109/4500
32/32 [==============================] - 0s 6ms/step - loss: 279719680.0000 - root_mean_squared_error: 16724.8223
Epoch 110/4500
32/32 [==============================] - 0s 6ms/step - loss: 115067032.0000 - root_mean_squared_error: 10726.9307
Epoch 111/4500
32/32 [==============================] - 0s 6ms/step - loss: 123152968.0000 - root_mean_squared_error: 11097.4307
Epoch 112/4500
32/32 [==============================] - 0s 6ms/step - loss: 132819408.0000 - root_mean_squared_error: 11524.7305
Epoch 113/4500
32/32 [==============================] - 0s 6ms/step - loss: 86724264.0000 - root_mean_squared_error: 9312.5859
Epoch 114/4500
32/32 [==============================] - 0s 6ms/step - loss: 30264432.0000 - root_mean_squared_error: 5501.3120
Epoch 115/4500
32/32 [==============================] - 0s 6ms/step - loss: 22960674.0000 - root_mean_squared_error: 4791.7300
Epoch 116/4500
32/32 [==============================] - 0s 6ms/step - loss: 25354108.0000 - root_mean_squared_error: 5035.2861
Epoch 117/4500
32/32 [==============================] - 0s 6ms/step - loss: 17194978.0000 - root_mean_squared_error: 4146.6826
Epoch 118/4500
32/32 [==============================] - 0s 6ms/step - loss: 12261668.0000 - root_mean_squared_error: 3501.6665
Epoch 119/4500
32/32 [==============================] - 0s 6ms/step - loss: 9269152.0000 - root_mean_squared_error: 3044.5283
Epoch 120/4500
32/32 [==============================] - 0s 6ms/step - loss: 9186651.0000 - root_mean_squared_error: 3030.9490
Epoch 121/4500
32/32 [==============================] - 0s 6ms/step - loss: 9053037.0000 - root_mean_squared_error: 3008.8264
Epoch 122/4500
32/32 [==============================] - 0s 6ms/step - loss: 7448474.5000 - root_mean_squared_error: 2729.1895
Epoch 123/4500
32/32 [==============================] - 0s 6ms/step - loss: 4213888.5000 - root_mean_squared_error: 2052.7759
Epoch 124/4500
32/32 [==============================] - 0s 6ms/step - loss: 7233473.0000 - root_mean_squared_error: 2689.5117
Epoch 125/4500
32/32 [==============================] - 0s 6ms/step - loss: 6367088.5000 - root_mean_squared_error: 2523.3091
Epoch 126/4500
32/32 [==============================] - 0s 6ms/step - loss: 10602625.0000 - root_mean_squared_error: 3256.1672
Epoch 127/4500
32/32 [==============================] - 0s 6ms/step - loss: 22203418.0000 - root_mean_squared_error: 4712.0503
Epoch 128/4500
32/32 [==============================] - 0s 6ms/step - loss: 29772630.0000 - root_mean_squared_error: 5456.4302
Epoch 129/4500
32/32 [==============================] - 0s 6ms/step - loss: 14065837.0000 - root_mean_squared_error: 3750.4448
Epoch 130/4500
32/32 [==============================] - 0s 6ms/step - loss: 12558279.0000 - root_mean_squared_error: 3543.7661
Epoch 131/4500
32/32 [==============================] - 0s 6ms/step - loss: 13937056.0000 - root_mean_squared_error: 3733.2366
Epoch 132/4500
32/32 [==============================] - 0s 6ms/step - loss: 11478595.0000 - root_mean_squared_error: 3388.0076
Epoch 133/4500
32/32 [==============================] - 0s 6ms/step - loss: 9372402.0000 - root_mean_squared_error: 3061.4380
Epoch 134/4500
32/32 [==============================] - 0s 6ms/step - loss: 13097125.0000 - root_mean_squared_error: 3618.9951
Epoch 135/4500
32/32 [==============================] - 0s 6ms/step - loss: 17817076.0000 - root_mean_squared_error: 4221.0278
Epoch 136/4500
32/32 [==============================] - 0s 6ms/step - loss: 12623054.0000 - root_mean_squared_error: 3552.8938
Epoch 137/4500
32/32 [==============================] - 0s 6ms/step - loss: 7707564.5000 - root_mean_squared_error: 2776.2500
Epoch 138/4500
32/32 [==============================] - 0s 6ms/step - loss: 8280970.0000 - root_mean_squared_error: 2877.6675
Epoch 139/4500
32/32 [==============================] - 0s 6ms/step - loss: 6233127.5000 - root_mean_squared_error: 2496.6233
Epoch 140/4500
32/32 [==============================] - 0s 6ms/step - loss: 11419193.0000 - root_mean_squared_error: 3379.2297
Epoch 141/4500
32/32 [==============================] - 0s 6ms/step - loss: 17367470.0000 - root_mean_squared_error: 4167.4297
Epoch 142/4500
32/32 [==============================] - 0s 6ms/step - loss: 15487352.0000 - root_mean_squared_error: 3935.3972
Epoch 143/4500
32/32 [==============================] - 0s 6ms/step - loss: 32524532.0000 - root_mean_squared_error: 5703.0283
Epoch 144/4500
32/32 [==============================] - 0s 6ms/step - loss: 37960824.0000 - root_mean_squared_error: 6161.2354
Epoch 145/4500
32/32 [==============================] - 0s 7ms/step - loss: 39812456.0000 - root_mean_squared_error: 6309.7114
Epoch 146/4500
32/32 [==============================] - 0s 6ms/step - loss: 16762155.0000 - root_mean_squared_error: 4094.1611
Epoch 147/4500
32/32 [==============================] - 0s 6ms/step - loss: 13670633.0000 - root_mean_squared_error: 3697.3818
Epoch 148/4500
32/32 [==============================] - 0s 6ms/step - loss: 22354976.0000 - root_mean_squared_error: 4728.1050
Epoch 149/4500
32/32 [==============================] - 0s 6ms/step - loss: 21133446.0000 - root_mean_squared_error: 4597.1128
Epoch 150/4500
32/32 [==============================] - 0s 6ms/step - loss: 13927516.0000 - root_mean_squared_error: 3731.9587
Epoch 151/4500
32/32 [==============================] - 0s 6ms/step - loss: 12497458.0000 - root_mean_squared_error: 3535.1743
Epoch 152/4500
32/32 [==============================] - 0s 6ms/step - loss: 39925176.0000 - root_mean_squared_error: 6318.6372
Epoch 153/4500
32/32 [==============================] - 0s 6ms/step - loss: 87290344.0000 - root_mean_squared_error: 9342.9297
Epoch 154/4500
32/32 [==============================] - 0s 6ms/step - loss: 71996120.0000 - root_mean_squared_error: 8485.0527
Epoch 155/4500
32/32 [==============================] - 0s 6ms/step - loss: 31586024.0000 - root_mean_squared_error: 5620.1445
Epoch 156/4500
32/32 [==============================] - 0s 6ms/step - loss: 28717266.0000 - root_mean_squared_error: 5358.8491
Epoch 157/4500
32/32 [==============================] - 0s 6ms/step - loss: 25965984.0000 - root_mean_squared_error: 5095.6831
Epoch 158/4500

**Evaluate the Model**

In [28]:
mse_test, rmse_test = model.evaluate(X_test, Y_test)

14/14 [==============================] - 0s 3ms/step - loss: 982625984.0000 - root_mean_squared_error: 31346.8652

In [29]:
rmse_test

31346.865234375