# Import libraries

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

In [2]:
import tensorflow as tf
import sklearn.metrics as sk_metrics

print(tf.__version__)
tf.random.set_seed(42)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

2.11.0

# Load the dataset

In [3]:
train_data = pd.read_csv('/kaggle/input/titanic/train.csv')
train_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
test_data = pd.read_csv('/kaggle/input/titanic/test.csv')
test_data.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

---   

## EDA

In [5]:
def preprocess(df, isTrain=False):
    df = df.drop_duplicates()
    if 'Cabin' in df.columns:
        df = df.drop(['Cabin'], axis=1)
    
    df.fillna({'Age': df['Age'].mean(), 'Fare': df['Fare'].mean(), 'Embarked': "S"}, inplace=True)
    return df

In [6]:
train_data = preprocess(train_data)
test_data = preprocess(test_data)

---

## Feature Engineering

1. Tokenize names and extract titles -> correlates with age & sex -> Might help disentangle the two features for better learning?

In [7]:
def extract_title(tokens):
    return tokens[1].split(" ")[1]

def tokenize(name):
    tokens = name.split(",")
#     print(tokens)
    title = extract_title(tokens)
    return tokens, title

def get_titles(df):
    title_lst = []
    for name in df['Name']:
        name_tokens, title = tokenize(name)
        title_lst.append(title)
    return title_lst

In [8]:
train_titles = get_titles(train_data)
train_data['Title'] = train_titles
train_data.head(5)
# print("train titles:")
# for title in set(train_titles):
#     print(title, "->", train_titles.count(title))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,Mr.
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Mrs.
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Miss.
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Mrs.
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,Mr.

In [9]:
test_titles = get_titles(test_data)
test_data['Title'] = test_titles
test_data.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Title
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,Mr.
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,Mrs.
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,Mr.
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,Mr.
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,Mrs.

**One-Hot Encoding:**

In [10]:
# Notice that features: embarked is not used for training & testing

x_train, y_train = train_data.loc[:, ['Pclass','Sex','Age', 'Parch','SibSp', 'Fare', 'Title']], train_data.loc[:, ['Survived']]
x_test = test_data.loc[:, ['Pclass','Sex','Age', 'Parch', 'SibSp', 'Fare', 'Title']]

print(x_train.shape, y_train.shape, x_test.shape)

(891, 7) (891, 1) (418, 7)

In [11]:
import category_encoders as ce

encoder = ce.OrdinalEncoder(cols=['Sex', 'Title'])

x_train = encoder.fit_transform(x_train)
x_test = encoder.transform(x_test)

In [12]:
x_train, y_train = tf.convert_to_tensor(x_train, dtype=tf.float32), tf.convert_to_tensor(y_train, dtype=tf.float32)
x_test = tf.convert_to_tensor(x_test, dtype=tf.float32)

#### Random Forest Classifier

In [13]:
import tensorflow_decision_forests as tfdf

#### Auto Hyper-param tuning:

In [14]:
# tuner = tfdf.tuner.RandomSearch(num_trials=100, use_predefined_hps=True)

# tuner.choice("num_trees", [100,200,300,400,500,600,700,800,900,1000])

# local_search_space = tuner.choice("growing_strategy", ["LOCAL"])
# local_search_space.choice("max_depth", [3, 4, 5, 6, 8])

# Build the model

In [15]:
model = tfdf.keras.RandomForestModel(name='rcf_sibsp_m', 
                                     num_trees=500,
                                     max_depth=5
                                    )

history = model.fit(x=x_train, y=y_train, verbose=1)
print(history.history)

Use /tmp/tmpyfguqv21 as temporary training directory
Reading training dataset...
Training dataset read in 0:00:05.777799. Found 891 examples.
Training model...
Model trained in 0:00:00.230634
Compiling model...

[INFO 2023-05-23T04:35:27.967081366+00:00 kernel.cc:1214] Loading model from path /tmp/tmpyfguqv21/model/ with prefix 0b3b1e97ebdf4334
[INFO 2023-05-23T04:35:28.020817679+00:00 decision_forest.cc:661] Model loaded with 500 root(s), 13992 node(s), and 7 input feature(s).
[INFO 2023-05-23T04:35:28.021074044+00:00 abstract_model.cc:1311] Engine "RandomForestOptPred" built
[INFO 2023-05-23T04:35:28.02126348+00:00 kernel.cc:1046] Use fast generic engine

WARNING: AutoGraph could not transform <function simple_ml_inference_op_with_handle at 0x7aa88d738670> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Model compiled.
{'num_examples': [891], 'accuracy': [0.8271604938271605], 'loss': [1.6339915383870554]}

In [16]:
model.summary()

Model: "rcf_sibsp_m"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
=================================================================
Total params: 1
Trainable params: 0
Non-trainable params: 1
_________________________________________________________________
Type: "RANDOM_FOREST"
Task: CLASSIFICATION
Label: "__LABEL"

Input Features (7):
	data:0.0
	data:0.1
	data:0.2
	data:0.3
	data:0.4
	data:0.5
	data:0.6

No weights

Variable Importance: INV_MEAN_MIN_DEPTH:
    1. "data:0.6"  0.395216 ################
    2. "data:0.5"  0.316351 #########
    3. "data:0.0"  0.313328 ########
    4. "data:0.1"  0.302833 #######
    5. "data:0.2"  0.248110 ###
    6. "data:0.4"  0.225574 #
    7. "data:0.3"  0.211693

Variable Importance: NUM_AS_ROOT:
    1. "data:0.6" 260.000000 ################
    2. "data:0.1" 168.000000 #########
    3. "data:0.0" 36.000000
    4. "data:0.5" 36.000000

Variable Importance: NUM_NODES:
    1. "data:0.5" 2279.000000 ################
    2. "data:0.2" 1766.000000 ###########
    3. "data:0.0" 781.000000 ###
    4. "data:0.6" 663.000000 ##
    5. "data:0.4" 530.000000 #
    6. "data:0.1" 423.000000
    7. "data:0.3" 304.000000

Variable Importance: SUM_SCORE:
    1. "data:0.6" 45463.872211 ################
    2. "data:0.1" 29058.209991 ##########
    3. "data:0.5" 20894.774659 #######
    4. "data:0.0" 20182.695389 ######
    5. "data:0.2" 10528.039148 ###
    6. "data:0.4" 6064.192380 #
    7. "data:0.3" 1554.453851



Winner takes all: true
Out-of-bag evaluation: accuracy:0.82716 logloss:1.63399
Number of trees: 500
Total number of nodes: 13992

Number of nodes by tree:
Count: 500 Average: 27.984 StdDev: 2.11086
Min: 19 Max: 31 Ignored: 0
----------------------------------------------
[ 19, 20)   1   0.20%   0.20%
[ 20, 21)   0   0.00%   0.20%
[ 21, 22)   3   0.60%   0.80%
[ 22, 23)   0   0.00%   0.80%
[ 23, 24)  13   2.60%   3.40% #
[ 24, 25)   0   0.00%   3.40%
[ 25, 26)  65  13.00%  16.40% ####
[ 26, 27)   0   0.00%  16.40%
[ 27, 28) 152  30.40%  46.80% ########
[ 28, 29)   0   0.00%  46.80%
[ 29, 30) 182  36.40%  83.20% ##########
[ 30, 31)   0   0.00%  83.20%
[ 31, 31]  84  16.80% 100.00% #####

Depth by leafs:
Count: 7246 Average: 3.89912 StdDev: 0.311535
Min: 2 Max: 4 Ignored: 0
----------------------------------------------
[ 2, 3)   23   0.32%   0.32%
[ 3, 4)  685   9.45%   9.77% #
[ 4, 4] 6538  90.23% 100.00% ##########

Number of training obs by leaf:
Count: 7246 Average: 61.4822 StdDev: 77.9358
Min: 5 Max: 475 Ignored: 0
----------------------------------------------
[   5,  28) 3624  50.01%  50.01% ##########
[  28,  52)  995  13.73%  63.75% ###
[  52,  75)  547   7.55%  71.29% ##
[  75,  99)  577   7.96%  79.26% ##
[  99, 122)  528   7.29%  86.54% #
[ 122, 146)  265   3.66%  90.20% #
[ 146, 169)  129   1.78%  91.98%
[ 169, 193)   88   1.21%  93.20%
[ 193, 216)   61   0.84%  94.04%
[ 216, 240)   48   0.66%  94.70%
[ 240, 264)   61   0.84%  95.54%
[ 264, 287)   61   0.84%  96.38%
[ 287, 311)   52   0.72%  97.10%
[ 311, 334)   51   0.70%  97.81%
[ 334, 358)   57   0.79%  98.59%
[ 358, 381)   45   0.62%  99.21%
[ 381, 405)   32   0.44%  99.65%
[ 405, 428)   18   0.25%  99.90%
[ 428, 452)    5   0.07%  99.97%
[ 452, 475]    2   0.03% 100.00%

Attribute in nodes:
	2279 : data:0.5 [NUMERICAL]
	1766 : data:0.2 [NUMERICAL]
	781 : data:0.0 [NUMERICAL]
	663 : data:0.6 [NUMERICAL]
	530 : data:0.4 [NUMERICAL]
	423 : data:0.1 [NUMERICAL]
	304 : data:0.3 [NUMERICAL]

Attribute in nodes with depth <= 0:
	260 : data:0.6 [NUMERICAL]
	168 : data:0.1 [NUMERICAL]
	36 : data:0.5 [NUMERICAL]
	36 : data:0.0 [NUMERICAL]

Attribute in nodes with depth <= 1:
	437 : data:0.0 [NUMERICAL]
	356 : data:0.6 [NUMERICAL]
	333 : data:0.5 [NUMERICAL]
	230 : data:0.1 [NUMERICAL]
	77 : data:0.4 [NUMERICAL]
	59 : data:0.2 [NUMERICAL]
	8 : data:0.3 [NUMERICAL]

Attribute in nodes with depth <= 2:
	1034 : data:0.5 [NUMERICAL]
	641 : data:0.0 [NUMERICAL]
	576 : data:0.2 [NUMERICAL]
	499 : data:0.6 [NUMERICAL]
	306 : data:0.1 [NUMERICAL]
	292 : data:0.4 [NUMERICAL]
	129 : data:0.3 [NUMERICAL]

Attribute in nodes with depth <= 3:
	2279 : data:0.5 [NUMERICAL]
	1766 : data:0.2 [NUMERICAL]
	781 : data:0.0 [NUMERICAL]
	663 : data:0.6 [NUMERICAL]
	530 : data:0.4 [NUMERICAL]
	423 : data:0.1 [NUMERICAL]
	304 : data:0.3 [NUMERICAL]

Attribute in nodes with depth <= 5:
	2279 : data:0.5 [NUMERICAL]
	1766 : data:0.2 [NUMERICAL]
	781 : data:0.0 [NUMERICAL]
	663 : data:0.6 [NUMERICAL]
	530 : data:0.4 [NUMERICAL]
	423 : data:0.1 [NUMERICAL]
	304 : data:0.3 [NUMERICAL]

Condition type in nodes:
	6746 : HigherCondition
Condition type in nodes with depth <= 0:
	500 : HigherCondition
Condition type in nodes with depth <= 1:
	1500 : HigherCondition
Condition type in nodes with depth <= 2:
	3477 : HigherCondition
Condition type in nodes with depth <= 3:
	6746 : HigherCondition
Condition type in nodes with depth <= 5:
	6746 : HigherCondition
Node format: NOT_SET

Training OOB:
	trees: 1, Out-of-bag evaluation: accuracy:0.797619 logloss:7.29455
	trees: 11, Out-of-bag evaluation: accuracy:0.825056 logloss:4.73566
	trees: 21, Out-of-bag evaluation: accuracy:0.826038 logloss:3.72578
	trees: 31, Out-of-bag evaluation: accuracy:0.824916 logloss:3.50797
	trees: 41, Out-of-bag evaluation: accuracy:0.829405 logloss:3.13847
	trees: 51, Out-of-bag evaluation: accuracy:0.826038 logloss:2.86681
	trees: 61, Out-of-bag evaluation: accuracy:0.82716 logloss:2.75407
	trees: 71, Out-of-bag evaluation: accuracy:0.828283 logloss:2.67931
	trees: 81, Out-of-bag evaluation: accuracy:0.828283 logloss:2.60881
	trees: 91, Out-of-bag evaluation: accuracy:0.82716 logloss:2.4996
	trees: 101, Out-of-bag evaluation: accuracy:0.824916 logloss:2.3911
	trees: 111, Out-of-bag evaluation: accuracy:0.826038 logloss:2.31723
	trees: 121, Out-of-bag evaluation: accuracy:0.82716 logloss:2.28449
	trees: 131, Out-of-bag evaluation: accuracy:0.82716 logloss:2.13712
	trees: 141, Out-of-bag evaluation: accuracy:0.826038 logloss:2.1358
	trees: 151, Out-of-bag evaluation: accuracy:0.82716 logloss:2.09665
	trees: 161, Out-of-bag evaluation: accuracy:0.828283 logloss:2.02843
	trees: 171, Out-of-bag evaluation: accuracy:0.828283 logloss:2.0285
	trees: 181, Out-of-bag evaluation: accuracy:0.828283 logloss:1.99349
	trees: 191, Out-of-bag evaluation: accuracy:0.829405 logloss:1.99417
	trees: 201, Out-of-bag evaluation: accuracy:0.82716 logloss:1.99225
	trees: 211, Out-of-bag evaluation: accuracy:0.82716 logloss:1.99491
	trees: 221, Out-of-bag evaluation: accuracy:0.82716 logloss:1.99079
	trees: 231, Out-of-bag evaluation: accuracy:0.82716 logloss:1.95506
	trees: 241, Out-of-bag evaluation: accuracy:0.828283 logloss:1.9556
	trees: 251, Out-of-bag evaluation: accuracy:0.82716 logloss:1.95365
	trees: 261, Out-of-bag evaluation: accuracy:0.82716 logloss:1.91765
	trees: 271, Out-of-bag evaluation: accuracy:0.82716 logloss:1.91666
	trees: 281, Out-of-bag evaluation: accuracy:0.826038 logloss:1.91482
	trees: 291, Out-of-bag evaluation: accuracy:0.82716 logloss:1.91372
	trees: 301, Out-of-bag evaluation: accuracy:0.82716 logloss:1.84069
	trees: 311, Out-of-bag evaluation: accuracy:0.82716 logloss:1.84154
	trees: 321, Out-of-bag evaluation: accuracy:0.82716 logloss:1.84241
	trees: 331, Out-of-bag evaluation: accuracy:0.82716 logloss:1.8431
	trees: 341, Out-of-bag evaluation: accuracy:0.82716 logloss:1.77327
	trees: 351, Out-of-bag evaluation: accuracy:0.826038 logloss:1.77234
	trees: 361, Out-of-bag evaluation: accuracy:0.82716 logloss:1.77202
	trees: 371, Out-of-bag evaluation: accuracy:0.82716 logloss:1.77119
	trees: 381, Out-of-bag evaluation: accuracy:0.829405 logloss:1.77172
	trees: 391, Out-of-bag evaluation: accuracy:0.82716 logloss:1.73628
	trees: 401, Out-of-bag evaluation: accuracy:0.82716 logloss:1.73674
	trees: 411, Out-of-bag evaluation: accuracy:0.826038 logloss:1.738
	trees: 421, Out-of-bag evaluation: accuracy:0.826038 logloss:1.73905
	trees: 431, Out-of-bag evaluation: accuracy:0.826038 logloss:1.73862
	trees: 441, Out-of-bag evaluation: accuracy:0.826038 logloss:1.73921
	trees: 451, Out-of-bag evaluation: accuracy:0.826038 logloss:1.73906
	trees: 461, Out-of-bag evaluation: accuracy:0.826038 logloss:1.73826
	trees: 471, Out-of-bag evaluation: accuracy:0.82716 logloss:1.73815
	trees: 481, Out-of-bag evaluation: accuracy:0.826038 logloss:1.66875
	trees: 491, Out-of-bag evaluation: accuracy:0.82716 logloss:1.63411
	trees: 500, Out-of-bag evaluation: accuracy:0.82716 logloss:1.63399

In [17]:
p=model.predict(x_train)
p[p >= 0.5] = 1
p[p  < 0.5] = 0
p = p.flatten()
print(p.shape)
# print(p)

confusion_matrix(y_train,p)
print(classification_report(y_train,p))

28/28 [==============================] - 0s 2ms/step
(891,)

NameError: name 'confusion_matrix' is not defined

In [ ]:
predictions = model.predict(x_test)
print("predictions shape:", predictions.shape)

In [ ]:
predictions[predictions >= 0.5] = 1
predictions[predictions < 0.5] = 0
predictions = predictions.flatten()
print(predictions.shape)

---

## Submission

In [ ]:
submission_df = pd.DataFrame()
submission_df['PassengerId'] = test_data['PassengerId'].copy()


submission_df['Survived'] = predictions

print(submission_df.head(5))
submission_df['Survived'] = pd.to_numeric(submission_df['Survived'], downcast='integer')

submission_df.to_csv('submission.csv', index=False)