In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv

In [2]:
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.compose import make_column_transformer, ColumnTransformer
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

In [3]:
df = pd.read_csv("../input/house-prices-advanced-regression-techniques/train.csv")
df1 = df.copy()
test_df = pd.read_csv('../input/house-prices-advanced-regression-techniques/test.csv')
test_df1 = test_df.copy()

In [4]:
df1.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

Since there are limited features, we will use all the features

In [5]:
# We shall combine the test and train data into a single table and do modifications on the datasets

tt_df = pd.concat([df1, test_df1], axis=0).reset_index()
tt_df

,index,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,NaN
2915,1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,NaN
2916,1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml,NaN
2917,1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,NaN
2918,1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,NaN

In [6]:
# Passing the "SalePrice" into a seperate variable 'target' which will be used to fit the model i.e the value to be predicted
target = tt_df.pop('SalePrice')
target = target[0:len(df1)]
target

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
1455    175000.0
1456    210000.0
1457    266500.0
1458    142125.0
1459    147500.0
Name: SalePrice, Length: 1460, dtype: float64

In [7]:
# Dropping 'index' and 'Id' columns from table as they don't contributed to predictions
tt_df.drop(['index','Id'], axis=1, inplace=True)

In [8]:
# A simple function for seperating features into numerical and categorical lists
def num_cat_seperator(dataframe):
  categorical_cols = []
  numerical_cols = []
  for col in dataframe.columns:
    
    if (dataframe[col].dtypes == 'float64') | (dataframe[col].dtypes == 'int64') :
      numerical_cols.append(col)
    else:
      categorical_cols.append(col)

  print(f'categorical column lengh: {len(categorical_cols)}')
  print(f'numerical column lengh: {len(numerical_cols)}')
  return categorical_cols, numerical_cols

In [9]:
cat, num = num_cat_seperator(tt_df)

categorical column lengh: 43
numerical column lengh: 36

In [10]:
# If we go by data description, we can observe that certain categorical columns have value 'NA' which is not 
# a missing value, but rather that the feature lacks character. We will seperate out those in a list cat1 and remove
# those from 'cat' list.

cat1 = [
        'Alley',
        'BsmtQual',
        'BsmtCond',
        'BsmtExposure',
        'BsmtFinType1',
        'BsmtFinType2',
        'FireplaceQu',
        'GarageType',
        'GarageFinish',
        'GarageQual',
        'GarageCond',
        'PoolQC',
        'Fence',
        'MiscFeature',
        ]

for item in cat1:
  cat.remove(item)
len(cat)

29

In [11]:
# Seeing the number of 'na' values in cat1. Remember these are not missing values.
tt_df[cat1].isna().sum()

Alley           2721
BsmtQual          81
BsmtCond          82
BsmtExposure      82
BsmtFinType1      79
BsmtFinType2      80
FireplaceQu     1420
GarageType       157
GarageFinish     159
GarageQual       159
GarageCond       159
PoolQC          2909
Fence           2348
MiscFeature     2814
dtype: int64

In [12]:
# Filling those 'na' values with 'None' and checking 'na' vlues gin
tt_df[cat1] = tt_df[cat1].fillna('None')
tt_df[cat1].isna().sum()

Alley           0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
PoolQC          0
Fence           0
MiscFeature     0
dtype: int64

In [13]:
# Checking 'na' values in cat list
tt_df[cat].isna().sum()

MSZoning          4
Street            0
LotShape          0
LandContour       0
Utilities         2
LotConfig         0
LandSlope         0
Neighborhood      0
Condition1        0
Condition2        0
BldgType          0
HouseStyle        0
RoofStyle         0
RoofMatl          0
Exterior1st       1
Exterior2nd       1
MasVnrType       24
ExterQual         0
ExterCond         0
Foundation        0
Heating           0
HeatingQC         0
CentralAir        0
Electrical        1
KitchenQual       1
Functional        2
PavedDrive        0
SaleType          1
SaleCondition     0
dtype: int64

In [14]:
# Imputing 'cat' values with median 
imputer = SimpleImputer(strategy='most_frequent')
tt_df[cat] = imputer.fit_transform(tt_df[cat])

# Rechecking 'na' values of 'cat' columns again
tt_df[cat].isna().sum()

MSZoning         0
Street           0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
ExterQual        0
ExterCond        0
Foundation       0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
KitchenQual      0
Functional       0
PavedDrive       0
SaleType         0
SaleCondition    0
dtype: int64

In [15]:
# Checking 'na' values of 'cat' columns
tt_df[num].isna().sum()

MSSubClass         0
LotFrontage      486
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea        23
BsmtFinSF1         1
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       2
BsmtHalfBath       2
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt      159
GarageCars         1
GarageArea         1
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
dtype: int64

In [16]:
# Fill in the 'na' values with KNNImputer
imputer = KNNImputer(n_neighbors=4)
tt_df[num] = imputer.fit_transform(tt_df[num])

# Rechecking 'na' values of 'num' columns
tt_df[num].isna().sum()

MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
dtype: int64

In [17]:
# Making a new column for total bathrooms in a house
tt_df['Tot_Bathroom'] = tt_df['BsmtFullBath'] + 0.5 * tt_df['BsmtHalfBath'] + tt_df['FullBath'] + 0.5 * tt_df['HalfBath']

In [18]:
# Making a new column based on equal weightage to 'overallcondition' and 'OverallQuality'
tt_df['Avg_Qual_Cond'] = 0.5 * tt_df['OverallCond'] + 0.5 * tt_df['OverallQual']

In [19]:
# Making a new column for Square footage per room
tt_df['Room_sqfoot'] = tt_df['GrLivArea']/ (tt_df['TotRmsAbvGrd']+tt_df['FullBath']+
                                           tt_df['HalfBath']+tt_df['KitchenAbvGr'])

In [20]:
# Making a new column for above ground Square footage
tt_df['HiQualSF'] = tt_df['1stFlrSF'] + tt_df['2ndFlrSF']

In [21]:
# The 'MoSold' feature is cyclic in nature since it accounts for seasonality. Hence we can convert it accordingly
# to account for it using sin/cosine function.
tt_df['MoSold'] = -np.cos(0.5246*tt_df['MoSold']) # Converting month to cyclic using cos function

In [22]:
# Now we can see the skew of the numerical columns
tt_df[num].skew()

MSSubClass        1.376165
LotFrontage       1.369826
LotArea          12.829025
OverallQual       0.197212
OverallCond       0.570605
YearBuilt        -0.600114
YearRemodAdd     -0.451252
MasVnrArea        2.602007
BsmtFinSF1        1.426185
BsmtFinSF2        4.148206
BsmtUnfSF         0.919488
TotalBsmtSF       1.163360
1stFlrSF          1.470360
2ndFlrSF          0.862118
LowQualFinSF     12.094977
GrLivArea         1.270010
BsmtFullBath      0.625016
BsmtHalfBath      3.933616
FullBath          0.167692
HalfBath          0.694924
BedroomAbvGr      0.326492
KitchenAbvGr      4.304467
TotRmsAbvGrd      0.758757
Fireplaces        0.733872
GarageYrBlt      -0.319375
GarageCars       -0.218705
GarageArea        0.240972
WoodDeckSF        1.843380
OpenPorchSF       2.536417
EnclosedPorch     4.005950
3SsnPorch        11.381914
ScreenPorch       3.948723
PoolArea         16.907017
MiscVal          21.958480
MoSold           -0.753812
YrSold            0.132467
dtype: float64

In [23]:
# Collecting 'num' features with skew greater than 0.5 into a seperate list 'num_skew'
num_skew = tt_df[num].skew()[tt_df[num].skew() > 0.5].index.to_list()

In [24]:
# Transforming 'num_skew' to a near normal distribution using log(1+x) function
tt_df[num_skew] = np.log1p(tt_df[num_skew])

In [25]:
# Splitting the combined into train and test table seperately
tt_train = tt_df.iloc[0:len(df1), :]
tt_test = tt_df.iloc[len(df1):len(tt_df), :]

In [26]:
# Transforming the target variable also into near normal distribution using log(x) function since target does not have 0 values
target1 = np.log(target)

In [27]:
# Making a pipeline for processing 'num' and 'cat','cat1' features seperately

cat_preprocessing = make_pipeline(
    
    OneHotEncoder(handle_unknown="ignore", sparse=False),
)

# pipeline for numerical data
num_preprocessing = make_pipeline(StandardScaler())

# combine both pipeline using a columnTransformer
preprocessing = ColumnTransformer(
    [("num", num_preprocessing, num), ("cat", cat_preprocessing, cat+cat1)]
)

preprocessing

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('standardscaler',
                                                  StandardScaler())]),
                                 ['MSSubClass', 'LotFrontage', 'LotArea',
                                  'OverallQual', 'OverallCond', 'YearBuilt',
                                  'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
                                  'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
                                  '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
                                  'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
                                  'FullBath', 'HalfBath...
                                 ['MSZoning', 'Street', 'LotShape',
                                  'LandContour', 'Utilities', 'LotConfig',
                                  'LandSlope', 'Neighborhood', 'Condition1',
                                  'Condition2', 'BldgType', 'HouseStyle',
                                  'RoofStyle', 'RoofMatl', 'Exterior1st',
                                  'Exterior2nd', 'MasVnrType', 'ExterQual',
                                  'ExterCond', 'Foundation', 'Heating',
                                  'HeatingQC', 'CentralAir', 'Electrical',
                                  'KitchenQual', 'Functional', 'PavedDrive',
                                  'SaleType', 'SaleCondition', 'Alley', ...])])

In [28]:
# Making a Pipeline for evaluation of various models by fitting the data and targets and getting the best model using
# GridSearchCV

full_pipe = Pipeline(
    [
        ("preprocess", preprocessing),
        ("regressor", RandomForestRegressor()),
    ]
)

# model tunning with GridSearch
param_grid = {
    
    "regressor": [
        
        GradientBoostingRegressor(random_state=42),
        RandomForestRegressor(random_state=42),
        XGBRegressor(random_state=42),
        #Ridge(random_state=42)
    ],
}

grid = GridSearchCV(
    full_pipe,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    return_train_score=True,
)

grid.fit(tt_train, target1)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocess',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('standardscaler',
                                                                                          StandardScaler())]),
                                                                         ['MSSubClass',
                                                                          'LotFrontage',
                                                                          'LotArea',
                                                                          'OverallQual',
                                                                          'OverallCond',
                                                                          'YearBuilt',
                                                                          'YearRemodAdd',
                                                                          'MasVnrArea',
                                                                          'BsmtFinSF1',
                                                                          'BsmtFinSF2',
                                                                          'BsmtUnfSF',
                                                                          'TotalBsmtSF',
                                                                          '1stFlrSF',
                                                                          '2ndFlrSF',
                                                                          'LowQualFinSF',
                                                                          'GrL...
                                                    interaction_constraints=None,
                                                    learning_rate=None,
                                                    max_bin=None,
                                                    max_cat_to_onehot=None,
                                                    max_delta_step=None,
                                                    max_depth=None,
                                                    max_leaves=None,
                                                    min_child_weight=None,
                                                    missing=nan,
                                                    monotone_constraints=None,
                                                    n_estimators=100,
                                                    n_jobs=None,
                                                    num_parallel_tree=None,
                                                    predictor=None,
                                                    random_state=42,
                                                    reg_alpha=None,
                                                    reg_lambda=None, ...)]},
             return_train_score=True, scoring='neg_mean_squared_error')

In [29]:
grid.best_params_

{'regressor': GradientBoostingRegressor(random_state=42)}

In [30]:
print(np.sqrt(-grid.best_score_))

0.1260178648258695

In [31]:
# We can see that GradientBoosting performed best. So we can try to tune its hyperparameters

full_pipe = Pipeline(
    [
        ("preprocess", preprocessing),
        ("regressor", GradientBoostingRegressor()),
    ]
)

param_grid = [
    {
        "regressor": [GradientBoostingRegressor(random_state=42)],
        "regressor__n_estimators": [100, 300, 500],
        "regressor__learning_rate": [0.1, 0.01],
        "regressor__max_depth": [2, 3, 5],
        "regressor__max_features": ["log2", "sqrt", "auto"],
    },
    
]


grid = GridSearchCV(
    full_pipe,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    return_train_score=True,
)

grid.fit(tt_train, target1)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocess',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('standardscaler',
                                                                                          StandardScaler())]),
                                                                         ['MSSubClass',
                                                                          'LotFrontage',
                                                                          'LotArea',
                                                                          'OverallQual',
                                                                          'OverallCond',
                                                                          'YearBuilt',
                                                                          'YearRemodAdd',
                                                                          'MasVnrArea',
                                                                          'BsmtFinSF1',
                                                                          'BsmtFinSF2',
                                                                          'BsmtUnfSF',
                                                                          'TotalBsmtSF',
                                                                          '1stFlrSF',
                                                                          '2ndFlrSF',
                                                                          'LowQualFinSF',
                                                                          'GrL...
                                        GradientBoostingRegressor())]),
             param_grid=[{'regressor': [GradientBoostingRegressor(max_features='sqrt',
                                                                  n_estimators=500,
                                                                  random_state=42)],
                          'regressor__learning_rate': [0.1, 0.01],
                          'regressor__max_depth': [2, 3, 5],
                          'regressor__max_features': ['log2', 'sqrt', 'auto'],
                          'regressor__n_estimators': [100, 300, 500]}],
             return_train_score=True, scoring='neg_mean_squared_error')

In [32]:
print(np.sqrt(-grid.best_score_)) # We can see that score has improved with tuning

0.12122169357787976

In [33]:
# Using the grid's best regressor with tuned hyperparameter to make predictions

y_pred = grid.predict(tt_test)

# Transforming the predicted values back using exponential function ( We had transformed target values using log function)
y_pred = np.exp(y_pred)

In [34]:
# Converting predicted values into Dataframe

dataframe = {'Id':test_df1.Id, 'SalePrice':y_pred}
output = pd.DataFrame(dataframe)
output

        Id      SalePrice
0     1461  122910.640982
1     1462  165926.368346
2     1463  183030.804527
3     1464  199796.095874
4     1465  187980.447284
...    ...            ...
1454  2915   80688.185171
1455  2916   80219.535411
1456  2917  177151.230189
1457  2918  115117.554911
1458  2919  219518.507108

[1459 rows x 2 columns]

In [35]:
# Making Csv file out of output dataframe

output.to_csv('submission_GrBoost_featurengg', index = False)

In [36]:
## Let's make another prediction using CatBoostRegressor through pipeline and see if it performs better

full_pipe = Pipeline(
    [
        ("preprocess", preprocessing),
        ("regressor", RandomForestRegressor()),
    ]
)

# model tunning with GridSearch
param_grid = {
    
    "regressor": [
        CatBoostRegressor(random_state=42),
        GradientBoostingRegressor(random_state=42),
        RandomForestRegressor(random_state=42),
        XGBRegressor(random_state=42),
        #Ridge(random_state=42)
    ],
}

grid = GridSearchCV(
    full_pipe,
    param_grid=param_grid,
    cv=5,
    scoring="neg_mean_squared_error",
    return_train_score=True,
)

grid.fit(tt_train, target1)

Learning rate set to 0.04196
0:	learn: 0.3912707	total: 63.3ms	remaining: 1m 3s
1:	learn: 0.3810908	total: 67.6ms	remaining: 33.7s
2:	learn: 0.3718392	total: 71.6ms	remaining: 23.8s
3:	learn: 0.3622998	total: 76.1ms	remaining: 19s
4:	learn: 0.3541861	total: 80.5ms	remaining: 16s
5:	learn: 0.3450529	total: 86.8ms	remaining: 14.4s
6:	learn: 0.3364253	total: 92.3ms	remaining: 13.1s
7:	learn: 0.3281244	total: 98.4ms	remaining: 12.2s
8:	learn: 0.3198792	total: 105ms	remaining: 11.6s
9:	learn: 0.3125751	total: 115ms	remaining: 11.3s
10:	learn: 0.3053970	total: 119ms	remaining: 10.7s
11:	learn: 0.2989446	total: 124ms	remaining: 10.2s
12:	learn: 0.2927556	total: 129ms	remaining: 9.79s
13:	learn: 0.2860005	total: 134ms	remaining: 9.46s
14:	learn: 0.2798686	total: 143ms	remaining: 9.37s
15:	learn: 0.2739877	total: 147ms	remaining: 9.07s
16:	learn: 0.2685041	total: 151ms	remaining: 8.72s
17:	learn: 0.2624777	total: 155ms	remaining: 8.43s
18:	learn: 0.2573457	total: 158ms	remaining: 8.15s
19:	learn: 0.2527472	total: 161ms	remaining: 7.9s
20:	learn: 0.2481034	total: 165ms	remaining: 7.68s
21:	learn: 0.2433937	total: 168ms	remaining: 7.48s
22:	learn: 0.2395515	total: 172ms	remaining: 7.3s
23:	learn: 0.2349628	total: 176ms	remaining: 7.15s
24:	learn: 0.2306991	total: 180ms	remaining: 7.01s
25:	learn: 0.2264349	total: 183ms	remaining: 6.86s
26:	learn: 0.2225566	total: 187ms	remaining: 6.74s
27:	learn: 0.2187156	total: 192ms	remaining: 6.66s
28:	learn: 0.2153752	total: 197ms	remaining: 6.58s
29:	learn: 0.2121080	total: 200ms	remaining: 6.47s
30:	learn: 0.2089961	total: 204ms	remaining: 6.37s
31:	learn: 0.2061773	total: 208ms	remaining: 6.28s
32:	learn: 0.2027684	total: 211ms	remaining: 6.19s
33:	learn: 0.2000623	total: 215ms	remaining: 6.09s
34:	learn: 0.1969829	total: 218ms	remaining: 6.01s
35:	learn: 0.1944684	total: 221ms	remaining: 5.93s
36:	learn: 0.1917312	total: 225ms	remaining: 5.85s
37:	learn: 0.1890986	total: 228ms	remaining: 5.78s
38:	learn: 0.1864550	total: 232ms	remaining: 5.7s
39:	learn: 0.1839564	total: 235ms	remaining: 5.64s
40:	learn: 0.1816569	total: 238ms	remaining: 5.58s
41:	learn: 0.1795247	total: 242ms	remaining: 5.51s
42:	learn: 0.1774056	total: 245ms	remaining: 5.45s
43:	learn: 0.1755145	total: 248ms	remaining: 5.4s
44:	learn: 0.1737297	total: 252ms	remaining: 5.34s
45:	learn: 0.1717153	total: 255ms	remaining: 5.29s
46:	learn: 0.1697909	total: 259ms	remaining: 5.25s
47:	learn: 0.1679367	total: 262ms	remaining: 5.2s
48:	learn: 0.1663639	total: 266ms	remaining: 5.15s
49:	learn: 0.1646975	total: 269ms	remaining: 5.12s
50:	learn: 0.1628845	total: 273ms	remaining: 5.09s
51:	learn: 0.1615562	total: 277ms	remaining: 5.05s
52:	learn: 0.1600571	total: 281ms	remaining: 5.01s
53:	learn: 0.1584905	total: 284ms	remaining: 4.98s
54:	learn: 0.1570200	total: 288ms	remaining: 4.94s
55:	learn: 0.1557120	total: 291ms	remaining: 4.91s
56:	learn: 0.1544188	total: 295ms	remaining: 4.88s
57:	learn: 0.1531643	total: 299ms	remaining: 4.85s
58:	learn: 0.1516236	total: 303ms	remaining: 4.83s
59:	learn: 0.1503146	total: 306ms	remaining: 4.79s
60:	learn: 0.1493349	total: 310ms	remaining: 4.76s
61:	learn: 0.1482739	total: 313ms	remaining: 4.73s
62:	learn: 0.1472712	total: 316ms	remaining: 4.71s
63:	learn: 0.1462238	total: 320ms	remaining: 4.67s
64:	learn: 0.1450618	total: 323ms	remaining: 4.65s
65:	learn: 0.1440845	total: 327ms	remaining: 4.62s
66:	learn: 0.1430720	total: 333ms	remaining: 4.64s
67:	learn: 0.1422173	total: 337ms	remaining: 4.62s
68:	learn: 0.1414554	total: 341ms	remaining: 4.6s
69:	learn: 0.1405423	total: 345ms	remaining: 4.58s
70:	learn: 0.1394201	total: 348ms	remaining: 4.56s
71:	learn: 0.1385182	total: 352ms	remaining: 4.54s
72:	learn: 0.1376973	total: 356ms	remaining: 4.52s
73:	learn: 0.1369506	total: 360ms	remaining: 4.5s
74:	learn: 0.1361894	total: 364ms	remaining: 4.48s
75:	learn: 0.1354543	total: 367ms	remaining: 4.47s
76:	learn: 0.1346139	total: 371ms	remaining: 4.45s
77:	learn: 0.1339389	total: 375ms	remaining: 4.43s
78:	learn: 0.1332512	total: 379ms	remaining: 4.42s
79:	learn: 0.1326527	total: 383ms	remaining: 4.4s
80:	learn: 0.1320374	total: 387ms	remaining: 4.38s
81:	learn: 0.1314726	total: 394ms	remaining: 4.41s
82:	learn: 0.1307830	total: 398ms	remaining: 4.4s
83:	learn: 0.1300718	total: 402ms	remaining: 4.39s
84:	learn: 0.1293406	total: 406ms	remaining: 4.37s
85:	learn: 0.1286747	total: 409ms	remaining: 4.34s
86:	learn: 0.1280715	total: 412ms	remaining: 4.33s
87:	learn: 0.1274458	total: 416ms	remaining: 4.31s
88:	learn: 0.1268884	total: 419ms	remaining: 4.29s
89:	learn: 0.1263226	total: 422ms	remaining: 4.27s
90:	learn: 0.1256611	total: 425ms	remaining: 4.25s
91:	learn: 0.1251224	total: 429ms	remaining: 4.23s
92:	learn: 0.1244577	total: 432ms	remaining: 4.21s
93:	learn: 0.1239700	total: 436ms	remaining: 4.2s
94:	learn: 0.1234533	total: 439ms	remaining: 4.18s
95:	learn: 0.1228325	total: 443ms	remaining: 4.17s
96:	learn: 0.1222863	total: 446ms	remaining: 4.16s
97:	learn: 0.1216427	total: 450ms	remaining: 4.14s
98:	learn: 0.1214489	total: 454ms	remaining: 4.13s
99:	learn: 0.1209081	total: 457ms	remaining: 4.11s
100:	learn: 0.1204851	total: 460ms	remaining: 4.1s
101:	learn: 0.1200041	total: 464ms	remaining: 4.09s
102:	learn: 0.1195310	total: 468ms	remaining: 4.08s
103:	learn: 0.1191083	total: 472ms	remaining: 4.06s
104:	learn: 0.1186581	total: 475ms	remaining: 4.05s
105:	learn: 0.1181757	total: 479ms	remaining: 4.04s
106:	learn: 0.1177956	total: 483ms	remaining: 4.03s
107:	learn: 0.1173369	total: 486ms	remaining: 4.02s
108:	learn: 0.1169516	total: 490ms	remaining: 4.01s
109:	learn: 0.1164832	total: 494ms	remaining: 4s
110:	learn: 0.1161613	total: 498ms	remaining: 3.99s
111:	learn: 0.1157121	total: 501ms	remaining: 3.97s
112:	learn: 0.1154284	total: 505ms	remaining: 3.96s
113:	learn: 0.1149600	total: 508ms	remaining: 3.95s
114:	learn: 0.1145897	total: 512ms	remaining: 3.94s
115:	learn: 0.1141578	total: 515ms	remaining: 3.93s
116:	learn: 0.1138459	total: 519ms	remaining: 3.92s
117:	learn: 0.1135204	total: 523ms	remaining: 3.91s
118:	learn: 0.1132027	total: 527ms	remaining: 3.9s
119:	learn: 0.1127626	total: 531ms	remaining: 3.89s
120:	learn: 0.1124261	total: 535ms	remaining: 3.88s
121:	learn: 0.1120662	total: 538ms	remaining: 3.87s
122:	learn: 0.1117754	total: 542ms	remaining: 3.87s
123:	learn: 0.1112876	total: 546ms	remaining: 3.86s
124:	learn: 0.1110366	total: 550ms	remaining: 3.85s
125:	learn: 0.1108218	total: 553ms	remaining: 3.84s
126:	learn: 0.1104782	total: 557ms	remaining: 3.83s
127:	learn: 0.1101077	total: 561ms	remaining: 3.82s
128:	learn: 0.1098110	total: 565ms	remaining: 3.81s
129:	learn: 0.1095014	total: 569ms	remaining: 3.8s
130:	learn: 0.1092976	total: 572ms	remaining: 3.8s
131:	learn: 0.1090269	total: 576ms	remaining: 3.79s
132:	learn: 0.1088391	total: 578ms	remaining: 3.77s
133:	learn: 0.1086054	total: 582ms	remaining: 3.76s
134:	learn: 0.1083921	total: 585ms	remaining: 3.75s
135:	learn: 0.1080933	total: 589ms	remaining: 3.74s
136:	learn: 0.1077411	total: 595ms	remaining: 3.75s
137:	learn: 0.1075417	total: 599ms	remaining: 3.74s
138:	learn: 0.1072717	total: 603ms	remaining: 3.73s
139:	learn: 0.1069660	total: 607ms	remaining: 3.73s
140:	learn: 0.1066028	total: 611ms	remaining: 3.72s
141:	learn: 0.1063839	total: 614ms	remaining: 3.71s
142:	learn: 0.1061804	total: 618ms	remaining: 3.7s
143:	learn: 0.1059124	total: 621ms	remaining: 3.69s
144:	learn: 0.1056264	total: 625ms	remaining: 3.69s
145:	learn: 0.1054117	total: 629ms	remaining: 3.68s
146:	learn: 0.1051477	total: 633ms	remaining: 3.67s
147:	learn: 0.1049097	total: 636ms	remaining: 3.66s
148:	learn: 0.1046719	total: 640ms	remaining: 3.65s
149:	learn: 0.1044336	total: 644ms	remaining: 3.65s
150:	learn: 0.1041098	total: 648ms	remaining: 3.64s
151:	learn: 0.1039025	total: 652ms	remaining: 3.63s
152:	learn: 0.1035279	total: 656ms	remaining: 3.63s
153:	learn: 0.1033576	total: 659ms	remaining: 3.62s
154:	learn: 0.1030895	total: 663ms	remaining: 3.61s
155:	learn: 0.1028633	total: 667ms	remaining: 3.61s
156:	learn: 0.1027196	total: 671ms	remaining: 3.6s
157:	learn: 0.1023982	total: 674ms	remaining: 3.59s
158:	learn: 0.1021591	total: 678ms	remaining: 3.59s
159:	learn: 0.1019190	total: 682ms	remaining: 3.58s
160:	learn: 0.1017389	total: 685ms	remaining: 3.57s
161:	learn: 0.1015891	total: 689ms	remaining: 3.56s
162:	learn: 0.1013627	total: 693ms	remaining: 3.56s
163:	learn: 0.1011918	total: 696ms	remaining: 3.55s
164:	learn: 0.1010453	total: 700ms	remaining: 3.54s
165:	learn: 0.1008683	total: 704ms	remaining: 3.54s
166:	learn: 0.1006252	total: 708ms	remaining: 3.53s
167:	learn: 0.1002954	total: 711ms	remaining: 3.52s
168:	learn: 0.1000659	total: 715ms	remaining: 3.52s
169:	learn: 0.0998360	total: 719ms	remaining: 3.51s
170:	learn: 0.0996470	total: 722ms	remaining: 3.5s
171:	learn: 0.0993151	total: 726ms	remaining: 3.49s
172:	learn: 0.0990622	total: 729ms	remaining: 3.49s
173:	learn: 0.0988911	total: 733ms	remaining: 3.48s
174:	learn: 0.0986748	total: 736ms	remaining: 3.47s
175:	learn: 0.0984720	total: 739ms	remaining: 3.46s
176:	learn: 0.0982821	total: 743ms	remaining: 3.45s
177:	learn: 0.0980256	total: 746ms	remaining: 3.44s
178:	learn: 0.0977362	total: 750ms	remaining: 3.44s
179:	learn: 0.0975440	total: 754ms	remaining: 3.43s
180:	learn: 0.0972380	total: 757ms	remaining: 3.43s
181:	learn: 0.0970491	total: 761ms	remaining: 3.42s
182:	learn: 0.0967780	total: 764ms	remaining: 3.41s
183:	learn: 0.0964964	total: 768ms	remaining: 3.41s
184:	learn: 0.0962109	total: 772ms	remaining: 3.4s
185:	learn: 0.0960194	total: 776ms	remaining: 3.4s
186:	learn: 0.0957423	total: 780ms	remaining: 3.39s
187:	learn: 0.0955485	total: 784ms	remaining: 3.38s
188:	learn: 0.0954141	total: 788ms	remaining: 3.38s
189:	learn: 0.0951004	total: 792ms	remaining: 3.38s
190:	learn: 0.0948347	total: 797ms	remaining: 3.38s
191:	learn: 0.0946950	total: 801ms	remaining: 3.37s
192:	learn: 0.0945984	total: 805ms	remaining: 3.36s
193:	learn: 0.0944945	total: 809ms	remaining: 3.36s
194:	learn: 0.0943935	total: 814ms	remaining: 3.36s
195:	learn: 0.0941748	total: 820ms	remaining: 3.36s
196:	learn: 0.0940053	total: 825ms	remaining: 3.36s
197:	learn: 0.0938791	total: 829ms	remaining: 3.36s
198:	learn: 0.0936664	total: 834ms	remaining: 3.35s
199:	learn: 0.0935907	total: 838ms	remaining: 3.35s
200:	learn: 0.0934162	total: 844ms	remaining: 3.35s
201:	learn: 0.0932670	total: 848ms	remaining: 3.35s
202:	learn: 0.0930738	total: 852ms	remaining: 3.35s
203:	learn: 0.0929050	total: 857ms	remaining: 3.34s
204:	learn: 0.0926822	total: 862ms	remaining: 3.34s
205:	learn: 0.0925338	total: 867ms	remaining: 3.34s
206:	learn: 0.0923624	total: 872ms	remaining: 3.34s
207:	learn: 0.0921683	total: 877ms	remaining: 3.34s
208:	learn: 0.0920533	total: 881ms	remaining: 3.33s
209:	learn: 0.0918842	total: 885ms	remaining: 3.33s
210:	learn: 0.0917097	total: 890ms	remaining: 3.33s
211:	learn: 0.0914904	total: 894ms	remaining: 3.32s
212:	learn: 0.0913402	total: 898ms	remaining: 3.32s
213:	learn: 0.0911953	total: 902ms	remaining: 3.31s
214:	learn: 0.0910690	total: 906ms	remaining: 3.31s
215:	learn: 0.0908941	total: 910ms	remaining: 3.3s
216:	learn: 0.0906964	total: 915ms	remaining: 3.3s
217:	learn: 0.0905601	total: 919ms	remaining: 3.29s
218:	learn: 0.0904352	total: 923ms	remaining: 3.29s
219:	learn: 0.0903397	total: 927ms	remaining: 3.29s
220:	learn: 0.0901964	total: 931ms	remaining: 3.28s
221:	learn: 0.0901274	total: 935ms	remaining: 3.28s
222:	learn: 0.0900179	total: 939ms	remaining: 3.27s
223:	learn: 0.0899556	total: 944ms	remaining: 3.27s
224:	learn: 0.0899084	total: 948ms	remaining: 3.26s
225:	learn: 0.0897460	total: 952ms	remaining: 3.26s
226:	learn: 0.0895873	total: 956ms	remaining: 3.26s
227:	learn: 0.0894044	total: 961ms	remaining: 3.25s
228:	learn: 0.0892651	total: 965ms	remaining: 3.25s
229:	learn: 0.0891509	total: 969ms	remaining: 3.24s
230:	learn: 0.0889988	total: 973ms	remaining: 3.24s
231:	learn: 0.0888923	total: 978ms	remaining: 3.24s
232:	learn: 0.0886594	total: 982ms	remaining: 3.23s
233:	learn: 0.0885528	total: 986ms	remaining: 3.23s
234:	learn: 0.0884049	total: 992ms	remaining: 3.23s
235:	learn: 0.0882460	total: 997ms	remaining: 3.23s
236:	learn: 0.0880340	total: 1s	remaining: 3.22s
237:	learn: 0.0878132	total: 1.01s	remaining: 3.22s
238:	learn: 0.0876081	total: 1.01s	remaining: 3.22s
239:	learn: 0.0874383	total: 1.01s	remaining: 3.21s
240:	learn: 0.0873035	total: 1.02s	remaining: 3.21s
241:	learn: 0.0872136	total: 1.02s	remaining: 3.21s
242:	learn: 0.0871028	total: 1.03s	remaining: 3.2s
243:	learn: 0.0868991	total: 1.03s	remaining: 3.2s
244:	learn: 0.0866916	total: 1.04s	remaining: 3.19s
245:	learn: 0.0865012	total: 1.04s	remaining: 3.19s
246:	learn: 0.0863002	total: 1.04s	remaining: 3.19s
247:	learn: 0.0862068	total: 1.05s	remaining: 3.18s
248:	learn: 0.0860382	total: 1.05s	remaining: 3.18s
249:	learn: 0.0859882	total: 1.06s	remaining: 3.17s
250:	learn: 0.0858921	total: 1.06s	remaining: 3.17s
251:	learn: 0.0858565	total: 1.07s	remaining: 3.17s
252:	learn: 0.0857563	total: 1.07s	remaining: 3.16s
253:	learn: 0.0855695	total: 1.07s	remaining: 3.16s
254:	learn: 0.0854099	total: 1.08s	remaining: 3.15s
255:	learn: 0.0853759	total: 1.08s	remaining: 3.15s
256:	learn: 0.0852581	total: 1.09s	remaining: 3.15s
257:	learn: 0.0851018	total: 1.09s	remaining: 3.14s
258:	learn: 0.0850300	total: 1.1s	remaining: 3.14s
259:	learn: 0.0848643	total: 1.1s	remaining: 3.13s
260:	learn: 0.0847775	total: 1.11s	remaining: 3.13s
261:	learn: 0.0846086	total: 1.12s	remaining: 3.15s
262:	learn: 0.0844255	total: 1.12s	remaining: 3.14s
263:	learn: 0.0843418	total: 1.13s	remaining: 3.14s
264:	learn: 0.0842097	total: 1.13s	remaining: 3.13s
265:	learn: 0.0840920	total: 1.14s	remaining: 3.13s
266:	learn: 0.0838650	total: 1.14s	remaining: 3.13s
267:	learn: 0.0837354	total: 1.14s	remaining: 3.13s
268:	learn: 0.0835597	total: 1.15s	remaining: 3.12s
269:	learn: 0.0834393	total: 1.15s	remaining: 3.12s
270:	learn: 0.0833289	total: 1.16s	remaining: 3.12s
271:	learn: 0.0830960	total: 1.16s	remaining: 3.11s
272:	learn: 0.0830235	total: 1.17s	remaining: 3.11s
273:	learn: 0.0828493	total: 1.17s	remaining: 3.1s
274:	learn: 0.0827019	total: 1.18s	remaining: 3.1s
275:	learn: 0.0825242	total: 1.18s	remaining: 3.1s
276:	learn: 0.0823521	total: 1.19s	remaining: 3.1s
277:	learn: 0.0822018	total: 1.19s	remaining: 3.1s
278:	learn: 0.0821231	total: 1.2s	remaining: 3.1s
279:	learn: 0.0819867	total: 1.2s	remaining: 3.09s
280:	learn: 0.0818151	total: 1.21s	remaining: 3.09s
281:	learn: 0.0816574	total: 1.21s	remaining: 3.09s
282:	learn: 0.0815021	total: 1.22s	remaining: 3.09s
283:	learn: 0.0814128	total: 1.22s	remaining: 3.08s
284:	learn: 0.0812415	total: 1.23s	remaining: 3.08s
285:	learn: 0.0810779	total: 1.23s	remaining: 3.07s
286:	learn: 0.0809918	total: 1.24s	remaining: 3.07s
287:	learn: 0.0808930	total: 1.24s	remaining: 3.07s
288:	learn: 0.0807888	total: 1.24s	remaining: 3.06s
289:	learn: 0.0806285	total: 1.25s	remaining: 3.06s
290:	learn: 0.0805035	total: 1.25s	remaining: 3.05s
291:	learn: 0.0803568	total: 1.26s	remaining: 3.05s
292:	learn: 0.0802321	total: 1.26s	remaining: 3.04s
293:	learn: 0.0801021	total: 1.27s	remaining: 3.04s
294:	learn: 0.0799173	total: 1.27s	remaining: 3.04s
295:	learn: 0.0798326	total: 1.27s	remaining: 3.03s
296:	learn: 0.0796936	total: 1.28s	remaining: 3.03s
297:	learn: 0.0795339	total: 1.28s	remaining: 3.02s
298:	learn: 0.0794396	total: 1.29s	remaining: 3.02s
299:	learn: 0.0793293	total: 1.29s	remaining: 3.02s
300:	learn: 0.0791442	total: 1.3s	remaining: 3.01s
301:	learn: 0.0790417	total: 1.3s	remaining: 3.01s
302:	learn: 0.0789813	total: 1.31s	remaining: 3.01s
303:	learn: 0.0789159	total: 1.31s	remaining: 3s
304:	learn: 0.0788202	total: 1.31s	remaining: 3s
305:	learn: 0.0787232	total: 1.32s	remaining: 2.99s
306:	learn: 0.0786617	total: 1.32s	remaining: 2.99s
307:	learn: 0.0785729	total: 1.33s	remaining: 2.99s
308:	learn: 0.0784096	total: 1.34s	remaining: 2.99s
309:	learn: 0.0783481	total: 1.34s	remaining: 2.99s
310:	learn: 0.0781577	total: 1.35s	remaining: 2.99s
311:	learn: 0.0780124	total: 1.35s	remaining: 2.98s
312:	learn: 0.0779349	total: 1.36s	remaining: 2.98s
313:	learn: 0.0778580	total: 1.36s	remaining: 2.97s
314:	learn: 0.0777225	total: 1.37s	remaining: 2.98s
315:	learn: 0.0775939	total: 1.37s	remaining: 2.98s
316:	learn: 0.0774473	total: 1.38s	remaining: 2.97s
317:	learn: 0.0772849	total: 1.38s	remaining: 2.97s
318:	learn: 0.0771698	total: 1.39s	remaining: 2.97s
319:	learn: 0.0770605	total: 1.4s	remaining: 2.97s
320:	learn: 0.0769179	total: 1.4s	remaining: 2.97s
321:	learn: 0.0767812	total: 1.41s	remaining: 2.97s
322:	learn: 0.0767199	total: 1.41s	remaining: 2.96s
323:	learn: 0.0766019	total: 1.42s	remaining: 2.96s
324:	learn: 0.0764893	total: 1.42s	remaining: 2.96s
325:	learn: 0.0763575	total: 1.43s	remaining: 2.95s
326:	learn: 0.0762970	total: 1.43s	remaining: 2.95s
327:	learn: 0.0761609	total: 1.44s	remaining: 2.94s
328:	learn: 0.0760444	total: 1.44s	remaining: 2.94s
329:	learn: 0.0759871	total: 1.45s	remaining: 2.94s
330:	learn: 0.0758428	total: 1.45s	remaining: 2.94s
331:	learn: 0.0757734	total: 1.46s	remaining: 2.93s
332:	learn: 0.0756315	total: 1.46s	remaining: 2.93s
333:	learn: 0.0754700	total: 1.47s	remaining: 2.92s
334:	learn: 0.0754527	total: 1.47s	remaining: 2.92s
335:	learn: 0.0753133	total: 1.47s	remaining: 2.91s
336:	learn: 0.0751771	total: 1.48s	remaining: 2.91s
337:	learn: 0.0750481	total: 1.48s	remaining: 2.9s
338:	learn: 0.0750284	total: 1.49s	remaining: 2.9s
339:	learn: 0.0749555	total: 1.49s	remaining: 2.9s
340:	learn: 0.0748629	total: 1.5s	remaining: 2.89s
341:	learn: 0.0747589	total: 1.5s	remaining: 2.89s
342:	learn: 0.0746526	total: 1.5s	remaining: 2.88s
343:	learn: 0.0744943	total: 1.51s	remaining: 2.88s
344:	learn: 0.0743748	total: 1.51s	remaining: 2.87s
345:	learn: 0.0742479	total: 1.52s	remaining: 2.88s
346:	learn: 0.0742235	total: 1.53s	remaining: 2.88s
347:	learn: 0.0740504	total: 1.53s	remaining: 2.87s
348:	learn: 0.0739431	total: 1.54s	remaining: 2.87s
349:	learn: 0.0738891	total: 1.54s	remaining: 2.86s
350:	learn: 0.0737720	total: 1.54s	remaining: 2.86s
351:	learn: 0.0737072	total: 1.55s	remaining: 2.85s
352:	learn: 0.0736132	total: 1.55s	remaining: 2.85s
353:	learn: 0.0734967	total: 1.56s	remaining: 2.84s
354:	learn: 0.0733713	total: 1.56s	remaining: 2.84s
355:	learn: 0.0732928	total: 1.57s	remaining: 2.83s
356:	learn: 0.0732779	total: 1.57s	remaining: 2.83s
357:	learn: 0.0732157	total: 1.58s	remaining: 2.83s
358:	learn: 0.0730722	total: 1.58s	remaining: 2.82s
359:	learn: 0.0730397	total: 1.58s	remaining: 2.82s
360:	learn: 0.0729881	total: 1.59s	remaining: 2.81s
361:	learn: 0.0728159	total: 1.6s	remaining: 2.81s
362:	learn: 0.0726550	total: 1.6s	remaining: 2.81s
363:	learn: 0.0725635	total: 1.6s	remaining: 2.8s
364:	learn: 0.0724518	total: 1.61s	remaining: 2.8s
365:	learn: 0.0724230	total: 1.61s	remaining: 2.79s
366:	learn: 0.0723133	total: 1.62s	remaining: 2.79s
367:	learn: 0.0721184	total: 1.62s	remaining: 2.79s
368:	learn: 0.0720092	total: 1.63s	remaining: 2.78s
369:	learn: 0.0719167	total: 1.63s	remaining: 2.78s
370:	learn: 0.0718676	total: 1.63s	remaining: 2.77s
371:	learn: 0.0717189	total: 1.64s	remaining: 2.77s
372:	learn: 0.0716692	total: 1.64s	remaining: 2.76s
373:	learn: 0.0715114	total: 1.65s	remaining: 2.76s
374:	learn: 0.0713788	total: 1.65s	remaining: 2.75s
375:	learn: 0.0712121	total: 1.66s	remaining: 2.75s
376:	learn: 0.0711164	total: 1.66s	remaining: 2.75s
377:	learn: 0.0709936	total: 1.67s	remaining: 2.74s
378:	learn: 0.0708692	total: 1.67s	remaining: 2.73s
379:	learn: 0.0707104	total: 1.67s	remaining: 2.73s
380:	learn: 0.0706124	total: 1.68s	remaining: 2.73s
381:	learn: 0.0705277	total: 1.68s	remaining: 2.72s
382:	learn: 0.0703880	total: 1.69s	remaining: 2.72s
383:	learn: 0.0703017	total: 1.69s	remaining: 2.71s
384:	learn: 0.0702291	total: 1.69s	remaining: 2.71s
385:	learn: 0.0701099	total: 1.7s	remaining: 2.7s
386:	learn: 0.0700379	total: 1.7s	remaining: 2.7s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocess',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('standardscaler',
                                                                                          StandardScaler())]),
                                                                         ['MSSubClass',
                                                                          'LotFrontage',
                                                                          'LotArea',
                                                                          'OverallQual',
                                                                          'OverallCond',
                                                                          'YearBuilt',
                                                                          'YearRemodAdd',
                                                                          'MasVnrArea',
                                                                          'BsmtFinSF1',
                                                                          'BsmtFinSF2',
                                                                          'BsmtUnfSF',
                                                                          'TotalBsmtSF',
                                                                          '1stFlrSF',
                                                                          '2ndFlrSF',
                                                                          'LowQualFinSF',
                                                                          'GrL...
                                                    interaction_constraints=None,
                                                    learning_rate=None,
                                                    max_bin=None,
                                                    max_cat_to_onehot=None,
                                                    max_delta_step=None,
                                                    max_depth=None,
                                                    max_leaves=None,
                                                    min_child_weight=None,
                                                    missing=nan,
                                                    monotone_constraints=None,
                                                    n_estimators=100,
                                                    n_jobs=None,
                                                    num_parallel_tree=None,
                                                    predictor=None,
                                                    random_state=42,
                                                    reg_alpha=None,
                                                    reg_lambda=None, ...)]},
             return_train_score=True, scoring='neg_mean_squared_error')

In [37]:
print(np.sqrt(-grid.best_score_))

0.11915202607198713

In [38]:
print(grid.best_params_)

{'regressor': <catboost.core.CatBoostRegressor object at 0x7f065fa96650>}

In [39]:
# Using CatBoostRegressor to predict through grid

y_pred1 = grid.predict(tt_test)

# Transforming predictions back using exponential function
y_pred1 = np.exp(y_pred1)

In [40]:
# Converting to Dataframe

dataframe1 = {'Id':test_df1.Id, 'SalePrice':y_pred1}
output1 = pd.DataFrame(dataframe1)
output1

        Id      SalePrice
0     1461  124724.637137
1     1462  157790.034726
2     1463  185338.819083
3     1464  193767.430304
4     1465  183724.995622
...    ...            ...
1454  2915   81606.686570
1455  2916   81590.608672
1456  2917  166379.654093
1457  2918  112756.193360
1458  2919  231649.018149

[1459 rows x 2 columns]

In [41]:
output1.to_csv('submission_CatBoost_featurengg',index = False)

In [42]:
# Combining Catboost and Gradient Boosting predictions with weightage of 0.6 & 0.4 respectively 
dataframe3 = {'Id':test_df1.Id, 'SalePrice':(0.6*y_pred1+0.4*y_pred)}
output2 = pd.DataFrame(dataframe3)
output2

        Id      SalePrice
0     1461  123999.038675
1     1462  161044.568174
2     1463  184415.613261
3     1464  196178.896532
4     1465  185427.176287
...    ...            ...
1454  2915   81239.286010
1455  2916   81042.179368
1456  2917  170688.284531
1457  2918  113700.737980
1458  2919  226796.813733

[1459 rows x 2 columns]

In [43]:
output2.to_csv('submission_CatBoost_GrBoost_featurengg',index = False)