## version 2021/04/08

In [1]:
!pip install evalml

Collecting evalml
  Downloading evalml-0.22.0-py3-none-any.whl (6.2 MB)
     |████████████████████████████████| 6.2 MB 1.2 MB/s
Requirement already satisfied: networkx>=2.5 in /opt/conda/lib/python3.7/site-packages (from evalml) (2.5)
Requirement already satisfied: matplotlib>=3.3.3 in /opt/conda/lib/python3.7/site-packages (from evalml) (3.4.0)
Collecting lightgbm<3.1.0,>=2.3.1
  Downloading lightgbm-3.0.0-py2.py3-none-manylinux1_x86_64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 25.5 MB/s
Requirement already satisfied: psutil>=5.6.3 in /opt/conda/lib/python3.7/site-packages (from evalml) (5.8.0)
Requirement already satisfied: statsmodels>=0.12.2 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.12.2)
Requirement already satisfied: imbalanced-learn>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.8.0)
Collecting requirements-parser>=0.2.0
  Downloading requirements-parser-0.2.0.tar.gz (6.3 kB)
Collecting graphviz>=0.13
  Downloading graphviz-0.16-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: scikit-optimize>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.8.1)
Requirement already satisfied: click>=7.0.0 in /opt/conda/lib/python3.7/site-packages (from evalml) (7.1.2)
Requirement already satisfied: featuretools>=0.20.0 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.23.2)
Collecting pyzmq<22.0.0
  Downloading pyzmq-21.0.2-cp37-cp37m-manylinux1_x86_64.whl (6.7 MB)
     |████████████████████████████████| 6.7 MB 17.8 MB/s
Requirement already satisfied: plotly>=4.14.0 in /opt/conda/lib/python3.7/site-packages (from evalml) (4.14.3)
Collecting sktime>=0.5.3
  Downloading sktime-0.6.0-cp37-cp37m-manylinux2014_x86_64.whl (5.7 MB)
     |████████████████████████████████| 5.7 MB 16.7 MB/s
Requirement already satisfied: texttable>=1.6.2 in /opt/conda/lib/python3.7/site-packages (from evalml) (1.6.3)
Requirement already satisfied: shap>=0.35.0 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.39.0)
Requirement already satisfied: category-encoders>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from evalml) (2.2.2)
Requirement already satisfied: catboost>=0.20 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.25)
Requirement already satisfied: scipy>=1.2.1 in /opt/conda/lib/python3.7/site-packages (from evalml) (1.5.4)
Requirement already satisfied: cloudpickle>=0.2.2 in /opt/conda/lib/python3.7/site-packages (from evalml) (1.6.0)
Collecting woodwork==0.0.11
  Downloading woodwork-0.0.11-py3-none-any.whl (91 kB)
     |████████████████████████████████| 91 kB 6.4 MB/s
Requirement already satisfied: ipywidgets>=7.5 in /opt/conda/lib/python3.7/site-packages (from evalml) (7.6.3)
Collecting nlp-primitives>=1.1.0
  Downloading nlp_primitives-1.1.0-py3-none-any.whl (18.0 MB)
     |████████████████████████████████| 18.0 MB 24.3 MB/s
Requirement already satisfied: scikit-learn>=0.23.1 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.24.1)
Requirement already satisfied: colorama in /opt/conda/lib/python3.7/site-packages (from evalml) (0.4.4)
Requirement already satisfied: seaborn>=0.11.1 in /opt/conda/lib/python3.7/site-packages (from evalml) (0.11.1)
Requirement already satisfied: numpy>=1.19.1 in /opt/conda/lib/python3.7/site-packages (from evalml) (1.19.5)
Collecting kaleido>=0.1.0
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     |████████████████████████████████| 79.9 MB 167 kB/s
Collecting xgboost<1.3.0,>=0.82
  Downloading xgboost-1.2.1-py3-none-manylinux2010_x86_64.whl (148.9 MB)
     |████████████████████████████████| 148.9 MB 78 kB/s
Requirement already satisfied: pandas>=1.1.0 in /opt/conda/lib/python3.7/site-packages (from evalml) (1.2.2)
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from catboost>=0.20->evalml) (1.15.0)
Requirement already satisfied: patsy>=0.5.1 in /opt/conda/lib/python3.7/site-packages (from category-encoders>=2.0.0->evalml) (0.5.1)
Requirement already satisfied: dask[dataframe]>=2.12.0 in /opt/conda/lib/python3.7/site-packages (from featuretools>=0.20.0->evalml) (2021.3.1)
Requirement already satisfied: distributed>=2.12.0 in /opt/conda/lib/python3.7/site-packages (from featuretools>=0.20.0->evalml) (2021.3.1)
Requirement already satisfied: tqdm>=4.32.0 in /opt/conda/lib/python3.7/site-packages (from featuretools>=0.20.0->evalml) (4.56.2)
Requirement already satisfied: pyyaml>=3.12 in /opt/conda/lib/python3.7/site-packages (from featuretools>=0.20.0->evalml) (5.3.1)
Requirement already satisfied: fsspec>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from dask[dataframe]>=2.12.0->featuretools>=0.20.0->evalml) (0.8.5)
Requirement already satisfied: toolz>=0.8.2 in /opt/conda/lib/python3.7/site-packages (from dask[dataframe]>=2.12.0->featuretools>=0.20.0->evalml) (0.11.1)
Requirement already satisfied: partd>=0.3.10 in /opt/conda/lib/python3.7/site-packages (from dask[dataframe]>=2.12.0->featuretools>=0.20.0->evalml) (1.1.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from distributed>=2.12.0->featuretools>=0.20.0->evalml) (49.6.0.post20210108)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /opt/conda/lib/python3.7/site-packages (from distributed>=2.12.0->featuretools>=0.20.0->evalml) (2.3.0)
Requirement already satisfied: zict>=0.1.3 in /opt/conda/lib/python3.7/site-packages (from distributed>=2.12.0->featuretools>=0.20.0->evalml) (2.0.0)
Requirement already satisfied: tornado>=5 in /opt/conda/lib/python3.7/site-packages (from distributed>=2.12.0->featuretools>=0.20.0->evalml) (5.0.2)
Requirement already satisfied: tblib>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from distributed>=2.12.0->featuretools>=0.20.0->evalml) (1.7.0)
Requirement already satisfied: msgpack>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from distributed>=2.12.0->featuretools>=0.20.0->evalml) (1.0.2)
Requirement already satisfied: joblib>=0.11 in /opt/conda/lib/python3.7/site-packages (from imbalanced-learn>=0.7.0->evalml) (1.0.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.5->evalml) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.5->evalml) (5.1.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.5->evalml) (1.0.0)
Requirement already satisfied: traitlets>=4.3.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.5->evalml) (5.0.5)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.5->evalml) (5.1.1)
Requirement already satisfied: ipython>=4.0.0 in /opt/conda/lib/python3.7/site-packages (from ipywidgets>=7.5->evalml) (7.20.0)
Requirement already satisfied: jupyter-client in /opt/conda/lib/python3.7/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.5->evalml) (6.1.11)
Requirement already satisfied: pickleshare in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.7.5)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (4.8.0)
Requirement already satisfied: backcall in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.17.2)
Requirement already satisfied: pygments in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (2.8.0)
Requirement already satisfied: decorator in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (3.0.16)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /opt/conda/lib/python3.7/site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.7.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.3->evalml) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.3->evalml) (2.8.1)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.3->evalml) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.3->evalml) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.7/site-packages (from matplotlib>=3.3.3->evalml) (7.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.5->evalml) (3.2.0)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.5->evalml) (0.2.0)
Requirement already satisfied: jupyter-core in /opt/conda/lib/python3.7/site-packages (from nbformat>=4.2.0->ipywidgets>=7.5->evalml) (4.7.1)
Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (3.4.0)
Requirement already satisfied: attrs>=17.4.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (0.17.3)
Collecting nltk>=3.4.5
  Downloading nltk-3.6.1-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 27.5 MB/s
Requirement already satisfied: regex in /opt/conda/lib/python3.7/site-packages (from nltk>=3.4.5->nlp-primitives>=1.1.0->evalml) (2020.11.13)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=1.1.0->evalml) (2021.1)
Requirement already satisfied: locket in /opt/conda/lib/python3.7/site-packages (from partd>=0.3.10->dask[dataframe]>=2.12.0->featuretools>=0.20.0->evalml) (0.2.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.7/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.7.0)
Requirement already satisfied: retrying>=1.3.3 in /opt/conda/lib/python3.7/site-packages (from plotly>=4.14.0->evalml) (1.3.3)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.2.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from scikit-learn>=0.23.1->evalml) (2.1.0)
Requirement already satisfied: pyaml>=16.9 in /opt/conda/lib/python3.7/site-packages (from scikit-optimize>=0.8.1->evalml) (20.4.0)
Requirement already satisfied: slicer==0.0.7 in /opt/conda/lib/python3.7/site-packages (from shap>=0.35.0->evalml) (0.0.7)
Requirement already satisfied: numba in /opt/conda/lib/python3.7/site-packages (from shap>=0.35.0->evalml) (0.52.0)
Requirement already satisfied: wheel in /opt/conda/lib/python3.7/site-packages (from sktime>=0.5.3->evalml) (0.36.2)
Requirement already satisfied: llvmlite<0.36,>=0.35.0 in /opt/conda/lib/python3.7/site-packages (from numba->shap>=0.35.0->evalml) (0.35.0)
Requirement already satisfied: notebook>=4.4.1 in /opt/conda/lib/python3.7/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (5.5.0)
Requirement already satisfied: terminado>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.9.2)
Requirement already satisfied: nbconvert in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (6.0.7)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (2.11.3)
Requirement already satisfied: Send2Trash in /opt/conda/lib/python3.7/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (1.5.0)
Requirement already satisfied: heapdict in /opt/conda/lib/python3.7/site-packages (from zict>=0.1.3->distributed>=2.12.0->featuretools>=0.20.0->evalml) (1.0.1)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (3.7.4.3)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.7/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (1.1.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (1.4.2)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.5.2)
Requirement already satisfied: entrypoints>=0.2.2 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.3)
Requirement already satisfied: testpath in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.4.4)
Requirement already satisfied: defusedxml in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.6.0)
Requirement already satisfied: jupyterlab-pygments in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.1.2)
Requirement already satisfied: bleach in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (3.3.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /opt/conda/lib/python3.7/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.8.4)
Requirement already satisfied: nest-asyncio in /opt/conda/lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (1.4.3)
Requirement already satisfied: async-generator in /opt/conda/lib/python3.7/site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (1.10)
Requirement already satisfied: packaging in /opt/conda/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (20.9)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.7/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.5.1)
Building wheels for collected packages: requirements-parser
  Building wheel for requirements-parser (setup.py) ... - \ done
  Created wheel for requirements-parser: filename=requirements_parser-0.2.0-py3-none-any.whl size=7655 sha256=ea2a0e5493379493e5959608a5c00c8c5136ac327af49b9b56599e1358b281ee
  Stored in directory: /root/.cache/pip/wheels/40/e4/ca/8af24ee94c3863d620d6a52793d82930f4d1d3515a5121d495
Successfully built requirements-parser
Installing collected packages: pyzmq, nltk, graphviz, xgboost, woodwork, sktime, requirements-parser, nlp-primitives, lightgbm, kaleido, evalml
  Attempting uninstall: pyzmq
    Found existing installation: pyzmq 22.0.3
    Uninstalling pyzmq-22.0.3:
      Successfully uninstalled pyzmq-22.0.3
  Attempting uninstall: nltk
    Found existing installation: nltk 3.2.4
    Uninstalling nltk-3.2.4:
      Successfully uninstalled nltk-3.2.4
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.8.4
    Uninstalling graphviz-0.8.4:
      Successfully uninstalled graphviz-0.8.4
  Attempting uninstall: xgboost
    Found existing installation: xgboost 1.3.3
    Uninstalling xgboost-1.3.3:
      Successfully uninstalled xgboost-1.3.3
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 3.1.1
    Uninstalling lightgbm-3.1.1:
      Successfully uninstalled lightgbm-3.1.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
preprocessing 0.1.13 requires nltk==3.2.4, but you have nltk 3.6.1 which is incompatible.
mxnet 1.8.0.post0 requires graphviz<0.9.0,>=0.8.1, but you have graphviz 0.16 which is incompatible.
jupyterlab-git 0.11.0 requires nbdime<2.0.0,>=1.1.0, but you have nbdime 2.1.0 which is incompatible.
autogluon-core 0.1.0 requires graphviz<0.9.0,>=0.8.1, but you have graphviz 0.16 which is incompatible.
Successfully installed evalml-0.22.0 graphviz-0.16 kaleido-0.2.1 lightgbm-3.0.0 nlp-primitives-1.1.0 nltk-3.6.1 pyzmq-21.0.2 requirements-parser-0.2.0 sktime-0.6.0 woodwork-0.0.11 xgboost-1.2.1

In [2]:
import pandas as pd
from evalml.automl import AutoMLSearch

train = pd.read_csv('../input/titanic/train.csv')
test = pd.read_csv('../input/titanic/test.csv')
submission = pd.read_csv('../input/titanic/gender_submission.csv')
label = 'Survived'

X_train = train.drop(columns=[label])
y_train = train[label]

automl = AutoMLSearch(X_train=X_train,y_train=y_train,problem_type='binary')
automl.search()
automl.rankings

Using default limit of max_batches=1.

Generating pipelines to search over...

*****************************
* Beginning pipeline search *
*****************************

Optimizing for Log Loss Binary.
Lower score is better.

Using SequentialEngine to train and score pipelines.
Searching up to 1 batches for a total of 9 pipelines.
Allowed model families: decision_tree, extra_trees, random_forest, linear_model, xgboost, catboost, lightgbm

FigureWidget({
    'data': [{'mode': 'lines+markers',
              'name': 'Best Score',
              'type'…

Batch 1: (1/9) Mode Baseline Binary Classification P... Elapsed:00:00
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 13.257
Batch 1: (2/9) Decision Tree Classifier w/ Imputer +... Elapsed:00:00
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 1.363
High coefficient of variation (cv >= 0.2) within cross validation scores. Decision Tree Classifier w/ Imputer + Text Featurization Component + One Hot Encoder may not perform as estimated on unseen data.
Batch 1: (3/9) LightGBM Classifier w/ Imputer + Text... Elapsed:00:08
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.581
Batch 1: (4/9) Extra Trees Classifier w/ Imputer + T... Elapsed:00:13
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.458
Batch 1: (5/9) Elastic Net Classifier w/ Imputer + T... Elapsed:00:20
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.659
Batch 1: (6/9) CatBoost Classifier w/ Imputer + Text... Elapsed:00:26
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.611
Batch 1: (7/9) XGBoost Classifier w/ Imputer + Text ... Elapsed:00:31
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.527
Batch 1: (8/9) Random Forest Classifier w/ Imputer +... Elapsed:00:36
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.438
Batch 1: (9/9) Logistic Regression Classifier w/ Imp... Elapsed:00:43
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.505

Search finished after 00:53
Best pipeline: Random Forest Classifier w/ Imputer + Text Featurization Component + One Hot Encoder
Best pipeline Log Loss Binary: 0.438022

,id,pipeline_name,score,validation_score,percent_better_than_baseline,high_variance_cv,parameters
0,7,Random Forest Classifier w/ Imputer + Text Fea...,0.438022,0.399600,96.695997,False,{'Imputer': {'categorical_impute_strategy': 'm...
1,3,Extra Trees Classifier w/ Imputer + Text Featu...,0.458485,0.422407,96.541642,False,{'Imputer': {'categorical_impute_strategy': 'm...
2,8,Logistic Regression Classifier w/ Imputer + Te...,0.505447,0.495130,96.187405,False,{'Imputer': {'categorical_impute_strategy': 'm...
3,6,XGBoost Classifier w/ Imputer + Text Featuriza...,0.527371,0.490597,96.022032,False,{'Imputer': {'categorical_impute_strategy': 'm...
4,2,LightGBM Classifier w/ Imputer + Text Featuriz...,0.581151,0.582969,95.616375,False,{'Imputer': {'categorical_impute_strategy': 'm...
5,5,CatBoost Classifier w/ Imputer + Text Featuriz...,0.611425,0.601494,95.388014,False,{'Imputer': {'categorical_impute_strategy': 'm...
6,4,Elastic Net Classifier w/ Imputer + Text Featu...,0.659238,0.666304,95.027360,False,{'Imputer': {'categorical_impute_strategy': 'm...
7,1,Decision Tree Classifier w/ Imputer + Text Fea...,1.362844,0.827350,89.720054,True,{'Imputer': {'categorical_impute_strategy': 'm...
8,0,Mode Baseline Binary Classification Pipeline,13.257308,13.257308,0.000000,False,{'Baseline Classifier': {'strategy': 'mode'}}

In [3]:
pipeline = automl.best_pipeline
pipeline.fit(X_train,y_train)
prediction = pipeline.predict(test)

submission[label] = prediction.to_series()
submission.to_csv('submission.csv',index=False)
submission.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1