# Import libraries

* Import the necessary libraries including Pandas, Plotly, and others.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

plt.rcParams['figure.figsize'] = (12,6)
plt.style.use('fivethirtyeight')

import warnings
warnings.filterwarnings("ignore")

from plotly.subplots import make_subplots
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

from sklearn.model_selection import GridSearchCV

from sklearn.pipeline import make_pipeline

# Load the Dataset

* Load the dataset into a Pandas DataFrame.

In [2]:
df = pd.read_csv('/kaggle/input/spaceship-titanic/train.csv')

In [3]:
df.head(5).style.set_properties(**{'background-color':'lightblue','color':'black','border-color':'#8b8c8c'})

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

### Check for the presence of missing values in the dataset and handle them appropriately.

In [5]:
# Check for the presence of missing values
df.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [6]:
df['HomePlanet'].value_counts()

Earth     4602
Europa    2131
Mars      1759
Name: HomePlanet, dtype: int64

In [7]:
df['Cabin'] = df['Cabin'].fillna('0')

In [8]:
df['Cabin'] = df['Cabin'].str.split('/')
df['Cabin']

0          [B, 0, P]
1          [F, 0, S]
2          [A, 0, S]
3          [A, 0, S]
4          [F, 1, S]
            ...
8688      [A, 98, P]
8689    [G, 1499, S]
8690    [G, 1500, S]
8691     [E, 608, S]
8692     [E, 608, S]
Name: Cabin, Length: 8693, dtype: object

In [9]:
df['Cabin'].isnull().sum()

0

In [10]:
def get_cabin(x):
  print(x)
  print(type(x))
  print(type(x) == np.float32)
  print('nan', x == np.nan)
  if type(x) == 'float':
    return np.nan
  elif len(x) > 1:
    return x[0]
  else:
    return x[0]

In [11]:
df['Cabin_zone'] = df['Cabin'].apply(get_cabin)

['B', '0', 'P']
<class 'list'>
False
nan False
['F', '0', 'S']
<class 'list'>
False
nan False
['A', '0', 'S']
<class 'list'>
False
nan False
['A', '0', 'S']
<class 'list'>
False
nan False
['F', '1', 'S']
<class 'list'>
False
nan False
['F', '0', 'P']
<class 'list'>
False
nan False
['F', '2', 'S']
<class 'list'>
False
nan False
['G', '0', 'S']
<class 'list'>
False
nan False
['F', '3', 'S']
<class 'list'>
False
nan False
['B', '1', 'P']
<class 'list'>
False
nan False
['B', '1', 'P']
<class 'list'>
False
nan False
['B', '1', 'P']
<class 'list'>
False
nan False
['F', '1', 'P']
<class 'list'>
False
nan False
['G', '1', 'S']
<class 'list'>
False
nan False
['F', '2', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['F', '3', 'P']
<class 'list'>
False
nan False
['F', '4', 'P']
<class 'list'>
False
nan False
['F', '5', 'P']
<class 'list'>
False
nan False
['G', '0', 'P']
<class 'list'>
False
nan False
['F', '6', 'P']
<class 'list'>
False
nan False
['E', '0', 'S']
<class 'list'>
False
nan False
['E', '0', 'S']
<class 'list'>
False
nan False
['E', '0', 'S']
<class 'list'>
False
nan False
['E', '0', 'S']
<class 'list'>
False
nan False
['E', '0', 'S']
<class 'list'>
False
nan False
['E', '0', 'S']
<class 'list'>
False
nan False
['D', '0', 'P']
<class 'list'>
False
nan False
['C', '2', 'S']
<class 'list'>
False
nan False
['F', '6', 'S']
<class 'list'>
False
nan False
['C', '0', 'P']
<class 'list'>
False
nan False
['F', '8', 'P']
<class 'list'>
False
nan False
['G', '4', 'S']
<class 'list'>
False
nan False
['F', '9', 'P']
<class 'list'>
False
nan False
['F', '9', 'P']
<class 'list'>
False
nan False
['F', '9', 'P']
<class 'list'>
False
nan False
['D', '1', 'S']
<class 'list'>
False
nan False
['D', '1', 'P']
<class 'list'>
False
nan False
['F', '8', 'S']
<class 'list'>
False
nan False
['F', '10', 'S']
<class 'list'>
False
nan False
['G', '1', 'P']
<class 'list'>
False
nan False
['G', '2', 'P']
<class 'list'>
False
nan False
['B', '3', 'P']
<class 'list'>
False
nan False
['G', '3', 'P']
<class 'list'>
False
nan False
['G', '3', 'P']
<class 'list'>
False
nan False
['G', '3', 'P']
<class 'list'>
False
nan False
['F', '10', 'P']
<class 'list'>
False
nan False
['F', '10', 'P']
<class 'list'>
False
nan False
['E', '1', 'S']
<class 'list'>
False
nan False
['E', '2', 'S']
<class 'list'>
False
nan False
['G', '6', 'S']
<class 'list'>
False
nan False
['F', '11', 'S']
<class 'list'>
False
nan False
['A', '1', 'S']
<class 'list'>
False
nan False
['A', '1', 'S']
<class 'list'>
False
nan False
['A', '1', 'S']
<class 'list'>
False
nan False
['G', '7', 'S']
<class 'list'>
False
nan False
['F', '12', 'S']
<class 'list'>
False
nan False
['F', '13', 'S']
<class 'list'>
False
nan False
['F', '14', 'S']
<class 'list'>
False
nan False
['E', '3', 'S']
<class 'list'>
False
nan False
['G', '6', 'P']
<class 'list'>
False
nan False
['G', '10', 'S']
<class 'list'>
False
nan False
['G', '10', 'S']
<class 'list'>
False
nan False
['F', '15', 'S']
<class 'list'>
False
nan False
['E', '4', 'S']
<class 'list'>
False
nan False
['F', '16', 'S']
<class 'list'>
False
nan False
['F', '13', 'P']
<class 'list'>
False
nan False
['F', '14', 'P']
<class 'list'>
False
nan False
['F', '17', 'S']
<class 'list'>
False
nan False
['D', '3', 'P']
<class 'list'>
False
nan False
['C', '3', 'S']
<class 'list'>
False
nan False
['F', '18', 'S']
<class 'list'>
False
nan False
['F', '15', 'P']
<class 'list'>
False
nan False
['C', '4', 'S']
<class 'list'>
False
nan False
['G', '13', 'S']
<class 'list'>
False
nan False
['F', '16', 'P']
<class 'list'>
False
nan False
['F', '16', 'P']
<class 'list'>
False
nan False
['F', '16', 'P']
<class 'list'>
False
nan False
['G', '14', 'S']
<class 'list'>
False
nan False
['C', '5', 'S']
<class 'list'>
False
nan False
['F', '17', 'P']
<class 'list'>
False
nan False
['E', '5', 'S']
<class 'list'>
False
nan False
['G', '15', 'S']
<class 'list'>
False
nan False
['G', '16', 'S']
<class 'list'>
False
nan False
['F', '20', 'S']
<class 'list'>
False
nan False
['G', '9', 'P']
<class 'list'>
False
nan False
['G', '9', 'P']
<class 'list'>
False
nan False
['G', '9', 'P']
<class 'list'>
False
nan False
['A', '2', 'S']
<class 'list'>
False
nan False
['G', '11', 'P']
<class 'list'>
False
nan False
['G', '11', 'P']
<class 'list'>
False
nan False
['F', '19', 'P']
<class 'list'>
False
nan False
['G', '12', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['F', '23', 'S']
<class 'list'>
False
nan False
['F', '24', 'S']
<class 'list'>
False
nan False
['G', '18', 'S']
<class 'list'>
False
nan False
['G', '18', 'S']
<class 'list'>
False
nan False
['F', '21', 'P']
<class 'list'>
False
nan False
['D', '2', 'S']
<class 'list'>
False
nan False
['G', '19', 'S']
<class 'list'>
False
nan False
['G', '19', 'S']
<class 'list'>
False
nan False
['G', '19', 'S']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['B', '5', 'P']
<class 'list'>
False
nan False
['B', '5', 'P']
<class 'list'>
False
nan False
['B', '5', 'P']
<class 'list'>
False
nan False
['E', '6', 'S']
<class 'list'>
False
nan False
['B', '1', 'S']
<class 'list'>
False
nan False
['F', '23', 'P']
<class 'list'>
False
nan False
['G', '20', 'S']
<class 'list'>
False
nan False
['F', '24', 'P']
<class 'list'>
False
nan False
['D', '4', 'P']
<class 'list'>
False
nan False
['A', '0', 'P']
<class 'list'>
False
nan False
['A', '0', 'P']
<class 'list'>
False
nan False
['F', '25', 'P']
<class 'list'>
False
nan False
['G', '21', 'S']
<class 'list'>
False
nan False
['F', '27', 'P']
<class 'list'>
False
nan False
['F', '27', 'S']
<class 'list'>
False
nan False
['E', '7', 'S']
<class 'list'>
False
nan False
['D', '3', 'S']
<class 'list'>
False
nan False
['E', '8', 'S']
<class 'list'>
False
nan False
['G', '22', 'S']
<class 'list'>
False
nan False
['F', '29', 'S']
<class 'list'>
False
nan False
['D', '5', 'S']
<class 'list'>
False
nan False
['G', '17', 'P']
<class 'list'>
False
nan False
['G', '23', 'S']
<class 'list'>
False
nan False
['G', '18', 'P']
<class 'list'>
False
nan False
['E', '5', 'P']
<class 'list'>
False
nan False
['C', '6', 'S']
<class 'list'>
False
nan False
['G', '19', 'P']
<class 'list'>
False
nan False
['F', '29', 'P']
<class 'list'>
False
nan False
['F', '30', 'P']
<class 'list'>
False
nan False
['F', '31', 'S']
<class 'list'>
False
nan False
['G', '25', 'S']
<class 'list'>
False
nan False
['G', '26', 'S']
<class 'list'>
False
nan False
['F', '31', 'P']
<class 'list'>
False
nan False
['G', '27', 'S']
<class 'list'>
False
nan False
['G', '20', 'P']
<class 'list'>
False
nan False
['F', '32', 'P']
<class 'list'>
False
nan False
['G', '22', 'P']
<class 'list'>
False
nan False
['B', '8', 'P']
<class 'list'>
False
nan False
['B', '8', 'P']
<class 'list'>
False
nan False
['G', '28', 'S']
<class 'list'>
False
nan False
['G', '28', 'S']
<class 'list'>
False
nan False
['F', '37', 'P']
<class 'list'>
False
nan False
['F', '35', 'S']
<class 'list'>
False
nan False
['F', '35', 'S']
<class 'list'>
False
nan False
['G', '23', 'P']
<class 'list'>
False
nan False
['E', '10', 'S']
<class 'list'>
False
nan False
['G', '30', 'S']
<class 'list'>
False
nan False
['G', '24', 'P']
<class 'list'>
False
nan False
['E', '11', 'S']
<class 'list'>
False
nan False
['F', '38', 'P']
<class 'list'>
False
nan False
['B', '2', 'S']
<class 'list'>
False
nan False
['D', '6', 'S']
<class 'list'>
False
nan False
['G', '26', 'P']
<class 'list'>
False
nan False
['G', '26', 'P']
<class 'list'>
False
nan False
['G', '26', 'P']
<class 'list'>
False
nan False
['G', '27', 'P']
<class 'list'>
False
nan False
['C', '3', 'P']
<class 'list'>
False
nan False
['F', '36', 'S']
<class 'list'>
False
nan False
['G', '28', 'P']
<class 'list'>
False
nan False
['G', '31', 'S']
<class 'list'>
False
nan False
['E', '8', 'P']
<class 'list'>
False
nan False
['G', '32', 'S']
<class 'list'>
False
nan False
['G', '29', 'P']
<class 'list'>
False
nan False
['G', '29', 'P']
<class 'list'>
False
nan False
['G', '29', 'P']
<class 'list'>
False
nan False
['F', '41', 'P']
<class 'list'>
False
nan False
['F', '41', 'P']
<class 'list'>
False
nan False
['F', '41', 'P']
<class 'list'>
False
nan False
['F', '42', 'P']
<class 'list'>
False
nan False
['D', '5', 'P']
<class 'list'>
False
nan False
['C', '5', 'P']
<class 'list'>
False
nan False
['G', '30', 'P']
<class 'list'>
False
nan False
['G', '33', 'S']
<class 'list'>
False
nan False
['G', '31', 'P']
<class 'list'>
False
nan False
['B', '3', 'S']
<class 'list'>
False
nan False
['B', '3', 'S']
<class 'list'>
False
nan False
['B', '9', 'P']
<class 'list'>
False
nan False
['A', '2', 'P']
<class 'list'>
False
nan False
['C', '8', 'S']
<class 'list'>
False
nan False
['G', '34', 'S']
<class 'list'>
False
nan False
['C', '9', 'S']
<class 'list'>
False
nan False
['G', '32', 'P']
<class 'list'>
False
nan False
['D', '6', 'P']
<class 'list'>
False
nan False
['F', '44', 'P']
<class 'list'>
False
nan False
['F', '44', 'P']
<class 'list'>
False
nan False
['F', '44', 'P']
<class 'list'>
False
nan False
['E', '9', 'P']
<class 'list'>
False
nan False
['F', '45', 'P']
<class 'list'>
False
nan False
['F', '46', 'P']
<class 'list'>
False
nan False
['F', '40', 'S']
<class 'list'>
False
nan False
['F', '47', 'P']
<class 'list'>
False
nan False
['G', '36', 'P']
<class 'list'>
False
nan False
['G', '37', 'P']
<class 'list'>
False
nan False
['G', '37', 'P']
<class 'list'>
False
nan False
['G', '37', 'P']
<class 'list'>
False
nan False
['E', '10', 'P']
<class 'list'>
False
nan False
['F', '48', 'P']
<class 'list'>
False
nan False
['G', '37', 'P']
<class 'list'>
False
nan False
['G', '37', 'P']
<class 'list'>
False
nan False
['E', '13', 'S']
<class 'list'>
False
nan False
['E', '13', 'S']
<class 'list'>
False
nan False
['E', '13', 'S']
<class 'list'>
False
nan False
['E', '13', 'S']
<class 'list'>
False
nan False
['E', '13', 'S']
<class 'list'>
False
nan False
['E', '13', 'S']
<class 'list'>
False
nan False
['E', '13', 'S']
<class 'list'>
False
nan False
['F', '41', 'S']
<class 'list'>
False
nan False
['F', '41', 'S']
<class 'list'>
False
nan False
['E', '14', 'S']
<class 'list'>
False
nan False
['G', '35', 'S']
<class 'list'>
False
nan False
['F', '42', 'S']
<class 'list'>
False
nan False
['G', '38', 'P']
<class 'list'>
False
nan False
['F', '43', 'S']
<class 'list'>
False
nan False
['F', '44', 'S']
<class 'list'>
False
nan False
['G', '36', 'S']
<class 'list'>
False
nan False
['F', '45', 'S']
<class 'list'>
False
nan False
['F', '50', 'P']
<class 'list'>
False
nan False
['B', '11', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['F', '52', 'P']
<class 'list'>
False
nan False
['E', '11', 'P']
<class 'list'>
False
nan False
['F', '46', 'S']
<class 'list'>
False
nan False
['G', '37', 'S']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['F', '47', 'S']
<class 'list'>
False
nan False
['C', '6', 'P']
<class 'list'>
False
nan False
['C', '6', 'P']
<class 'list'>
False
nan False
['D', '8', 'P']
<class 'list'>
False
nan False
['C', '10', 'S']
<class 'list'>
False
nan False
['G', '38', 'S']
<class 'list'>
False
nan False
['C', '11', 'S']
<class 'list'>
False
nan False
['F', '53', 'P']
<class 'list'>
False
nan False
['G', '42', 'P']
<class 'list'>
False
nan False
['F', '54', 'P']
<class 'list'>
False
nan False
['A', '3', 'S']
<class 'list'>
False
nan False
['F', '49', 'S']
<class 'list'>
False
nan False
['F', '49', 'S']
<class 'list'>
False
nan False
['F', '50', 'S']
<class 'list'>
False
nan False
['E', '16', 'S']
<class 'list'>
False
nan False
['F', '56', 'P']
<class 'list'>
False
nan False
['G', '43', 'P']
<class 'list'>
False
nan False
['D', '8', 'S']
<class 'list'>
False
nan False
['F', '51', 'S']
<class 'list'>
False
nan False
['F', '52', 'S']
<class 'list'>
False
nan False
['F', '59', 'P']
<class 'list'>
False
nan False
['D', '9', 'S']
<class 'list'>
False
nan False
['F', '61', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['G', '45', 'P']
<class 'list'>
False
nan False
['F', '63', 'P']
<class 'list'>
False
nan False
['F', '54', 'S']
<class 'list'>
False
nan False
['G', '46', 'P']
<class 'list'>
False
nan False
['F', '64', 'P']
<class 'list'>
False
nan False
['E', '16', 'P']
<class 'list'>
False
nan False
['E', '16', 'P']
<class 'list'>
False
nan False
['F', '65', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['B', '12', 'P']
<class 'list'>
False
nan False
['F', '55', 'S']
<class 'list'>
False
nan False
['C', '12', 'S']
<class 'list'>
False
nan False
['B', '7', 'S']
<class 'list'>
False
nan False
['B', '7', 'S']
<class 'list'>
False
nan False
['B', '7', 'S']
<class 'list'>
False
nan False
['B', '7', 'S']
<class 'list'>
False
nan False
['D', '10', 'S']
<class 'list'>
False
nan False
['B', '8', 'S']
<class 'list'>
False
nan False
['G', '47', 'P']
<class 'list'>
False
nan False
['A', '3', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['F', '67', 'P']
<class 'list'>
False
nan False
['G', '41', 'S']
<class 'list'>
False
nan False
['E', '18', 'S']
<class 'list'>
False
nan False
['C', '7', 'P']
<class 'list'>
False
nan False
['E', '19', 'S']
<class 'list'>
False
nan False
['F', '59', 'S']
<class 'list'>
False
nan False
['F', '60', 'S']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['F', '68', 'P']
<class 'list'>
False
nan False
['G', '50', 'P']
<class 'list'>
False
nan False
['F', '68', 'P']
<class 'list'>
False
nan False
['G', '50', 'P']
<class 'list'>
False
nan False
['G', '51', 'P']
<class 'list'>
False
nan False
['G', '42', 'S']
<class 'list'>
False
nan False
['B', '9', 'S']
<class 'list'>
False
nan False
['B', '9', 'S']
<class 'list'>
False
nan False
['G', '44', 'S']
<class 'list'>
False
nan False
['G', '44', 'S']
<class 'list'>
False
nan False
['F', '61', 'S']
<class 'list'>
False
nan False
['G', '45', 'S']
<class 'list'>
False
nan False
['G', '53', 'P']
<class 'list'>
False
nan False
['G', '47', 'S']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['C', '14', 'S']
<class 'list'>
False
nan False
['C', '14', 'S']
<class 'list'>
False
nan False
['C', '14', 'S']
<class 'list'>
False
nan False
['F', '72', 'P']
<class 'list'>
False
nan False
['F', '73', 'P']
<class 'list'>
False
nan False
['F', '62', 'S']
<class 'list'>
False
nan False
['F', '74', 'P']
<class 'list'>
False
nan False
['F', '63', 'S']
<class 'list'>
False
nan False
['F', '63', 'S']
<class 'list'>
False
nan False
['F', '63', 'S']
<class 'list'>
False
nan False
['G', '48', 'S']
<class 'list'>
False
nan False
['B', '10', 'S']
<class 'list'>
False
nan False
['G', '57', 'P']
<class 'list'>
False
nan False
['F', '76', 'P']
<class 'list'>
False
nan False
['E', '21', 'S']
<class 'list'>
False
nan False
['G', '59', 'P']
<class 'list'>
False
nan False
['F', '64', 'S']
<class 'list'>
False
nan False
['D', '12', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['G', '60', 'P']
<class 'list'>
False
nan False
['F', '78', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['B', '15', 'P']
<class 'list'>
False
nan False
['F', '65', 'S']
<class 'list'>
False
nan False
['G', '50', 'S']
<class 'list'>
False
nan False
['G', '50', 'S']
<class 'list'>
False
nan False
['F', '66', 'S']
<class 'list'>
False
nan False
['F', '67', 'S']
<class 'list'>
False
nan False
['F', '68', 'S']
<class 'list'>
False
nan False
['G', '51', 'S']
<class 'list'>
False
nan False
['F', '82', 'P']
<class 'list'>
False
nan False
['F', '82', 'P']
<class 'list'>
False
nan False
['G', '53', 'S']
<class 'list'>
False
nan False
['F', '83', 'P']
<class 'list'>
False
nan False
['F', '84', 'P']
<class 'list'>
False
nan False
['F', '85', 'P']
<class 'list'>
False
nan False
['G', '62', 'P']
<class 'list'>
False
nan False
['E', '22', 'P']
<class 'list'>
False
nan False
['G', '54', 'S']
<class 'list'>
False
nan False
['C', '15', 'S']
<class 'list'>
False
nan False
['B', '11', 'S']
<class 'list'>
False
nan False
['B', '11', 'S']
<class 'list'>
False
nan False
['B', '11', 'S']
<class 'list'>
False
nan False
['B', '11', 'S']
<class 'list'>
False
nan False
['B', '11', 'S']
<class 'list'>
False
nan False
['B', '11', 'S']
<class 'list'>
False
nan False
['B', '11', 'S']
<class 'list'>
False
nan False
['G', '63', 'P']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['B', '16', 'P']
<class 'list'>
False
nan False
['B', '16', 'P']
<class 'list'>
False
nan False
['G', '64', 'P']
<class 'list'>
False
nan False
['G', '55', 'S']
<class 'list'>
False
nan False
['G', '55', 'S']
<class 'list'>
False
nan False
['G', '56', 'S']
<class 'list'>
False
nan False
['G', '56', 'S']
<class 'list'>
False
nan False
['G', '65', 'P']
<class 'list'>
False
nan False
['G', '66', 'P']
<class 'list'>
False
nan False
['G', '57', 'S']
<class 'list'>
False
nan False
['E', '23', 'P']
<class 'list'>
False
nan False
['C', '9', 'P']
<class 'list'>
False
nan False
['E', '24', 'P']
<class 'list'>
False
nan False
['B', '17', 'P']
<class 'list'>
False
nan False
['B', '17', 'P']
<class 'list'>
False
nan False
['G', '59', 'S']
<class 'list'>
False
nan False
['F', '69', 'S']
<class 'list'>
False
nan False
['D', '13', 'S']
<class 'list'>
False
nan False
['D', '14', 'S']
<class 'list'>
False
nan False
['D', '14', 'S']
<class 'list'>
False
nan False
['D', '15', 'S']
<class 'list'>
False
nan False
['D', '13', 'P']
<class 'list'>
False
nan False
['F', '89', 'P']
<class 'list'>
False
nan False
['G', '69', 'P']
<class 'list'>
False
nan False
['F', '90', 'P']
<class 'list'>
False
nan False
['G', '69', 'P']
<class 'list'>
False
nan False
['E', '25', 'P']
<class 'list'>
False
nan False
['F', '71', 'S']
<class 'list'>
False
nan False
['F', '72', 'S']
<class 'list'>
False
nan False
['F', '91', 'P']
<class 'list'>
False
nan False
['C', '11', 'P']
<class 'list'>
False
nan False
['F', '92', 'P']
<class 'list'>
False
nan False
['G', '60', 'S']
<class 'list'>
False
nan False
['B', '18', 'P']
<class 'list'>
False
nan False
['B', '18', 'P']
<class 'list'>
False
nan False
['B', '18', 'P']
<class 'list'>
False
nan False
['B', '19', 'P']
<class 'list'>
False
nan False
['F', '96', 'P']
<class 'list'>
False
nan False
['F', '96', 'P']
<class 'list'>
False
nan False
['F', '96', 'P']
<class 'list'>
False
nan False
['E', '26', 'P']
<class 'list'>
False
nan False
['C', '16', 'S']
<class 'list'>
False
nan False
['A', '5', 'S']
<class 'list'>
False
nan False
['A', '5', 'S']
<class 'list'>
False
nan False
['F', '75', 'S']
<class 'list'>
False
nan False
['F', '97', 'P']
<class 'list'>
False
nan False
['F', '76', 'S']
<class 'list'>
False
nan False
['B', '20', 'P']
<class 'list'>
False
nan False
['B', '20', 'P']
<class 'list'>
False
nan False
['F', '77', 'S']
<class 'list'>
False
nan False
['G', '62', 'S']
<class 'list'>
False
nan False
['G', '63', 'S']
<class 'list'>
False
nan False
['G', '63', 'S']
<class 'list'>
False
nan False
['F', '78', 'S']
<class 'list'>
False
nan False
['F', '78', 'S']
<class 'list'>
False
nan False
['B', '13', 'S']
<class 'list'>
False
nan False
['C', '13', 'P']
<class 'list'>
False
nan False
['F', '79', 'S']
<class 'list'>
False
nan False
['F', '98', 'P']
<class 'list'>
False
nan False
['D', '15', 'P']
<class 'list'>
False
nan False
['F', '99', 'P']
<class 'list'>
False
nan False
['F', '80', 'S']
<class 'list'>
False
nan False
['E', '25', 'S']
<class 'list'>
False
nan False
['B', '21', 'P']
<class 'list'>
False
nan False
['F', '81', 'S']
<class 'list'>
False
nan False
['E', '27', 'P']
<class 'list'>
False
nan False
['G', '71', 'P']
<class 'list'>
False
nan False
['G', '64', 'S']
<class 'list'>
False
nan False
['E', '26', 'S']
<class 'list'>
False
nan False
['B', '14', 'S']
<class 'list'>
False
nan False
['0']
<class 'list'>
False
nan False
['B', '14', 'S']
<class 'list'>
False
nan False
['B', '15', 'S']
<class 'list'>
False
nan False
['B', '15', 'S']
<class 'list'>
False
nan False
['B', '15', 'S']
<class 'list'>
False
nan False
['F', '83', 'S']
<class 'list'>
False
nan False
['G', '72', 'P']
<class 'list'>
False
nan False

In [12]:
import plotly.express as px
import plotly.graph_objects as go

# define function for random color palette
def r_color(num=2, seed=None):
    pal = px.colors.qualitative.Pastel
    if seed==None:
        seed = np.random.randint(0,420,size=1)
    np.random.seed(seed)
    print(seed)
    return [pal[i] for i in np.random.randint(0,5,size=num)]

# define function for count plot
def count_plot(column, seed=None, num=3, transported=False):
    # create figure
    fig = go.Figure()
    # add trace for count plot
    fig.add_trace(px.histogram(df, x=column, color='Transported', color_discrete_sequence=r_color(num, seed=seed)).data[0])
    # set layout
    fig.update_layout(
        title=f'Count of {column}',
        xaxis_title='Count',
        yaxis_title=column,
        font=dict(
            size=18
        )
    )
    # show figure
    fig.show()
    # print value counts
    print('value_counts\n',df[column].value_counts())
    print('')
    print('')
    if transported:
        # print transported grouped by
        print('transported grouped by \n', df.groupby(column)['Transported'].value_counts())

# fill missing values in Cabin column with '0'
df['Cabin'] = df['Cabin'].fillna('0')
# split Cabin column values by '/'
df['Cabin'] = df['Cabin'].str.split('/')
# apply function to get the first value from the list or NaN if the value is a float
df['Cabin'] = df['Cabin'].apply(lambda x: x[0] if type(x) == list and len(x) > 0 else np.nan if type(x) == float else x)

# call count_plot function for each column
for col in ['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']:
    count_plot(col)

[131]

value_counts
 Earth     4602
Europa    2131
Mars      1759
Name: HomePlanet, dtype: int64


[409]

value_counts
 False    5439
True     3037
Name: CryoSleep, dtype: int64


[163]

value_counts
 Series([], Name: Cabin, dtype: int64)


[307]

value_counts
 TRAPPIST-1e      5915
55 Cancri e      1800
PSO J318.5-22     796
Name: Destination, dtype: int64


[317]

value_counts
 24.0    324
18.0    320
21.0    311
19.0    293
23.0    292
       ...
72.0      4
78.0      3
79.0      3
76.0      2
77.0      2
Name: Age, Length: 80, dtype: int64


[222]

value_counts
 False    8291
True      199
Name: VIP, dtype: int64


[342]

value_counts
 0.0       5577
1.0        117
2.0         79
3.0         61
4.0         47
          ...
1612.0       1
2598.0       1
632.0        1
378.0        1
745.0        1
Name: RoomService, Length: 1273, dtype: int64


[242]

value_counts
 0.0       5456
1.0        116
2.0         75
3.0         53
4.0         53
          ...
3846.0       1
5193.0       1
312.0        1
827.0        1
4688.0       1
Name: FoodCourt, Length: 1507, dtype: int64


[36]

value_counts
 0.0       5587
1.0        153
2.0         80
3.0         59
4.0         45
          ...
3627.0       1
2074.0       1
871.0        1
742.0        1
1872.0       1
Name: ShoppingMall, Length: 1115, dtype: int64


[250]

value_counts
 0.0       5324
1.0        146
2.0        105
5.0         53
3.0         53
          ...
273.0        1
2581.0       1
2948.0       1
3778.0       1
1643.0       1
Name: Spa, Length: 1327, dtype: int64


[58]

value_counts
 0.0       5495
1.0        139
2.0         70
3.0         56
5.0         51
          ...
408.0        1
876.0        1
2891.0       1
2102.0       1
3235.0       1
Name: VRDeck, Length: 1306, dtype: int64

In [13]:
fig = px.histogram(df, x="HomePlanet", color="Transported", barmode="stack")
fig.show()

### Check the distribution of the target variable "Transported" using a count plot created with Plotly.

In [14]:
# Create a count plot to show the distribution of the target variable
fig = px.histogram(df, x='Transported', color='Transported', barmode='group')
fig.show()

In [15]:
# define function for random color palette
def r_color(num=2, seed=None):
    pal = px.colors.qualitative.Pastel
    if seed==None:
        seed = np.random.randint(0,420,size=1)
    np.random.seed(seed)
    print(seed)
    return [pal[i] for i in np.random.randint(0,5,size=num)]

# define function for bivariate plot
def bivariate_plot(column):
    df_tmp1 = pd.DataFrame(df[column].value_counts() / sum(df[column].value_counts()))
    df_tmp2 = pd.DataFrame(df[df['Transported'] == 1 ][column].value_counts() / sum(df[df['Transported'] == 1 ][column].value_counts()))
    df_tmp3 = df_tmp2 - df_tmp1
    df_final = pd.concat([df_tmp1,df_tmp2,df_tmp3], axis=1)
    df_final.columns = [f'% {column} Start', f'% {column} Transp\'d', 'Difference']
    fig = px.histogram(df, x=column, color='Transported', barmode='group', color_discrete_sequence=r_color(2))
    fig.update_layout(
        title=f'{column} vs Transported',
        xaxis_title=column,
        yaxis_title='Transported',
        font=dict(
            size=18
        )
    )
    fig.show()
    fig = px.histogram(df_final, x='Difference', color_discrete_sequence=r_color(2))
    fig.update_layout(
        title=f'{column} Difference in Proportion',
        xaxis_title='Difference in Proportion',
        yaxis_title='Transported',
        font=dict(
            size=18
        )
    )
    fig.show()

# call bivariate_plot function for each column
for col in ['HomePlanet', 'Cabin', 'Destination', 'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']:
    bivariate_plot(col)

[398]

[29]

[34]

[361]

[248]

[363]

[283]

[299]

[53]

[189]

[284]

[71]

[55]

[381]

[419]

[306]

[281]

[143]

[33]

[66]

In [16]:
# Create a scatter plot to show the relationship between age and spa billing amount
fig = px.scatter(df, x='Age', y='Spa', color='Transported')
fig.show()

### Create a scatter plot using Plotly to show the relationship between the age of passengers and the amount they billed at the spa on the Spaceship Titanic.

In [17]:
transported = df[df['Transported'] == True]
not_transported = df[df['Transported'] == False]

fig = px.histogram(df, x="Age", color="Transported", nbins=20,
                   labels={'Age':'Passenger Age', 'count': 'Number of Passengers'},
                   title="Distribution of Passenger Ages by Transported Status")
fig.show()

### Create a heatmap using Plotly to show the correlation between the different amenities on the Spaceship Titanic.

Add color to the heatmap to show the strength of the correlation between the amenities.

In [18]:
import plotly.figure_factory as ff

corr = df[['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']].corr()
corr_matrix = np.array(corr)

fig = ff.create_annotated_heatmap(z=corr_matrix, x=list(corr.columns), y=list(corr.columns),
                                  annotation_text=corr_matrix.round(2),
                                  colorscale='Viridis', showscale=True,
                                  xgap=1, ygap=1)
fig.update_layout(title='Correlation Between Different Amenities on Spaceship Titanic')
fig.show()

### Create a pair plot using Plotly to show the pairwise relationships between all the numeric variables in the dataset.

Add color to the pair plot to distinguish between passengers who were transported to another dimension and those who were not.

In [19]:
fig = px.scatter_matrix(df, dimensions=['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'],
                        color='Transported', title="Pairwise Relationships Between Numeric Variables")
fig.show()

Add color to the box plot to distinguish between the two groups.

In [20]:
df["BilledAmount"] = df["VIP"]*100 + df["RoomService"]*10 + df["FoodCourt"]*5 + df["ShoppingMall"]*20 + df["Spa"]*50 + df["VRDeck"]*30

In [21]:
fig = px.box(df, x="Destination", y="BilledAmount", color="Transported")
fig.update_layout(title="Distribution of Billed Amounts for Amenities by Transported Status")
fig.show()

### Create a histogram using Plotly to show the distribution of passenger ages for those who were transported to another dimension and those who were not.

In [22]:
fig = px.histogram(df, x="Age", color="Transported")
fig.update_layout(title="Distribution of Passenger Ages by Transported Status")
fig.show()

# Preprocessing:

Before we start with the modeling, we need to preprocess the data. We will first check for null values in the dataset and then perform feature scaling.

In [23]:
# Check for null values
print(df.isnull().sum())

PassengerId        0
HomePlanet       201
CryoSleep        217
Cabin           8693
Destination      182
Age              179
VIP              203
RoomService      181
FoodCourt        183
ShoppingMall     208
Spa              183
VRDeck           188
Name             200
Transported        0
Cabin_zone         0
BilledAmount    1096
dtype: int64

In [24]:
df[(df['HomePlanet'].isnull()) & (df['CryoSleep'].isnull())]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Cabin_zone,BilledAmount
3622,3896_01,NaN,NaN,NaN,55 Cancri e,18.0,False,0.0,4387.0,0.0,2241.0,0.0,Ainoxa Preeldy,True,C,133985.0
7218,7711_01,NaN,NaN,NaN,TRAPPIST-1e,24.0,False,0.0,82.0,0.0,1624.0,77.0,Jihoton Muspereed,False,D,83920.0

In [25]:
df[(df['HomePlanet'].isnull()) & (df['CryoSleep'].isnull())].index

Int64Index([3622, 7218], dtype='int64')

In [26]:
df[(df['HomePlanet'].isnull()) & (df['CryoSleep'].isnull()) & (df['Cabin'].isnull())]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,Cabin_zone,BilledAmount
3622,3896_01,NaN,NaN,NaN,55 Cancri e,18.0,False,0.0,4387.0,0.0,2241.0,0.0,Ainoxa Preeldy,True,C,133985.0
7218,7711_01,NaN,NaN,NaN,TRAPPIST-1e,24.0,False,0.0,82.0,0.0,1624.0,77.0,Jihoton Muspereed,False,D,83920.0

In [27]:
inds_drop = []
for col1 in df.columns:
  for col2 in df.columns:
    if col1 != col2:
      for col3 in df.columns:
        if col2 != col3:
          inds = df[(df[col1].isnull()) & (df[col2].isnull()) & (df[col3].isnull())].index
          print(col1,col2,col3,inds)
          for i in inds:
            inds_drop.append(i)
len(inds_drop)

PassengerId HomePlanet PassengerId Int64Index([], dtype='int64')
PassengerId HomePlanet CryoSleep Int64Index([], dtype='int64')
PassengerId HomePlanet Cabin Int64Index([], dtype='int64')
PassengerId HomePlanet Destination Int64Index([], dtype='int64')
PassengerId HomePlanet Age Int64Index([], dtype='int64')
PassengerId HomePlanet VIP Int64Index([], dtype='int64')
PassengerId HomePlanet RoomService Int64Index([], dtype='int64')
PassengerId HomePlanet FoodCourt Int64Index([], dtype='int64')
PassengerId HomePlanet ShoppingMall Int64Index([], dtype='int64')
PassengerId HomePlanet Spa Int64Index([], dtype='int64')
PassengerId HomePlanet VRDeck Int64Index([], dtype='int64')
PassengerId HomePlanet Name Int64Index([], dtype='int64')
PassengerId HomePlanet Transported Int64Index([], dtype='int64')
PassengerId HomePlanet Cabin_zone Int64Index([], dtype='int64')
PassengerId HomePlanet BilledAmount Int64Index([], dtype='int64')
PassengerId CryoSleep PassengerId Int64Index([], dtype='int64')
PassengerId CryoSleep HomePlanet Int64Index([], dtype='int64')
PassengerId CryoSleep Cabin Int64Index([], dtype='int64')
PassengerId CryoSleep Destination Int64Index([], dtype='int64')
PassengerId CryoSleep Age Int64Index([], dtype='int64')
PassengerId CryoSleep VIP Int64Index([], dtype='int64')
PassengerId CryoSleep RoomService Int64Index([], dtype='int64')
PassengerId CryoSleep FoodCourt Int64Index([], dtype='int64')
PassengerId CryoSleep ShoppingMall Int64Index([], dtype='int64')
PassengerId CryoSleep Spa Int64Index([], dtype='int64')
PassengerId CryoSleep VRDeck Int64Index([], dtype='int64')
PassengerId CryoSleep Name Int64Index([], dtype='int64')
PassengerId CryoSleep Transported Int64Index([], dtype='int64')
PassengerId CryoSleep Cabin_zone Int64Index([], dtype='int64')
PassengerId CryoSleep BilledAmount Int64Index([], dtype='int64')
PassengerId Cabin PassengerId Int64Index([], dtype='int64')
PassengerId Cabin HomePlanet Int64Index([], dtype='int64')
PassengerId Cabin CryoSleep Int64Index([], dtype='int64')
PassengerId Cabin Destination Int64Index([], dtype='int64')
PassengerId Cabin Age Int64Index([], dtype='int64')
PassengerId Cabin VIP Int64Index([], dtype='int64')
PassengerId Cabin RoomService Int64Index([], dtype='int64')
PassengerId Cabin FoodCourt Int64Index([], dtype='int64')
PassengerId Cabin ShoppingMall Int64Index([], dtype='int64')
PassengerId Cabin Spa Int64Index([], dtype='int64')
PassengerId Cabin VRDeck Int64Index([], dtype='int64')
PassengerId Cabin Name Int64Index([], dtype='int64')
PassengerId Cabin Transported Int64Index([], dtype='int64')
PassengerId Cabin Cabin_zone Int64Index([], dtype='int64')
PassengerId Cabin BilledAmount Int64Index([], dtype='int64')
PassengerId Destination PassengerId Int64Index([], dtype='int64')
PassengerId Destination HomePlanet Int64Index([], dtype='int64')
PassengerId Destination CryoSleep Int64Index([], dtype='int64')
PassengerId Destination Cabin Int64Index([], dtype='int64')
PassengerId Destination Age Int64Index([], dtype='int64')
PassengerId Destination VIP Int64Index([], dtype='int64')
PassengerId Destination RoomService Int64Index([], dtype='int64')
PassengerId Destination FoodCourt Int64Index([], dtype='int64')
PassengerId Destination ShoppingMall Int64Index([], dtype='int64')
PassengerId Destination Spa Int64Index([], dtype='int64')
PassengerId Destination VRDeck Int64Index([], dtype='int64')
PassengerId Destination Name Int64Index([], dtype='int64')
PassengerId Destination Transported Int64Index([], dtype='int64')
PassengerId Destination Cabin_zone Int64Index([], dtype='int64')
PassengerId Destination BilledAmount Int64Index([], dtype='int64')
PassengerId Age PassengerId Int64Index([], dtype='int64')
PassengerId Age HomePlanet Int64Index([], dtype='int64')
PassengerId Age CryoSleep Int64Index([], dtype='int64')
PassengerId Age Cabin Int64Index([], dtype='int64')
PassengerId Age Destination Int64Index([], dtype='int64')
PassengerId Age VIP Int64Index([], dtype='int64')
PassengerId Age RoomService Int64Index([], dtype='int64')
PassengerId Age FoodCourt Int64Index([], dtype='int64')
PassengerId Age ShoppingMall Int64Index([], dtype='int64')
PassengerId Age Spa Int64Index([], dtype='int64')
PassengerId Age VRDeck Int64Index([], dtype='int64')
PassengerId Age Name Int64Index([], dtype='int64')
PassengerId Age Transported Int64Index([], dtype='int64')
PassengerId Age Cabin_zone Int64Index([], dtype='int64')
PassengerId Age BilledAmount Int64Index([], dtype='int64')
PassengerId VIP PassengerId Int64Index([], dtype='int64')
PassengerId VIP HomePlanet Int64Index([], dtype='int64')
PassengerId VIP CryoSleep Int64Index([], dtype='int64')
PassengerId VIP Cabin Int64Index([], dtype='int64')
PassengerId VIP Destination Int64Index([], dtype='int64')
PassengerId VIP Age Int64Index([], dtype='int64')
PassengerId VIP RoomService Int64Index([], dtype='int64')
PassengerId VIP FoodCourt Int64Index([], dtype='int64')
PassengerId VIP ShoppingMall Int64Index([], dtype='int64')
PassengerId VIP Spa Int64Index([], dtype='int64')
PassengerId VIP VRDeck Int64Index([], dtype='int64')
PassengerId VIP Name Int64Index([], dtype='int64')
PassengerId VIP Transported Int64Index([], dtype='int64')
PassengerId VIP Cabin_zone Int64Index([], dtype='int64')
PassengerId VIP BilledAmount Int64Index([], dtype='int64')
PassengerId RoomService PassengerId Int64Index([], dtype='int64')
PassengerId RoomService HomePlanet Int64Index([], dtype='int64')
PassengerId RoomService CryoSleep Int64Index([], dtype='int64')
PassengerId RoomService Cabin Int64Index([], dtype='int64')
PassengerId RoomService Destination Int64Index([], dtype='int64')
PassengerId RoomService Age Int64Index([], dtype='int64')
PassengerId RoomService VIP Int64Index([], dtype='int64')
PassengerId RoomService FoodCourt Int64Index([], dtype='int64')
PassengerId RoomService ShoppingMall Int64Index([], dtype='int64')
PassengerId RoomService Spa Int64Index([], dtype='int64')
PassengerId RoomService VRDeck Int64Index([], dtype='int64')
PassengerId RoomService Name Int64Index([], dtype='int64')
PassengerId RoomService Transported Int64Index([], dtype='int64')
PassengerId RoomService Cabin_zone Int64Index([], dtype='int64')
PassengerId RoomService BilledAmount Int64Index([], dtype='int64')
PassengerId FoodCourt PassengerId Int64Index([], dtype='int64')
PassengerId FoodCourt HomePlanet Int64Index([], dtype='int64')
PassengerId FoodCourt CryoSleep Int64Index([], dtype='int64')
PassengerId FoodCourt Cabin Int64Index([], dtype='int64')
PassengerId FoodCourt Destination Int64Index([], dtype='int64')
PassengerId FoodCourt Age Int64Index([], dtype='int64')
PassengerId FoodCourt VIP Int64Index([], dtype='int64')
PassengerId FoodCourt RoomService Int64Index([], dtype='int64')
PassengerId FoodCourt ShoppingMall Int64Index([], dtype='int64')
PassengerId FoodCourt Spa Int64Index([], dtype='int64')
PassengerId FoodCourt VRDeck Int64Index([], dtype='int64')
PassengerId FoodCourt Name Int64Index([], dtype='int64')
PassengerId FoodCourt Transported Int64Index([], dtype='int64')
PassengerId FoodCourt Cabin_zone Int64Index([], dtype='int64')
PassengerId FoodCourt BilledAmount Int64Index([], dtype='int64')
PassengerId ShoppingMall PassengerId Int64Index([], dtype='int64')
PassengerId ShoppingMall HomePlanet Int64Index([], dtype='int64')
PassengerId ShoppingMall CryoSleep Int64Index([], dtype='int64')
PassengerId ShoppingMall Cabin Int64Index([], dtype='int64')
PassengerId ShoppingMall Destination Int64Index([], dtype='int64')
PassengerId ShoppingMall Age Int64Index([], dtype='int64')
PassengerId ShoppingMall VIP Int64Index([], dtype='int64')
PassengerId ShoppingMall RoomService Int64Index([], dtype='int64')
PassengerId ShoppingMall FoodCourt Int64Index([], dtype='int64')
PassengerId ShoppingMall Spa Int64Index([], dtype='int64')
PassengerId ShoppingMall VRDeck Int64Index([], dtype='int64')
PassengerId ShoppingMall Name Int64Index([], dtype='int64')
PassengerId ShoppingMall Transported Int64Index([], dtype='int64')
PassengerId ShoppingMall Cabin_zone Int64Index([], dtype='int64')
PassengerId ShoppingMall BilledAmount Int64Index([], dtype='int64')
PassengerId Spa PassengerId Int64Index([], dtype='int64')
PassengerId Spa HomePlanet Int64Index([], dtype='int64')
PassengerId Spa CryoSleep Int64Index([], dtype='int64')
PassengerId Spa Cabin Int64Index([], dtype='int64')
PassengerId Spa Destination Int64Index([], dtype='int64')
PassengerId Spa Age Int64Index([], dtype='int64')
PassengerId Spa VIP Int64Index([], dtype='int64')
PassengerId Spa RoomService Int64Index([], dtype='int64')
PassengerId Spa FoodCourt Int64Index([], dtype='int64')
PassengerId Spa ShoppingMall Int64Index([], dtype='int64')
PassengerId Spa VRDeck Int64Index([], dtype='int64')
PassengerId Spa Name Int64Index([], dtype='int64')
PassengerId Spa Transported Int64Index([], dtype='int64')
PassengerId Spa Cabin_zone Int64Index([], dtype='int64')
PassengerId Spa BilledAmount Int64Index([], dtype='int64')
PassengerId VRDeck PassengerId Int64Index([], dtype='int64')
PassengerId VRDeck HomePlanet Int64Index([], dtype='int64')
PassengerId VRDeck CryoSleep Int64Index([], dtype='int64')
PassengerId VRDeck Cabin Int64Index([], dtype='int64')
PassengerId VRDeck Destination Int64Index([], dtype='int64')
PassengerId VRDeck Age Int64Index([], dtype='int64')
PassengerId VRDeck VIP Int64Index([], dtype='int64')
PassengerId VRDeck RoomService Int64Index([], dtype='int64')
PassengerId VRDeck FoodCourt Int64Index([], dtype='int64')
PassengerId VRDeck ShoppingMall Int64Index([], dtype='int64')
PassengerId VRDeck Spa Int64Index([], dtype='int64')
PassengerId VRDeck Name Int64Index([], dtype='int64')
PassengerId VRDeck Transported Int64Index([], dtype='int64')
PassengerId VRDeck Cabin_zone Int64Index([], dtype='int64')
PassengerId VRDeck BilledAmount Int64Index([], dtype='int64')
PassengerId Name PassengerId Int64Index([], dtype='int64')
PassengerId Name HomePlanet Int64Index([], dtype='int64')
PassengerId Name CryoSleep Int64Index([], dtype='int64')
PassengerId Name Cabin Int64Index([], dtype='int64')
PassengerId Name Destination Int64Index([], dtype='int64')
PassengerId Name Age Int64Index([], dtype='int64')
PassengerId Name VIP Int64Index([], dtype='int64')
PassengerId Name RoomService Int64Index([], dtype='int64')
PassengerId Name FoodCourt Int64Index([], dtype='int64')
PassengerId Name ShoppingMall Int64Index([], dtype='int64')
PassengerId Name Spa Int64Index([], dtype='int64')
PassengerId Name VRDeck Int64Index([], dtype='int64')
PassengerId Name Transported Int64Index([], dtype='int64')
PassengerId Name Cabin_zone Int64Index([], dtype='int64')
PassengerId Name BilledAmount Int64Index([], dtype='int64')
PassengerId Transported PassengerId Int64Index([], dtype='int64')
PassengerId Transported HomePlanet Int64Index([], dtype='int64')
PassengerId Transported CryoSleep Int64Index([], dtype='int64')
PassengerId Transported Cabin Int64Index([], dtype='int64')
PassengerId Transported Destination Int64Index([], dtype='int64')
PassengerId Transported Age Int64Index([], dtype='int64')
PassengerId Transported VIP Int64Index([], dtype='int64')
PassengerId Transported RoomService Int64Index([], dtype='int64')
PassengerId Transported FoodCourt Int64Index([], dtype='int64')
PassengerId Transported ShoppingMall Int64Index([], dtype='int64')
PassengerId Transported Spa Int64Index([], dtype='int64')
PassengerId Transported VRDeck Int64Index([], dtype='int64')
PassengerId Transported Name Int64Index([], dtype='int64')
PassengerId Transported Cabin_zone Int64Index([], dtype='int64')
PassengerId Transported BilledAmount Int64Index([], dtype='int64')
PassengerId Cabin_zone PassengerId Int64Index([], dtype='int64')
PassengerId Cabin_zone HomePlanet Int64Index([], dtype='int64')
PassengerId Cabin_zone CryoSleep Int64Index([], dtype='int64')
PassengerId Cabin_zone Cabin Int64Index([], dtype='int64')
PassengerId Cabin_zone Destination Int64Index([], dtype='int64')
PassengerId Cabin_zone Age Int64Index([], dtype='int64')
PassengerId Cabin_zone VIP Int64Index([], dtype='int64')
PassengerId Cabin_zone RoomService Int64Index([], dtype='int64')
PassengerId Cabin_zone FoodCourt Int64Index([], dtype='int64')
PassengerId Cabin_zone ShoppingMall Int64Index([], dtype='int64')
PassengerId Cabin_zone Spa Int64Index([], dtype='int64')
PassengerId Cabin_zone VRDeck Int64Index([], dtype='int64')
PassengerId Cabin_zone Name Int64Index([], dtype='int64')
PassengerId Cabin_zone Transported Int64Index([], dtype='int64')
PassengerId Cabin_zone BilledAmount Int64Index([], dtype='int64')
PassengerId BilledAmount PassengerId Int64Index([], dtype='int64')
PassengerId BilledAmount HomePlanet Int64Index([], dtype='int64')
PassengerId BilledAmount CryoSleep Int64Index([], dtype='int64')
PassengerId BilledAmount Cabin Int64Index([], dtype='int64')
PassengerId BilledAmount Destination Int64Index([], dtype='int64')
PassengerId BilledAmount Age Int64Index([], dtype='int64')
PassengerId BilledAmount VIP Int64Index([], dtype='int64')
PassengerId BilledAmount RoomService Int64Index([], dtype='int64')
PassengerId BilledAmount FoodCourt Int64Index([], dtype='int64')
PassengerId BilledAmount ShoppingMall Int64Index([], dtype='int64')
PassengerId BilledAmount Spa Int64Index([], dtype='int64')
PassengerId BilledAmount VRDeck Int64Index([], dtype='int64')
PassengerId BilledAmount Name Int64Index([], dtype='int64')
PassengerId BilledAmount Transported Int64Index([], dtype='int64')
PassengerId BilledAmount Cabin_zone Int64Index([], dtype='int64')
HomePlanet PassengerId HomePlanet Int64Index([], dtype='int64')
HomePlanet PassengerId CryoSleep Int64Index([], dtype='int64')
HomePlanet PassengerId Cabin Int64Index([], dtype='int64')
HomePlanet PassengerId Destination Int64Index([], dtype='int64')
HomePlanet PassengerId Age Int64Index([], dtype='int64')
HomePlanet PassengerId VIP Int64Index([], dtype='int64')
HomePlanet PassengerId RoomService Int64Index([], dtype='int64')
HomePlanet PassengerId FoodCourt Int64Index([], dtype='int64')
HomePlanet PassengerId ShoppingMall Int64Index([], dtype='int64')
HomePlanet PassengerId Spa Int64Index([], dtype='int64')
HomePlanet PassengerId VRDeck Int64Index([], dtype='int64')
HomePlanet PassengerId Name Int64Index([], dtype='int64')
HomePlanet PassengerId Transported Int64Index([], dtype='int64')
HomePlanet PassengerId Cabin_zone Int64Index([], dtype='int64')
HomePlanet PassengerId BilledAmount Int64Index([], dtype='int64')
HomePlanet CryoSleep PassengerId Int64Index([], dtype='int64')
HomePlanet CryoSleep HomePlanet Int64Index([3622, 7218], dtype='int64')
HomePlanet CryoSleep Cabin Int64Index([3622, 7218], dtype='int64')
HomePlanet CryoSleep Destination Int64Index([], dtype='int64')
HomePlanet CryoSleep Age Int64Index([], dtype='int64')
HomePlanet CryoSleep VIP Int64Index([], dtype='int64')
HomePlanet CryoSleep RoomService Int64Index([], dtype='int64')
HomePlanet CryoSleep FoodCourt Int64Index([], dtype='int64')
HomePlanet CryoSleep ShoppingMall Int64Index([], dtype='int64')
HomePlanet CryoSleep Spa Int64Index([], dtype='int64')
HomePlanet CryoSleep VRDeck Int64Index([], dtype='int64')
HomePlanet CryoSleep Name Int64Index([], dtype='int64')
HomePlanet CryoSleep Transported Int64Index([], dtype='int64')
HomePlanet CryoSleep Cabin_zone Int64Index([], dtype='int64')
HomePlanet CryoSleep BilledAmount Int64Index([], dtype='int64')
HomePlanet Cabin PassengerId Int64Index([], dtype='int64')
HomePlanet Cabin HomePlanet Int64Index([  59,  113,  186,  225,  234,  274,  286,  291,  347,  365,
            ...
            8353, 8383, 8454, 8468, 8489, 8515, 8613, 8666, 8674, 8684],
           dtype='int64', length=201)
HomePlanet Cabin CryoSleep Int64Index([3622, 7218], dtype='int64')
HomePlanet Cabin Destination Int64Index([347, 5208, 5687, 6629], dtype='int64')
HomePlanet Cabin Age Int64Index([6169, 7682], dtype='int64')
HomePlanet Cabin VIP Int64Index([5055, 5208, 8666], dtype='int64')
HomePlanet Cabin RoomService Int64Index([568, 637, 2791, 3433, 4154, 6257], dtype='int64')
HomePlanet Cabin FoodCourt Int64Index([2773, 3535], dtype='int64')
HomePlanet Cabin ShoppingMall Int64Index([59, 186, 2166, 2638, 4548, 5634, 7211], dtype='int64')
HomePlanet Cabin Spa Int64Index([3535, 3946, 7434], dtype='int64')
HomePlanet Cabin VRDeck Int64Index([7682], dtype='int64')
HomePlanet Cabin Name Int64Index([1855, 2274, 3091, 4548, 5762, 7211, 8613], dtype='int64')
HomePlanet Cabin Transported Int64Index([], dtype='int64')
HomePlanet Cabin Cabin_zone Int64Index([], dtype='int64')
HomePlanet Cabin BilledAmount Int64Index([  59,  186,  568,  637, 2166, 2638, 2773, 2791, 3433, 3535, 3946,
            4154, 4548, 5055, 5208, 5634, 6257, 7211, 7434, 7682, 8666],
           dtype='int64')
HomePlanet Destination PassengerId Int64Index([], dtype='int64')
HomePlanet Destination HomePlanet Int64Index([347, 5208, 5687, 6629], dtype='int64')
HomePlanet Destination CryoSleep Int64Index([], dtype='int64')
HomePlanet Destination Cabin Int64Index([347, 5208, 5687, 6629], dtype='int64')
HomePlanet Destination Age Int64Index([], dtype='int64')
HomePlanet Destination VIP Int64Index([5208], dtype='int64')
HomePlanet Destination RoomService Int64Index([], dtype='int64')
HomePlanet Destination FoodCourt Int64Index([], dtype='int64')
HomePlanet Destination ShoppingMall Int64Index([], dtype='int64')
HomePlanet Destination Spa Int64Index([], dtype='int64')
HomePlanet Destination VRDeck Int64Index([], dtype='int64')
HomePlanet Destination Name Int64Index([], dtype='int64')
HomePlanet Destination Transported Int64Index([], dtype='int64')
HomePlanet Destination Cabin_zone Int64Index([], dtype='int64')
HomePlanet Destination BilledAmount Int64Index([5208], dtype='int64')
HomePlanet Age PassengerId Int64Index([], dtype='int64')
HomePlanet Age HomePlanet Int64Index([6169, 7682], dtype='int64')
HomePlanet Age CryoSleep Int64Index([], dtype='int64')
HomePlanet Age Cabin Int64Index([6169, 7682], dtype='int64')
HomePlanet Age Destination Int64Index([], dtype='int64')
HomePlanet Age VIP Int64Index([], dtype='int64')
HomePlanet Age RoomService Int64Index([], dtype='int64')
HomePlanet Age FoodCourt Int64Index([], dtype='int64')
HomePlanet Age ShoppingMall Int64Index([], dtype='int64')
HomePlanet Age Spa Int64Index([], dtype='int64')
HomePlanet Age VRDeck Int64Index([7682], dtype='int64')
HomePlanet Age Name Int64Index([], dtype='int64')
HomePlanet Age Transported Int64Index([], dtype='int64')
HomePlanet Age Cabin_zone Int64Index([], dtype='int64')
HomePlanet Age BilledAmount Int64Index([7682], dtype='int64')
HomePlanet VIP PassengerId Int64Index([], dtype='int64')
HomePlanet VIP HomePlanet Int64Index([5055, 5208, 8666], dtype='int64')
HomePlanet VIP CryoSleep Int64Index([], dtype='int64')
HomePlanet VIP Cabin Int64Index([5055, 5208, 8666], dtype='int64')
HomePlanet VIP Destination Int64Index([5208], dtype='int64')
HomePlanet VIP Age Int64Index([], dtype='int64')
HomePlanet VIP RoomService Int64Index([], dtype='int64')
HomePlanet VIP FoodCourt Int64Index([], dtype='int64')
HomePlanet VIP ShoppingMall Int64Index([], dtype='int64')
HomePlanet VIP Spa Int64Index([], dtype='int64')
HomePlanet VIP VRDeck Int64Index([], dtype='int64')
HomePlanet VIP Name Int64Index([], dtype='int64')
HomePlanet VIP Transported Int64Index([], dtype='int64')
HomePlanet VIP Cabin_zone Int64Index([], dtype='int64')
HomePlanet VIP BilledAmount Int64Index([5055, 5208, 8666], dtype='int64')
HomePlanet RoomService PassengerId Int64Index([], dtype='int64')
HomePlanet RoomService HomePlanet Int64Index([568, 637, 2791, 3433, 4154, 6257], dtype='int64')
HomePlanet RoomService CryoSleep Int64Index([], dtype='int64')
HomePlanet RoomService Cabin Int64Index([568, 637, 2791, 3433, 4154, 6257], dtype='int64')
HomePlanet RoomService Destination Int64Index([], dtype='int64')
HomePlanet RoomService Age Int64Index([], dtype='int64')
HomePlanet RoomService VIP Int64Index([], dtype='int64')
HomePlanet RoomService FoodCourt Int64Index([], dtype='int64')

19314

In [28]:
print(df.shape)
df = df.drop(inds_drop)
df.shape

(8693, 16)

(6764, 16)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6764 entries, 0 to 8692
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   6764 non-null   object
 1   HomePlanet    6764 non-null   object
 2   CryoSleep     6764 non-null   object
 3   Cabin         0 non-null      float64
 4   Destination   6764 non-null   object
 5   Age           6764 non-null   float64
 6   VIP           6764 non-null   object
 7   RoomService   6764 non-null   float64
 8   FoodCourt     6764 non-null   float64
 9   ShoppingMall  6764 non-null   float64
 10  Spa           6764 non-null   float64
 11  VRDeck        6764 non-null   float64
 12  Name          6764 non-null   object
 13  Transported   6764 non-null   bool
 14  Cabin_zone    6764 non-null   object
 15  BilledAmount  6764 non-null   object
dtypes: bool(1), float64(7), object(8)
memory usage: 852.1+ KB

In [30]:
df['Cabin'].value_counts().index

Float64Index([], dtype='float64')

In [31]:
for feat in df.columns[:-2]: #not cabin
  if feat not in ['Cabin', 'Cabin_zone', 'Cabin_code']:
    if df[feat].dtype == 'float':
      df[feat] = df[feat].fillna(df[feat].median())
    elif df[feat].dtype == 'object':
      
      df[feat] = df[feat].fillna(df[feat].value_counts().index[0])

In [32]:
df.isnull().sum()

PassengerId        0
HomePlanet         0
CryoSleep          0
Cabin           6764
Destination        0
Age                0
VIP                0
RoomService        0
FoodCourt          0
ShoppingMall       0
Spa                0
VRDeck             0
Name               0
Transported        0
Cabin_zone         0
BilledAmount       0
dtype: int64

# Treat Outliers:

We can check for outliers using a boxplot. If we find any outliers, we can remove them using the IQR method.

In [39]:
import plotly.express as px
import plotly.graph_objs as go

def plot(column, bins=30, hue=None, num=3):
    # Plot histogram
    fig_hist = px.histogram(df, x=column, color=hue, nbins=bins)
    fig_hist.update_layout(title={
        'text': f"{column} Histogram",
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 22, 'color': 'black', 'family':'Arial'}
    })
    fig_hist.show()

    # Identify outliers
    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)
    iqr = q3 - q1
    upper_bound = q3 + 1.5 * iqr
    lower_bound = q1 - 1.5 * iqr

    # Plot box plot with outliers
    fig_box = go.Figure()
    fig_box.add_trace(go.Box(y=df[column], name=column, boxpoints='outliers'))
    fig_box.update_layout(title={
        'text': f"{column} Box Plot",
        'x': 0.5,
        'xanchor': 'center',
        'font': {'size': 22, 'color': 'black', 'family':'Arial'}
    })
    fig_box.add_shape(
        type='line', x0=upper_bound, y0=0, x1=upper_bound, y1=1,
        line=dict(color='red', width=2, dash='dash')
    )
    fig_box.add_shape(
        type='line', x0=lower_bound, y0=0, x1=lower_bound, y1=1,
        line=dict(color='red', width=2, dash='dash')
    )
    fig_box.show()

# Dimension Reduction using PCA

In [41]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder


# create sample dataframe
df = pd.DataFrame({
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Age': [25, 30, 35, 40],
    'RoomService': [8, 9, 2, 5],
    'FoodCourt': [5, 6, 8, 9],
    'ShoppingMall': [7, 8, 9, 6],
    'Spa': [6, 5, 9, 8],
    'VRDeck': [4, 6, 8, 7],
    'Transported': ['True', 'False', 'False', 'True']
})

# perform one-hot encoding on categorical columns
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df_encoded = pd.get_dummies(df, columns=['Transported'])

# perform one-hot encoding on 'Transported'
df_encoded[['Transported_False', 'Transported_True']] = pd.get_dummies(df['Transported'])

# create a new DataFrame with the actual `Transported` values
df_transported = df_encoded.drop(['Transported_False', 'Transported_True'], axis=1)
df_transported['Transported'] = df['Transported'].replace({'False': 0, 'True': 1})

# show encoded dataframe
df_encoded.head()

,Gender,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported_False,Transported_True
0,1,25,8,5,7,6,4,0,1
1,0,30,9,6,8,5,6,1,0
2,1,35,2,8,9,9,8,1,0
3,0,40,5,9,6,8,7,0,1

In [42]:
def remove_outliers(df, columns=None):
    """
    Removes outliers from a Pandas DataFrame.
    :param df: the DataFrame to remove outliers from
    :param columns: the list of columns to check for outliers (default is all columns)
    :return: the DataFrame with outliers removed
    """
    if columns is None:
        columns = df.columns
    for col in columns:
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1
        df = df[(df[col] >= q1 - 1.5*iqr) & (df[col] <= q3 + 1.5*iqr)]
    return df

In [43]:
# remove outliers from the dataframe
df = remove_outliers(df_encoded)

# perform PCA on the cleaned dataframe
pca = PCA(n_components=2)
principal_components = pca.fit_transform(df.drop(['Transported_False', 'Transported_True'], axis=1))

In [44]:
# create the original DataFrame
data = {
    'Gender': [1, 0, 1, 0],
    'Age': [25, 30, 35, 40],
    'RoomService': [8, 9, 2, 5],
    'FoodCourt': [5, 6, 8, 9],
    'ShoppingMall': [7, 8, 9, 6],
    'Spa': [6, 5, 9, 8],
    'VRDeck': [4, 6, 8, 7],
    'Transported_False': [0, 1, 1, 0],
    'Transported_True': [1, 0, 0, 1]
}

df = pd.DataFrame(data)

# Rename columns
df = df.rename(columns={'Transported_False': 'Transported_0', 'Transported_True': 'Transported_1'})

# Create a new column with the actual `Transported` values
df['Transported'] = df['Transported_1']

# Drop unnecessary columns
df = df.drop(['Transported_0', 'Transported_1'], axis=1)

# Show DataFrame
df.head()

   Gender  Age  RoomService  FoodCourt  ShoppingMall  Spa  VRDeck  Transported
0       1   25            8          5             7    6       4            1
1       0   30            9          6             8    5       6            0
2       1   35            2          8             9    9       8            0
3       0   40            5          9             6    8       7            1

In [45]:
df_pca = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])
df_pca['Transported'] = df['Transported']

fig = px.scatter(df_pca, x='PC1', y='PC2', color='Transported')
fig.show()