(See [Version 2](https://www.kaggle.com/niteshhalai/titanic-linear-regression-v2) for a model with slightly better accuracy.

I am trying to use linear regression to the titanic dataset to see if it results in any meaningful prediction

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/titanic/test.csv
/kaggle/input/titanic/train.csv
/kaggle/input/titanic/gender_submission.csv

In [2]:
train = pd.read_csv('/kaggle/input/titanic/train.csv')
train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

First I will  split the data between variable and targets. I will also remove the columns PassenderId, Name, Ticket (these should not have any effect on whether the passenger survived or not) and Cabin (as these have a lot of missing values). I will fill the

In [4]:
y = train['Survived']
train.drop(labels = ['Survived','PassengerId','Name','Ticket','Cabin'], axis = 1, inplace = True)

In [5]:
train.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
Pclass      891 non-null int64
Sex         891 non-null object
Age         714 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB

Filling the age missing age values with mean age.

In [7]:
train['Age'].fillna(train['Age'].mean(), inplace = True)

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
Pclass      891 non-null int64
Sex         891 non-null object
Age         891 non-null float64
SibSp       891 non-null int64
Parch       891 non-null int64
Fare        891 non-null float64
Embarked    889 non-null object
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB

I want to turn the sex and Embarked columns to dummy variables using one hot encoding:

In [9]:
categorical_columns = ['Sex','Embarked']
train = pd.get_dummies(train,columns = categorical_columns, dtype = int)

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
Pclass        891 non-null int64
Age           891 non-null float64
SibSp         891 non-null int64
Parch         891 non-null int64
Fare          891 non-null float64
Sex_female    891 non-null int64
Sex_male      891 non-null int64
Embarked_C    891 non-null int64
Embarked_Q    891 non-null int64
Embarked_S    891 non-null int64
dtypes: float64(2), int64(8)
memory usage: 69.7 KB

In [11]:
X = []
for column in train.columns:
    X.append(column)
X = train[X]
X

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,22.000000,1,0,7.2500,0,1,0,0,1
1,1,38.000000,1,0,71.2833,1,0,1,0,0
2,3,26.000000,0,0,7.9250,1,0,0,0,1
3,1,35.000000,1,0,53.1000,1,0,0,0,1
4,3,35.000000,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
886,2,27.000000,0,0,13.0000,0,1,0,0,1
887,1,19.000000,0,0,30.0000,1,0,0,0,1
888,3,29.699118,1,2,23.4500,1,0,0,0,1
889,1,26.000000,0,0,30.0000,0,1,1,0,0
890,3,32.000000,0,0,7.7500,0,1,0,1,0

In [12]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(X, y)

Making predictions for train data set:

In [13]:
y_pred = model.predict(train)
y_pred

array([ 9.38886961e-02,  9.30722369e-01,  6.15550382e-01,  8.77866256e-01,
        5.87680436e-02,  1.53977596e-01,  3.03019829e-01,  1.17355474e-01,
        5.78879927e-01,  8.88493303e-01,  6.90604724e-01,  7.75964032e-01,
        1.47156586e-01, -7.86327171e-02,  6.86240879e-01,  6.18798350e-01,
        1.42271209e-01,  2.63238735e-01,  5.47728464e-01,  6.58862950e-01,
        2.35736973e-01,  2.37895487e-01,  7.44255032e-01,  4.51526752e-01,
        5.85785174e-01,  4.31077284e-01,  1.55077833e-01,  4.14447531e-01,
        6.57596375e-01,  8.99595695e-02,  4.43892400e-01,  1.00124674e+00,
        6.57559264e-01,  4.86151764e-02,  4.88990217e-01,  3.32517194e-01,
        1.55079039e-01,  1.41264016e-01,  5.83078905e-01,  7.11271866e-01,
        4.92246661e-01,  7.43973508e-01,  1.55270510e-01,  9.24917761e-01,
        7.20641669e-01,  9.00038611e-02,  1.14747256e-01,  6.57559264e-01,
        7.67236597e-02,  6.24274421e-01,  5.19858250e-02,  1.41192207e-01,
        8.67468358e-01,  7.33624544e-01,  2.90568665e-01,  4.41514583e-01,
        8.17565920e-01,  1.62144923e-01,  8.43849451e-01, -2.66154437e-02,
        2.00446625e-01,  1.07071083e+00,  3.23880208e-01,  9.16810028e-02,
        5.04591065e-01,  1.00279014e-01,  7.70425364e-01,  1.53080263e-01,
        4.71872235e-01,  2.94711750e-02,  2.48962538e-01,  4.47706826e-01,
        3.31876608e-01,  1.37698657e-01,  9.03610815e-02,  1.17578844e-01,
        8.99595695e-02,  9.00038611e-02,  4.06248355e-01,  5.93287023e-01,
        1.35644320e-01,  9.45399512e-02,  6.57570036e-01,  4.54858678e-01,
        8.41136198e-01,  4.52819845e-01,  8.94862305e-02,  9.00038611e-02,
        8.94662371e-01,  1.23586308e-01,  9.41234604e-02,  1.47100345e-01,
        3.11582298e-01,  4.24464034e-02, -8.28834118e-02,  9.00038611e-02,
        2.63214262e-01,  5.38452708e-01,  7.28703244e-01,  2.00376579e-01,
        6.03756856e-01,  8.99595695e-02,  4.88927860e-01,  7.07267299e-02,
       -3.55589250e-02,  9.99717382e-02,  6.44934239e-01,  8.99248715e-02,
        4.10460435e-02,  6.21016956e-01,  3.44307310e-01,  7.09248323e-01,
        1.35371447e-01,  6.10198582e-01,  7.35771040e-01,  1.41228112e-01,
       -8.66478867e-02,  2.28403252e-01,  5.85458055e-01,  5.66967715e-01,
        2.49370683e-01,  9.00038611e-02,  2.75695650e-01,  7.50519458e-01,
        2.94473068e-01,  2.19271887e-01,  1.53774147e-01,  1.23325412e-01,
        6.06107090e-01, -4.66428775e-04,  1.35819831e-01,  1.46869351e-01,
        4.52442030e-01,  7.33624544e-01,  2.90928612e-01,  3.68612317e-01,
        9.73998214e-01,  3.62296000e-01,  1.71061981e-01,  5.52960140e-01,
        6.29467383e-01,  6.39070393e-01,  5.88358895e-01,  2.16532206e-01,
        3.31745746e-01,  2.76003187e-01,  1.05835584e-01,  6.09116082e-01,
        1.95198697e-01,  1.90754931e-01,  1.37585369e-01,  9.58347332e-01,
       -6.20296306e-02, -3.48784399e-03,  8.97920253e-02,  3.72892296e-01,
        7.38277470e-01,  8.82308909e-02,  9.01797925e-02, -2.54054309e-01,
       -7.80255052e-03,  7.07115084e-01,  1.11722179e-01,  1.65010226e-01,
        8.73412418e-02,  1.83858685e-01,  9.35051072e-01,  4.04677276e-01,
        4.38764308e-01,  1.13931359e-01,  2.56497489e-01,  1.30486070e-01,
        7.06683481e-01,  1.41228112e-01,  3.50465813e-01,  1.01782811e-01,
       -4.46020516e-02,  8.89036674e-01,  2.61465765e-01,  5.05632323e-02,
        2.49730809e-01,  3.29138507e-01,  2.19669249e-02,  3.41462754e-01,
        7.17537502e-01,  4.45679491e-01,  6.18532373e-01,  3.48782318e-01,
        3.81988802e-02,  5.28311825e-02,  7.53465743e-01,  3.26284029e-01,
        6.15525069e-01,  3.67196522e-01,  9.24107240e-01,  8.75734786e-01,
        1.53774147e-01,  1.77208529e-03,  6.57559264e-01,  8.00606299e-01,
        1.00432521e-01, -2.54054309e-01,  6.42141924e-02,  6.19700358e-02,
        1.58941725e-01,  7.41851197e-01,  3.74332224e-02,  1.80196295e-01,
        7.38282267e-01,  4.44834301e-01,  1.23299073e-01,  7.38085915e-01,
        1.35141659e-01,  2.61465765e-01,  1.12521184e-01,  9.84031841e-01,
        6.09657812e-01,  1.53523259e-01,  1.00876934e+00,  2.60747677e-01,
        1.70726864e-01,  2.79143473e-01, -3.55130680e-02,  8.99595695e-02,
        3.67002402e-01,  1.35744852e-01,  3.25565942e-01,  1.43980513e-01,
        3.32176599e-01,  4.59183066e-01,  8.86591020e-01,  9.40444708e-02,
        9.07248677e-02,  5.49322320e-01,  2.96103094e-01,  5.93645361e-01,
        1.41450885e-01,  8.66993853e-01,  3.25565942e-01,  2.43579811e-01,
        6.19686467e-01,  6.18532373e-01,  2.66640247e-01,  1.35105754e-01,
        1.53304863e-01,  3.54250479e-01,  6.21399866e-01,  7.69337730e-01,
        3.46289517e-01,  8.25251899e-02,  8.97740731e-02,  5.41498859e-01,
        2.48608637e-01,  4.92901701e-02,  4.98991819e-01,  6.33586983e-01,
        1.02316281e+00,  9.58175716e-01,  1.11633686e+00,  6.35283837e-01,
        1.53774147e-01,  5.73223417e-02,  2.65683837e-01,  3.70619076e-01,
        6.57559264e-01,  2.25392261e-01, -1.04730024e-03,  7.63617860e-02,
        7.96568034e-01,  9.42825672e-01,  4.40222026e-01,  1.15381497e-01,
        6.86449935e-01,  4.46288894e-01,  6.57559264e-01,  7.20014485e-01,
        5.03541296e-01,  2.59504680e-01,  1.12808362e-01,  5.08954755e-01,
       -5.42387546e-02,  9.99597893e-02,  1.71143354e-01,  1.53049155e-01,
        4.38785851e-01,  1.36040055e-01,  8.86473817e-02,  1.35327155e-01,
        1.90754931e-01,  7.02926850e-01,  9.79548646e-01,  1.04836726e+00,
        2.91385384e-01,  6.27601213e-01,  1.23542016e-01,  5.04591065e-01,
        1.91607771e-01,  1.06889991e+00,  4.40078408e-01,  9.36036366e-01,
        6.57559264e-01,  7.57203644e-02,  1.50736913e-01,  8.30693606e-01,
        9.00038611e-02,  5.71478772e-01,  1.03226336e+00,  1.06527116e+00,
        2.88683328e-01,  1.01499289e+00,  1.05788222e+00,  1.03050960e+00,
        7.35452542e-01,  9.99717382e-02,  1.31565552e-01,  6.15530045e-01,
        7.63087391e-01,  1.20331333e-01,  9.43093384e-01,  9.21245568e-01,
        1.35141659e-01,  1.05864308e-01,  8.28920636e-01,  7.59884525e-01,
       -2.54054309e-01,  1.00224404e+00, -9.49593761e-02,  7.29895465e-01,
        5.32604022e-01,  1.08194075e+00,  5.79505482e-01,  3.46396141e-01,
        4.10634306e-01,  9.10789265e-02,  9.32238853e-01,  8.99595695e-02,
        4.13314229e-01,  9.72455672e-01, -1.57651147e-04,  3.51353071e-01,
        3.73089092e-01,  8.88769801e-01,  2.73250904e-01,  2.90928612e-01,
        2.26110348e-01,  8.00606299e-01,  7.06325187e-01,  5.54848258e-01,
        1.92482388e-01,  1.76959887e-02,  1.29816378e-01,  4.41370966e-01,
        1.84591938e-01,  7.92413169e-02,  1.55077833e-01,  1.00432521e-01,
        9.80418658e-01,  7.18110326e-01,  6.57596375e-01,  6.57596375e-01,
       -6.96449941e-02,  2.95644641e-01,  5.54928207e-01,  5.84808086e-02,
        1.14747256e-01,  8.80011029e-02,  8.02225216e-01,  6.58864156e-01,
        6.57559264e-01,  1.05390163e+00,  4.98990393e-01,  1.17242341e-01,
        1.53049155e-01,  5.80954898e-01,  6.15248021e-01,  9.82763166e-01,
        6.38926776e-01,  5.41584201e-01,  2.11307815e-01,  1.52970165e-01,
        9.93283139e-01,  7.98721368e-01,  7.64098476e-02,  8.77550298e-01,
        8.99595695e-02,  3.49554316e-01,  3.23102510e-02,  7.29895465e-01,
        1.53768173e-01,  9.06877991e-01,  3.55705170e-01,  1.41191001e-01,
        1.74742002e-02,  1.03117240e+00,  5.98156587e-01,  1.35298432e-01,
        5.86067198e-01,  1.70918708e-01,  3.01995664e-01,  7.76935489e-01,
        3.51618613e-02,  1.11801169e-01,  6.04306013e-01,  6.10035003e-02,
        6.51117634e-01,  1.98940404e-01, -3.55992385e-02,  3.65114069e-01,
        1.41185027e-01,  4.59183066e-01,  8.99595695e-02,  1.53518020e-01,
        9.64106824e-01,  2.59504680e-01,  5.69901395e-03,  5.93788978e-01,
        6.90179014e-01,  8.04262295e-01,  2.61465765e-01,  6.82792460e-01,
        1.55270510e-01,  2.05029505e-01,  9.40731943e-02,  5.48522416e-01,
        1.05332547e-01,  8.97740731e-02,  7.39517113e-01,  8.33803201e-01,
        1.53774147e-01,  7.64457520e-02,  4.48955999e-01,  5.54848258e-01,
        6.57021141e-01,  1.64568602e-01,  2.86496855e-01,  9.89126816e-01,
        5.38405248e-01,  6.72202843e-01,  2.00088409e-01,  2.54855108e-01,
        6.23565531e-01,  1.47573076e-01,  7.63617860e-02,  7.77036021e-01,
        9.00218133e-02,  5.74564725e-01,  8.51441880e-01,  4.13600582e-01,
        7.09504966e-01,  3.08668910e-01,  1.57394680e-01,  5.21737918e-02,
        5.02826482e-01,  3.67237774e-01,  9.00038611e-02,  1.59390109e-01,
        2.30930928e-01,  9.08746621e-01,  6.46681405e-01,  1.53774147e-01,
        3.31104609e-01,  6.46606130e-02,  3.40429637e-01,  1.55399514e-01,
        9.00038611e-02,  4.08031002e-02,  2.59504680e-01,  2.83964054e-01,
        1.53766966e-01,  7.34548386e-01,  8.97740731e-02,  4.12662666e-02,
        6.78857506e-01,  8.72037213e-01,  6.39669997e-01,  4.46253961e-01,
        1.98940404e-01,  5.25820564e-02,  1.35219442e-01,  7.42375401e-01,
       -1.48303047e-02,  2.59504680e-01, -2.96204985e-02,  3.98002839e-01,
        5.09226730e-01,  4.59183066e-01,  8.88465228e-01,  3.38394645e-01,
        8.82308909e-02,  1.57126971e-01,  5.21737918e-02,  1.41034228e-01,
        2.90991201e-01,  2.67479702e-01,  1.41264016e-01,  1.57155490e-01,
        8.38447134e-01,  9.20288679e-02,  9.33370816e-01,  1.23513293e-01,
        1.65010226e-01,  7.08819419e-01,  6.57524566e-01,  5.51209646e-01,
        1.04067169e+00,  5.55593474e-01,  7.19607808e-01,  4.38943830e-01,
        1.04173757e-01,  1.25716498e-01,  1.57893746e-01,  9.00038611e-02,
        4.01740044e-01,  8.33027958e-01,  1.23427122e-01,  3.39143054e-01,
        7.40962517e-01,  1.58484801e-01,  6.92376558e-01,  7.64014604e-02,
        9.60186361e-01,  1.35327155e-01,  1.55077833e-01,  9.16948801e-01,
        1.55079039e-01,  9.01291975e-02,  6.46681405e-01,  4.95020490e-01,
        3.51618613e-02,  2.03927263e-01,  8.76874209e-01,  1.55079039e-01,
        1.72806799e-01,  6.31510342e-01,  5.92191940e-01,  8.72886423e-01,
        3.48782318e-01,  1.02920981e+00,  9.18565269e-02,  1.02830010e+00,
        8.86668735e-01,  5.25719728e-01,  5.13934589e-01,  2.12161718e-01,
        3.66320344e-01,  2.36665519e-01,  7.92550239e-01,  3.28797416e-01,
        1.70337659e-02,  3.40821451e-01,  5.71609258e-01,  2.82877528e-01,
        1.53796896e-01,  2.00445418e-01,  6.39077574e-01,  2.48608637e-01,
        8.62696121e-01,  5.61981825e-01,  8.46072357e-01,  5.18093276e-01,
        1.53774147e-01,  2.92609046e-02,  2.73394521e-01,  9.00038611e-02,
        5.93788978e-01,  4.57048660e-02,  1.53004863e-01,  5.38250971e-01,
        1.55079039e-01,  7.63895114e-02,  7.21854542e-02,  7.30081493e-01,
        4.01768767e-01,  6.57559264e-01,  1.70726864e-01,  1.54901821e-01,
        7.41680604e-01,  8.55100237e-01,  6.19687644e-01,  7.64098476e-02,
        7.42494051e-01,  9.20354595e-01,  1.23778153e-01,  4.71025599e-01,
        1.55505095e-01,  9.95219568e-01,  1.61866554e-01,  2.83724966e-01,
        1.35371447e-01,  9.00038611e-02,  5.85023512e-02,  8.50232273e-01,
       -1.21725781e-02,  6.25859843e-01,  1.82698871e-01,  3.97284391e-04,
        7.72768552e-01, -2.60401708e-02,  1.55077833e-01,  3.57995987e-01,
        7.06271953e-01,  8.99595695e-02,  4.43496505e-01,  5.73491833e-03,
        4.73018953e-01,  1.37767740e-02,  8.81865993e-02,  4.55983146e-01,
        8.12958941e-01,  9.18483995e-01,  4.25152400e-01,  8.97166261e-02,
        6.18532373e-01,  1.53774147e-01,  5.87680436e-02,  7.42590135e-01,
        9.38188205e-03,  5.76645565e-01,  8.27570163e-01,  2.84317955e-01,
        1.31806088e-01,  3.32676380e-01,  1.57574178e-01,  1.41207776e-01,
        1.43576258e-01,  2.56158782e-01,  1.66036143e-01,  1.00875537e+00,
        1.11756877e-01,  1.53769350e-01,  1.43533347e-01, -3.57990966e-02,
        4.91831240e-01,  4.31317741e-01,  5.66003273e-01,  7.77036021e-01,
        7.64098476e-02,  2.02276386e-01,  4.57036588e-01,  5.10631402e-02,
        1.47100345e-01,  1.05390163e+00,  6.07251259e-01,  1.03919191e-01,
        7.34548386e-01,  3.69575810e-01,  1.53004863e-01,  3.51845747e-01,
        8.98602436e-02,  6.33120377e-01,  8.99595695e-02,  8.22984355e-01,
        1.41374113e-01,  6.57582013e-01,  7.26209893e-01,  2.31692974e-01,
        8.99595695e-02,  5.89124553e-01,  3.02713751e-01,  3.30700890e-01,
        2.67576414e-01,  9.43791679e-02,  3.36720715e-01,  5.27162885e-02,
        1.05867719e-01,  1.84552418e-01,  2.90928612e-01,  8.99248715e-02,
        1.16274878e-02,  9.08786115e-01,  6.56690624e-01,  3.97335459e-01,
        2.50448985e-02,  2.55573195e-01,  2.59504680e-01,  1.58862735e-01,
        1.20640023e-01,  6.63241481e-01,  3.90220459e-01,  5.90809463e-01,
        6.57670568e-01,  5.34572731e-01,  1.47494087e-01, -4.42931521e-02,
        3.50541175e-02,  2.91496116e-01,  1.07378387e-02,  1.53658323e-01,
        1.58868709e-01,  1.06657225e+00,  3.98771634e-01,  7.96225549e-01,
        1.03919191e-01,  1.82767710e-01,  2.60393776e-01,  1.31972854e-01,
        5.73491833e-03,  6.57554468e-01,  3.57643783e-01,  1.74051633e-02,
        1.09345184e+00,  4.07632613e-01,  7.14027582e-01,  1.81461640e-01,
        7.04919656e-02,  2.12166695e-01,  6.77005958e-01,  3.66384627e-01,
        1.02400091e+00,  1.00279014e-01,  1.04821558e+00,  4.38943830e-01,
        2.97161778e-01,  9.45351543e-02,  1.31829236e-01,  1.52934261e-01,
        1.01685342e+00,  7.82210503e-01,  1.56000218e-01,  7.04741929e-02,
        8.96567539e-01,  1.23295303e-01,  2.37895487e-01,  1.43614375e-01,
        4.21221695e-01,  1.47332517e-01,  6.43789874e-01,  6.57555674e-01,
        2.53409705e-01,  5.80189989e-01,  9.99925985e-01,  2.68584837e-01,
        2.59504680e-01,  3.02713751e-01,  3.02713751e-01,  9.93819869e-02,
        4.04709125e-01,  6.12551743e-01,  8.99595695e-02,  8.99595695e-02,
        4.39934791e-01,  3.75584871e-01,  1.01283189e+00,  8.46455869e-02,
        8.23024171e-02,  1.57133004e-01,  1.17128457e-01,  7.65250882e-01,
        4.68362251e-01,  1.46108607e-01,  8.64227365e-01,  2.15073863e-01,
        7.09696733e-02,  1.29434586e-01,  6.01168468e-01,  3.77623007e-01,
        9.99430147e-02,  3.31745746e-01,  6.46606130e-02,  9.40498007e-01,
        9.18565269e-02,  2.31469344e-02,  2.12231764e-01,  8.59490287e-01,
        1.70647874e-01,  7.90725319e-01,  5.08003187e-01,  6.52840009e-01,
        1.17231839e-01,  7.65355129e-02,  1.24002799e-01, -1.78916002e-02,
        6.05433419e-01,  1.55077833e-01,  5.37899470e-01,  1.58855554e-01,
        1.53774147e-01,  7.40601260e-01,  1.53770557e-01,  9.01580302e-01,
        7.57264867e-01,  9.85052723e-01,  4.44054390e-01,  2.14748963e-02,
        1.17406503e-01,  1.17463950e-01,  6.62567656e-01,  1.06915792e-01,
        1.89760640e-01,  4.23323612e-01,  1.53774147e-01,  3.47695793e-01,
        2.49730809e-01,  5.05445589e-01,  1.17649447e-01,  2.08432640e-01,
        8.28818842e-01,  5.86305345e-01,  1.53306069e-01,  5.39537819e-01,
        2.37895487e-01,  7.06061503e-01,  5.03019407e-01,  3.12128378e-01,
        1.05599822e-01,  8.22593318e-02,  3.76511645e-01,  6.62647852e-01,
        2.08432640e-01,  8.89651395e-01,  1.11754493e-01,  3.98222492e-02,
        2.31284830e-01,  5.43397437e-01,  8.52846062e-02,  4.31317741e-01,
        6.33228090e-01,  2.70676309e-01,  1.11679118e-02,  5.63255860e-02,
        7.73447159e-01,  1.06084531e-01,  3.82404215e-01,  5.95115021e-01,
        8.14486724e-02,  1.53544359e-01,  1.03919191e-01,  4.72856645e-01,
        1.53774147e-01,  9.29289166e-01,  7.06302039e-01,  3.77900944e-01,
        1.55079039e-01,  1.29422637e-01,  1.59013533e-01,  9.12391004e-01,
        1.41439948e-01,  9.00038611e-02,  9.03610815e-02,  5.05159561e-01,
        1.47120681e-01,  3.43243650e-01,  1.00754511e+00,  1.26562102e-01,
        1.65010226e-01,  1.73764398e-02, -2.54054309e-01,  1.24034693e-01,
        2.63145893e-01,  9.84754681e-01,  5.13974583e-02, -1.71121155e-01,
        7.26035120e-01,  1.01129321e+00,  6.45236002e-01,  6.47250537e-01,
        8.35194160e-01,  3.13426901e-01,  6.48352650e-01,  1.55079039e-01,
       -5.73531427e-02,  2.72815075e-01,  8.34711411e-01,  2.49730809e-01,
        2.96821182e-01,  6.94540048e-01,  8.07233102e-01,  4.38156362e-01,
        9.04203519e-02,  1.85220656e-01,  1.11756877e-01,  7.91148939e-01,
        4.13303237e-01, -1.16699168e-02,  8.04253584e-01,  7.45478522e-01,
        1.47672402e-01,  1.53004863e-01,  8.99595695e-02,  8.53470286e-01,
        7.82598074e-01,  7.05088909e-02,  6.39865087e-01,  2.72532816e-01,
        1.17406503e-01,  5.29644264e-01,  2.79143473e-01,  1.00676520e+00,
        5.25260014e-01,  5.27043039e-01,  1.40216038e-01])

Getting the range of the predictions

In [14]:
print(y_pred.max())
print(y_pred.min())

1.116336860416321
-0.25405430859028666

Function to convert the prediction to a one (survived) or zer (not survived)

In [15]:
def one_or_zero(abc):
    if (1 - abc) < (abc - 0):
        return 1
    else: 
        return 0

Converting the predictions to 1 or 0:

In [16]:
list_of_predictions = []

for pred in y_pred:
    list_of_predictions.append(one_or_zero(pred))
    
y_pred = np.asarray(list_of_predictions)
y_pred

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0])

Accuracy of the model on the same data it trained on:

In [17]:
unique, counts = np.unique( np.asarray(y_pred == y), return_counts=True)
true_false_values = dict(zip(unique, counts))
accuracy = true_false_values[True]/len(np.asarray(y_pred == y))
accuracy

0.7991021324354658

**Using the model on the test data**

In [18]:
original_test = pd.read_csv('/kaggle/input/titanic/test.csv')
test = pd.read_csv('/kaggle/input/titanic/test.csv')
test.drop(labels = ['PassengerId','Name','Ticket','Cabin'], axis = 1, inplace = True)
test['Age'].fillna(test['Age'].mean(), inplace = True)
categorical_columns = ['Sex','Embarked']
test = pd.get_dummies(test,columns = categorical_columns, dtype = int)

Looks like there are some null values in the test data which were not there in train:

In [19]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
Pclass        418 non-null int64
Age           418 non-null float64
SibSp         418 non-null int64
Parch         418 non-null int64
Fare          417 non-null float64
Sex_female    418 non-null int64
Sex_male      418 non-null int64
Embarked_C    418 non-null int64
Embarked_Q    418 non-null int64
Embarked_S    418 non-null int64
dtypes: float64(2), int64(8)
memory usage: 32.8 KB

Filling the null value in Fare column with the mean:

In [20]:
test['Fare'].fillna(test['Fare'].mean(), inplace = True)

In [21]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
Pclass        418 non-null int64
Age           418 non-null float64
SibSp         418 non-null int64
Parch         418 non-null int64
Fare          418 non-null float64
Sex_female    418 non-null int64
Sex_male      418 non-null int64
Embarked_C    418 non-null int64
Embarked_Q    418 non-null int64
Embarked_S    418 non-null int64
dtypes: float64(2), int64(8)
memory usage: 32.8 KB

In [22]:
test_pred = model.predict(test)
list_of_predictions_test = []

for pred in test_pred:
    list_of_predictions_test.append(one_or_zero(pred))
    
test_pred = np.asarray(list_of_predictions_test)
test_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

In [23]:
submission = pd.DataFrame({
        "PassengerId": original_test["PassengerId"],
        "Survived": test_pred
    }) 

filename = 'submission.csv'
submission.to_csv(filename,index=False)
print('Saved file: ' + filename)

Saved file: submission.csv