In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
sns.set(rc={'figure.figsize':(11.7,8.27)})

In [2]:
train = pd.read_csv('../input/titanic/train.csv')
test = pd.read_csv('../input/titanic/test.csv')

In [3]:
train.shape

(891, 12)

In [4]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
print(f'number of duplicate rows: {train.duplicated().sum()}\nnumber of null values:\n{train.isna().sum()}')

number of duplicate rows: 0
number of null values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
print(f'number of duplicate rows: {test.duplicated().sum()}\nnumber of null values:\n{test.isna().sum()}')

number of duplicate rows: 0
number of null values:
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [9]:
train['catSex'] = train['Sex'].apply(lambda x: 1 if x == 'male' else 0)
train['catEmbark'] = train['Embarked'].apply(lambda x: 0 if x =='S' else(1 if x == 'C' else '2'))

In [10]:
test['catSex'] = test['Sex'].apply(lambda x: 1 if x == 'male' else 0)
test['catEmbark'] = test['Embarked'].apply(lambda x: 0 if x =='S' else(1 if x == 'C' else '2'))

In [11]:
for n in ['Name', 'Ticket', 'Cabin', 'Sex', 'Embarked']:
    train.drop(n, axis=1, inplace = True)
for n in ['Name', 'Ticket', 'Cabin', 'Sex', 'Embarked']:
    test.drop(n, axis=1, inplace = True)
train.dropna(inplace = True)

test['Age'].fillna(test['Age'].mode()[0], inplace=True)
test['Fare'].fillna(test['Fare'].mode()[0], inplace=True)

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  714 non-null    int64
 1   Survived     714 non-null    int64
 2   Pclass       714 non-null    int64
 3   Age          714 non-null    float64
 4   SibSp        714 non-null    int64
 5   Parch        714 non-null    int64
 6   Fare         714 non-null    float64
 7   catSex       714 non-null    int64
 8   catEmbark    714 non-null    object
dtypes: float64(2), int64(6), object(1)
memory usage: 55.8+ KB

In [13]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Age          418 non-null    float64
 3   SibSp        418 non-null    int64
 4   Parch        418 non-null    int64
 5   Fare         418 non-null    float64
 6   catSex       418 non-null    int64
 7   catEmbark    418 non-null    object
dtypes: float64(2), int64(5), object(1)
memory usage: 26.2+ KB

In [14]:
print(f'number of duplicate rows: {train.duplicated().sum()}\nnumber of null values:\n{train.isna().sum()}')

number of duplicate rows: 0
number of null values:
PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
catSex         0
catEmbark      0
dtype: int64

In [15]:
print(f'number of duplicate rows: {test.duplicated().sum()}\nnumber of null values:\n{test.isna().sum()}')

number of duplicate rows: 0
number of null values:
PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
catSex         0
catEmbark      0
dtype: int64

In [16]:
X, y = train.loc[:, train.columns != 'Survived'].values, train['Survived'].values

In [17]:
lr_model = LogisticRegression(max_iter = 10000)
lr_model.fit(X, y)

LogisticRegression(max_iter=10000)

In [18]:
y_pred = lr_model.predict(test.values)

In [19]:
test['Survived'] = lr_model.predict(test.values)
submission = test[['PassengerId','Survived']]
submission.to_csv("submission.csv", index=False)
submission.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

I would greatly appreciate it if you could upvote this notebook and also take a look at [my other notebooks](https://www.kaggle.com/hosseinfaridnasr/code).