# <div style='background-color:red;color:yellow;font-size:50px;text-align:center;padding:20px;'>
    KAGGLERS WITH MOST FOLLOWERS
</div>

Inspired from [this](https://www.kaggle.com/code/carlmcbrideellis/simple-eda-of-kaggle-grandmasters-scheduled) notebook. please acknowledge the original @carlmcbrideellis auther also.

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import datetime
pd.set_option('display.max_rows', None)
from IPython.display import Markdown

df_f = pd.read_csv('../input/meta-kaggle/UserFollowers.csv')
df_u = pd.read_csv('../input/meta-kaggle/Users.csv')

In [2]:
df_f.head(2)

       Id  UserId  FollowingUserId CreationDate
0      64     368              993   05/23/2017
1  122289     368            67483   08/07/2018

In [3]:
df_u.head(2)

    Id      UserName        DisplayName RegisterDate  PerformanceTier
0    1    kaggleteam        Kaggle Team   03/24/2011                5
1  368  antgoldbloom  Anthony Goldbloom   01/20/2010                2

In [4]:
df = df_f.merge(df_u, on = 'Id')

In [5]:
df.head(5)

,Id,UserId,FollowingUserId,CreationDate,UserName,DisplayName,RegisterDate,PerformanceTier
0,122289,368,67483,08/07/2018,rebecca8,Rebecca,08/30/2013,0
1,323230,368,1663522,09/18/2019,germanomosconi,germanomosconi,04/01/2015,0
2,412502,368,1302389,03/08/2020,qianandao,Andrew McLaughlin,09/04/2015,0
3,447841,368,391404,04/27/2020,dongzhou,Dong Zhou,10/21/2015,0
4,798317,368,769452,06/21/2021,alokk2,Alok,11/17/2016,0

In [6]:
len(df.FollowingUserId.unique())

162480

In [7]:
len(df.UserName.unique())

992531

In [8]:
len(df.UserId.unique())

333145

In [9]:
tf = df.groupby(['FollowingUserId']).size().sort_values(ascending=False).head(10)

In [10]:
# tf.UserName.map(lambda x: make_clickable_link(x))
tff = tf.to_frame()

In [11]:
tff.head()

                     0
FollowingUserId
5309             16488
4476084          12833
71388            12726
1723677          12497
708283           12172

In [12]:
tf

FollowingUserId
5309       16488
4476084    12833
71388      12726
1723677    12497
708283     12172
1014468    10930
54836       9895
1162990     8870
417337      8286
9028        7872
dtype: int64

In [13]:
df.groupby('UserName').size().sort_values(ascending=True).head(10)

UserName
Amateurscience     1
petersee           1
peterseemann       1
petersegerstrom    1
petersenjeffrey    1
petersenlyle       1
petersforbes       1
petersh            1
petershaw          1
petershen          1
dtype: int64