In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [2]:
import pandas as pd
import numpy as nm
import matplotlib as plt

In [3]:
train = pd.read_csv("/kaggle/input/titanic/train.csv")
test = pd.read_csv("/kaggle/input/titanic/test.csv")

In [4]:
train.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [5]:
train.shape

(891, 12)

In [6]:
y=train.Survived
train=train.drop(['Survived'],axis='columns')
datas=pd.concat([train,test],axis=0)
datas.shape

(1309, 11)

In [7]:
per=test.PassengerId

In [8]:
nan_cols = [i for i in datas.columns if datas[i].isnull().any()]
nan_cols

['Age', 'Fare', 'Cabin', 'Embarked']

In [9]:
cols_to_fill_zero1 = ['Fare','Age']
datas[cols_to_fill_zero1]=datas[cols_to_fill_zero1].fillna(datas[cols_to_fill_zero1].median())
datas['Cabin']=datas['Cabin'].fillna('none')

In [10]:
datas['Embarked'].value_counts()

S    914
C    270
Q    123
Name: Embarked, dtype: int64

In [11]:
datas['Embarked']=datas['Embarked'].fillna('S')

In [12]:
datas.tail()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,3,"Spector, Mr. Woolf",male,28.0,0,0,A.5. 3236,8.0500,none,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,none,S
416,1308,3,"Ware, Mr. Frederick",male,28.0,0,0,359309,8.0500,none,S
417,1309,3,"Peter, Master. Michael J",male,28.0,1,1,2668,22.3583,none,C

In [13]:
datas=datas.drop(['Name','Ticket','PassengerId'],axis='columns')

In [14]:
dataset = pd.get_dummies(datas, drop_first=True)

In [15]:
dataset.tail()

,Pclass,Age,SibSp,Parch,Fare,Sex_male,Cabin_A11,Cabin_A14,Cabin_A16,Cabin_A18,...,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Cabin_none,Embarked_Q,Embarked_S
413,3,28.0,0,0,8.0500,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
414,1,39.0,0,0,108.9000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
415,3,38.5,0,0,7.2500,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
416,3,28.0,0,0,8.0500,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
417,3,28.0,1,1,22.3583,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [16]:
X=dataset.iloc[:891,:]
test=dataset.iloc[891:,:]

In [17]:
test.shape

(418, 194)

In [18]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
from sklearn.svm import SVC
model = SVC()
model.fit(train_X,train_y)

SVC()

In [22]:
model.score(test_X,test_y)

0.659217877094972

In [23]:
cross_val_score(model,X, y)

array([0.58659218, 0.71348315, 0.68539326, 0.68539326, 0.69101124])

In [24]:

model_C = SVC(C=45,coef0=1)
model_C.fit(train_X,train_y)
model_C.score(test_X,test_y)

0.7877094972067039

In [25]:
cross_val_score(model_C,X, y)

array([0.65363128, 0.78651685, 0.79775281, 0.78089888, 0.84269663])

In [26]:
from sklearn.linear_model import LogisticRegression
model_1=LogisticRegression()
model_1.fit(train_X,train_y)
model_1.score(test_X,test_y)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

0.7877094972067039

In [27]:
cross_val_score(model_1,X, y)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

array([0.81005587, 0.79213483, 0.79213483, 0.7752809 , 0.8258427 ])

In [28]:
from sklearn.ensemble import RandomForestClassifier
modl = RandomForestClassifier(n_estimators=35)
modl.fit(train_X,train_y)
modl.score(test_X,test_y)

0.776536312849162

In [29]:
cross_val_score(modl,X, y)

array([0.79329609, 0.79775281, 0.85955056, 0.78089888, 0.83146067])

In [30]:
from sklearn.svm import LinearSVC

model_2 = LinearSVC(loss='hinge',dual=True)
model_2.fit(train_X, train_y)
model_2.score(test_X,test_y)

/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,

0.770949720670391

In [31]:
cross_val_score(model_2,X, y)

/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,

array([0.80446927, 0.80337079, 0.7752809 , 0.76404494, 0.79775281])

Using Ensemble

In [32]:
from sklearn.ensemble import GradientBoostingClassifier #For Regression
cl = GradientBoostingClassifier(n_estimators=100, learning_rate=0.5, max_depth=3)
cl.fit(train_X,train_y)
cl.score(test_X,test_y)

0.7821229050279329

In [33]:
cross_val_score(cl,X, y)

array([0.83798883, 0.82022472, 0.87078652, 0.79775281, 0.83707865])

Making Final submission CSV file

In [34]:
predicted=cl.predict(test)

In [35]:
prediction = pd.DataFrame(predicted,columns=['Survived']).to_csv('submissio.csv',index=False)
result=pd.read_csv('submissio.csv')
result=pd.concat([per,result],axis='columns')
#result=result.drop([1459],axis=0)
result.tail()

     PassengerId  Survived
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

In [36]:
prediction = pd.DataFrame(result, columns=['PassengerId','Survived']).to_csv('submission.csv',index=False)
results=pd.read_csv('submission.csv')
results.tail()

     PassengerId  Survived
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0