In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from matplotlib import style
import seaborn as sns

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, plot_confusion_matrix, precision_score, recall_score

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression


# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [2]:
#importing input data
train = pd.read_csv('../input/titanic/train.csv')

test = pd.read_csv('../input/titanic/test.csv') 

val = pd.read_csv('../input/titanic/gender_submission.csv')

In [3]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [5]:
test['Survived'] = val['Survived']

In [6]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0

In [7]:
#DATA PREP
train.isnull().sum()#finding the missing values

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
train= train.dropna(axis=0, subset=['Embarked']) #dropped the whole row as the percent of its low, so dropping them

In [9]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [10]:
train['Age'] = train['Age'].fillna(train['Age'].median()) #taking the median values of age

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [11]:
train=train.drop(['Cabin'], axis=1)

In [12]:
train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

As we see no missing value is left

In [13]:
train.drop(['Name','Ticket'], axis = 1, inplace=True) #As Name and ticket are useless

In [14]:
train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,22.0,1,0,7.2500,S
1,2,1,1,female,38.0,1,0,71.2833,C
2,3,1,3,female,26.0,0,0,7.9250,S
3,4,1,1,female,35.0,1,0,53.1000,S
4,5,0,3,male,35.0,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,13.0000,S
887,888,1,1,female,19.0,0,0,30.0000,S
888,889,0,3,female,28.0,1,2,23.4500,S
889,890,1,1,male,26.0,0,0,30.0000,C
890,891,0,3,male,32.0,0,0,7.7500,Q

In [15]:
#Test data Preprocessing
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
Survived         0
dtype: int64

In [16]:
test['Fare'] = test['Fare'].fillna(test['Fare'].median()) #as for the test we can not drop any

In [17]:
test['Age'] =test['Age'].fillna(test['Age'].median())

In [18]:
test=test.drop(['Cabin'], axis=1) # as for the train we have done it, and we want to do the same for the test

In [19]:
test.drop(['Name','Ticket'], axis = 1, inplace=True) #As Name and ticket are useless
test

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived
0,892,3,male,34.5,0,0,7.8292,Q,0
1,893,3,female,47.0,1,0,7.0000,S,1
2,894,2,male,62.0,0,0,9.6875,Q,0
3,895,3,male,27.0,0,0,8.6625,S,0
4,896,3,female,22.0,1,1,12.2875,S,1
...,...,...,...,...,...,...,...,...,...
413,1305,3,male,27.0,0,0,8.0500,S,0
414,1306,1,female,39.0,0,0,108.9000,C,1
415,1307,3,male,38.5,0,0,7.2500,S,0
416,1308,3,male,27.0,0,0,8.0500,S,0
417,1309,3,male,27.0,1,1,22.3583,C,0

In [20]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Sex          889 non-null    object
 4   Age          889 non-null    float64
 5   SibSp        889 non-null    int64
 6   Parch        889 non-null    int64
 7   Fare         889 non-null    float64
 8   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 69.5+ KB

In [21]:
#Preparing for dummy variable
train["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [22]:
train['Survived'] = train['Survived'].apply(str)

In [23]:
train['Pclass'] = train['Pclass'].apply(str)

In [24]:
train

     PassengerId Survived Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0              1        0      3    male  22.0      1      0   7.2500        S
1              2        1      1  female  38.0      1      0  71.2833        C
2              3        1      3  female  26.0      0      0   7.9250        S
3              4        1      1  female  35.0      1      0  53.1000        S
4              5        0      3    male  35.0      0      0   8.0500        S
..           ...      ...    ...     ...   ...    ...    ...      ...      ...
886          887        0      2    male  27.0      0      0  13.0000        S
887          888        1      1  female  19.0      0      0  30.0000        S
888          889        0      3  female  28.0      1      2  23.4500        S
889          890        1      1    male  26.0      0      0  30.0000        C
890          891        0      3    male  32.0      0      0   7.7500        Q

[889 rows x 9 columns]

In [25]:
final_train = pd.get_dummies(train,columns=["Sex"])
final_train.drop('Sex_female', axis = 1, inplace=True)
final_train

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Sex_male
0,1,0,3,22.0,1,0,7.2500,S,1
1,2,1,1,38.0,1,0,71.2833,C,0
2,3,1,3,26.0,0,0,7.9250,S,0
3,4,1,1,35.0,1,0,53.1000,S,0
4,5,0,3,35.0,0,0,8.0500,S,1
...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,13.0000,S,1
887,888,1,1,19.0,0,0,30.0000,S,0
888,889,0,3,28.0,1,2,23.4500,S,0
889,890,1,1,26.0,0,0,30.0000,C,1
890,891,0,3,32.0,0,0,7.7500,Q,1

In [26]:
final_train = pd.get_dummies(final_train,columns=["Pclass"])
final_train.drop('Pclass_1', axis = 1, inplace=True)
final_train

,PassengerId,Survived,Age,SibSp,Parch,Fare,Embarked,Sex_male,Pclass_2,Pclass_3
0,1,0,22.0,1,0,7.2500,S,1,0,1
1,2,1,38.0,1,0,71.2833,C,0,0,0
2,3,1,26.0,0,0,7.9250,S,0,0,1
3,4,1,35.0,1,0,53.1000,S,0,0,0
4,5,0,35.0,0,0,8.0500,S,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,887,0,27.0,0,0,13.0000,S,1,1,0
887,888,1,19.0,0,0,30.0000,S,0,0,0
888,889,0,28.0,1,2,23.4500,S,0,0,1
889,890,1,26.0,0,0,30.0000,C,1,0,0
890,891,0,32.0,0,0,7.7500,Q,1,0,1

In [27]:
final_train = pd.get_dummies(final_train,columns=["Embarked"])
final_train.drop('Embarked_C', axis = 1, inplace=True)
final_train

,PassengerId,Survived,Age,SibSp,Parch,Fare,Sex_male,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,1,0,22.0,1,0,7.2500,1,0,1,0,1
1,2,1,38.0,1,0,71.2833,0,0,0,0,0
2,3,1,26.0,0,0,7.9250,0,0,1,0,1
3,4,1,35.0,1,0,53.1000,0,0,0,0,1
4,5,0,35.0,0,0,8.0500,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,27.0,0,0,13.0000,1,1,0,0,1
887,888,1,19.0,0,0,30.0000,0,0,0,0,1
888,889,0,28.0,1,2,23.4500,0,0,1,0,1
889,890,1,26.0,0,0,30.0000,1,0,0,0,0
890,891,0,32.0,0,0,7.7500,1,0,1,1,0

In [28]:
k = final_train.pop("Survived")

In [29]:
y_train = k
print(y_train)

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 889, dtype: object

In [30]:
final_train.shape

(889, 10)

In [31]:
test

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survived
0,892,3,male,34.5,0,0,7.8292,Q,0
1,893,3,female,47.0,1,0,7.0000,S,1
2,894,2,male,62.0,0,0,9.6875,Q,0
3,895,3,male,27.0,0,0,8.6625,S,0
4,896,3,female,22.0,1,1,12.2875,S,1
...,...,...,...,...,...,...,...,...,...
413,1305,3,male,27.0,0,0,8.0500,S,0
414,1306,1,female,39.0,0,0,108.9000,C,1
415,1307,3,male,38.5,0,0,7.2500,S,0
416,1308,3,male,27.0,0,0,8.0500,S,0
417,1309,3,male,27.0,1,1,22.3583,C,0

In [32]:
test['Survived'] = test['Survived'].apply(str)

In [33]:
test['Pclass'] = test['Pclass'].apply(str)

In [34]:
final_test = pd.get_dummies(test,columns=["Sex"])
final_test.drop('Sex_female', axis = 1, inplace=True)
final_test

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Embarked,Survived,Sex_male
0,892,3,34.5,0,0,7.8292,Q,0,1
1,893,3,47.0,1,0,7.0000,S,1,0
2,894,2,62.0,0,0,9.6875,Q,0,1
3,895,3,27.0,0,0,8.6625,S,0,1
4,896,3,22.0,1,1,12.2875,S,1,0
...,...,...,...,...,...,...,...,...,...
413,1305,3,27.0,0,0,8.0500,S,0,1
414,1306,1,39.0,0,0,108.9000,C,1,0
415,1307,3,38.5,0,0,7.2500,S,0,1
416,1308,3,27.0,0,0,8.0500,S,0,1
417,1309,3,27.0,1,1,22.3583,C,0,1

In [35]:
final_test = pd.get_dummies(final_test,columns=["Pclass"])
final_test.drop('Pclass_1', axis = 1, inplace=True)
final_test

,PassengerId,Age,SibSp,Parch,Fare,Embarked,Survived,Sex_male,Pclass_2,Pclass_3
0,892,34.5,0,0,7.8292,Q,0,1,0,1
1,893,47.0,1,0,7.0000,S,1,0,0,1
2,894,62.0,0,0,9.6875,Q,0,1,1,0
3,895,27.0,0,0,8.6625,S,0,1,0,1
4,896,22.0,1,1,12.2875,S,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
413,1305,27.0,0,0,8.0500,S,0,1,0,1
414,1306,39.0,0,0,108.9000,C,1,0,0,0
415,1307,38.5,0,0,7.2500,S,0,1,0,1
416,1308,27.0,0,0,8.0500,S,0,1,0,1
417,1309,27.0,1,1,22.3583,C,0,1,0,1

In [36]:
final_test = pd.get_dummies(final_test,columns=["Embarked"])
final_test.drop('Embarked_C', axis = 1, inplace=True)
final_test

,PassengerId,Age,SibSp,Parch,Fare,Survived,Sex_male,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,892,34.5,0,0,7.8292,0,1,0,1,1,0
1,893,47.0,1,0,7.0000,1,0,0,1,0,1
2,894,62.0,0,0,9.6875,0,1,1,0,1,0
3,895,27.0,0,0,8.6625,0,1,0,1,0,1
4,896,22.0,1,1,12.2875,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,27.0,0,0,8.0500,0,1,0,1,0,1
414,1306,39.0,0,0,108.9000,1,0,0,0,0,0
415,1307,38.5,0,0,7.2500,0,1,0,1,0,1
416,1308,27.0,0,0,8.0500,0,1,0,1,0,1
417,1309,27.0,1,1,22.3583,0,1,0,1,0,0

In [37]:
y_test = final_test.pop("Survived")

In [38]:
print(y_test)

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: object

In [39]:
final_train

,PassengerId,Age,SibSp,Parch,Fare,Sex_male,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,1,22.0,1,0,7.2500,1,0,1,0,1
1,2,38.0,1,0,71.2833,0,0,0,0,0
2,3,26.0,0,0,7.9250,0,0,1,0,1
3,4,35.0,1,0,53.1000,0,0,0,0,1
4,5,35.0,0,0,8.0500,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,887,27.0,0,0,13.0000,1,1,0,0,1
887,888,19.0,0,0,30.0000,0,0,0,0,1
888,889,28.0,1,2,23.4500,0,0,1,0,1
889,890,26.0,0,0,30.0000,1,0,0,0,0
890,891,32.0,0,0,7.7500,1,0,1,1,0

In [40]:
final_test

,PassengerId,Age,SibSp,Parch,Fare,Sex_male,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,892,34.5,0,0,7.8292,1,0,1,1,0
1,893,47.0,1,0,7.0000,0,0,1,0,1
2,894,62.0,0,0,9.6875,1,1,0,1,0
3,895,27.0,0,0,8.6625,1,0,1,0,1
4,896,22.0,1,1,12.2875,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
413,1305,27.0,0,0,8.0500,1,0,1,0,1
414,1306,39.0,0,0,108.9000,0,0,0,0,0
415,1307,38.5,0,0,7.2500,1,0,1,0,1
416,1308,27.0,0,0,8.0500,1,0,1,0,1
417,1309,27.0,1,1,22.3583,1,0,1,0,0

In [41]:
scaler= StandardScaler()

scaler.fit(final_train)

StandardScaler()

In [42]:
Logistic_model = LogisticRegression(max_iter=4000)

Logistic_model.fit(final_train,y_train)

LogisticRegression(max_iter=4000)

In [43]:
y_pred =  Logistic_model.predict(final_test)

In [44]:
accuracy_score(y_test, y_pred)

0.9497607655502392

In [45]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=2, random_state=0)
rf.fit(final_train, y_train)
RF_pred = rf.predict(final_test)

In [46]:
accuracy_score(y_test,RF_pred)

0.7703349282296651

In [47]:
submission = pd.DataFrame()
submission['PassengerId'] = test['PassengerId']
submission['Survived'] = y_pred
submission.to_csv('GettingStartedWithtitanicmodel.csv',index=False)
print("Submission was successfully saved!")

Submission was successfully saved!