In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/digit-recognizer/sample_submission.csv
/kaggle/input/digit-recognizer/train.csv
/kaggle/input/digit-recognizer/test.csv

In [2]:
import tensorflow as tf
import tensorflow_decision_forests as tfdf

from sklearn.preprocessing import MinMaxScaler

from keras.utils.np_utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPool2D, BatchNormalization, Dropout
from keras.optimizers import SGD

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")

In [3]:
train_data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')
test_data = pd.read_csv('/kaggle/input/digit-recognizer/test.csv')

In [4]:
train_data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
x_train = train_data.drop(['label'], axis=1)
y_train = train_data['label']
x_test = test_data
scaler = MinMaxScaler()

In [6]:
y_train.value_counts()

1    4684
7    4401
3    4351
9    4188
2    4177
6    4137
0    4132
4    4072
8    4063
5    3795
Name: label, dtype: int64

In [7]:
x_train = pd.DataFrame(scaler.fit_transform(x_train), columns=scaler.feature_names_in_)
x_test = pd.DataFrame(scaler.transform(x_test), columns=scaler.feature_names_in_)

x_train = x_train.values.reshape(-1,28,28,1)
x_test = x_test.values.reshape(-1,28,28,1)
y_train = to_categorical(y_train, num_classes=10)

In [8]:
model = Sequential()

model.add(Conv2D(filters=32, kernel_size=(5,5), kernel_initializer='he_uniform', padding='Same', activation='relu', input_shape=(28,28,1)))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Conv2D(filters=64, kernel_size=(5,5), kernel_initializer='he_uniform', padding='Same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2)))

model.add(Conv2D(filters=128, kernel_size=(5,5), kernel_initializer='he_uniform', padding='Same', activation='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(pool_size=(2,2)))


model.add(Flatten())
model.add(Dense(128, kernel_initializer='he_uniform', activation='relu'))
model.add(BatchNormalization())


model.add(Dense(10, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 28, 28, 32)        832

 batch_normalization (BatchN  (None, 28, 28, 32)       128
 ormalization)

 max_pooling2d (MaxPooling2D  (None, 14, 14, 32)       0
 )

 conv2d_1 (Conv2D)           (None, 14, 14, 64)        51264

 batch_normalization_1 (Batc  (None, 14, 14, 64)       256
 hNormalization)

 max_pooling2d_1 (MaxPooling  (None, 7, 7, 64)         0
 2D)

 conv2d_2 (Conv2D)           (None, 7, 7, 128)         204928

 batch_normalization_2 (Batc  (None, 7, 7, 128)        512
 hNormalization)

 max_pooling2d_2 (MaxPooling  (None, 3, 3, 128)        0
 2D)

 flatten (Flatten)           (None, 1152)              0

 dense (Dense)               (None, 128)               147584

 batch_normalization_3 (Batc  (None, 128)              512
 hNormalization)

 dense_1 (Dense)             (None, 10)                1290

=================================================================
Total params: 407,306
Trainable params: 406,602
Non-trainable params: 704
_________________________________________________________________

In [9]:
model.compile(optimizer=SGD(learning_rate=0.01, momentum=0.9,), loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, validation_split=0.1, batch_size=50, epochs=59, verbose=2)

predictions = model.predict(x_test)
n_predictions = np.argmax(predictions, axis=1)

Epoch 1/59
756/756 - 96s - loss: 0.1025 - accuracy: 0.9679 - val_loss: 0.0630 - val_accuracy: 0.9807 - 96s/epoch - 127ms/step
Epoch 2/59
756/756 - 96s - loss: 0.0302 - accuracy: 0.9912 - val_loss: 0.0353 - val_accuracy: 0.9895 - 96s/epoch - 127ms/step
Epoch 3/59
756/756 - 94s - loss: 0.0182 - accuracy: 0.9948 - val_loss: 0.0400 - val_accuracy: 0.9867 - 94s/epoch - 124ms/step
Epoch 4/59
756/756 - 95s - loss: 0.0099 - accuracy: 0.9974 - val_loss: 0.0301 - val_accuracy: 0.9907 - 95s/epoch - 125ms/step
Epoch 5/59
756/756 - 95s - loss: 0.0056 - accuracy: 0.9989 - val_loss: 0.0254 - val_accuracy: 0.9924 - 95s/epoch - 125ms/step
Epoch 6/59
756/756 - 95s - loss: 0.0027 - accuracy: 0.9998 - val_loss: 0.0272 - val_accuracy: 0.9917 - 95s/epoch - 125ms/step
Epoch 7/59
756/756 - 95s - loss: 0.0017 - accuracy: 0.9998 - val_loss: 0.0247 - val_accuracy: 0.9919 - 95s/epoch - 125ms/step
Epoch 8/59
756/756 - 93s - loss: 0.0013 - accuracy: 0.9999 - val_loss: 0.0257 - val_accuracy: 0.9924 - 93s/epoch - 123ms/step
Epoch 9/59
756/756 - 93s - loss: 0.0012 - accuracy: 0.9998 - val_loss: 0.0267 - val_accuracy: 0.9929 - 93s/epoch - 124ms/step
Epoch 10/59
756/756 - 95s - loss: 6.8745e-04 - accuracy: 1.0000 - val_loss: 0.0267 - val_accuracy: 0.9921 - 95s/epoch - 126ms/step
Epoch 11/59
756/756 - 94s - loss: 5.8387e-04 - accuracy: 1.0000 - val_loss: 0.0247 - val_accuracy: 0.9919 - 94s/epoch - 124ms/step
Epoch 12/59
756/756 - 94s - loss: 4.7812e-04 - accuracy: 1.0000 - val_loss: 0.0258 - val_accuracy: 0.9919 - 94s/epoch - 124ms/step
Epoch 13/59
756/756 - 93s - loss: 4.8177e-04 - accuracy: 1.0000 - val_loss: 0.0253 - val_accuracy: 0.9919 - 93s/epoch - 123ms/step
Epoch 14/59
756/756 - 93s - loss: 3.3873e-04 - accuracy: 1.0000 - val_loss: 0.0256 - val_accuracy: 0.9921 - 93s/epoch - 123ms/step
Epoch 15/59
756/756 - 92s - loss: 4.9527e-04 - accuracy: 0.9999 - val_loss: 0.0258 - val_accuracy: 0.9924 - 92s/epoch - 122ms/step
Epoch 16/59
756/756 - 93s - loss: 3.7018e-04 - accuracy: 1.0000 - val_loss: 0.0261 - val_accuracy: 0.9931 - 93s/epoch - 123ms/step
Epoch 17/59
756/756 - 93s - loss: 2.9376e-04 - accuracy: 1.0000 - val_loss: 0.0254 - val_accuracy: 0.9924 - 93s/epoch - 123ms/step
Epoch 18/59
756/756 - 93s - loss: 2.3847e-04 - accuracy: 1.0000 - val_loss: 0.0262 - val_accuracy: 0.9924 - 93s/epoch - 124ms/step
Epoch 19/59
756/756 - 92s - loss: 2.3321e-04 - accuracy: 1.0000 - val_loss: 0.0262 - val_accuracy: 0.9924 - 92s/epoch - 122ms/step
Epoch 20/59
756/756 - 94s - loss: 2.0115e-04 - accuracy: 1.0000 - val_loss: 0.0258 - val_accuracy: 0.9919 - 94s/epoch - 125ms/step
Epoch 21/59
756/756 - 94s - loss: 1.9557e-04 - accuracy: 1.0000 - val_loss: 0.0252 - val_accuracy: 0.9921 - 94s/epoch - 124ms/step
Epoch 22/59
756/756 - 94s - loss: 1.8066e-04 - accuracy: 1.0000 - val_loss: 0.0250 - val_accuracy: 0.9917 - 94s/epoch - 125ms/step
Epoch 23/59
756/756 - 95s - loss: 1.7859e-04 - accuracy: 1.0000 - val_loss: 0.0256 - val_accuracy: 0.9917 - 95s/epoch - 125ms/step
Epoch 24/59
756/756 - 94s - loss: 2.0974e-04 - accuracy: 1.0000 - val_loss: 0.0252 - val_accuracy: 0.9912 - 94s/epoch - 124ms/step
Epoch 25/59
756/756 - 93s - loss: 1.8387e-04 - accuracy: 1.0000 - val_loss: 0.0249 - val_accuracy: 0.9919 - 93s/epoch - 123ms/step
Epoch 26/59
756/756 - 93s - loss: 1.5574e-04 - accuracy: 1.0000 - val_loss: 0.0265 - val_accuracy: 0.9917 - 93s/epoch - 123ms/step
Epoch 27/59
756/756 - 94s - loss: 1.4550e-04 - accuracy: 1.0000 - val_loss: 0.0268 - val_accuracy: 0.9919 - 94s/epoch - 124ms/step
Epoch 28/59
756/756 - 94s - loss: 1.2199e-04 - accuracy: 1.0000 - val_loss: 0.0267 - val_accuracy: 0.9919 - 94s/epoch - 124ms/step
Epoch 29/59
756/756 - 93s - loss: 1.3110e-04 - accuracy: 1.0000 - val_loss: 0.0267 - val_accuracy: 0.9919 - 93s/epoch - 124ms/step
Epoch 30/59
756/756 - 94s - loss: 1.2752e-04 - accuracy: 1.0000 - val_loss: 0.0262 - val_accuracy: 0.9919 - 94s/epoch - 125ms/step
Epoch 31/59
756/756 - 95s - loss: 1.1045e-04 - accuracy: 1.0000 - val_loss: 0.0264 - val_accuracy: 0.9917 - 95s/epoch - 125ms/step
Epoch 32/59
756/756 - 94s - loss: 1.1139e-04 - accuracy: 1.0000 - val_loss: 0.0269 - val_accuracy: 0.9919 - 94s/epoch - 125ms/step
Epoch 33/59
756/756 - 94s - loss: 1.1387e-04 - accuracy: 1.0000 - val_loss: 0.0268 - val_accuracy: 0.9917 - 94s/epoch - 124ms/step
Epoch 34/59
756/756 - 94s - loss: 1.1113e-04 - accuracy: 1.0000 - val_loss: 0.0268 - val_accuracy: 0.9914 - 94s/epoch - 124ms/step
Epoch 35/59
756/756 - 93s - loss: 1.0382e-04 - accuracy: 1.0000 - val_loss: 0.0270 - val_accuracy: 0.9912 - 93s/epoch - 123ms/step
Epoch 36/59
756/756 - 93s - loss: 1.0160e-04 - accuracy: 1.0000 - val_loss: 0.0273 - val_accuracy: 0.9910 - 93s/epoch - 124ms/step
Epoch 37/59
756/756 - 94s - loss: 9.3987e-05 - accuracy: 1.0000 - val_loss: 0.0273 - val_accuracy: 0.9912 - 94s/epoch - 124ms/step
Epoch 38/59
756/756 - 93s - loss: 8.9408e-05 - accuracy: 1.0000 - val_loss: 0.0267 - val_accuracy: 0.9914 - 93s/epoch - 124ms/step
Epoch 39/59
756/756 - 93s - loss: 9.8684e-05 - accuracy: 1.0000 - val_loss: 0.0273 - val_accuracy: 0.9912 - 93s/epoch - 123ms/step
Epoch 40/59
756/756 - 93s - loss: 9.0855e-05 - accuracy: 1.0000 - val_loss: 0.0270 - val_accuracy: 0.9917 - 93s/epoch - 123ms/step
Epoch 41/59
756/756 - 94s - loss: 7.8836e-05 - accuracy: 1.0000 - val_loss: 0.0274 - val_accuracy: 0.9917 - 94s/epoch - 124ms/step
Epoch 42/59
756/756 - 94s - loss: 8.6816e-05 - accuracy: 1.0000 - val_loss: 0.0271 - val_accuracy: 0.9919 - 94s/epoch - 124ms/step
Epoch 43/59
756/756 - 94s - loss: 8.5032e-05 - accuracy: 1.0000 - val_loss: 0.0271 - val_accuracy: 0.9914 - 94s/epoch - 124ms/step
Epoch 44/59
756/756 - 94s - loss: 8.1779e-05 - accuracy: 1.0000 - val_loss: 0.0273 - val_accuracy: 0.9914 - 94s/epoch - 124ms/step
Epoch 45/59
756/756 - 94s - loss: 7.4218e-05 - accuracy: 1.0000 - val_loss: 0.0272 - val_accuracy: 0.9914 - 94s/epoch - 124ms/step
Epoch 46/59
756/756 - 94s - loss: 7.6976e-05 - accuracy: 1.0000 - val_loss: 0.0274 - val_accuracy: 0.9914 - 94s/epoch - 124ms/step
Epoch 47/59
756/756 - 94s - loss: 7.5344e-05 - accuracy: 1.0000 - val_loss: 0.0273 - val_accuracy: 0.9921 - 94s/epoch - 124ms/step
Epoch 48/59
756/756 - 94s - loss: 7.3838e-05 - accuracy: 1.0000 - val_loss: 0.0274 - val_accuracy: 0.9919 - 94s/epoch - 125ms/step
Epoch 49/59
756/756 - 95s - loss: 7.0278e-05 - accuracy: 1.0000 - val_loss: 0.0274 - val_accuracy: 0.9919 - 95s/epoch - 125ms/step
Epoch 50/59
756/756 - 94s - loss: 6.7021e-05 - accuracy: 1.0000 - val_loss: 0.0269 - val_accuracy: 0.9921 - 94s/epoch - 124ms/step
Epoch 51/59
756/756 - 93s - loss: 6.2805e-05 - accuracy: 1.0000 - val_loss: 0.0269 - val_accuracy: 0.9924 - 93s/epoch - 123ms/step
Epoch 52/59
756/756 - 93s - loss: 6.4002e-05 - accuracy: 1.0000 - val_loss: 0.0269 - val_accuracy: 0.9921 - 93s/epoch - 123ms/step
Epoch 53/59
756/756 - 93s - loss: 6.9125e-05 - accuracy: 1.0000 - val_loss: 0.0271 - val_accuracy: 0.9921 - 93s/epoch - 123ms/step
Epoch 54/59
756/756 - 95s - loss: 7.1337e-05 - accuracy: 1.0000 - val_loss: 0.0276 - val_accuracy: 0.9921 - 95s/epoch - 126ms/step
Epoch 55/59
756/756 - 95s - loss: 6.1309e-05 - accuracy: 1.0000 - val_loss: 0.0272 - val_accuracy: 0.9919 - 95s/epoch - 126ms/step
Epoch 56/59
756/756 - 95s - loss: 5.7573e-05 - accuracy: 1.0000 - val_loss: 0.0274 - val_accuracy: 0.9917 - 95s/epoch - 125ms/step
Epoch 57/59
756/756 - 94s - loss: 5.3103e-05 - accuracy: 1.0000 - val_loss: 0.0277 - val_accuracy: 0.9919 - 94s/epoch - 124ms/step
Epoch 58/59
756/756 - 95s - loss: 5.4438e-05 - accuracy: 1.0000 - val_loss: 0.0272 - val_accuracy: 0.9921 - 95s/epoch - 125ms/step
Epoch 59/59
756/756 - 94s - loss: 5.7427e-05 - accuracy: 1.0000 - val_loss: 0.0276 - val_accuracy: 0.9921 - 94s/epoch - 124ms/step
875/875 [==============================] - 19s 21ms/step

In [10]:
pd.read_csv('/kaggle/input/digit-recognizer/sample_submission.csv')

       ImageId  Label
0            1      0
1            2      0
2            3      0
3            4      0
4            5      0
...        ...    ...
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

[28000 rows x 2 columns]

In [11]:
df = pd.DataFrame()
df['ImageId'] = range(1, 28001)
df['Label'] = n_predictions
df.to_csv('submission.csv', index=False)