In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [2]:
train_data= pd.read_csv('../input/titanic/train.csv')
train_data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [3]:
test_data=pd.read_csv('../input/titanic/test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
print(train_data.isnull().sum())
print(test_data.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [5]:
features=['Pclass', 'Sex' ,'Age', 'SibSp', 'Parch' ,'Fare' ,'Embarked']
y=train_data.Survived

In [6]:
train_data['Age']=train_data['Age'].fillna(train_data['Age'].mode()[0])
train_data['Embarked']=train_data['Embarked'].fillna(train_data['Embarked'].mode()[0])
test_data['Age']=test_data['Age'].fillna(test_data['Age'].mode()[0])
test_data['Fare']=test_data['Fare'].fillna(test_data['Fare'].median())

In [7]:
train_data.isnull().sum()
test_data.isnull().sum()
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])
X.head()

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,22.0,1,0,7.2500,0,1,0,0,1
1,1,38.0,1,0,71.2833,1,0,1,0,0
2,3,26.0,0,0,7.9250,1,0,0,0,1
3,1,35.0,1,0,53.1000,1,0,0,0,1
4,3,35.0,0,0,8.0500,0,1,0,0,1

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=6)

sc= StandardScaler()
x_train= sc.fit_transform(x_train)
x_test =sc.transform(x_test)
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(x_train, y_train)
predictions = model.score(x_test,y_test)
predictions

0.8565022421524664

In [9]:
sc= StandardScaler()
X= sc.fit_transform(X)
X_test =sc.transform(X_test)
shuffle(X, y,random_state=6)

[array([[-1.56610693,  0.1086274 , -0.4745452 , ..., -0.48204268,
         -0.30756234,  0.61583843],
        [ 0.82737724,  0.48764032, -0.4745452 , ..., -0.48204268,
         -0.30756234,  0.61583843],
        [ 0.82737724,  0.1086274 , -0.4745452 , ..., -0.48204268,
         -0.30756234,  0.61583843],
        ...,
        [-0.36936484, -1.86223977,  1.34013193, ..., -0.48204268,
         -0.30756234,  0.61583843],
        [ 0.82737724, -0.61149714, -0.4745452 , ..., -0.48204268,
         -0.30756234,  0.61583843],
        [ 0.82737724,  0.03282482, -0.4745452 , ..., -0.48204268,
         -0.30756234,  0.61583843]]),
 257    1
 4      0
 488    0
 651    1
 512    1
       ..
 335    0
 365    0
 618    1
 227    0
 713    0
 Name: Survived, Length: 891, dtype: int64]

In [10]:
model.fit(X, y)

predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!