In [1]:
import pandas as pd
import numpy as np

train = pd.read_csv("../input/titanic/train.csv")
test = pd.read_csv("../input/titanic/test.csv")
train = train.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1)
test = test.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1)
train = pd.concat([train, test], axis=0, ignore_index=True)
train

      Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0          0.0       3    male  22.0      1      0    7.2500        S
1          1.0       1  female  38.0      1      0   71.2833        C
2          1.0       3  female  26.0      0      0    7.9250        S
3          1.0       1  female  35.0      1      0   53.1000        S
4          0.0       3    male  35.0      0      0    8.0500        S
...        ...     ...     ...   ...    ...    ...       ...      ...
1304       NaN       3    male   NaN      0      0    8.0500        S
1305       NaN       1  female  39.0      0      0  108.9000        C
1306       NaN       3    male  38.5      0      0    7.2500        S
1307       NaN       3    male   NaN      0      0    8.0500        S
1308       NaN       3    male   NaN      1      1   22.3583        C

[1309 rows x 8 columns]

In [2]:
train["is_rich"] = 0
train["is_young"] = 0
train["is_old"] = 0
train.loc[(train["Pclass"] == 1) | (train["Fare"] > 112), "is_rich"] = 1
train.loc[train["Age"] < 18, "is_young"] = 1
train.loc[train["Age"] > 60, "is_old"] = 1

enc_col = ["Embarked", "Pclass", "Sex", "is_rich", "is_young", "is_old"]
for col in enc_col:
    train[col + "_enc"] = train[col].map(train.groupby(col).size() / len(train))
train

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,is_rich,is_young,is_old,Embarked_enc,Pclass_enc,Sex_enc,is_rich_enc,is_young_enc,is_old_enc
0,0.0,3,male,22.0,1,0,7.2500,S,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1,1.0,1,female,38.0,1,0,71.2833,C,1,0,0,0.206264,0.246753,0.355997,0.246753,0.882353,0.97479
2,1.0,3,female,26.0,0,0,7.9250,S,0,0,0,0.698243,0.541635,0.355997,0.753247,0.882353,0.97479
3,1.0,1,female,35.0,1,0,53.1000,S,1,0,0,0.698243,0.246753,0.355997,0.246753,0.882353,0.97479
4,0.0,3,male,35.0,0,0,8.0500,S,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,NaN,3,male,NaN,0,0,8.0500,S,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1305,NaN,1,female,39.0,0,0,108.9000,C,1,0,0,0.206264,0.246753,0.355997,0.246753,0.882353,0.97479
1306,NaN,3,male,38.5,0,0,7.2500,S,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1307,NaN,3,male,NaN,0,0,8.0500,S,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1308,NaN,3,male,NaN,1,1,22.3583,C,0,0,0,0.206264,0.541635,0.644003,0.753247,0.882353,0.97479

In [3]:
from sklearn.preprocessing import LabelEncoder
categorical_cols = ["Pclass", "Sex", "Embarked", "is_rich", "is_young", "is_old"]
ignore_col = ["Pclass", "is_rich", "is_young", "is_old"]
train.fillna("NaN", inplace=True)
for col in categorical_cols:
    if col in ignore_col:
        continue
    train[col] = LabelEncoder().fit_transform(train[col])
train

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,is_rich,is_young,is_old,Embarked_enc,Pclass_enc,Sex_enc,is_rich_enc,is_young_enc,is_old_enc
0,0,3,1,22,1,0,7.25,3,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1,1,1,0,38,1,0,71.2833,0,1,0,0,0.206264,0.246753,0.355997,0.246753,0.882353,0.97479
2,1,3,0,26,0,0,7.925,3,0,0,0,0.698243,0.541635,0.355997,0.753247,0.882353,0.97479
3,1,1,0,35,1,0,53.1,3,1,0,0,0.698243,0.246753,0.355997,0.246753,0.882353,0.97479
4,0,3,1,35,0,0,8.05,3,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,NaN,3,1,NaN,0,0,8.05,3,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1305,NaN,1,0,39,0,0,108.9,0,1,0,0,0.206264,0.246753,0.355997,0.246753,0.882353,0.97479
1306,NaN,3,1,38.5,0,0,7.25,3,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1307,NaN,3,1,NaN,0,0,8.05,3,0,0,0,0.698243,0.541635,0.644003,0.753247,0.882353,0.97479
1308,NaN,3,1,NaN,1,1,22.3583,0,0,0,0,0.206264,0.541635,0.644003,0.753247,0.882353,0.97479

In [4]:
columns = train.columns[1:]
columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'is_rich',
       'is_young', 'is_old', 'Embarked_enc', 'Pclass_enc', 'Sex_enc',
       'is_rich_enc', 'is_young_enc', 'is_old_enc'],
      dtype='object')

In [5]:
from catboost import Pool, CatBoostClassifier, CatBoostRegressor
from sklearn.model_selection import train_test_split

test = train[891:].reset_index(drop=True)
train = train[:891].reset_index(drop=True)
train = train.astype({"Survived": "int8"})
test = test.drop("Survived", axis=1)

NUM_STACK_ROUND = 7
# pred = np.zeros((NUM_STACK_ROUND, len(train), 1))
# test_pred = np.zeros((NUM_STACK_ROUND, len(test), 1))
params = dict(
    grow_policy = "Lossguide",
    l2_leaf_reg = 2,
)
for i in range(NUM_STACK_ROUND):
    if i == 0:
        X_train, X_val, y_train, y_val = train_test_split(train[columns], train["Survived"], test_size=0.1, random_state=i, shuffle=True, stratify =  train["Survived"])
        train_pool = Pool(X_train, y_train, cat_features = categorical_cols)
        val_pool = Pool(X_val, y_val, cat_features = categorical_cols)

        model = CatBoostClassifier(iterations = 1000, loss_function="Logloss", eval_metric="Accuracy", random_seed = i, **params)
        model.fit(train_pool, eval_set = val_pool, early_stopping_rounds = 400, verbose=100)
        predictions = train["Survived"].values - model.predict(train[columns], prediction_type="Class").ravel()
        test_predictions = model.predict(test[columns], prediction_type="Class")
        
        train = pd.concat([train, pd.DataFrame(predictions, columns = ["stack_" + str(i)])], axis=1)
        test = pd.concat([test, pd.DataFrame(test_predictions, columns = ["stack_" + str(i)])], axis=1)
    else:
        X_train, X_val, y_train, y_val = train_test_split(train[columns], train["stack_" + str(i-1)], test_size=0.1, random_state=i, shuffle=True)
        train_pool = Pool(X_train, y_train, cat_features = categorical_cols)
        val_pool = Pool(X_val, y_val, cat_features = categorical_cols)
        model = CatBoostRegressor(iterations = 1000, loss_function="MAE",random_seed = i, **params)
        model.fit(train_pool, eval_set=val_pool, early_stopping_rounds = 400, verbose=100)
        predictions = train["Survived"].values - model.predict(train[columns], prediction_type="RawFormulaVal").ravel()
        test_predictions = test["stack_0"].values - model.predict(test[columns], prediction_type="RawFormulaVal").ravel()
        train = pd.concat([train, pd.DataFrame(predictions, columns = ["stack_" + str(i)])], axis=1)
        test = pd.concat([test, pd.DataFrame(test_predictions, columns = ["stack_" + str(i)])], axis=1)
    
 
# meta_feat = np.column_stack(tuple(pred))
# cv_pool = Pool(train.drop("Survived", axis=1), train["Survived"], cat_features = categorical_cols)
# grid = {
#     "max_leaves": [2**3-1, 2**5-1, 2**7-1],
#     "depth": [6, 7, 8, 9, 10],
#     "l2_leaf_reg": [0, 1, 1.5, 2],
#     "bootstrap_type": ["Bayesian", "Bernoulli", "Poisson"],
#     "min_data_in_leaf": [1, 5, 7, 10, 20, 50],
#     "rsm": [0, 0.1, 0.2, 0.5, 0.7, 1]
# }

# model = CatBoostClassifier(iterations = 1000, loss_function="Logloss", custom_metric="Accuracy", eval_metric="Accuracy")
# model.randomized_search(grid, cv_pool, cv=5, n_iter = 300, verbose=False)

0:	learn: 0.8152310	test: 0.8000000	best: 0.8000000 (0)	total: 57.2ms	remaining: 57.2s
100:	learn: 0.8639201	test: 0.7888889	best: 0.8222222 (1)	total: 667ms	remaining: 5.94s
200:	learn: 0.8913858	test: 0.8000000	best: 0.8222222 (1)	total: 1.27s	remaining: 5.05s
300:	learn: 0.9151061	test: 0.8111111	best: 0.8222222 (1)	total: 1.86s	remaining: 4.32s
400:	learn: 0.9413233	test: 0.8111111	best: 0.8222222 (1)	total: 2.65s	remaining: 3.97s
Stopped by overfitting detector  (400 iterations wait)

bestTest = 0.8222222222
bestIteration = 1

Shrink model to first 2 iterations.
0:	learn: 0.1571534	test: 0.2329999	best: 0.2329999 (0)	total: 4.67ms	remaining: 4.66s
100:	learn: 0.1532006	test: 0.2342615	best: 0.2323616 (8)	total: 617ms	remaining: 5.49s
200:	learn: 0.1516373	test: 0.2348578	best: 0.2323616 (8)	total: 1.14s	remaining: 4.53s
300:	learn: 0.1498536	test: 0.2345611	best: 0.2323616 (8)	total: 1.78s	remaining: 4.14s
400:	learn: 0.1489247	test: 0.2345848	best: 0.2323616 (8)	total: 2.42s	remaining: 3.61s
Stopped by overfitting detector  (400 iterations wait)

bestTest = 0.2323616315
bestIteration = 8

Shrink model to first 9 iterations.
0:	learn: 0.3773280	test: 0.4085329	best: 0.4085329 (0)	total: 6.01ms	remaining: 6s
100:	learn: 0.1827313	test: 0.2306313	best: 0.2306313 (100)	total: 649ms	remaining: 5.78s
200:	learn: 0.1636731	test: 0.2158396	best: 0.2158396 (200)	total: 1.26s	remaining: 5.03s
300:	learn: 0.1553886	test: 0.2140780	best: 0.2136300 (247)	total: 1.97s	remaining: 4.57s
400:	learn: 0.1496922	test: 0.2141098	best: 0.2136300 (247)	total: 2.62s	remaining: 3.91s
500:	learn: 0.1455919	test: 0.2160303	best: 0.2136300 (247)	total: 3.26s	remaining: 3.25s
600:	learn: 0.1415542	test: 0.2153503	best: 0.2136300 (247)	total: 3.82s	remaining: 2.53s
Stopped by overfitting detector  (400 iterations wait)

bestTest = 0.2136299775
bestIteration = 247

Shrink model to first 248 iterations.
0:	learn: 0.1692455	test: 0.1521485	best: 0.1521485 (0)	total: 5.52ms	remaining: 5.51s
100:	learn: 0.1635057	test: 0.1525235	best: 0.1514193 (15)	total: 641ms	remaining: 5.7s
200:	learn: 0.1592600	test: 0.1523211	best: 0.1514193 (15)	total: 1.21s	remaining: 4.82s
300:	learn: 0.1546388	test: 0.1539593	best: 0.1514193 (15)	total: 1.81s	remaining: 4.2s
400:	learn: 0.1474843	test: 0.1553730	best: 0.1514193 (15)	total: 2.5s	remaining: 3.73s
Stopped by overfitting detector  (400 iterations wait)

bestTest = 0.1514193084
bestIteration = 15

Shrink model to first 16 iterations.
0:	learn: 0.3867841	test: 0.2952949	best: 0.2952949 (0)	total: 4.6ms	remaining: 4.6s
100:	learn: 0.1894234	test: 0.1338901	best: 0.1338901 (100)	total: 611ms	remaining: 5.43s
200:	learn: 0.1705629	test: 0.1239685	best: 0.1237941 (189)	total: 1.25s	remaining: 4.96s
300:	learn: 0.1612159	test: 0.1212279	best: 0.1211856 (294)	total: 1.94s	remaining: 4.51s
400:	learn: 0.1537988	test: 0.1211735	best: 0.1209120 (322)	total: 2.79s	remaining: 4.18s
500:	learn: 0.1492395	test: 0.1225124	best: 0.1209120 (322)	total: 3.51s	remaining: 3.49s
600:	learn: 0.1449775	test: 0.1246184	best: 0.1209120 (322)	total: 4.14s	remaining: 2.75s
700:	learn: 0.1417157	test: 0.1253459	best: 0.1209120 (322)	total: 4.78s	remaining: 2.04s
Stopped by overfitting detector  (400 iterations wait)

bestTest = 0.1209120466
bestIteration = 322

Shrink model to first 323 iterations.
0:	learn: 0.1612869	test: 0.1772146	best: 0.1772146 (0)	total: 5.94ms	remaining: 5.93s
100:	learn: 0.1575287	test: 0.1751914	best: 0.1751914 (100)	total: 581ms	remaining: 5.17s
200:	learn: 0.1544624	test: 0.1744397	best: 0.1742618 (187)	total: 1.16s	remaining: 4.6s
300:	learn: 0.1505007	test: 0.1748951	best: 0.1742618 (187)	total: 1.76s	remaining: 4.1s
400:	learn: 0.1462377	test: 0.1770031	best: 0.1742618 (187)	total: 2.38s	remaining: 3.55s
500:	learn: 0.1428706	test: 0.1775588	best: 0.1742618 (187)	total: 3.03s	remaining: 3.02s
Stopped by overfitting detector  (400 iterations wait)

bestTest = 0.1742618042
bestIteration = 187

Shrink model to first 188 iterations.
0:	learn: 0.3813479	test: 0.3641483	best: 0.3641483 (0)	total: 7.35ms	remaining: 7.35s
100:	learn: 0.1776643	test: 0.1997592	best: 0.1997592 (100)	total: 602ms	remaining: 5.36s
200:	learn: 0.1610197	test: 0.1931210	best: 0.1918016 (180)	total: 1.25s	remaining: 4.96s
300:	learn: 0.1512838	test: 0.1935477	best: 0.1918016 (180)	total: 1.86s	remaining: 4.33s
400:	learn: 0.1459918	test: 0.1951775	best: 0.1918016 (180)	total: 2.45s	remaining: 3.66s
500:	learn: 0.1428159	test: 0.1962691	best: 0.1918016 (180)	total: 3.02s	remaining: 3s
Stopped by overfitting detector  (400 iterations wait)

bestTest = 0.1918016364
bestIteration = 180

Shrink model to first 181 iterations.

In [6]:
train

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,is_rich,is_young,...,is_rich_enc,is_young_enc,is_old_enc,stack_0,stack_1,stack_2,stack_3,stack_4,stack_5,stack_6
0,0,3,1,22,1,0,7.25,3,0,0,...,0.753247,0.882353,0.97479,0,5.204621e-07,3.362071e-04,-8.567926e-07,1.168520e-04,0.000362,0.000113
1,1,1,0,38,1,0,71.2833,0,1,0,...,0.246753,0.882353,0.97479,0,1.000001e+00,1.549361e-04,9.985560e-01,5.620011e-04,0.999399,0.004332
2,1,3,0,26,0,0,7.925,3,0,0,...,0.753247,0.882353,0.97479,0,1.057328e+00,9.043289e-01,1.000309e+00,6.919216e-01,1.000393,0.822465
3,1,1,0,35,1,0,53.1,3,1,0,...,0.246753,0.882353,0.97479,0,1.000001e+00,3.244058e-03,9.996953e-01,2.120479e-03,0.999153,0.004482
4,0,3,1,35,0,0,8.05,3,0,0,...,0.753247,0.882353,0.97479,0,5.204621e-07,-3.584100e-07,5.995649e-07,-5.332139e-07,-0.000002,-0.000022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,3,0,0,...,0.753247,0.882353,0.97479,0,5.204621e-07,2.682764e-05,-6.347211e-05,-1.795075e-03,0.001979,-0.001984
887,1,1,0,19,0,0,30,3,1,0,...,0.246753,0.882353,0.97479,0,1.000001e+00,1.594307e-02,9.978724e-01,3.103227e-03,1.000972,0.005356
888,0,3,0,NaN,1,2,23.45,3,0,0,...,0.753247,0.882353,0.97479,0,8.304284e-07,-1.480709e-01,1.779497e-02,-1.665398e-01,0.023377,-0.183973
889,1,1,1,26,0,0,30,0,1,0,...,0.246753,0.882353,0.97479,1,1.000001e+00,8.807214e-01,9.964435e-01,8.660238e-01,1.007065,0.806430
890,0,3,1,32,0,0,7.75,2,0,0,...,0.753247,0.882353,0.97479,0,5.804621e-07,5.638075e-04,-1.236506e-04,4.104884e-05,-0.000251,0.000040

In [7]:
test

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,is_rich,is_young,is_old,...,is_rich_enc,is_young_enc,is_old_enc,stack_0,stack_1,stack_2,stack_3,stack_4,stack_5,stack_6
0,3,1,34.5,0,0,7.8292,2,0,0,0,...,0.753247,0.882353,0.97479,0,5.804621e-07,5.419342e-04,-1.236506e-04,4.409255e-05,-0.002016,0.000084
1,3,0,47,1,0,7,3,0,0,0,...,0.753247,0.882353,0.97479,1,1.027355e+00,7.938139e-01,1.000573e+00,9.503240e-01,1.009900,0.878692
2,2,1,62,0,0,9.6875,2,0,0,1,...,0.753247,0.882353,0.02521,0,5.204621e-07,-8.367802e-02,-4.341420e-05,-1.462447e-01,0.077209,-0.040312
3,3,1,27,0,0,8.6625,3,0,0,0,...,0.753247,0.882353,0.97479,0,5.204621e-07,-8.661013e-06,2.737739e-06,3.064074e-05,-0.000038,-0.000021
4,3,0,22,1,1,12.2875,3,0,0,0,...,0.753247,0.882353,0.97479,1,1.028228e+00,7.182231e-01,9.793952e-01,4.668096e-01,1.008809,0.679651
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,3,1,NaN,0,0,8.05,3,0,0,0,...,0.753247,0.882353,0.97479,0,5.204621e-07,-1.931956e-06,7.911536e-07,-1.153193e-06,0.000001,-0.000023
414,1,0,39,0,0,108.9,0,1,0,0,...,0.246753,0.882353,0.97479,1,1.000001e+00,4.229950e-04,9.998408e-01,4.765380e-04,0.999678,0.004321
415,3,1,38.5,0,0,7.25,3,0,0,0,...,0.753247,0.882353,0.97479,0,5.204621e-07,-9.943007e-08,5.995649e-07,5.347934e-07,-0.000004,-0.000021
416,3,1,NaN,0,0,8.05,3,0,0,0,...,0.753247,0.882353,0.97479,0,5.204621e-07,-1.931956e-06,7.911536e-07,-1.153193e-06,0.000001,-0.000023
417,3,1,NaN,1,1,22.3583,0,0,0,0,...,0.753247,0.882353,0.97479,0,5.786621e-07,-1.752062e-01,-6.703783e-03,-2.909005e-01,0.000285,-0.078489

In [8]:
sub = pd.read_csv("../input/titanic/gender_submission.csv")
stack_cols = [c for c in test.columns if "stack_" in c]
LR = 0.1
final_pred = test.stack_0
for col in stack_cols[2:]:
    final_pred += test[col].values * LR

THRESHOLD = 0.502684253587
final_pred = np.where(final_pred > THRESHOLD, 1, 0)
sub["Survived"] = final_pred
sub.head(15)

    PassengerId  Survived
0           892         0
1           893         1
2           894         0
3           895         0
4           896         1
5           897         0
6           898         1
7           899         0
8           900         1
9           901         0
10          902         0
11          903         0
12          904         1
13          905         0
14          906         1

In [9]:
sub.to_csv("submission.csv", index=False)