In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
train_raw_data=pd.read_csv('../input/titanic/train.csv')
test_raw_data=pd.read_csv('../input/titanic/test.csv')

In [3]:
trainrow=train_raw_data.shape[0]
testrow=test_raw_data.shape[0]
y_train=train_raw_data['Survived'].copy()
train_raw_data=train_raw_data.drop(['Survived'],1)

In [4]:
combine=pd.concat([train_raw_data,test_raw_data])
combine.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
print(combine.shape)
print(train_raw_data.shape)
print(test_raw_data.shape)

(1309, 11)
(891, 11)
(418, 11)

In [6]:
combine.isnull().sum()

PassengerId       0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [7]:
#here we can se only three features has missing data
#Emabarked lets replace it with most frequent data
combine['Embarked']=combine['Embarked'].fillna(combine['Embarked'].value_counts().index[0])

In [8]:
combine['Cabin']=combine['Cabin'].fillna('U')
combine['Cabin'].value_counts()
combine['Cabin']=combine['Cabin'].astype(str).str[0]
combine.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,U,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,U,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,U,S

In [9]:
combine.loc[combine['Fare'].isnull()]

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
152,1044,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,U,S

In [10]:
#fare depend on Pclass,Sex, and age
combine['Fare']=combine['Fare'].fillna(combine.loc[(combine['Pclass']==3) & (combine['Sex']=="male") & (combine['Age']<65) & (combine['Age']>55)].dropna()['Fare'].mean())

In [11]:
combine.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,U,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,U,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,U,S

In [12]:
passengerids=test_raw_data['PassengerId']
combine=combine.drop(['PassengerId','Ticket'],1)

In [13]:
combine.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,U,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,U,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,U,S

In [14]:
combine['familysize']=combine['SibSp']+combine['Parch']+1
combine.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,familysize
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,U,S,2
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,C,2
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,U,S,1
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C,S,2
4,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,U,S,1

In [15]:
combine['Title'] = combine.Name.str.extract(' ([A-Za-z]+)\.', expand=False)
combine.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,familysize,Title
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,7.2500,U,S,2,Mr
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,71.2833,C,C,2,Mrs
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,7.9250,U,S,1,Miss
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,53.1000,C,S,2,Mrs
4,3,"Allen, Mr. William Henry",male,35.0,0,0,8.0500,U,S,1,Mr

In [16]:
combine.Title.unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'Countess',
       'Jonkheer', 'Dona'], dtype=object)

In [17]:
combine['Title'].value_counts()

Mr          757
Miss        260
Mrs         197
Master       61
Rev           8
Dr            8
Col           4
Ms            2
Major         2
Mlle          2
Don           1
Lady          1
Capt          1
Jonkheer      1
Mme           1
Countess      1
Sir           1
Dona          1
Name: Title, dtype: int64

In [18]:
# combine['Title']=combine['Title'].map({"Mr":0,"Miss":1,"Mrs":2,"Master":3,"Dr":3,"Rev":3,"Major":3,"Col":3,"Mlle":3,"Don":3,"Jonkheer":3,"Countess":3,"Sir":0,"Capt":3,"Mme":2,"Lady":1,"Ms":0,"Dona":3})
# combine.head()

In [19]:
combine=combine.drop(['Name'],1)
combine.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,familysize,Title
0,3,male,22.0,1,0,7.2500,U,S,2,Mr
1,1,female,38.0,1,0,71.2833,C,C,2,Mrs
2,3,female,26.0,0,0,7.9250,U,S,1,Miss
3,1,female,35.0,1,0,53.1000,C,S,2,Mrs
4,3,male,35.0,0,0,8.0500,U,S,1,Mr

In [20]:
combine=combine.drop(['SibSp','Parch'],1)
combine.head()

   Pclass     Sex   Age     Fare Cabin Embarked  familysize Title
0       3    male  22.0   7.2500     U        S           2    Mr
1       1  female  38.0  71.2833     C        C           2   Mrs
2       3  female  26.0   7.9250     U        S           1  Miss
3       1  female  35.0  53.1000     C        S           2   Mrs
4       3    male  35.0   8.0500     U        S           1    Mr

In [21]:
combine['Sex']=combine['Sex'].map({'male':0,'female':1})
combine.head()

   Pclass  Sex   Age     Fare Cabin Embarked  familysize Title
0       3    0  22.0   7.2500     U        S           2    Mr
1       1    1  38.0  71.2833     C        C           2   Mrs
2       3    1  26.0   7.9250     U        S           1  Miss
3       1    1  35.0  53.1000     C        S           2   Mrs
4       3    0  35.0   8.0500     U        S           1    Mr

In [22]:
print(combine.Pclass.unique())
print(combine.Sex.unique())

[3 1 2]
[0 1]

In [23]:
for i in range(0,2):
    for j in range(0,3):
        print(i,j+1)
        temp_dataset=combine[(combine['Sex']==i) &  (combine['Pclass']==j+1)]['Age'].dropna()
        print(temp_dataset)
        #print(str(temp_dataset.median())+"  "+str(i)+"  "+str(j+1))
        combine.loc[(combine.Age.isnull()) & (combine.Sex==i) & (combine.Pclass==j+1),'Age']=int(temp_dataset.median())

0 1
6      54.0
23     28.0
27     19.0
30     40.0
34     28.0
       ...
378    55.0
390    23.0
403    17.0
404    43.0
407    50.0
Name: Age, Length: 151, dtype: float64
0 2
20     35.0
21     34.0
33     66.0
70     32.0
72     21.0
       ...
387    57.0
393    47.0
401    38.0
405    20.0
406    23.0
Name: Age, Length: 158, dtype: float64
0 3
0      22.0
4      35.0
7       2.0
12     20.0
13     39.0
       ...
394    29.0
396    24.0
398    22.0
399    31.0
415    38.5
Name: Age, Length: 349, dtype: float64
1 1
1      38.0
3      35.0
11     58.0
52     49.0
61     38.0
       ...
397    48.0
400    30.0
402    22.0
411    37.0
414    39.0
Name: Age, Length: 133, dtype: float64
1 2
9      14.0
15     55.0
41     27.0
43      3.0
53     29.0
       ...
330    48.0
349    31.0
361    24.0
362    31.0
385    24.0
Name: Age, Length: 103, dtype: float64
1 3
2      26.0
8      27.0
10      4.0
14     14.0
18     31.0
       ...
367    22.0
376    22.0
383    19.0
409     3.0
412    28.0
Name: Age, Length: 152, dtype: float64

In [24]:
combine.isnull().sum()

Pclass        0
Sex           0
Age           0
Fare          0
Cabin         0
Embarked      0
familysize    0
Title         0
dtype: int64

In [25]:
combine.head()

   Pclass  Sex   Age     Fare Cabin Embarked  familysize Title
0       3    0  22.0   7.2500     U        S           2    Mr
1       1    1  38.0  71.2833     C        C           2   Mrs
2       3    1  26.0   7.9250     U        S           1  Miss
3       1    1  35.0  53.1000     C        S           2   Mrs
4       3    0  35.0   8.0500     U        S           1    Mr

In [26]:
combine_checkpoint=combine.copy()
combine.head()

   Pclass  Sex   Age     Fare Cabin Embarked  familysize Title
0       3    0  22.0   7.2500     U        S           2    Mr
1       1    1  38.0  71.2833     C        C           2   Mrs
2       3    1  26.0   7.9250     U        S           1  Miss
3       1    1  35.0  53.1000     C        S           2   Mrs
4       3    0  35.0   8.0500     U        S           1    Mr

In [27]:
combine=combine_checkpoint.copy()
combine.head()

   Pclass  Sex   Age     Fare Cabin Embarked  familysize Title
0       3    0  22.0   7.2500     U        S           2    Mr
1       1    1  38.0  71.2833     C        C           2   Mrs
2       3    1  26.0   7.9250     U        S           1  Miss
3       1    1  35.0  53.1000     C        S           2   Mrs
4       3    0  35.0   8.0500     U        S           1    Mr

In [28]:
combine['Age_Band']=pd.cut(combine['Age'],5)
combine['Age_Band'].unique()

[(16.136, 32.102], (32.102, 48.068], (48.068, 64.034], (0.0902, 16.136], (64.034, 80.0]]
Categories (5, interval[float64]): [(0.0902, 16.136] < (16.136, 32.102] < (32.102, 48.068] < (48.068, 64.034] < (64.034, 80.0]]

In [29]:
combine.loc[(combine['Age']<=16.136),'Age']=1
combine.loc[(combine['Age']>16.136) & (combine['Age']<=32.102),'Age']=2
combine.loc[(combine['Age']>32.102) & (combine['Age']<=48.068),'Age']=3
combine.loc[(combine['Age']>48.068) & (combine['Age']<=64.034),'Age']=4
combine.loc[(combine['Age']>64.034) & (combine['Age']<=80.),'Age']=5
combine['Age'].unique()

array([2., 3., 4., 1., 5.])

In [30]:
combine=combine.drop(['Age_Band'],1)

In [31]:
combine['Fare_Band']=pd.cut(combine['Fare'],3)
combine['Fare_Band'].unique()

[(-0.512, 170.776], (170.776, 341.553], (341.553, 512.329]]
Categories (3, interval[float64]): [(-0.512, 170.776] < (170.776, 341.553] < (341.553, 512.329]]

In [32]:
combine.loc[(combine['Fare']<=170.776),'Fare']=1
combine.loc[(combine['Fare']>170.776) & (combine['Fare']<=314.553),'Fare']=2
combine.loc[(combine['Fare']>314.553) & (combine['Fare']<=513),'Fare']=3
combine=combine.drop(['Fare_Band'],1)

In [33]:
combine['Fare'].value_counts()

1.0    1271
2.0      34
3.0       4
Name: Fare, dtype: int64

In [34]:
combine=pd.get_dummies(columns=['Pclass','Sex','Cabin','Embarked','Title','Age','Fare'],data=combine)
combine.head()

,familysize,Pclass_1,Pclass_2,Pclass_3,Sex_0,Sex_1,Cabin_A,Cabin_B,Cabin_C,Cabin_D,...,Title_Rev,Title_Sir,Age_1.0,Age_2.0,Age_3.0,Age_4.0,Age_5.0,Fare_1.0,Fare_2.0,Fare_3.0
0,2,0,0,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1,2,1,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,1,0,0
2,1,0,0,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,2,1,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,1,0,0
4,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [35]:
x_train=combine.iloc[:trainrow]
x_test=combine.iloc[trainrow:]

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
scaler=StandardScaler()
scaler.fit(x_train)
x_scaled_train=scaler.transform(x_train)
x_scaled_train

array([[ 0.05915988, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [ 0.05915988,  1.76776695, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [-0.56097483, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       ...,
       [ 1.29942929, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [-0.56097483,  1.76776695, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [-0.56097483, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382]])

In [38]:
x_scaled_test=scaler.transform(x_test)
x_scaled_test

array([[-0.56097483, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [ 0.05915988, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [-0.56097483, -0.56568542,  1.96020185, ...,  0.15153255,
        -0.13946613, -0.05812382],
       ...,
       [-0.56097483, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [-0.56097483, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382],
       [ 0.67929458, -0.56568542, -0.51015154, ...,  0.15153255,
        -0.13946613, -0.05812382]])

In [39]:
from sklearn.linear_model import LogisticRegression
reg=LogisticRegression()
reg.fit(x_scaled_train,y_train)
print(reg.score(x_scaled_train,y_train))
y_pred=reg.predict(x_scaled_test)
y_pred

0.8406285072951739

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1])

In [40]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(x_scaled_train,y_train,early_stopping_rounds=5, 
             eval_set=[(x_scaled_train, y_train)], 
             verbose=False)
print(xgb.score(x_scaled_train,y_train))
y_pred=xgb.predict(x_scaled_test)

0.8720538720538721

In [41]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=4,n_estimators=500,warm_start=True,max_depth=6,min_samples_leaf=2,max_features='sqrt')
rfc.fit(x_scaled_train,y_train)
print(rfc.score(x_scaled_train,y_train))
y_pred=rfc.predict(x_scaled_test)

0.8462401795735129

In [42]:
# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier(n_neighbors = 2)
# classifier.fit(x_scaled_train,y_train)
# print(classifier.score(x_scaled_train,y_train))
# y_pred=classifier.predict(x_scaled_test)

In [43]:
passengerids.head()

0    892
1    893
2    894
3    895
4    896
Name: PassengerId, dtype: int64

In [44]:
submission = pd.DataFrame({
        "PassengerId": passengerids,
        "Survived": y_pred
    })
submission

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [45]:
submission.to_csv('submission1.csv', index=False)


<h1>Check out my other Notebooks</h1><font size='4'>
<a href="https://www.kaggle.com/vishalvanpariya/top-5-on-leaderboard" target="_blank">House Price</a><br>
<a href="https://www.kaggle.com/vishalvanpariya/data-explanation-titanic" target="_blank">Titanic EDA</a><br>
<a href="https://www.kaggle.com/vishalvanpariya/nlp-for-beginners" target="_blank">NLP</a><br><font>
<a href="https://www.kaggle.com/vishalvanpariya/basic-visualization-for-beginners" target="_blank">Basic Visualization</a><br><font>