**What are you trying to do in this notebook?**

My task is to predict whether a passenger was transported to an alternate dimension during the Spaceship Titanic's collision with the spaceship anomaly.

The Spaceship titanic was an interstellar passenger liner launched a month ago. With almost 13,000 passengers on board, the vessel set out on it's maiden voyage transporting immigrants from our solar system to three new habitable exoplanets orbiting nearby stars.

**Why are you trying it?**

To help rescue crews and retrieve the lost passengers and to predict where passengers were transported by the anomaly using records recovered from the spaceship’s damaged computer system.

Help, save them and change history!

There is a information about dataset :-

* PassengerId - A unique Id for each passenger. Each Id takes the form gggg_pp where gggg indicates a group the passenger is travelling with and pp is their number within the group. People in a group are often family members, but not always.

* HomePlanet - The planet the passenger departed from, typically their planet of permanent residence.

* CryoSleep - Indicates whether the passenger elected to be put into suspended animation for the duration of the voyage. Passengers in cryosleep are confined to their cabins.

* Cabin - The cabin number where the passenger is staying. Takes the form deck/num/side, where side can be either P for Port or S for Starboard.

* Destination - The planet the passenger will be debarking to.

* Age - The age of the passenger.

* VIP - Whether the passenger has paid for special VIP service during the voyage.

* RoomService, FoodCourt, ShoppingMall, Spa, VRDeck - Amount the passenger has billed at each of the Spaceship Titanic's many luxury amenities.

* Name - The first and last names of the passenger.

* Transported - Whether the passenger was transported to another dimension. This is the target, the column you are trying to predict.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spaceship-titanic-models/80687_submission_v11.csv
/kaggle/input/spaceship-titanic-models/80921_submission_v1.csv
/kaggle/input/spaceship-titanic-models/78419_submission_v9.csv
/kaggle/input/spaceship-titanic-models/80921a_submission_smakoto_v2.csv
/kaggle/input/spaceship-titanic-models/80500_submission_v4.csv
/kaggle/input/spaceship-titanic-models/76689_submission_knn_v3.csv
/kaggle/input/spaceship-titanic-models/80967a_submission_v1.csv
/kaggle/input/spaceship-titanic-models/80967_submission_v10.csv
/kaggle/input/spaceship-titanic-models/81131a_submission_v5.csv
/kaggle/input/spaceship-titanic-models/80570_submission_v9.csv
/kaggle/input/spaceship-titanic-models/80710_submission_v3.csv
/kaggle/input/spaceship-titanic-models/80804_submission_v8.csv
/kaggle/input/spaceship-titanic-models/80991a_submission_v5.csv
/kaggle/input/spaceship-titanic-models/80593_submission_v24.csv
/kaggle/input/spaceship-titanic-models/80617_submission_stack_v55.csv
/kaggle/input/spaceship-titanic-models/80640_submission_v16.csv
/kaggle/input/spaceship-titanic-models/80991_submission_v4.csv
/kaggle/input/spaceship-titanic/sample_submission.csv
/kaggle/input/spaceship-titanic/train.csv
/kaggle/input/spaceship-titanic/test.csv

In [2]:
sub = pd.read_csv('../input/spaceship-titanic/sample_submission.csv')

In [3]:
sub.sort_values(by=['PassengerId'], inplace=True)
sub['Transported'] = sub['Transported'].astype('float')

In [4]:
sub.head(10)

  PassengerId  Transported
0     0013_01          0.0
1     0018_01          0.0
2     0019_01          0.0
3     0021_01          0.0
4     0023_01          0.0
5     0027_01          0.0
6     0029_01          0.0
7     0032_01          0.0
8     0032_02          0.0
9     0033_01          0.0

In [5]:
sub1 = pd.read_csv('../input/spaceship-titanic-models/80967_submission_v10.csv')
sub1.sort_values(by=['PassengerId'], inplace=True)
sub1['Transported'] = sub1['Transported'].astype('float')

In [6]:
sub2 = pd.read_csv('../input/spaceship-titanic-models/80921_submission_v1.csv')
sub2.sort_values(by=['PassengerId'], inplace=True)
sub2['Transported'] = sub2['Transported'].astype('float')

In [7]:
sub3 = pd.read_csv('../input/spaceship-titanic-models/80921a_submission_smakoto_v2.csv')
sub3.sort_values(by=['PassengerId'], inplace=True)
sub3['Transported'] = sub3['Transported'].astype('float')

In [8]:
sub4 = pd.read_csv('../input/spaceship-titanic-models/80804_submission_v8.csv')
sub4.sort_values(by=['PassengerId'], inplace=True)
sub4['Transported'] = sub4['Transported'].astype('float')

In [9]:
sub5 = pd.read_csv('../input/spaceship-titanic-models/80710_submission_v3.csv')
sub5.sort_values(by=['PassengerId'], inplace=True)
sub5['Transported'] = sub5['Transported'].astype('float')

In [10]:
sub6 = pd.read_csv('../input/spaceship-titanic-models/80687_submission_v11.csv')
sub6.sort_values(by=['PassengerId'], inplace=True)
sub6['Transported'] = sub6['Transported'].astype('float')

In [11]:
sub7 = pd.read_csv('../input/spaceship-titanic-models/80640_submission_v16.csv')
sub7.sort_values(by=['PassengerId'], inplace=True)
sub7['Transported'] = sub7['Transported'].astype('float')

In [12]:
sub8 = pd.read_csv('../input/spaceship-titanic-models/80617_submission_stack_v55.csv')
sub8.sort_values(by=['PassengerId'], inplace=True)
sub8['Transported'] = sub8['Transported'].astype('float')

In [13]:
sub9 = pd.read_csv('../input/spaceship-titanic-models/80593_submission_v24.csv')
sub9.sort_values(by=['PassengerId'], inplace=True)
sub9['Transported'] = sub9['Transported'].astype('float')

In [14]:
sub10 = pd.read_csv('../input/spaceship-titanic-models/80570_submission_v9.csv')
sub10.sort_values(by=['PassengerId'], inplace=True)
sub10['Transported'] = sub10['Transported'].astype('float')

In [15]:
sub11 = pd.read_csv('../input/spaceship-titanic-models/80500_submission_v4.csv')
sub11.sort_values(by=['PassengerId'], inplace=True)
sub11['Transported'] = sub11['Transported'].astype('float')

In [16]:
sub12 = pd.read_csv('../input/spaceship-titanic-models/78419_submission_v9.csv')
sub12.sort_values(by=['PassengerId'], inplace=True)
sub12['Transported'] = sub12['Transported'].astype('float')

In [17]:
sub13 = pd.read_csv('../input/spaceship-titanic-models/76689_submission_knn_v3.csv')
sub13.sort_values(by=['PassengerId'], inplace=True)
sub13['Transported'] = sub13['Transported'].astype('float')

In [18]:
sub14 = pd.read_csv('../input/spaceship-titanic-models/80991_submission_v4.csv')
sub14.sort_values(by=['PassengerId'], inplace=True)
sub14['Transported'] = sub14['Transported'].astype('float')

In [19]:
sub15 = pd.read_csv('../input/spaceship-titanic-models/80991a_submission_v5.csv')
sub15.sort_values(by=['PassengerId'], inplace=True)
sub15['Transported'] = sub15['Transported'].astype('float')

In [20]:
sub16 = pd.read_csv('../input/spaceship-titanic-models/81131a_submission_v5.csv')
sub16.sort_values(by=['PassengerId'], inplace=True)
sub16['Transported'] = sub16['Transported'].astype('float')

In [21]:
sub17 = pd.read_csv('../input/spaceship-titanic-models/80967a_submission_v1.csv')
sub17.sort_values(by=['PassengerId'], inplace=True)
sub17['Transported'] = sub17['Transported'].astype('float')

In [22]:
b = 1000.0
S = 0.81131
q = 0.0

In [23]:
sub['Transported'] = sub1['Transported']*np.exp(b*(0.80967-S))
q = q + np.exp(b*(0.80967-S))

In [24]:
sub['Transported'] = sub['Transported'] + sub2['Transported']*np.exp(b*(0.80921-S))
q = q + np.exp(b*(0.80921-S))

In [25]:
sub['Transported'] = sub['Transported'] + sub3['Transported']*np.exp(b*(0.80921-S))
q = q + np.exp(b*(0.80921-S))

In [26]:
sub['Transported'] = sub['Transported'] + sub4['Transported']*np.exp(b*(0.80804-S))
q = q + np.exp(b*(0.80804-S))

In [27]:
sub['Transported'] = sub['Transported'] + sub5['Transported']*np.exp(b*(0.80710-S))
q = q + np.exp(b*(0.80710-S))

In [28]:
sub['Transported'] = sub['Transported'] + sub6['Transported']*np.exp(b*(0.80687-S))
q = q + np.exp(b*(0.80687-S))

In [29]:
sub['Transported'] = sub['Transported'] + sub7['Transported']*np.exp(b*(0.80640-S))
q = q + np.exp(b*(0.80640-S))

In [30]:
sub['Transported'] = sub['Transported'] + sub8['Transported']*np.exp(b*(0.80617-S))
q = q + np.exp(b*(0.80617-S))

In [31]:
sub['Transported'] = sub['Transported'] + sub9['Transported']*np.exp(b*(0.80593-S))
q = q + np.exp(b*(0.80593-S))

In [32]:
sub['Transported'] = sub['Transported'] + sub10['Transported']*np.exp(b*(0.80570-S))
q = q + np.exp(b*(0.80570-S))

In [33]:
sub['Transported'] = sub['Transported'] + sub11['Transported']*np.exp(b*(0.80500-S))
q = q + np.exp(b*(0.80500-S))

In [34]:
sub['Transported'] = sub['Transported'] + sub12['Transported']*np.exp(b*(0.78419-S))
q = q + np.exp(b*(0.78419-S))

In [35]:
sub['Transported'] = sub['Transported'] + sub13['Transported']*np.exp(b*(0.76689-S))
q = q + np.exp(b*(0.76689-S))

In [36]:
sub['Transported'] = sub['Transported'] + sub14['Transported']*np.exp(b*(0.80991-S))
q = q + np.exp(b*(0.80991-S))

In [37]:
sub['Transported'] = sub['Transported'] + sub15['Transported']*np.exp(b*(0.80991-S))
q = q + np.exp(b*(0.80991-S))

In [38]:
sub['Transported'] = sub['Transported'] + sub16['Transported']*np.exp(b*(0.81131-S))
q = q + np.exp(b*(0.81131-S))

In [39]:
sub['Transported'] = sub['Transported'] + sub17['Transported']*np.exp(b*(0.80967-S))
q = q + np.exp(b*(0.80967-S))

In [40]:
sub['Transported'] = sub['Transported']/q
print(q)

2.2140327054773135

In [41]:
sub.head(10)

  PassengerId  Transported
0     0013_01     0.827901
1     0018_01     0.000000
2     0019_01     1.000000
3     0021_01     1.000000
4     0023_01     0.104851
5     0027_01     0.732484
6     0029_01     1.000000
7     0032_01     1.000000
8     0032_02     1.000000
9     0033_01     0.944691

In [42]:
sub['Transported'] = np.rint(sub['Transported'])

In [43]:
sub.head(10)

  PassengerId  Transported
0     0013_01          1.0
1     0018_01          0.0
2     0019_01          1.0
3     0021_01          1.0
4     0023_01          0.0
5     0027_01          1.0
6     0029_01          1.0
7     0032_01          1.0
8     0032_02          1.0
9     0033_01          1.0

In [44]:
sub['Transported'] = sub['Transported'].astype('bool')

In [45]:
sub.to_csv('submission.csv', index=False)

In [46]:
sub.head(10)

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01        False
5     0027_01         True
6     0029_01         True
7     0032_01         True
8     0032_02         True
9     0033_01         True

**Did it work?**

My observations are -

* 8693 rows(obervations) and 14 columns(13 features + 1 target varible)
* data types -int,float,obj
* Notice - we have some feature which have multiple informations in one column and this are also have the greatest cardinality
* we also some missing values
* we haveBinary columns- Transported,CryoSleep,VIP
* high cardinality in columns

**What did you not understand about it?**

Well, everything provides in the competition data page. I've no problem while working on it. If you guys don't understand the thing that I'll do in this notebook then please comment on this notebook.

The Spaceship Titanic was an interstellar passenger liner launched a month ago. With almost 13,000 passengers on board, the vessel set out on its maiden voyage transporting emigrants from our solar system to three newly habitable exoplanets orbiting nearby stars.

While rounding Alpha Centauri en route to its first destination—the torrid 55 Cancri E—the unwary Spaceship Titanic collided with a spacetime anomaly hidden within a dust cloud. Sadly, it met a similar fate as its namesake from 1000 years before. Though the ship stayed intact, almost half of the passengers were transported to an alternate dimension!

**I Hope you find this notebook useful , Good Luck!**