In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv

In [2]:
dataset = pd.read_csv('../input/house-prices-advanced-regression-techniques/train.csv')
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
from pycaret.regression import *

ModuleNotFoundError: No module named 'pycaret'

In [4]:
data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (1314, 81)
Unseen Data For Predictions: (146, 81)

In [5]:
exp_reg101 = setup(data = data, target = 'SalePrice', session_id=123,categorical_imputation= 'mode',
                  normalize = True, transformation = True, transform_target = True, numeric_imputation= 'mean', remove_outliers= True,outliers_threshold=0.05, remove_multicollinearity= True,feature_selection = True,feature_selection_threshold = 0.4, feature_selection_method='classic')

NameError: name 'setup' is not defined

In [6]:
best = compare_models(exclude = ['ransac'])

NameError: name 'compare_models' is not defined

In [7]:
huber = create_model('huber')

NameError: name 'create_model' is not defined

In [8]:
print(huber)

NameError: name 'huber' is not defined

In [9]:
tuned_huber = tune_model(huber)

NameError: name 'tune_model' is not defined

In [10]:
plot_model(tuned_huber)

NameError: name 'plot_model' is not defined

In [11]:
plot_model(tuned_huber, plot = 'error')

NameError: name 'plot_model' is not defined

In [12]:
plot_model(tuned_huber, plot='feature')

NameError: name 'plot_model' is not defined

In [13]:
predict_model(tuned_huber)

NameError: name 'predict_model' is not defined

In [14]:
final_huber = finalize_model(tuned_huber)
print(final_huber)

NameError: name 'finalize_model' is not defined

In [15]:
predict_model(final_huber)

NameError: name 'predict_model' is not defined

In [16]:
unseen_predictions = predict_model(final_huber, data=data_unseen)
unseen_predictions.head()

NameError: name 'predict_model' is not defined

In [17]:
from pycaret.utils import check_metric
check_metric(unseen_predictions.SalePrice, unseen_predictions.Label, 'R2')

ModuleNotFoundError: No module named 'pycaret'

In [18]:
save_model(final_huber,'Final Huber Model 21Jan2021')

NameError: name 'save_model' is not defined

In [19]:
saved_final_huber = load_model('Final Huber Model 21Jan2021')

NameError: name 'load_model' is not defined

In [20]:
new_prediction = predict_model(saved_final_huber, data=data_unseen)

NameError: name 'predict_model' is not defined

In [21]:
from pycaret.utils import check_metric
check_metric(unseen_predictions.SalePrice, unseen_predictions.Label, 'R2')

ModuleNotFoundError: No module named 'pycaret'

In [22]:
dataset_test = pd.read_csv('../input/house-prices-advanced-regression-techniques/test.csv')
dataset_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [23]:
new_test_prediction = predict_model(saved_final_huber, data=dataset_test)

NameError: name 'predict_model' is not defined

In [24]:
new_test_prediction.to_excel('House Prediction.xlsx')

NameError: name 'new_test_prediction' is not defined