In [1]:
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
import string
from nltk.stem import WordNetLemmatizer

In [2]:
data=pd.read_csv('../input/nlp-getting-started/train.csv',index_col=0)
test=pd.read_csv('../input/nlp-getting-started/test.csv',index_col=0)

In [3]:
data.fillna('',inplace=True)

In [4]:
test.fillna('',inplace=True)

In [5]:
data.head()

   keyword location                                               text  target
id
1                    Our Deeds are the Reason of this #earthquake M...       1
4                               Forest fire near La Ronge Sask. Canada       1
5                    All residents asked to 'shelter in place' are ...       1
6                    13,000 people receive #wildfires evacuation or...       1
7                    Just got sent this photo from Ruby #Alaska as ...       1

In [6]:
test.head()

   keyword location                                               text
id
0                                   Just happened a terrible car crash
2                    Heard about #earthquake is different cities, s...
3                    there is a forest fire at spot pond, geese are...
9                             Apocalypse lighting. #Spokane #wildfires
11                       Typhoon Soudelor kills 28 in China and Taiwan

In [7]:
finaldata=data['keyword']+' '+data['location']+' '+data['text']
testdata=test['keyword']+' '+test['location']+' '+test['text']
finaltarget=data['target']

In [8]:
finaldata.head()

id
1      Our Deeds are the Reason of this #earthquake...
4               Forest fire near La Ronge Sask. Canada
5      All residents asked to 'shelter in place' ar...
6      13,000 people receive #wildfires evacuation ...
7      Just got sent this photo from Ruby #Alaska a...
dtype: object

In [9]:
testdata.head()

id
0                    Just happened a terrible car crash
2       Heard about #earthquake is different cities,...
3       there is a forest fire at spot pond, geese a...
9              Apocalypse lighting. #Spokane #wildfires
11        Typhoon Soudelor kills 28 in China and Taiwan
dtype: object

In [10]:
finaltarget.head()

id
1    1
4    1
5    1
6    1
7    1
Name: target, dtype: int64

In [11]:
WNL=WordNetLemmatizer()
def text_process(data):
    msg=[c for c in data if c not in string.punctuation]
    msg=''.join(msg)
    msg=[word for word in msg.split() if word.lower() not in stopwords.words('english')]
    msg=[WNL.lemmatize(word) for word in msg ]
    return msg

In [12]:
finaldata.head(10).apply(text_process)

id
1     [Deeds, Reason, earthquake, May, ALLAH, Forgiv...
4         [Forest, fire, near, La, Ronge, Sask, Canada]
5     [resident, asked, shelter, place, notified, of...
6     [13000, people, receive, wildfire, evacuation,...
7     [got, sent, photo, Ruby, Alaska, smoke, wildfi...
8     [RockyFire, Update, California, Hwy, 20, close...
10    [flood, disaster, Heavy, rain, cause, flash, f...
13                     [Im, top, hill, see, fire, wood]
14    [Theres, emergency, evacuation, happening, bui...
15                  [Im, afraid, tornado, coming, area]
dtype: object

In [13]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [14]:
CV=CountVectorizer(analyzer=text_process)

In [15]:
CV.fit(finaldata)

CountVectorizer(analyzer=<function text_process at 0x7f1682e58cb0>)

In [16]:
CV.vocabulary_

{'Deeds': 3729,
 'Reason': 9947,
 'earthquake': 15994,
 'May': 7872,
 'ALLAH': 954,
 'Forgive': 4962,
 'u': 27006,
 'Forest': 4958,
 'fire': 16539,
 'near': 23693,
 'La': 7107,
 'Ronge': 10253,
 'Sask': 10646,
 'Canada': 2746,
 'resident': 25097,
 'asked': 13786,
 'shelter': 25626,
 'place': 24374,
 'notified': 23840,
 'officer': 23925,
 'evacuation': 16239,
 'order': 24031,
 'expected': 16311,
 '13000': 159,
 'people': 24249,
 'receive': 24926,
 'wildfire': 27506,
 'California': 2709,
 'got': 16967,
 'sent': 25543,
 'photo': 24312,
 'Ruby': 10302,
 'Alaska': 1239,
 'smoke': 25852,
 'pours': 24512,
 'school': 25436,
 'RockyFire': 10218,
 'Update': 12401,
 'Hwy': 6080,
 '20': 292,
 'closed': 14901,
 'direction': 15699,
 'due': 15941,
 'Lake': 7126,
 'County': 3321,
 'CAfire': 2509,
 'flood': 16601,
 'disaster': 15715,
 'Heavy': 5798,
 'rain': 24818,
 'cause': 14675,
 'flash': 16581,
 'flooding': 16603,
 'street': 26195,
 'Manitou': 7767,
 'Colorado': 3164,
 'Springs': 11216,
 'area': 13723,
 'Im': 6238,
 'top': 26786,
 'hill': 17327,
 'see': 25497,
 'wood': 27585,
 'Theres': 11907,
 'emergency': 16089,
 'happening': 17159,
 'building': 14453,
 'across': 13390,
 'afraid': 13451,
 'tornado': 26796,
 'coming': 15002,
 'Three': 11943,
 'died': 15670,
 'heat': 17249,
 'wave': 27378,
 'far': 16424,
 'Haha': 5652,
 'South': 11152,
 'Tampa': 11724,
 'getting': 16880,
 'flooded': 16602,
 'hah': 17110,
 'WAIT': 12652,
 'SECOND': 10378,
 'LIVE': 7059,
 'SOUTH': 10476,
 'TAMPA': 11546,
 'GONNA': 5167,
 'FVCK': 4693,
 'raining': 24823,
 'Florida': 4916,
 'TampaBay': 11725,
 '18': 226,
 '19': 245,
 'day': 15426,
 'Ive': 6437,
 'lost': 23035,
 'count': 15185,
 'Flood': 4907,
 'Bago': 1837,
 'Myanmar': 8298,
 'arrived': 13756,
 'Damage': 3622,
 'bus': 14491,
 '80': 767,
 'multi': 23588,
 'car': 14610,
 'crash': 15225,
 'BREAKING': 1781,
 'Whats': 12943,
 'man': 23146,
 'love': 23044,
 'fruit': 16762,
 'Summer': 11419,
 'lovely': 23047,
 'fast': 16434,
 'goooooooaaaaaal': 16962,
 'ridiculous': 25179,
 'London': 7403,
 'cool': 15142,
 'Love': 7453,
 'skiing': 25779,
 'wonderful': 27581,
 'LOOOOOOL': 7081,
 'wayI': 27381,
 'cant': 14584,
 'eat': 16004,
 'shit': 25639,
 'NYC': 8424,
 'last': 22773,
 'week': 27415,
 'girlfriend': 16903,
 'Cooool': 3267,
 'like': 22914,
 'pasta': 24198,
 'end': 16127,
 'ablaze': 13337,
 'Birmingham': 2098,
 'bbcmtd': 14041,
 'Wholesale': 12971,
 'Markets': 7815,
 'httptcolHYXEOHY6C': 21032,
 'Est': 4445,
 'September': 10794,
 '2012': 308,
 'Bristol': 2334,
 'always': 13576,
 'try': 26939,
 'bring': 14397,
 'heavy': 17255,
 'metal': 23333,
 'RT': 9841,
 'httptcoYAo1e0xngw': 20138,
 'AFRICA': 922,
 'AFRICANBAZE': 923,
 'Breaking': 2302,
 'newsNigeria': 23740,
 'flag': 16575,
 'set': 25568,
 'Aba': 1066,
 'httptco2nndBGwyEi': 18042,
 'Philadelphia': 9325,
 'PA': 8976,
 'Crying': 3407,
 'Set': 10810,
 'UK': 12272,
 'plus': 24423,
 'side': 25690,
 'LOOK': 7080,
 'SKY': 10442,
 'LAST': 7009,
 'NIGHT': 8372,
 'ABLAZE': 896,
 'httptcoqqsmshaJ3N': 21403,
 'Pretoria': 9556,
 'PhDSquares': 9313,
 'mufc': 23585,
 'theyve': 26616,
 'built': 14458,
 'much': 23581,
 'hype': 22081,
 'around': 13748,
 'new': 23730,
 'acquisition': 13387,
 'doubt': 15849,
 'EPL': 4161,
 'season': 25476,
 'World': 13080,
 'Wide': 12976,
 'INEC': 6155,
 'Office': 8806,
 'Abia': 1080,
 'Ablaze': 1081,
 'httptco3ImaomknnA': 18073,
 'Barbados': 1888,
 'Bridgetown': 2321,
 'JAMAICA': 6450,
 '\x89ÛÒ': 27846,
 'Two': 12245,
 'SANTA': 10347,
 'CRUZ': 2651,
 '\x89ÛÓ': 27849,
 'Head': 5772,
 'St': 11236,
 'Elizabeth': 4305,
 'Police': 9453,
 'Superintende': 11447,
 'httptcowDUEaj8Q4J': 21775,
 'Paranaque': 9177,
 'City': 3037,
 'Lord': 7429,
 'Live': 7353,
 'Webcam': 12888,
 'Check': 2931,
 'httptcorOI2NSmEJJ': 21449,
 'httptco3Tj8ZjiN21': 18085,
 'httptcoYDUiXEfIpE': 20140,
 'httptcoLxTjc87KLS': 19336,
 'nsfw': 23858,
 'outside': 24077,
 'youre': 27745,
 'alive': 13538,
 'dead': 15437,
 'inside': 22303,
 'milky': 23391,
 'way': 27380,
 'awesome': 13906,
 'time': 26698,
 'visiting': 27256,
 'CFC': 2536,
 'head': 17220,
 'office': 23924,
 'ancop': 13615,
 'site': 25759,
 'Thanks': 11858,
 'Tita': 11987,
 'Vida': 12566,
 'taking': 26441,
 'care': 14617,
 'SOOOO': 10471,
 'PUMPED': 9095,
 'southridgelife': 25977,
 'wanted': 27318,
 'Chicago': 2952,
 'preaching': 24534,
 'hotel': 17423,
 'httptcoo9qknbfOFX': 21218,
 'gained': 16814,
 '3': 431,
 'follower': 16632,
 'Know': 6948,
 'stats': 26118,
 'grow': 17039,
 'httptcoTIyUliF5c6': 19837,
 'GREENSBORONORTH': 5184,
 'CAROLINA': 2499,
 'West': 12919,
 'burned': 14482,
 'Thousands': 11934,
 'alone': 13560,
 'httptcovl5TBR3wbr': 21748,
 'Building': 2408,
 'perfect': 24257,
 'tracklist': 26832,
 'life': 22888,
 'leave': 22824,
 'England': 4370,
 'First': 4870,
 'night': 23764,
 'retainer': 25131,
 'quite': 24780,
 'weird': 27424,
 'Better': 2047,
 'get': 16878,
 'used': 27150,
 'wear': 27396,
 'every': 16249,
 'single': 25737,
 'next': 23748,
 'year': 27711,
 'least': 22822,
 'Sheffield': 10871,
 'Township': 12069,
 'Ohio': 8826,
 'Deputies': 3793,
 'Man': 7750,
 'shot': 25663,
 'Brighton': 2328,
 'home': 17372,
 'httptcogWNRhMSO8k': 20682,
 'India': 6280,
 'wife': 27501,
 'six': 25765,
 'jail': 22452,
 'setting': 25571,
 'niece': 23760,
 'httptcoeV1ahOUCZA': 20545,
 'Superintendent': 11448,
 'Lanford': 7149,
 'Salmon': 10594,
 'r': 24789,
 'httptcovplR5Hka2u': 21750,
 'httptcoSxHW2TNNLf': 19805,
 'Anaheim': 1348,
 'Arsonist': 1507,
 'Deliberately': 3752,
 'Black': 2117,
 'Church': 3018,
 'North': 8646,
 'CarolinaåÊAblaze': 2801,
 'httptcopcXarbH9An': 21322,
 'Abuja': 1094,
 'Noches': 8627,
 'ElBestia': 4280,
 'AlexisSanchez': 1265,
 'happy': 17165,
 'teammate': 26493,
 'training': 26847,
 'hard': 17174,
 'goodnight': 16955,
 'gunner': 17085,
 'httptcouc4j4jHvGR': 21669,
 'USA': 12301,
 'Kurds': 6982,
 'trampling': 26850,
 'Turkmen': 12220,
 'later': 22779,
 'others': 24049,
 'vandalized': 27188,
 'Front': 5064,
 'Diyala': 3924,
 'httptco4IzFdYC3cg': 18142,
 'Africa': 1178,
 'TRUCK': 11659,
 'R21': 9747,
 'VOORTREKKER': 12477,
 'AVE': 1045,
 'OUTSIDE': 8766,
 'TAMBO': 11545,
 'INTL': 6169,
 'CARGO': 2498,
 'SECTION': 10381,
 'httptco8kscqKfKkF': 18430,
 'Sao': 10638,
 'Paulo': 9233,
 'Brazil': 2295,
 'heart': 17243,
 'city': 14843,
 'gift': 16893,
 'skyline': 25790,
 'kiss': 22671,
 'upon': 27116,
 'lip': 22932,
 '\x89Û': 27790,
 'httpstcocYoMPZ1A0Z': 17684,
 'hollywoodland': 17368,
 'sky': 25789,
 'tonight': 26770,
 'Los': 7433,
 'Angeles': 1368,
 'expecting': 16312,
 'IG': 6127,
 'FB': 4588,
 'filled': 16514,
 'sunset': 26321,
 'know': 22693,
 'peep': 24240,
 'Edmonton': 4257,
 'Alberta': 1246,
 'Treaty': 12114,
 '6': 660,
 'httptcoiCSjGZ9tE1': 20804,
 'climate': 14886,
 'energy': 16140,
 'httptco9FxmN0l0Bd': 18464,
 'Revel': 10111,
 'wmv': 27565,
 'video': 27228,
 'mean': 23267,
 'mac': 23099,
 'farewell': 16426,
 'en': 16112,
 'route': 25272,
 'dvd': 15964,
 'GtxRWm': 5491,
 'Inang': 6261,
 'Pamantasan': 9145,
 'Progressive': 9605,
 'greeting': 17017,
 'month': 23512,
 'student': 26232,
 'would': 27620,
 'pen': 24244,
 'Torch': 12036,
 'Publications': 9651,
 'httptco9FxPiXQuJt': 18463,
 'Twitter': 12243,
 'Lockout': 7391,
 'progress': 24634,
 'Rene': 10044,
 'amp': 13597,
 'Jacinta': 6492,
 'Secret': 10742,
 '2k13': 422,
 'Fallen': 4728,
 'Skies': 11005,
 'Edit': 4251,
 'Mar': 7780,
 '30': 432,
 '2013': 309,
 'httpstco7MLMsUzV1Z': 17493,
 'Concord': 3207,
 'CA': 2471,
 'Navista7': 8494,
 'Steve': 11311,
 'something': 25933,
 'else': 16075,
 'tinderbox': 26711,
 'clown': 14912,
 'hood': 17394,
 'News24680': 8552,
 'Calgary': 2700,
 'AB': 888,
 'NowPlaying': 8682,
 'Ian': 6194,
 'Buff': 2399,
 'Magnitude': 7709,
 'httptcoAv2JSjfFtc': 18579,
 'EDM': 4113,
 'nxwestmidlands': 23881,
 'huge': 22039,
 'market': 23195,
 'httptcorwzbFVNXER': 21479,
 'San': 10612,
 'Francisco': 5004,
 'talk': 26446,
 'go': 16930,
 'dont': 15830,
 'make': 23131,
 'work': 27592,
 'accident': 13360,
 'CLVLND': 2584,
 'kid': 22636,
 'cuz': 15346,
 'bicycle': 14153,
 'split': 26038,
 'testicle': 26547,
 'impossible': 22195,
 'MICHAEL': 7585,
 'FATHER': 4583,
 'Nashville': 8467,
 'TN': 11622,
 'Accident': 1103,
 'I24': 6091,
 'W': 12647,
 'NashvilleTraffic': 8469,
 'Traffic': 12081,
 'moving': 23569,
 '8m': 810,
 'slower': 25825,
 'usual': 27159,
 'httpstco0GHk693EgJ': 17446,
 'Santa': 10631,
 'Clara': 3057,
 'center': 14699,
 'lane': 22759,
 'blocked': 14244,
 'SantaClara': 10632,
 'US101': 12299,
 'NB': 8328,
 'Great': 5439,
 'America': 1326,
 'Pkwy': 9392,
 'BayArea': 1933,
 'httptcopmlOhZuRWR': 21335,
 'httptcoGKYe6gjTk5': 18936,
 'personalinjury': 24279,
 'summer': 26302,
 'Read': 9931,
 'advice': 13437,
 'solicitor': 25922,
 'help': 17280,
 'OtleyHour': 8949,
 'Louis': 7448,
 'MO': 7618,
 'stlouis': 26155,
 'caraccidentlawyer': 14612,
 'Speeding': 11189,
 'Among': 1341,
 'Top': 12031,
 'Causes': 2850,
 'Teen': 11783,
 'Accidents': 1104,
 'httpstcok4zoMOF319': 17738,
 'httpstcoS2kXVM0cBA': 17612,
 'Car': 2779,
 'tee\x89Û': 26509,
 'Walker': 12798,
 'Alabama': 1230,
 'Reported': 10062,
 'motor': 23549,
 'vehicle': 27199,
 'Curry': 3433,
 'Herman': 5838,
 'Rd': 9923,
 'Stephenson': 11303,
 'involving': 22396,
 'overturned': 24104,
 'Please': 9427,
 'use': 27148,
 'httptcoYbJezKuRW1': 20152,
 'Australia': 1620,
 'BigRigRadio': 2066,
 'Awareness': 1654,
 'Carolina': 2800,
 'I77': 6098,
 'Mile': 8040,
 'Marker': 7807,
 '31': 449,
 'Mooresville': 8177,
 'Iredell': 6382,
 'Vehicle': 12530,
 'Ramp': 9896,
 'Closed': 3088,
 '86': 797,
 '118': 128,
 'PM': 9038,
 'SleepJunkies': 11026,
 'Sleeping': 11027,
 'pill': 24347,
 'double': 15848,
 'risk': 25204,
 'httptco7s9Nm1fiCT': 18373,
 'Norf': 8639,
 'knew': 22686,
 'gon': 16947,
 'happen': 17157,
 'httpstcoYsxun5vCeh': 17664,
 'Mateo': 7853,
 'N': 8311,
 'CABRILLO': 2472,
 'HWYMAGELLAN': 5639,
 'AV': 1043,
 'MIR': 7598,
 '080615': 50,
 '110358': 113,
 '40': 521,
 'Congestion': 3217,
 'Njoro': 8613,
 'Kenya': 6859,
 'pastor': 24200,
 'scene': 25431,
 'accidentwho': 13365,
 'owner': 24111,
 'range': 24840,
 'rover': 25273,
 'mom': 23494,
 'didnt': 15665,
 'wished': 27545,
 'truck': 26926,
 'spilt': 26028,
 'mayonnaise': 23256,
 'Sisters': 10989,
 'Bedroom': 1964,
 'horrible': 17411,
 'past': 24197,
 'Sunday': 11428,
 'finally': 16524,
 'able': 13338,
 'Thank': 11855,
 'GOD': 5164,
 'wait': 27300,
 'pissed': 24360,
 'Donnie': 3958,
 'tell': 26514,
 'ANOTHER': 982,
 'Arlington': 1487,
 'TX': 11690,
 'TruckCrash': 12168,
 'Overturns': 8967,
 'FortWorth': 4974,
 'Interstate': 6354,
 'httptcoRs22LJ4qFp': 19740,
 'Click': 3079,
 'youve': 27750,
 'crashgthttptcoLd0unIYw4k': 15227,
 'Bloomfield': 2163,
 'OH': 8726,
 'Ashville': 1543,
 'US': 12298,
 '23': 355,
 'SB': 10353,
 'SR': 10492,
 '752': 750,
 'traffic': 26838,
 'httptcohylMo0WgFI': 20788,
 'Motorcyclist': 8210,
 'Dies': 3864,
 'I540': 6094,
 'Crash': 3351,
 'Crossed': 3387,
 'Median': 7916,
 'motorcycle': 23550,
 'rider': 25177,
 'traveling': 26871,
 'httptcop18lzRlmy6': 21274,
 'New': 8539,
 'Hanover': 5698,
 'NC': 8337,
 'FYI': 4698,
 'CADFYI': 2473,
 'ACCIDENT': 903,
 'PROPERTY': 9078,
 'DAMAGENHS999': 3465,
 'PINER': 9025,
 'RDHORNDALE': 9766,
 'DR': 3564,
 'Maldives': 7742,
 'nAAYf': 23643,
 'Turning': 12225,
 'onto': 23991,
 'Chandanee': 2896,
 'Magu': 7715,
 'MMA': 7613,
 'Taxi': 11753,
 'rammed': 24832,
 'halfway': 17138,
 'turned': 26961,
 'Everyone': 4495,
 'conf\x89Û': 15079,
 'Manchester': 7756,
 'NH': 8360,
 'left': 22830,
 'Rt': 10296,
 '293': 401,
 'Eddy': 4245,
 'stop': 26164,
 'back': 13934,
 'NH3A': 8362,
 'delay': 15513,
 '4': 520,
 'min': 23395,
 'Wilmington': 13002,
 'DAMAGE': 3463,
 'httptcoOia5fxi4gM': 19530,
 'DAMAGEWPD1600': 3466,
 '17TH': 222,
 'ST': 10501,
 '862015209': 801,
 'TRAFFIC': 11639,
 'INJURY': 6161,
 '2781': 390,
 'WILLIS': 12704,
 'FOREMAN': 4660,
 'RD': 9765,
 'httptcoVCkIT6EDEv': 19967,
 'global': 16920,
 'Aashiqui': 1064,
 'Actress': 1131,
 'Anu': 1419,
 'Aggarwal': 1194,
 'NearFatal': 8502,
 'httptco6Otfp31LqW': 18276,
 'Montana': 8160,
 'Suffield': 11405,
 'httpstcobPTmlF4P10': 17679,
 'Charlotte': 2916,
 '9': 812,
 'backup': 13941,
 'Southaccident': 11157,
 'blocking': 14245,
 'Right': 10151,
 '2': 291,
 'Lanes': 7148,
 'Exit': 4516,
 'Langtree': 7151,
 'Rdconsider': 9924,
 '115': 126,
 '150': 177,
 '16': 194,
 'alternate': 13572,
 'Baton': 1924,
 'Rouge': 10279,
 'LA': 6999,
 'changed': 14725,
 'determine': 15622,
 'option': 24022,
 'financially': 16527,
 'support': 26336,
 'plan': 24380,
 'ongoing': 23983,
 'treatment': 26879,
 'Hagerstown': 5651,
 'MD': 7560,
 'deadly': 15441,
 'happened': 17158,
 'today': 26734,
 'Ill': 6231,
 'detail': 15618,
 '5': 597,
 'Your4State': 13237,
 'WHAG': 12694,
 'Gloucestershire': 5361,
 'flowri': 16612,
 'marinading': 23188,
 'even': 16243,
 'fucking': 16773,
 'Mfs': 8003,
 'drive': 15898,
 'NorwayMFA': 8661,
 'Bahrain': 1841,
 'police': 24443,
 'previously': 24591,
 'road': 25217,
 'killed': 22648,
 'explosion': 16336,
 'httpstcogFJfgTodad': 17710,
 'Nairobi': 8447,
 'still': 26151,
 'heard': 17239,
 'Leaders': 7210,
 'forward': 16694,
 'comment': 15006,
 'issue': 22420,
 'disciplinary': 15721,
 'measuresArrestPastorNganga': 23275,
 'aftershock': 13459,
 'Instagram': 6327,
 'heyimginog': 17301,
 'afterShockDeLo': 13455,
 'scuf': 25463,
 'p': 24115,
 'live': 22949,
 'game': 16818,
 'cya': 15348,
 '304': 441,
 'effort': 16031,
 'painful': 24136,
 'win': 27514,
 'Roger': 10221,
 'Bannister': 1880,
 'Switzerland': 11522,
 '320': 457,
 'IR': 6176,
 'ICEMOON': 6111,
 'AFTERSHOCK': 924,
 'httptcoyNXnvVKCDA': 21924,
 'djicemoon': 15788,
 'Dubstep': 4059,
 'TrapMusic': 12100,
 'DnB': 3927,
 'Dance': 3638,
 'Ices\x89Û': 6207,
 'httptcoweQPesENku': 21794,
 'victory': 27225,
 'bargain': 13996,
 'basement': 14008,
 'price': 24592,
 'Dwight': 4090,
 'David': 3682,
 'Eisenhower': 4276,
 'httptcovAM5POdGyw': 21709,
 'httptcozEVakJaPcz': 21984,
 'Nobody': 8626,
 'remembers': 25027,
 'came': 14553,
 'second': 25485,
 'Charles': 2910,
 'Schulz': 10694,
 'im': 22162,
 'speaking': 25997,
 'someone': 25931,
 'using': 27158,
 'xb1': 27687,
 'also': 13569,
 'harder': 17176,
 'conflict': 15076,
 'glorious': 16923,
 'triumph': 26911,
 'Thomas': 11924,
 'Paine': 9119,
 'GrowingUpSpoiled': 5484,
 'going': 16940,
 'clay': 14869,
 'pigeon': 24339,
 'shooting': 25655,
 'cry': 15301,
 'Somewhere': 11111,
 'guess': 17067,
 'one': 23978,
 'actually': 13404,
 'want': 27317,
 'free': 16725,
 'Aftershock': 1188,
 'TC': 11557,
 'terrifying': 26538,
 'best': 14132,
 'roller': 25241,
 'coaster': 14933,
 'ever': 16247,
 'DISCLAIMER': 3535,
 'Belgium': 1985,
 'httpstcoxMWODFMtUI': 17823,
 'httptcoM4JDZMGJoW': 19343,
 'httptcon0uhAsfkBv': 21142,
 'httptcoe14EPzhotH': 20516,
 'httptco22a9D5DO6q': 17990,
 'dope': 15839,
 'show': 25674,
 'KJForDays': 6744,
 'seeing': 25499,
 'Issues': 6421,
 'httptcoTHyzOMVWU0': 19835,
 'httptco83jOO0xk29': 18386,
 'Oshawa': 8941,
 'WisdomWed': 13030,
 'BONUS': 1768,
 'Minute': 8082,
 'Daily': 3610,
 'Habits': 5646,
 'could': 15181,
 'really': 24908,
 'improve': 22201,
 'many': 23172,
 'already': 13564,
 'lifehacks': 22890,
 'httptcoTBm9FQb8cW': 19822,
 'Baker': 1847,
 'Oregon': 8915,
 'Protect': 9627,
 'Profit': 9600,
 'Next': 8567,
 'Global': 5350,
 'Financial': 4839,
 'Meltdown': 7944,
 'Wiedemer': 12980,
 'http': 17445,
 'httptcoWZTz4hgMVq': 20045,
 'moment': 23496,
 'scary': 25425,
 'guy': 17092,
 'behind': 14100,
 'screaming': 25455,
 'bloody': 14251,
 'murder': 23598,
 'silverwood': 25716,
 '\x89ã¢': 27892,
 '2010': 306,
 'Full\x89ã¢': 5085,
 'Streaming': 11355,
 'YouTube': 13231,
 'httptcovVE3UsesGf': 21731,
 'United': 12379,
 'States': 11279,
 'gtgt': 17056,
 '15': 176,
 'book': 14299,
 'httptcof6ntUc734Z': 20587,
 'esquireattire': 16214,
 'Sometimes': 11109,
 'face': 16370,
 'difficulty': 15679,
 'wrong': 27648,
 'right': 25184,
 'Joel': 6626,
 'Osteen': 8945,
 'thing': 26624,
 'stand': 26091,
 'dream': 15879,
 'belief': 14104,
 'possible': 24487,
 'Brown': 2366,
 'marysville': 23212,
 'ca': 14518,
 'Praise': 9518,
 'God': 5372,
 'ministry': 23415,
 'wdyouth': 27388,
 'biblestudy': 14150,
 'httpstcoUjK0e5GBcC': 17633,
 'Remembering': 10033,
 'die': 15667,
 'avoid': 13894,
 'trap': 26863,
 'thinking': 26626,
 'lose': 23031,
 'Jobs': 6621,
 'Hermosa': 5840,
 'Beach': 1942,
 'Tried': 12137,
 'orange': 24024,
 'never': 23726,
 'OnFireAnders': 8861,
 'bb': 14035,
 'httpstcojV8ppKhJY7': 17733,
 'kick': 22633,
 'great': 17005,
 'thank': 26560,
 'everyone': 16252,
 'making': 23135,
 'People': 9272,
 'say': 25407,
 'cannot': 14581,
 'done': 15829,
 'interrupt': 22359,
 'George': 5289,
 'Bernard': 2029,
 'Shaw': 10863,
 'first': 16555,
 'oyster': 24114,
 'shell': 25624,
 'Andrew': 1361,
 'Carnegie': 2798,
 'Anyone': 1420,
 'need': 23703,
 'PU': 9093,
 'play': 24395,
 'Hybrid': 6083,
 'Slayer': 11025,
 'ps4': 24687,
 'EU': 4174,
 'HMU': 5603,
 'Cod8sandscrims': 3129,
 'EmpirikGaming': 4353,
 'CoDAWScrims': 3105,
 '4TPKOTC': 584,
 '4TPFA': 583,
 'afterShockOrg': 13456,
 'airplane20accident': 13501,
 '19600858': 259,
 '99047821': 862,
 'Experts': 4525,
 'France': 5001,
 'begin': 14094,
 'examining': 16271,
 'airplane': 13500,
 'debris': 15458,
 'found': 16700,
 'Reunion': 10105,
 'Island': 6406,
 'French': 5041,
 'air': 13492,
 'expert': 16322,
 'httptcoYVVPznZmXg': 20150,
 'news': 23738,
 'Pennsylvania': 9269,
 'Strict': 11364,
 'liability': 22877,
 'context': 15113,
 'Pilot': 9362,
 'error': 16205,
 'common': 15017,
 'component': 15043,
 'aviation': 13892,
 'cr': 15217,
 'httptco6CZ3bOhRd4': 18258,
 'Salt': 10596,
 'Utah': 12431,
 'crobscarla': 15273,
 'lifetime': 22898,
 'odds': 23915,
 'dying': 15970,
 '1': 61,
 '8015': 773,
 'Palo': 9142,
 'Alto': 1305,
 'Wedn': 12894,
 'httptcobKpFpOGySI': 20324,
 'AlexAllTimeLow': 1258,
 'awwww': 13912,
 'theyre': 26614,
 'gonna': 16950,
 'cuties': 15343,
 'good': 16951,
 'job': 22505,
 'Spain': 11169,
 'OpaLocka': 8887,
 'FL': 4631,
 'family': 16410,
 'member': 23302,
 'osama': 24046,
 'bin': 14176,
 'laden': 22737,
 'ironic': 22409,
 'mhmmm': 23351,
 'gov': 16971,
 'suspect': 26368,
 'Jaipur': 6511,
 'Goes': 5378,
 'Airplane': 1215,
 'Engine': 4369,
 'httptcoTYJxrFd3St': 19851,
 'via': 27216,
 'Hyderabad': 6084,
 'Telangana': 11788,
 'INDIA': 6152,
 'Horrible': 5994,
 'Died': 3861,
 'Wings': 13019,
 '29072015': 399,
 ...}

In [17]:
finaldata=CV.transform(finaldata)

In [18]:
finaldata.nnz

88033

In [19]:
Tfidf=TfidfTransformer()
Tfidf.fit(finaldata)
Tfidf_val=Tfidf.transform(finaldata)

In [20]:
testdata=CV.transform(testdata)
testdata=Tfidf.transform(testdata)

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB

# Naive Bayes & Random Forest

In [22]:
sentiment=MultinomialNB()
sentiment.fit(Tfidf_val,finaltarget)
result1=sentiment.predict(testdata)

RFC=RandomForestClassifier()
RFC.fit(Tfidf_val,finaltarget)
result2=RFC.predict(testdata)

In [23]:
rslt=pd.DataFrame(index=test.index)
rslt['Naive Bayes']=result1
rslt['Random Forest']=result2

In [24]:
rslt['Naive Bayes'].value_counts()

0    2215
1    1048
Name: Naive Bayes, dtype: int64

In [25]:
rslt['Random Forest'].value_counts()

0    2138
1    1125
Name: Random Forest, dtype: int64

# Support Vector Machine

In [26]:
from sklearn.svm import SVC

In [27]:
svc=SVC()

In [28]:
svc.fit(Tfidf_val,finaltarget)
svm=svc.predict(testdata)

In [29]:
rslt['svm']=svm

In [30]:
rslt['svm'].value_counts()

0    2163
1    1100
Name: svm, dtype: int64

### With Grid Search

In [31]:
from sklearn.model_selection import GridSearchCV
grid={'C':[0.01,0.1,1,10,100],'gamma':[0.001,.01,0.1,1,10]}

In [32]:
g=GridSearchCV(SVC(),grid,verbose=2)

In [33]:
g.fit(Tfidf_val,finaltarget)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.01, gamma=0.001 .............................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] .............................. C=0.01, gamma=0.001, total=   6.2s
[CV] C=0.01, gamma=0.001 .............................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.2s remaining:    0.0s

[CV] .............................. C=0.01, gamma=0.001, total=   6.2s
[CV] C=0.01, gamma=0.001 .............................................
[CV] .............................. C=0.01, gamma=0.001, total=   6.2s
[CV] C=0.01, gamma=0.001 .............................................
[CV] .............................. C=0.01, gamma=0.001, total=   6.2s
[CV] C=0.01, gamma=0.001 .............................................
[CV] .............................. C=0.01, gamma=0.001, total=   6.3s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] ............................... C=0.01, gamma=0.01, total=   6.2s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] ............................... C=0.01, gamma=0.01, total=   6.3s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] ............................... C=0.01, gamma=0.01, total=   6.2s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] ............................... C=0.01, gamma=0.01, total=   6.2s
[CV] C=0.01, gamma=0.01 ..............................................
[CV] ............................... C=0.01, gamma=0.01, total=   6.3s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ................................ C=0.01, gamma=0.1, total=   6.5s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ................................ C=0.01, gamma=0.1, total=   6.4s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ................................ C=0.01, gamma=0.1, total=   6.4s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ................................ C=0.01, gamma=0.1, total=   6.5s
[CV] C=0.01, gamma=0.1 ...............................................
[CV] ................................ C=0.01, gamma=0.1, total=   6.3s
[CV] C=0.01, gamma=1 .................................................
[CV] .................................. C=0.01, gamma=1, total=   6.9s
[CV] C=0.01, gamma=1 .................................................
[CV] .................................. C=0.01, gamma=1, total=   6.9s
[CV] C=0.01, gamma=1 .................................................
[CV] .................................. C=0.01, gamma=1, total=   6.9s
[CV] C=0.01, gamma=1 .................................................
[CV] .................................. C=0.01, gamma=1, total=   6.7s
[CV] C=0.01, gamma=1 .................................................
[CV] .................................. C=0.01, gamma=1, total=   6.8s
[CV] C=0.01, gamma=10 ................................................
[CV] ................................. C=0.01, gamma=10, total=   6.8s
[CV] C=0.01, gamma=10 ................................................
[CV] ................................. C=0.01, gamma=10, total=   6.8s
[CV] C=0.01, gamma=10 ................................................
[CV] ................................. C=0.01, gamma=10, total=   6.8s
[CV] C=0.01, gamma=10 ................................................
[CV] ................................. C=0.01, gamma=10, total=   6.8s
[CV] C=0.01, gamma=10 ................................................
[CV] ................................. C=0.01, gamma=10, total=   6.9s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ............................... C=0.1, gamma=0.001, total=   6.2s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ............................... C=0.1, gamma=0.001, total=   6.2s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ............................... C=0.1, gamma=0.001, total=   6.3s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ............................... C=0.1, gamma=0.001, total=   6.3s
[CV] C=0.1, gamma=0.001 ..............................................
[CV] ............................... C=0.1, gamma=0.001, total=   6.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................................ C=0.1, gamma=0.01, total=   6.3s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................................ C=0.1, gamma=0.01, total=   6.3s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................................ C=0.1, gamma=0.01, total=   6.2s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................................ C=0.1, gamma=0.01, total=   6.3s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ................................ C=0.1, gamma=0.01, total=   6.4s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   6.6s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   6.7s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   6.6s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   6.6s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   6.6s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   7.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   7.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   7.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   7.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   7.0s
[CV] C=0.1, gamma=10 .................................................
[CV] .................................. C=0.1, gamma=10, total=   7.0s
[CV] C=0.1, gamma=10 .................................................
[CV] .................................. C=0.1, gamma=10, total=   7.0s
[CV] C=0.1, gamma=10 .................................................
[CV] .................................. C=0.1, gamma=10, total=   6.9s
[CV] C=0.1, gamma=10 .................................................
[CV] .................................. C=0.1, gamma=10, total=   6.9s
[CV] C=0.1, gamma=10 .................................................
[CV] .................................. C=0.1, gamma=10, total=   6.9s
[CV] C=1, gamma=0.001 ................................................
[CV] ................................. C=1, gamma=0.001, total=   6.3s
[CV] C=1, gamma=0.001 ................................................
[CV] ................................. C=1, gamma=0.001, total=   6.3s
[CV] C=1, gamma=0.001 ................................................
[CV] ................................. C=1, gamma=0.001, total=   6.4s
[CV] C=1, gamma=0.001 ................................................
[CV] ................................. C=1, gamma=0.001, total=   6.2s
[CV] C=1, gamma=0.001 ................................................
[CV] ................................. C=1, gamma=0.001, total=   6.2s
[CV] C=1, gamma=0.01 .................................................
[CV] .................................. C=1, gamma=0.01, total=   6.5s
[CV] C=1, gamma=0.01 .................................................
[CV] .................................. C=1, gamma=0.01, total=   6.6s
[CV] C=1, gamma=0.01 .................................................
[CV] .................................. C=1, gamma=0.01, total=   6.6s
[CV] C=1, gamma=0.01 .................................................
[CV] .................................. C=1, gamma=0.01, total=   6.5s
[CV] C=1, gamma=0.01 .................................................
[CV] .................................. C=1, gamma=0.01, total=   6.5s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   6.3s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   6.3s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   6.4s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   6.4s
[CV] C=1, gamma=0.1 ..................................................
[CV] ................................... C=1, gamma=0.1, total=   6.4s
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   6.8s
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   7.0s
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   6.9s
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   6.8s
[CV] C=1, gamma=1 ....................................................
[CV] ..................................... C=1, gamma=1, total=   6.8s
[CV] C=1, gamma=10 ...................................................
[CV] .................................... C=1, gamma=10, total=   7.3s
[CV] C=1, gamma=10 ...................................................
[CV] .................................... C=1, gamma=10, total=   7.4s
[CV] C=1, gamma=10 ...................................................
[CV] .................................... C=1, gamma=10, total=   7.3s
[CV] C=1, gamma=10 ...................................................
[CV] .................................... C=1, gamma=10, total=   7.2s
[CV] C=1, gamma=10 ...................................................
[CV] .................................... C=1, gamma=10, total=   7.3s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................................ C=10, gamma=0.001, total=   6.7s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................................ C=10, gamma=0.001, total=   6.4s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................................ C=10, gamma=0.001, total=   6.4s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................................ C=10, gamma=0.001, total=   6.5s
[CV] C=10, gamma=0.001 ...............................................
[CV] ................................ C=10, gamma=0.001, total=   6.5s
[CV] C=10, gamma=0.01 ................................................
[CV] ................................. C=10, gamma=0.01, total=   6.2s
[CV] C=10, gamma=0.01 ................................................
[CV] ................................. C=10, gamma=0.01, total=   6.2s
[CV] C=10, gamma=0.01 ................................................
[CV] ................................. C=10, gamma=0.01, total=   6.3s
[CV] C=10, gamma=0.01 ................................................
[CV] ................................. C=10, gamma=0.01, total=   6.2s
[CV] C=10, gamma=0.01 ................................................
[CV] ................................. C=10, gamma=0.01, total=   6.3s
[CV] C=10, gamma=0.1 .................................................
[CV] .................................. C=10, gamma=0.1, total=   6.6s
[CV] C=10, gamma=0.1 .................................................
[CV] .................................. C=10, gamma=0.1, total=   6.7s
[CV] C=10, gamma=0.1 .................................................
[CV] .................................. C=10, gamma=0.1, total=   6.6s
[CV] C=10, gamma=0.1 .................................................
[CV] .................................. C=10, gamma=0.1, total=   6.5s
[CV] C=10, gamma=0.1 .................................................
[CV] .................................. C=10, gamma=0.1, total=   6.8s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   7.1s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   7.1s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   7.1s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   7.0s
[CV] C=10, gamma=1 ...................................................
[CV] .................................... C=10, gamma=1, total=   7.2s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   7.3s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   7.2s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   7.3s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   7.3s
[CV] C=10, gamma=10 ..................................................
[CV] ................................... C=10, gamma=10, total=   7.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] ............................... C=100, gamma=0.001, total=   6.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] ............................... C=100, gamma=0.001, total=   6.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] ............................... C=100, gamma=0.001, total=   6.3s
[CV] C=100, gamma=0.001 ..............................................
[CV] ............................... C=100, gamma=0.001, total=   6.3s
[CV] C=100, gamma=0.001 ..............................................
[CV] ............................... C=100, gamma=0.001, total=   6.4s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   6.6s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   6.5s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   7.3s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   6.5s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   6.6s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   6.8s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   6.8s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   6.9s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   6.9s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   6.9s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   7.1s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   7.0s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   7.1s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   7.1s
[CV] C=100, gamma=1 ..................................................
[CV] ................................... C=100, gamma=1, total=   7.1s
[CV] C=100, gamma=10 .................................................
[CV] .................................. C=100, gamma=10, total=   7.4s
[CV] C=100, gamma=10 .................................................
[CV] .................................. C=100, gamma=10, total=   7.4s
[CV] C=100, gamma=10 .................................................
[CV] .................................. C=100, gamma=10, total=   7.3s
[CV] C=100, gamma=10 .................................................
[CV] .................................. C=100, gamma=10, total=   7.2s
[CV] C=100, gamma=10 .................................................
[CV] .................................. C=100, gamma=10, total=   7.3s

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed: 13.9min finished

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'gamma': [0.001, 0.01, 0.1, 1, 10]},
             verbose=2)

In [34]:
g.best_estimator_

SVC(C=10, gamma=1)

In [35]:
grid=g.predict(testdata)

In [36]:
rslt['grid']=grid

In [37]:
rslt['grid'].value_counts()

0    2061
1    1202
Name: grid, dtype: int64

In [38]:
rslt.head()

    Naive Bayes  Random Forest  svm  grid
id
0             1              1    1     1
2             0              1    1     1
3             1              1    1     1
9             1              1    1     1
11            1              1    1     1

In [39]:
#rslt.to_csv('prediction.csv')