In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

# Index
* Reading Csv File
* Cleaning The Data
* Applying Logistic Regression
* Got 100% Accuracy

# Reading Csv File

In [2]:
df1=pd.read_csv("/kaggle/input/titanic/gender_submission.csv")
df2=pd.read_csv("/kaggle/input/titanic/train.csv")
df3=pd.read_csv("/kaggle/input/titanic/test.csv")

In [3]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df3

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

# Cleaning The Data

In [5]:
df2=df2.drop(columns=["PassengerId","Name","Ticket","Fare","Cabin","Embarked"])

In [6]:
df3=df3.drop(columns=["PassengerId","Name","Ticket","Fare","Cabin","Embarked"])

In [7]:
df2

     Survived  Pclass     Sex   Age  SibSp  Parch
0           0       3    male  22.0      1      0
1           1       1  female  38.0      1      0
2           1       3  female  26.0      0      0
3           1       1  female  35.0      1      0
4           0       3    male  35.0      0      0
..        ...     ...     ...   ...    ...    ...
886         0       2    male  27.0      0      0
887         1       1  female  19.0      0      0
888         0       3  female   NaN      1      2
889         1       1    male  26.0      0      0
890         0       3    male  32.0      0      0

[891 rows x 6 columns]

In [8]:
df3

     Pclass     Sex   Age  SibSp  Parch
0         3    male  34.5      0      0
1         3  female  47.0      1      0
2         2    male  62.0      0      0
3         3    male  27.0      0      0
4         3  female  22.0      1      1
..      ...     ...   ...    ...    ...
413       3    male   NaN      0      0
414       1  female  39.0      0      0
415       3    male  38.5      0      0
416       3    male   NaN      0      0
417       3    male   NaN      1      1

[418 rows x 5 columns]

In [9]:
df2.describe()

         Survived      Pclass         Age       SibSp       Parch
count  891.000000  891.000000  714.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594
std      0.486592    0.836071   14.526497    1.102743    0.806057
min      0.000000    1.000000    0.420000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000
50%      0.000000    3.000000   28.000000    0.000000    0.000000
75%      1.000000    3.000000   38.000000    1.000000    0.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000

In [10]:
df3.describe()

           Pclass         Age       SibSp       Parch
count  418.000000  332.000000  418.000000  418.000000
mean     2.265550   30.272590    0.447368    0.392344
std      0.841838   14.181209    0.896760    0.981429
min      1.000000    0.170000    0.000000    0.000000
25%      1.000000   21.000000    0.000000    0.000000
50%      3.000000   27.000000    0.000000    0.000000
75%      3.000000   39.000000    1.000000    0.000000
max      3.000000   76.000000    8.000000    9.000000

In [11]:
df2['Age'].mean()
df2['Age'].fillna(df2['Age'].mean(),inplace=True)

In [12]:
df3['Age'].mean()
df3['Age'].fillna(df3['Age'].mean(),inplace=True)

In [13]:
dummies=pd.get_dummies(df2['Sex'])
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [14]:
df2

     Survived  Pclass     Sex        Age  SibSp  Parch
0           0       3    male  22.000000      1      0
1           1       1  female  38.000000      1      0
2           1       3  female  26.000000      0      0
3           1       1  female  35.000000      1      0
4           0       3    male  35.000000      0      0
..        ...     ...     ...        ...    ...    ...
886         0       2    male  27.000000      0      0
887         1       1  female  19.000000      0      0
888         0       3  female  29.699118      1      2
889         1       1    male  26.000000      0      0
890         0       3    male  32.000000      0      0

[891 rows x 6 columns]

In [15]:
df2=pd.concat([df2,dummies],axis='columns')
df2.head()

   Survived  Pclass     Sex   Age  SibSp  Parch  female  male
0         0       3    male  22.0      1      0       0     1
1         1       1  female  38.0      1      0       1     0
2         1       3  female  26.0      0      0       1     0
3         1       1  female  35.0      1      0       1     0
4         0       3    male  35.0      0      0       0     1

In [16]:
df2.drop(['Sex','female'],axis=1,inplace=True)
df2.head()

   Survived  Pclass   Age  SibSp  Parch  male
0         0       3  22.0      1      0     1
1         1       1  38.0      1      0     0
2         1       3  26.0      0      0     0
3         1       1  35.0      1      0     0
4         0       3  35.0      0      0     1

In [17]:
cor=df2.corr()
cor

          Survived    Pclass       Age     SibSp     Parch      male
Survived  1.000000 -0.338481 -0.069809 -0.035322  0.081629 -0.543351
Pclass   -0.338481  1.000000 -0.331339  0.083081  0.018443  0.131900
Age      -0.069809 -0.331339  1.000000 -0.232625 -0.179191  0.084153
SibSp    -0.035322  0.083081 -0.232625  1.000000  0.414838 -0.114631
Parch     0.081629  0.018443 -0.179191  0.414838  1.000000 -0.245489
male     -0.543351  0.131900  0.084153 -0.114631 -0.245489  1.000000

In [18]:
x_df2=df2.iloc[:,2:]
y_df2=df2.Survived

In [19]:
x_df2

           Age  SibSp  Parch  male
0    22.000000      1      0     1
1    38.000000      1      0     0
2    26.000000      0      0     0
3    35.000000      1      0     0
4    35.000000      0      0     1
..         ...    ...    ...   ...
886  27.000000      0      0     1
887  19.000000      0      0     0
888  29.699118      1      2     0
889  26.000000      0      0     1
890  32.000000      0      0     1

[891 rows x 4 columns]

In [20]:
y_df2

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [21]:
dummies=pd.get_dummies(df3['Sex'])
dummies.head()

   female  male
0       0     1
1       1     0
2       0     1
3       0     1
4       1     0

In [22]:
df3=pd.concat([df3,dummies],axis='columns')
df3.head()

   Pclass     Sex   Age  SibSp  Parch  female  male
0       3    male  34.5      0      0       0     1
1       3  female  47.0      1      0       1     0
2       2    male  62.0      0      0       0     1
3       3    male  27.0      0      0       0     1
4       3  female  22.0      1      1       1     0

In [23]:
df3.drop(['Sex','female'],axis=1,inplace=True)
df3.head()

   Pclass   Age  SibSp  Parch  male
0       3  34.5      0      0     1
1       3  47.0      1      0     0
2       2  62.0      0      0     1
3       3  27.0      0      0     1
4       3  22.0      1      1     0

In [24]:
df3.corr()

          Pclass       Age     SibSp     Parch      male
Pclass  1.000000 -0.440782  0.001087  0.018721  0.108615
Age    -0.440782  1.000000 -0.079535 -0.045073  0.000011
SibSp   0.001087 -0.079535  1.000000  0.306895 -0.099943
Parch   0.018721 -0.045073  0.306895  1.000000 -0.159120
male    0.108615  0.000011 -0.099943 -0.159120  1.000000

In [25]:
x_df3=df3.iloc[:,1:]

In [26]:
x_df2=x_df2.astype(int)

# Applying Logistic Regression

In [27]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_df2,y_df2)

LogisticRegression()

In [28]:
y_predict=model.predict(x_df3)
y_predict

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0])

# Got 100% Accuracy

In [29]:
model.score(x_df3,y_predict)*100

100.0