In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('../input/digit-recognizer/train.csv')
test = pd.read_csv('../input/digit-recognizer/test.csv')

In [3]:
target = train['label']
train = train.drop('label', axis = 1)

In [4]:
train.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
print(train.shape)

(42000, 784)

In [7]:
train_reshape = train.values.reshape(42000,28,28,1)

In [8]:
train_reshape = train_reshape/255

In [9]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten

Using TensorFlow backend.

In [10]:
# Initialising CNN
classifier = Sequential()

#Adding first conv layer
classifier.add(Convolution2D(32, 3, 3, input_shape = (28,28, 1), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2,2)))

#Adiing second conv layer
classifier.add(Convolution2D(32,3,3, activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2,2)))

classifier.add(Flatten())

#Full connection
classifier.add(Dense(output_dim = 128, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 10, init = 'uniform', activation = 'sigmoid'))

# Compiling ANN
classifier.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(28, 28, 1..., activation="relu")`
  """
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), activation="relu")`
  if __name__ == '__main__':
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:15: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128, kernel_initializer="uniform")`
  from ipykernel import kernelapp as app
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=10, kernel_initializer="uniform")`
  app.launch_new_instance()

In [11]:
# training ANN on train dataset
classifier.fit(train_reshape, target, batch_size = 20 , epochs = 15)

Epoch 1/15
42000/42000 [==============================] - 25s 600us/step - loss: 0.2033 - accuracy: 0.9360
Epoch 2/15
42000/42000 [==============================] - 26s 609us/step - loss: 0.0648 - accuracy: 0.9799
Epoch 3/15
42000/42000 [==============================] - 26s 623us/step - loss: 0.0433 - accuracy: 0.9865
Epoch 4/15
42000/42000 [==============================] - 25s 590us/step - loss: 0.0326 - accuracy: 0.9897
Epoch 5/15
42000/42000 [==============================] - 25s 595us/step - loss: 0.0245 - accuracy: 0.9920
Epoch 6/15
42000/42000 [==============================] - 26s 613us/step - loss: 0.0187 - accuracy: 0.9939
Epoch 7/15
42000/42000 [==============================] - 25s 603us/step - loss: 0.0154 - accuracy: 0.9947
Epoch 8/15
42000/42000 [==============================] - 25s 590us/step - loss: 0.0137 - accuracy: 0.9957
Epoch 9/15
42000/42000 [==============================] - 25s 599us/step - loss: 0.0104 - accuracy: 0.9965
Epoch 10/15
42000/42000 [==============================] - 25s 592us/step - loss: 0.0112 - accuracy: 0.9962
Epoch 11/15
42000/42000 [==============================] - 25s 592us/step - loss: 0.0073 - accuracy: 0.9976
Epoch 12/15
42000/42000 [==============================] - 25s 602us/step - loss: 0.0078 - accuracy: 0.9973
Epoch 13/15
21080/42000 [==============>...............] - ETA: 12s - loss: 0.0056 - accuracy: 0.9983

In [12]:
print(test.shape)

(28000, 784)

In [13]:
test_reshape = test.values.reshape(28000, 28,28,1)

In [14]:
test_pred = classifier.predict(test_reshape)

In [15]:
pred_int = []
for i in range(test_pred.shape[0]):
    pred_ratios = test_pred[i]
    for j in range(10):
        if(pred_ratios[j] == max(pred_ratios)):
            number = int(j)
    pred_int = np.append(pred_int, number)
pred_int = pred_int.astype(int)

In [16]:
submission = pd.read_csv('../input/digit-recognizer/sample_submission.csv')
submission['Label'] = pred_int
submission

       ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [17]:
submission.to_csv('submission.csv', index = False)