# Importing Required Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import plotly.figure_factory as ff
from sklearn.ensemble import GradientBoostingRegressor, AdaBoostRegressor, RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
import xgboost as xgb

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
raw_data = pd.read_csv('../input/house-prices-advanced-regression-techniques/train.csv')
raw_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [4]:
numerical_data = raw_data.select_dtypes(include=['int64', 'float64'])
categorical_data = raw_data.select_dtypes(include=['object'])
numerical_data.drop(['Id'], axis=1, inplace=True)
numerical_data.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,150,856,856,854,0,1710,1,0,2,1,3,1,8,0,2003.0,2,548,0,61,0,0,0,0,0,2,2008,208500
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,284,1262,1262,0,0,1262,0,1,2,0,3,1,6,1,1976.0,2,460,298,0,0,0,0,0,0,5,2007,181500
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,434,920,920,866,0,1786,1,0,2,1,3,1,6,1,2001.0,2,608,0,42,0,0,0,0,0,9,2008,223500
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,540,756,961,756,0,1717,1,0,1,0,3,1,7,1,1998.0,3,642,0,35,272,0,0,0,0,2,2006,140000
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,490,1145,1145,1053,0,2198,1,0,2,1,4,1,9,1,2000.0,3,836,192,84,0,0,0,0,0,12,2008,250000

In [5]:
numerical_data = numerical_data.astype('float64')
y_train = raw_data['SalePrice']

In [6]:
numerical_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 37 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   float64
 1   LotFrontage    1201 non-null   float64
 2   LotArea        1460 non-null   float64
 3   OverallQual    1460 non-null   float64
 4   OverallCond    1460 non-null   float64
 5   YearBuilt      1460 non-null   float64
 6   YearRemodAdd   1460 non-null   float64
 7   MasVnrArea     1452 non-null   float64
 8   BsmtFinSF1     1460 non-null   float64
 9   BsmtFinSF2     1460 non-null   float64
 10  BsmtUnfSF      1460 non-null   float64
 11  TotalBsmtSF    1460 non-null   float64
 12  1stFlrSF       1460 non-null   float64
 13  2ndFlrSF       1460 non-null   float64
 14  LowQualFinSF   1460 non-null   float64
 15  GrLivArea      1460 non-null   float64
 16  BsmtFullBath   1460 non-null   float64
 17  BsmtHalfBath   1460 non-null   float64
 18  FullBath       1460 non-null   float64
 19  HalfBath       1460 non-null   float64
 20  BedroomAbvGr   1460 non-null   float64
 21  KitchenAbvGr   1460 non-null   float64
 22  TotRmsAbvGrd   1460 non-null   float64
 23  Fireplaces     1460 non-null   float64
 24  GarageYrBlt    1379 non-null   float64
 25  GarageCars     1460 non-null   float64
 26  GarageArea     1460 non-null   float64
 27  WoodDeckSF     1460 non-null   float64
 28  OpenPorchSF    1460 non-null   float64
 29  EnclosedPorch  1460 non-null   float64
 30  3SsnPorch      1460 non-null   float64
 31  ScreenPorch    1460 non-null   float64
 32  PoolArea       1460 non-null   float64
 33  MiscVal        1460 non-null   float64
 34  MoSold         1460 non-null   float64
 35  YrSold         1460 non-null   float64
 36  SalePrice      1460 non-null   float64
dtypes: float64(37)
memory usage: 422.2 KB

In [7]:
numerical_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
MSSubClass,1460.0,56.897260,42.300571,20.0,20.00,50.0,70.00,190.0
LotFrontage,1201.0,70.049958,24.284752,21.0,59.00,69.0,80.00,313.0
LotArea,1460.0,10516.828082,9981.264932,1300.0,7553.50,9478.5,11601.50,215245.0
OverallQual,1460.0,6.099315,1.382997,1.0,5.00,6.0,7.00,10.0
OverallCond,1460.0,5.575342,1.112799,1.0,5.00,5.0,6.00,9.0
YearBuilt,1460.0,1971.267808,30.202904,1872.0,1954.00,1973.0,2000.00,2010.0
YearRemodAdd,1460.0,1984.865753,20.645407,1950.0,1967.00,1994.0,2004.00,2010.0
MasVnrArea,1452.0,103.685262,181.066207,0.0,0.00,0.0,166.00,1600.0
BsmtFinSF1,1460.0,443.639726,456.098091,0.0,0.00,383.5,712.25,5644.0
BsmtFinSF2,1460.0,46.549315,161.319273,0.0,0.00,0.0,0.00,1474.0
BsmtUnfSF,1460.0,567.240411,441.866955,0.0,223.00,477.5,808.00,2336.0
TotalBsmtSF,1460.0,1057.429452,438.705324,0.0,795.75,991.5,1298.25,6110.0
1stFlrSF,1460.0,1162.626712,386.587738,334.0,882.00,1087.0,1391.25,4692.0
2ndFlrSF,1460.0,346.992466,436.528436,0.0,0.00,0.0,728.00,2065.0
LowQualFinSF,1460.0,5.844521,48.623081,0.0,0.00,0.0,0.00,572.0
GrLivArea,1460.0,1515.463699,525.480383,334.0,1129.50,1464.0,1776.75,5642.0
BsmtFullBath,1460.0,0.425342,0.518911,0.0,0.00,0.0,1.00,3.0
BsmtHalfBath,1460.0,0.057534,0.238753,0.0,0.00,0.0,0.00,2.0
FullBath,1460.0,1.565068,0.550916,0.0,1.00,2.0,2.00,3.0
HalfBath,1460.0,0.382877,0.502885,0.0,0.00,0.0,1.00,2.0
BedroomAbvGr,1460.0,2.866438,0.815778,0.0,2.00,3.0,3.00,8.0
KitchenAbvGr,1460.0,1.046575,0.220338,0.0,1.00,1.0,1.00,3.0
TotRmsAbvGrd,1460.0,6.517808,1.625393,2.0,5.00,6.0,7.00,14.0
Fireplaces,1460.0,0.613014,0.644666,0.0,0.00,1.0,1.00,3.0
GarageYrBlt,1379.0,1978.506164,24.689725,1900.0,1961.00,1980.0,2002.00,2010.0
GarageCars,1460.0,1.767123,0.747315,0.0,1.00,2.0,2.00,4.0
GarageArea,1460.0,472.980137,213.804841,0.0,334.50,480.0,576.00,1418.0
WoodDeckSF,1460.0,94.244521,125.338794,0.0,0.00,0.0,168.00,857.0
OpenPorchSF,1460.0,46.660274,66.256028,0.0,0.00,25.0,68.00,547.0
EnclosedPorch,1460.0,21.954110,61.119149,0.0,0.00,0.0,0.00,552.0
3SsnPorch,1460.0,3.409589,29.317331,0.0,0.00,0.0,0.00,508.0
ScreenPorch,1460.0,15.060959,55.757415,0.0,0.00,0.0,0.00,480.0
PoolArea,1460.0,2.758904,40.177307,0.0,0.00,0.0,0.00,738.0
MiscVal,1460.0,43.489041,496.123024,0.0,0.00,0.0,0.00,15500.0
MoSold,1460.0,6.321918,2.703626,1.0,5.00,6.0,8.00,12.0
YrSold,1460.0,2007.815753,1.328095,2006.0,2007.00,2008.0,2009.00,2010.0
SalePrice,1460.0,180921.195890,79442.502883,34900.0,129975.00,163000.0,214000.00,755000.0

In [8]:
numerical_data.isnull().sum()

MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [9]:
corr = numerical_data.corr().round(2)
x = corr.index.to_list()
y = corr.columns.to_list()
c = []
for i in corr:
    c.append(list(corr[i].values))
hightlight_cols = list((corr['SalePrice'] > 0.2).index)[:-1]
numerical_data.drop(['SalePrice'], axis=1, inplace=True)

In [10]:
_template = dict(layout=go.Layout(font=dict(family='Franklin Gothic',size=14)))

The heatmap shows the Correlation between Numerical Features and our Target Sale Price.

In [11]:
fig = ff.create_annotated_heatmap(z=c, x=x, y=y, hovertemplate='Correlation between %{x} and %{y} = %{z} ', name='')
fig.update_layout(template='plotly_dark',  paper_bgcolor='#2B2E4A', plot_bgcolor='#53354A', height=1000, margin=dict(l=120, t=150), yaxis=dict(showgrid=False))
fig.show()

In [12]:
numerical_data.tail(10)

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
1450,90.0,60.0,9000.0,5.0,5.0,1974.0,1974.0,0.0,0.0,0.0,896.0,896.0,896.0,896.0,0.0,1792.0,0.0,0.0,2.0,2.0,4.0,2.0,8.0,0.0,NaN,0.0,0.0,32.0,45.0,0.0,0.0,0.0,0.0,0.0,9.0,2009.0
1451,20.0,78.0,9262.0,8.0,5.0,2008.0,2009.0,194.0,0.0,0.0,1573.0,1573.0,1578.0,0.0,0.0,1578.0,0.0,0.0,2.0,0.0,3.0,1.0,7.0,1.0,2008.0,3.0,840.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,5.0,2009.0
1452,180.0,35.0,3675.0,5.0,5.0,2005.0,2005.0,80.0,547.0,0.0,0.0,547.0,1072.0,0.0,0.0,1072.0,1.0,0.0,1.0,0.0,2.0,1.0,5.0,0.0,2005.0,2.0,525.0,0.0,28.0,0.0,0.0,0.0,0.0,0.0,5.0,2006.0
1453,20.0,90.0,17217.0,5.0,5.0,2006.0,2006.0,0.0,0.0,0.0,1140.0,1140.0,1140.0,0.0,0.0,1140.0,0.0,0.0,1.0,0.0,3.0,1.0,6.0,0.0,NaN,0.0,0.0,36.0,56.0,0.0,0.0,0.0,0.0,0.0,7.0,2006.0
1454,20.0,62.0,7500.0,7.0,5.0,2004.0,2005.0,0.0,410.0,0.0,811.0,1221.0,1221.0,0.0,0.0,1221.0,1.0,0.0,2.0,0.0,2.0,1.0,6.0,0.0,2004.0,2.0,400.0,0.0,113.0,0.0,0.0,0.0,0.0,0.0,10.0,2009.0
1455,60.0,62.0,7917.0,6.0,5.0,1999.0,2000.0,0.0,0.0,0.0,953.0,953.0,953.0,694.0,0.0,1647.0,0.0,0.0,2.0,1.0,3.0,1.0,7.0,1.0,1999.0,2.0,460.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,8.0,2007.0
1456,20.0,85.0,13175.0,6.0,6.0,1978.0,1988.0,119.0,790.0,163.0,589.0,1542.0,2073.0,0.0,0.0,2073.0,1.0,0.0,2.0,0.0,3.0,1.0,7.0,2.0,1978.0,2.0,500.0,349.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2010.0
1457,70.0,66.0,9042.0,7.0,9.0,1941.0,2006.0,0.0,275.0,0.0,877.0,1152.0,1188.0,1152.0,0.0,2340.0,0.0,0.0,2.0,0.0,4.0,1.0,9.0,2.0,1941.0,1.0,252.0,0.0,60.0,0.0,0.0,0.0,0.0,2500.0,5.0,2010.0
1458,20.0,68.0,9717.0,5.0,6.0,1950.0,1996.0,0.0,49.0,1029.0,0.0,1078.0,1078.0,0.0,0.0,1078.0,1.0,0.0,1.0,0.0,2.0,1.0,5.0,0.0,1950.0,1.0,240.0,366.0,0.0,112.0,0.0,0.0,0.0,0.0,4.0,2010.0
1459,20.0,75.0,9937.0,5.0,6.0,1965.0,1965.0,0.0,830.0,290.0,136.0,1256.0,1256.0,0.0,0.0,1256.0,1.0,0.0,1.0,1.0,3.0,1.0,6.0,0.0,1965.0,1.0,276.0,736.0,68.0,0.0,0.0,0.0,0.0,0.0,6.0,2008.0

# Exploratory Data Analysis

In [13]:
fig = make_subplots(rows=len(hightlight_cols)//3, cols=3)

for i, col in enumerate(hightlight_cols):
    _col = (i+1)%3
    _col = _col if _col != 0 else 3 
    fig.add_trace(go.Box(y=numerical_data[col], name=col, boxpoints='all'), row=i//3 + 1, col=_col )
    
fig.update_layout(template='plotly_dark', height=1800, showlegend=False, width=1500, title='Box Plot Distribution of correlated Features with Sale Price')
fig.show()

In [14]:
fig = make_subplots(rows=2, cols=3)
fig.add_trace(go.Histogram(x=numerical_data['OverallQual'], y=y_train, xbins=dict(start=-40, end=40, size=0.3), name='Overall'), row=1, col=1)
fig.add_trace(go.Scatter(x=numerical_data['GrLivArea'], y=y_train, name='GrLivArea', mode='markers', marker=dict(color='rgb(255, 25, 02)')), row=1, col=2)
fig.add_trace(go.Scatter(x=numerical_data['GarageArea'], y=y_train, name='GarageArea', mode='markers', marker=dict(color='rgb(86, 0, 222)')), row=1, col=3)
fig.add_trace(go.Scatter(x=numerical_data['GarageCars'], y=y_train, name='GarageArea', mode='markers'), row=2, col=1)
fig.add_trace(go.Scatter(x=numerical_data['FullBath'], y=y_train, name='GarageArea', mode='markers'), row=2, col=2)
fig.add_trace(go.Scatter(x=numerical_data['TotRmsAbvGrd'], y=y_train, name='GarageArea', mode='markers'), row=2, col=3)

fig.update_layout(template='plotly_dark', xaxis1_title='Overall', yaxis1_title='SalePrice', title='Max Correlated Features Distribution',
                 xaxis2_title='GrLivArea', yaxis4_title='SalePrice', xaxis3_title='GarageArea', xaxis4_title='GarageCars',
                  xaxis5_title='FullBath', xaxis6_title='TotRmsAbvGrd', showlegend=False, height=1000)
fig.show()

In [15]:
date_cols = ['YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'YrSold']
fig = go.Figure()
for col in date_cols:
    fig.add_trace(go.Scatter(x=raw_data[col], y=raw_data['SalePrice'], mode='markers', name=col))
fig.update_layout(template='plotly_dark', width=1300, title='SalePrice Distribution with Date columns', yaxis_title='SalePrice', xaxis_title='Year')
fig.show()

In [16]:
fig = make_subplots(rows=(categorical_data.shape[1]-1)//3, cols=3)
for i, col in enumerate(categorical_data.columns[:-1]):
    _col = (i+1)%3
    _col = _col if _col != 0 else 3 
    series = raw_data.groupby(col)['SalePrice'].mean()
    fig.add_trace(go.Scatter(y=series, x=series.index, name=col ), row=(i//3)+1, col=_col)
    fig.update_yaxes(title='SalePrice')
        
fig.update_layout(template='plotly_dark', height=2000, width=1400)
fig.show()

# Preprocessing Pipelines

Comparisons of Categorical data for Using OneHotEncoder or LabelEncoder.

In [17]:
categorical_data.describe()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1460,91,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1460,1452,1460,1460,1460,1423,1423,1422,1423,1422,1460,1460,1460,1459,1460,1460,770,1379,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,2,2,4,4,2,5,3,25,9,8,5,8,6,8,15,16,4,4,5,6,4,4,4,6,6,6,5,2,5,4,7,5,6,3,5,5,3,3,4,4,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,None,TA,TA,PConc,TA,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Gd,Attchd,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,1454,50,925,1311,1459,1052,1382,225,1260,1445,1220,726,1141,1434,515,504,864,906,1282,647,649,1311,953,430,1256,1428,741,1365,1334,735,1360,380,870,605,1311,1326,1340,3,157,49,1267,1198

In [18]:
test_data = pd.read_csv('../input/house-prices-advanced-regression-techniques/test.csv')
test_cat_col = list(test_data.select_dtypes(include=['object']))
test_data[test_cat_col].describe()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1455,1459,107,1459,1459,1457,1459,1459,1459,1459,1459,1459,1459,1459,1459,1458,1458,1443,1459,1459,1459,1415,1414,1415,1417,1417,1459,1459,1459,1459,1458,1457,729,1383,1381,1381,1381,1459,3,290,51,1458,1459
unique,5,2,2,4,4,1,5,3,25,9,5,5,7,6,4,13,15,4,4,5,6,4,4,4,6,6,4,5,2,4,4,7,5,6,3,4,5,3,2,4,3,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,None,TA,TA,PConc,TA,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Gd,Attchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
freq,1114,1453,70,934,1311,1457,1081,1396,218,1251,1444,1205,745,1169,1442,510,510,878,892,1256,661,634,1295,951,431,1237,1446,752,1358,1337,757,1357,364,853,625,1293,1328,1301,2,172,46,1258,1204

In [19]:
def ONEHOTCOLS(cat_df, test_df):
    one_hot_cols = []
    test_cat_col = list(test_data.select_dtypes(include=['object']))
    for idx in cat_df.describe():
        if (cat_df.describe()[idx])['unique'] == (test_df[test_cat_col].describe()[idx])['unique']:
            one_hot_cols.append(idx)
            
    return one_hot_cols

def OrdinalCols(cat_df, one_hot_cols):
    ordinal_cols = []
    for col in list(cat_df.columns):
        if col not in one_hot_cols:
            ordinal_cols.append(col)
    return ordinal_cols

In [20]:
one_hot_cols = ONEHOTCOLS(categorical_data, test_data)
ordinal_cols = OrdinalCols(categorical_data, one_hot_cols)

In [21]:
numeric_cols = list(numerical_data.columns)

In [22]:
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaling', StandardScaler())
])

one_hot_categorical_transformer = Pipeline(steps=[
     ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder())
])

ordinal_categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])

preprocessing = ColumnTransformer(transformers=[
    ('numeric', numerical_transformer, numeric_cols ),
    ('cat', one_hot_categorical_transformer, one_hot_cols ),
    ('cat2', ordinal_categorical_transformer, ordinal_cols)
])

In [23]:
train_dataset = numerical_data.join(categorical_data)

In [24]:
x_train = preprocessing.fit_transform(train_dataset)

# Boosting Model Comparisons

In [25]:
gb_model = GradientBoostingRegressor(random_state=42)
ada_model = AdaBoostRegressor(random_state=42)
rf_model = RandomForestRegressor(random_state=42)
xg_model = xgb.XGBRegressor()

models = [gb_model, ada_model, rf_model, xg_model]
model_name = ['GradientBoosting', 'AdaBoost', 'Random Forest', 'XGBoost']

In [26]:
for i, model in enumerate(models):
    score = cross_val_score(gb_model, x_train, y_train, cv=10)
    print('Accuracy of {} is {}'.format(model_name[i], score.mean()))

Accuracy of GradientBoosting is 0.88860685629414
Accuracy of AdaBoost is 0.88860685629414
Accuracy of Random Forest is 0.88860685629414
Accuracy of XGBoost is 0.88860685629414

In [27]:
gb_model.fit(x_train, y_train)

GradientBoostingRegressor(random_state=42)

# Prediction on Test Data

In [28]:
id_col = test_data['Id'].copy()
test_data.drop(['Id'], axis=1, inplace=True)
test_data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,CBlock,TA,TA,No,Rec,468.0,LwQ,144.0,270.0,882.0,GasA,TA,Y,SBrkr,896,0,0,896,0.0,0.0,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.0,Unf,1.0,730.0,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.0,TA,TA,CBlock,TA,TA,No,ALQ,923.0,Unf,0.0,406.0,1329.0,GasA,TA,Y,SBrkr,1329,0,0,1329,0.0,0.0,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.0,Unf,1.0,312.0,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,PConc,Gd,TA,No,GLQ,791.0,Unf,0.0,137.0,928.0,GasA,Gd,Y,SBrkr,928,701,0,1629,0.0,0.0,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.0,Fin,2.0,482.0,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,6,1998,1998,Gable,CompShg,VinylSd,VinylSd,BrkFace,20.0,TA,TA,PConc,TA,TA,No,GLQ,602.0,Unf,0.0,324.0,926.0,GasA,Ex,Y,SBrkr,926,678,0,1604,0.0,0.0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,1998.0,Fin,2.0,470.0,TA,TA,Y,360,36,0,0,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,Gtl,StoneBr,Norm,Norm,TwnhsE,1Story,8,5,1992,1992,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,PConc,Gd,TA,No,ALQ,263.0,Unf,0.0,1017.0,1280.0,GasA,Ex,Y,SBrkr,1280,0,0,1280,0.0,0.0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,1992.0,RFn,2.0,506.0,TA,TA,Y,0,82,0,0,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [29]:
x_test = preprocessing.fit_transform(test_data)
y_pred = gb_model.predict(x_test)
df = {'Id':id_col, 'SalePrice':y_pred}
df = pd.DataFrame(df)
df.to_csv('submission.csv', index=False)

# Thank you !
# Feel free to give Feedbacks.