# Neural Network - Titanic

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler, OneHotEncoder

# Read in the training and test sets
train_df = pd.read_csv('/kaggle/input/titanic/train.csv')
test_df = pd.read_csv('/kaggle/input/titanic/test.csv')
train_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
relevant_features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

X = train_df [relevant_features]
y = train_df["Survived"]

X.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [3]:

categorial = [col for col in X.select_dtypes(include="object")]
numerical = [col for col in X.select_dtypes(exclude ="object")]

numerical_pipeline = Pipeline( steps = [
                            ("imputer", SimpleImputer(strategy="most_frequent"))
])

categorial_pipeline = Pipeline(steps =[
                            ("Imputer", SimpleImputer(strategy = "most_frequent")),
                            ("encode", OneHotEncoder(handle_unknown ="ignore"))
])

pp = ColumnTransformer(transformers =[
                            ("num",numerical_pipeline, numerical),
                            ("cat", categorial_pipeline, categorial)
])


X = pp.fit_transform(X)
print(X.shape)

(891, 10)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

X_train.shape

(623, 10)

In [5]:
# using Subclassing API
import tensorflow as tf
from tensorflow import keras

class Basic_NN_Model(keras.models.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
        # define the NN architecture#
        self.hidden1 = keras.layers.Dense(50, activation='relu', input_shape=(10,))
        self.hidden2 = keras.layers.Dense(50, activation='relu')
        self.main_output = keras.layers.Dense(1, activation='sigmoid')        
        
    def call(self, inputs):
        hidden1 = self.hidden1(inputs)
        hidden2 = self.hidden2(hidden1)
        main_output = self.main_output(hidden2)
        
        return main_output
    
model = Basic_NN_Model()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=40, validation_data=(X_test, y_test))

test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Test Accuracy: {:.2f}%".format(test_accuracy * 100))

2023-01-31 21:12:25.010354: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2023-01-31 21:12:25.117997: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)

Epoch 1/40
20/20 [==============================] - 1s 12ms/step - loss: 0.7337 - accuracy: 0.6661 - val_loss: 0.6538 - val_accuracy: 0.6194
Epoch 2/40
20/20 [==============================] - 0s 4ms/step - loss: 0.6331 - accuracy: 0.6533 - val_loss: 0.6373 - val_accuracy: 0.6642
Epoch 3/40
20/20 [==============================] - 0s 5ms/step - loss: 0.5870 - accuracy: 0.6838 - val_loss: 0.5808 - val_accuracy: 0.6866
Epoch 4/40
20/20 [==============================] - 0s 5ms/step - loss: 0.5614 - accuracy: 0.7014 - val_loss: 0.5582 - val_accuracy: 0.6866
Epoch 5/40
20/20 [==============================] - 0s 4ms/step - loss: 0.5745 - accuracy: 0.6966 - val_loss: 0.7360 - val_accuracy: 0.6642
Epoch 6/40
20/20 [==============================] - 0s 4ms/step - loss: 0.6033 - accuracy: 0.7255 - val_loss: 0.6265 - val_accuracy: 0.6903
Epoch 7/40
20/20 [==============================] - 0s 4ms/step - loss: 0.5976 - accuracy: 0.7127 - val_loss: 0.5348 - val_accuracy: 0.7388
Epoch 8/40
20/20 [==============================] - 0s 4ms/step - loss: 0.5144 - accuracy: 0.7673 - val_loss: 0.5342 - val_accuracy: 0.7500
Epoch 9/40
20/20 [==============================] - 0s 5ms/step - loss: 0.5208 - accuracy: 0.7464 - val_loss: 0.5136 - val_accuracy: 0.7351
Epoch 10/40
20/20 [==============================] - 0s 3ms/step - loss: 0.5037 - accuracy: 0.7689 - val_loss: 0.5119 - val_accuracy: 0.7425
Epoch 11/40
20/20 [==============================] - 0s 3ms/step - loss: 0.4869 - accuracy: 0.7897 - val_loss: 0.5143 - val_accuracy: 0.7313
Epoch 12/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4876 - accuracy: 0.7705 - val_loss: 0.5077 - val_accuracy: 0.7201
Epoch 13/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4920 - accuracy: 0.7705 - val_loss: 0.4985 - val_accuracy: 0.7537
Epoch 14/40
20/20 [==============================] - 0s 3ms/step - loss: 0.4973 - accuracy: 0.7817 - val_loss: 0.5316 - val_accuracy: 0.7276
Epoch 15/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4719 - accuracy: 0.7913 - val_loss: 0.5076 - val_accuracy: 0.7537
Epoch 16/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4766 - accuracy: 0.7929 - val_loss: 0.4742 - val_accuracy: 0.7836
Epoch 17/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4482 - accuracy: 0.8138 - val_loss: 0.4884 - val_accuracy: 0.7649
Epoch 18/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4541 - accuracy: 0.8042 - val_loss: 0.4807 - val_accuracy: 0.7761
Epoch 19/40
20/20 [==============================] - 0s 3ms/step - loss: 0.4408 - accuracy: 0.8106 - val_loss: 0.4838 - val_accuracy: 0.7761
Epoch 20/40
20/20 [==============================] - 0s 4ms/step - loss: 0.5498 - accuracy: 0.7753 - val_loss: 0.5222 - val_accuracy: 0.7687
Epoch 21/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4922 - accuracy: 0.7673 - val_loss: 0.5999 - val_accuracy: 0.7388
Epoch 22/40
20/20 [==============================] - 0s 3ms/step - loss: 0.4863 - accuracy: 0.7994 - val_loss: 0.5234 - val_accuracy: 0.7351
Epoch 23/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4435 - accuracy: 0.8138 - val_loss: 0.4941 - val_accuracy: 0.7612
Epoch 24/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4937 - accuracy: 0.7913 - val_loss: 0.4944 - val_accuracy: 0.7612
Epoch 25/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4426 - accuracy: 0.7978 - val_loss: 0.4971 - val_accuracy: 0.7724
Epoch 26/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4414 - accuracy: 0.7994 - val_loss: 0.4945 - val_accuracy: 0.7649
Epoch 27/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4397 - accuracy: 0.8218 - val_loss: 0.4686 - val_accuracy: 0.7948
Epoch 28/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4294 - accuracy: 0.8138 - val_loss: 0.4640 - val_accuracy: 0.7724
Epoch 29/40
20/20 [==============================] - 0s 3ms/step - loss: 0.4202 - accuracy: 0.8170 - val_loss: 0.4666 - val_accuracy: 0.7836
Epoch 30/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4474 - accuracy: 0.8058 - val_loss: 0.5137 - val_accuracy: 0.7799
Epoch 31/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4285 - accuracy: 0.8202 - val_loss: 0.5441 - val_accuracy: 0.7761
Epoch 32/40
20/20 [==============================] - 0s 3ms/step - loss: 0.4528 - accuracy: 0.8074 - val_loss: 0.4710 - val_accuracy: 0.7799
Epoch 33/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4256 - accuracy: 0.8122 - val_loss: 0.4637 - val_accuracy: 0.7799
Epoch 34/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4301 - accuracy: 0.8186 - val_loss: 0.4679 - val_accuracy: 0.7836
Epoch 35/40
20/20 [==============================] - 0s 3ms/step - loss: 0.4169 - accuracy: 0.8138 - val_loss: 0.4901 - val_accuracy: 0.7724
Epoch 36/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4442 - accuracy: 0.8010 - val_loss: 0.5063 - val_accuracy: 0.7687
Epoch 37/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4426 - accuracy: 0.8090 - val_loss: 0.4801 - val_accuracy: 0.7687
Epoch 38/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4341 - accuracy: 0.8106 - val_loss: 0.5387 - val_accuracy: 0.7463
Epoch 39/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4444 - accuracy: 0.8122 - val_loss: 0.4540 - val_accuracy: 0.8022
Epoch 40/40
20/20 [==============================] - 0s 4ms/step - loss: 0.4372 - accuracy: 0.8186 - val_loss: 0.4595 - val_accuracy: 0.8022
Test Accuracy: 80.22%

In [6]:
# using Sequential API

#import tensorflow as tf

#model = tf.keras.Sequential()
#model.add(tf.keras.layers.Dense(50, activation='relu', input_shape=(X_train.shape[1:])))
#model.add(tf.keras.layers.Dense(50, activation='relu'))
#model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# Compile the model
#model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
#history = model.fit(X_train, y_train, epochs=40, validation_data=(X_test, y_test))

#test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
#print("Test Accuracy: {:.2f}%".format(test_accuracy * 100))

In [7]:
test_data = test_df[relevant_features] 
test_data.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [8]:
test_data = pp.transform(test_data)
print(test_data.shape)

(418, 10)

In [9]:
y_pred = model.predict(test_data)
y_pred = np.rint(y_pred)
#y_pred.astype(int).astype(str)

In [10]:
pred_df = pd.DataFrame(y_pred.astype(int).astype(str), columns=['Survived'])
pred_df.insert(0, 'PassengerId', test_df.PassengerId)
pred_df

     PassengerId Survived
0            892        0
1            893        0
2            894        0
3            895        0
4            896        1
..           ...      ...
413         1305        0
414         1306        1
415         1307        0
416         1308        0
417         1309        0

[418 rows x 2 columns]

In [11]:
#creating the submission file
pred_df.to_csv("submission.csv",index=False)

**Thank you for review. If you like it, please consider to upvote!**