<h1 style="color:#189AB4;font-size:80px;"><strong>Introduction</strong></h1>

<p style="font-size:120%">In this notebook,  I  would like to introduce a cool python hand-painted styles visualization package; cute charts. Cutecharts are perfect to give a more personal touch to charts. If you want to make charts less intimidating then add a spoonful of sweetness then cute charts are the best option.</p>

<p style="font-size:120%">It’s totally different from the regular Matplotlib and Seaborn library, it has a lookout of handmade charts and while hovering on the charts it shows us the values. The hovering effect is not there in the Matplotlib chart which is an advantage of cute charts. Creating charts in cute charts is a little bit longer compared to seaborn, but a still lesser number of codes than the standard matplotlib library.</p>

<p style="font-size:120%">This package can be used to generate the following kinds of charts. For now, this library support five different charts:<strong> Bar Chart, Pie Chart, Radar Chart, Scatter Chart, Line Chart</strong></p>

<h1 style="color:#189AB4;font-size:40px;"><strong>Installing the cute chart library</strong></h1>

In [1]:
!pip install cutecharts

Collecting cutecharts
  Downloading cutecharts-1.2.0-py3-none-any.whl (17 kB)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.7/site-packages (from cutecharts) (3.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.7/site-packages (from jinja2->cutecharts) (2.0.1)
Installing collected packages: cutecharts
Successfully installed cutecharts-1.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [2]:
import cutecharts.charts as ctc
from cutecharts.faker import Faker

import pandas as pd

<h1 style="color:#189AB4;font-size:40px;"><strong>Parameters</strong></h1>
<p style="font-size:120%">Assigning the chart name you want, for example, you want a pie chart then run the below code</p>

```
 chart = ctc.Pie()
```
<br>
<p style="font-size:120%">Setting the title, width, and height of the chart we need to add the width, height in the parameters, an example is given below.</p>

```
 chart = ctc.Pie('Title', width='600px', height='300px')
```
<br>
<p style="font-size:120%">Setting the chart option we will use set_options() function, an example is given below.</p>

```
 chart.set_options()
```

<br>
<p style="font-size:120%">Setting the x and y labels title we will use x_label, and y_label passing in set_options() function example is given below.</p>

```
 chart.set_options(x_label='X Labels',
                  y_label='Y Labels' ,
 )
```

<br>
<p style="font-size:120%">Finally, we will use a function to display the charts render_notebook() an example is given below.</p>

```
 chart.render_notebook()
```

<h1 style="color:#189AB4;font-size:40px;"><strong>Ready the Data</strong></h1>

In [3]:
df_tit = pd.read_csv('../input/titanic/train.csv')
df_tit[:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [4]:
df_netf = pd.read_csv('../input/netflix-shows/netflix_titles.csv')
df_netf[:2]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

<h1 style="color:#189AB4;font-size:40px;"><strong>Pie Chart</strong></h1>

In [5]:
# data
df_year = df_netf['release_year'].value_counts().reset_index().sort_values(by='index', ascending=False)[:5].rename(columns={'index':'release_year','release_year':'Count'})
df_year

   release_year  Count
5          2021    592
3          2020    953
2          2019   1030
0          2018   1147
1          2017   1032

<p style="font-size:120%">We will first make a pie chart where we will put the inner radius value to 0</p>

In [6]:
# pie chart
chart = ctc.Pie('Top 5 years', width='600px', height='300px')

# set the chart option
chart.set_options(labels=list(df_year['release_year']), inner_radius=0)

# label to be shown on graph while hovering the chart (eg: count number 1147)
chart.add_series(list(df_year['Count']))

# display the chart
chart.render_notebook()

<h1 style="color:#189AB4;font-size:40px;"><strong>Donut Chart</strong></h1>
<p style="font-size:120%">We will first make a Donut chart where we will put the inner radius value from 0 to 1</p>

In [7]:
df_year = df_netf['release_year'].value_counts().reset_index().sort_values(by='index', ascending=False)[:5].rename(columns={'index':'release_year','release_year':'Count'})

# Donut chart
chart = ctc.Pie('Top 5 years', width='600px', height='300px')

# set the chart options
chart.set_options(labels=list(df_year['release_year']), inner_radius=0.8)

# label to be shown on graph
chart.add_series(list(df_year['Count']))

# display the charts
chart.render_notebook()

<h1 style="color:#189AB4;font-size:40px;"><strong>Bar Chart</strong></h1>

In [8]:
rating = pd.DataFrame(df_netf['rating'].value_counts()).reset_index()[:5].rename(columns={'index':'rating','rating':'count'})
rating

  rating  count
0  TV-MA   3207
1  TV-14   2160
2  TV-PG    863
3      R    799
4  PG-13    490

In [9]:
# bar chart
bar = ctc.Bar("Distribution of Rating")

# set the chart options
bar.set_options(labels=list(rating.index),
                x_label='Rating',
                y_label='Count')

# label to be shown on graph
bar.add_series('Count',list(rating['count'])) 

# display the chart
bar.render_notebook()

In [10]:
df_age = pd.DataFrame(df_tit['Embarked'].value_counts()).reset_index().rename(columns={'index':'Embarked','Embarked':'Count'})
df_age

  Embarked  Count
0        S    644
1        C    168
2        Q     77

In [11]:
# bar chart
chart = ctc.Bar("Distribution of Embraked", width='700px')

# set the chart option
chart.set_options(labels=list(df_age['Embarked']),
                  x_label='Embarked',
                  y_label='Count',
 )

# label to be shown on graph
chart.add_series('Embarked',list(df_age['Count']))

# display the chart
chart.render_notebook()

<h1 style="color:#189AB4;font-size:40px;"><strong>Line Chart</strong></h1>

In [12]:
data = df_netf.groupby('release_year').count()['show_id'].reset_index().head(15)
data[:2]

   release_year  show_id
0          1925        1
1          1942        2

In [13]:
# line chart
chart = ctc.Line("Impact of First 15 Movie over the years of 19's", width='700px', height='500px')

# set the chart options
chart.set_options(labels=list(data['release_year']),
                  x_label='Years',
                  y_label='Count',
 )

# label to be shown on graph
chart.add_series('Years',list(data['show_id']))

# display the chart
chart.render_notebook()

<h1 style="color:#189AB4;font-size:40px;"><strong>Radar Chart</strong></h1>
<p style="font-size:120%">A radar chart is also known as a spider chart mostly used to display Multivariate values. For the Radar chart, we will take dummy data of coffee consumption where features are Day, This week, and last week.</p>

In [14]:
data = {'Day': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        'This week': [12, 10, 9, 9, 10, 3, 3], 
        'Last week': [15, 12, 8, 9, 11, 4, 3]
       }
df_coffee = pd.DataFrame(data, columns = ['Day', 'This week', 'Last week'])
df_coffee

   Day  This week  Last week
0  Mon         12         15
1  Tue         10         12
2  Wed          9          8
3  Thu          9          9
4  Fri         10         11
5  Sat          3          4
6  Sun          3          3

In [15]:
# radar chart
chart = ctc.Radar('Cups of coffee consumed per day')

# set the chart options
chart.set_options(
    labels=list(df_coffee['Day']), 
    is_show_legend=True,
    legend_pos='upRight' 
    )

# label to be shown on graph
chart.add_series('This Week', list(df_coffee['This week'])) 
chart.add_series('Last Week', list(df_coffee['Last week']))

# display the chart
chart.render_notebook()

If you want to read this article and other some amazing articles do gave a look [here](https://www.analyticsvidhya.com/blog/author/kashish1/) 

  <H2> If you like the notebook, Do upvote </H2>