In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [48]:
df = pd.read_csv("/kaggle/input/titanic/train.csv")

In [49]:
df1 = df.copy()

In [50]:
df1.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [51]:
df1.shape

(891, 12)

In [52]:
df1.ndim

2

In [53]:
df1.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [54]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [55]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [56]:
# Missing values
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [57]:
df1["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

### The average age of those who died in the accident

In [58]:
df1.loc[df1["Survived"] == 0]["Age"].mean()

30.62617924528302

### The average fare of those who died in the accident

In [59]:
df1.loc[df1["Survived"] == 0]["Fare"].mean()

22.117886885245902

### The median of the fare of those who died in the accident

In [60]:
df1.loc[df1["Survived"] == 0]["Fare"].median()

10.5

### The average age of men who died in the accident

In [61]:
df1.loc[(df1["Survived"] == 0) & (df1["Sex"] == "male")]["Age"].mean()

31.618055555555557

### The average age of women who died in the accident

In [62]:
df1.loc[(df1["Survived"] == 0) & (df1["Sex"] == "female")]["Age"].mean()

25.046875

### The average age of those who survived in the accident

In [63]:
df1.loc[df1["Survived"] == 1]["Age"].mean()

28.343689655172415

### The average fare of those who survived in the accident

In [64]:
df1.loc[df1["Survived"] == 1]["Fare"].mean()

48.39540760233918

### The total number of those who survived in the accident

In [65]:
len(df1.loc[df1["Survived"] == 1])

342

### The median of the fare of those whose age under 10

In [66]:
df1.loc[df1["Age"] < 10]["Fare"].median()

27.0

### The average fare and the median of those who has first,second and third class ticket

In [67]:
df1.loc[df1["Pclass"]]["Fare"].mean()

48.17900426487094

In [68]:
df1.loc[df1["Pclass"]]["Fare"].median()

53.1

### The ratio of men who died in the accident

In [69]:
len(df1.loc[(df1["Survived"] == 0) & (df1["Sex"] == "male")]) / len(df1.loc[df1["Sex"] == "male"])

0.8110918544194108

### The ratio of women who died in the accident

In [70]:
len(df1.loc[(df1["Survived"] == 0) & (df1["Sex"] == "female")]) / len(df1.loc[df1["Sex"] == "female"])

0.25796178343949044