In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/house-prices-advanced-regression-techniques/test.csv

In [2]:

import warnings
warnings.simplefilter(action='ignore', category=Warning)
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
import sys
np.set_printoptions(threshold=sys.maxsize)

In [3]:
train_df=pd.read_csv('../input/house-prices-advanced-regression-techniques/train.csv' ,index_col= 'Id')
test_df= pd.read_csv('../input/house-prices-advanced-regression-techniques/test.csv',index_col= 'Id')

# **check the Data ***

In [4]:

print(test_df.shape)
print(train_df.shape)

(1459, 79)
(1460, 80)

In [5]:
train_df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

# **Finding features with most number of missing values**

In [6]:

train_df.isnull().sum().nlargest(20)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageType        81
GarageYrBlt       81
GarageFinish      81
GarageQual        81
GarageCond        81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrType         8
MasVnrArea         8
Electrical         1
MSSubClass         0
dtype: int64

# **Drop columns with high amount of null objects from train Data**

In [7]:
train_df=train_df.drop(['Alley','PoolQC','Fence','MiscFeature','FireplaceQu'], axis=1)

In [8]:
test_df.isnull().sum().nlargest(20)

PoolQC          1456
MiscFeature     1408
Alley           1352
Fence           1169
FireplaceQu      730
LotFrontage      227
GarageYrBlt       78
GarageFinish      78
GarageQual        78
GarageCond        78
GarageType        76
BsmtCond          45
BsmtQual          44
BsmtExposure      44
BsmtFinType1      42
BsmtFinType2      42
MasVnrType        16
MasVnrArea        15
MSZoning           4
Utilities          2
dtype: int64

**drop same columns from test data**

In [9]:
test_df=test_df.drop(['Alley','PoolQC','Fence','MiscFeature','FireplaceQu'], axis=1)

# **Finding most important features (based on correlation)**

In [10]:
top_corr_features = train_df.corr()['SalePrice'].sort_values(ascending=False)
top_corr_features

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePrice, dtype: float64

In [11]:
Correlation_Matrix = train_df.corr()
Correlation_Matrix.style.background_gradient(cmap='coolwarm')

# **We still have columns with large null values but we do not remove them because they have high corr..like "LotFrontage"**

In [12]:
train_df.isnull().sum().nlargest(15)

LotFrontage     259
GarageType       81
GarageYrBlt      81
GarageFinish     81
GarageQual       81
GarageCond       81
BsmtExposure     38
BsmtFinType2     38
BsmtQual         37
BsmtCond         37
BsmtFinType1     37
MasVnrType        8
MasVnrArea        8
Electrical        1
MSSubClass        0
dtype: int64

In [13]:
low_corr_cols=['MoSold','3SsnPorch', 'BsmtFinSF2','BsmtHalfBath','MiscVal','LowQualFinSF','YrSold']

In [14]:
train_df=train_df.drop(low_corr_cols , axis=1)
test_df=test_df.drop(low_corr_cols , axis=1)

# **After Deleting low_corr and high_number_null columns , we have to categorize the features to Impute missing values**
#

In [15]:
categorical_feature = ['MSZoning','Street', 'LotShape','LandContour',
 'LotConfig', 'LandSlope', 'RoofStyle','RoofMatl','MasVnrType', 'ExterCond', 'BsmtCond', 'Heating', 'Functional', 'GarageType', 'GarageYrBlt', 'GarageFinish',
 'GarageQual','GarageCond', 'PavedDrive']

ordinal_feature = ["BsmtQual" ,"Foundation" ,"BsmtExposure"  ,"BsmtFinType1" ,"BsmtFinType2", "HeatingQC" ,"CentralAir" ,"Electrical" ,"KitchenQual"]
numerical_feature = ["LotFrontage" , "LotArea" ,"BsmtFinSF1" ,"1stFlrSF" , "2ndFlrSF" , "FullBath",
                     "TotRmsAbvGrd","ScreenPorch", "PoolArea", "OverallQual","OverallCond" ,"YearRemodAdd"
                   ,"TotalBsmtSF" ,"GarageCars",'MasVnrArea']
all_features=categorical_feature+ordinal_feature+numerical_feature

In [16]:
def Impute_Data(df , type_df):
  if type_df=='numerical':
        imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
        imp_mean.fit(df)
        df=imp_mean.transform(df)
        return df
  elif type_df in ['ordinal','categorical']:
        imp_mod = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
        imp_mod.fit(df)
        df=imp_mod.transform(df)
        return df

In [17]:
train_df=train_df[categorical_feature+ordinal_feature+numerical_feature+['SalePrice']]
test_df=test_df[categorical_feature+ordinal_feature+numerical_feature]

In [18]:
train_df[categorical_feature]=Impute_Data(train_df[categorical_feature],'categorical')
train_df[ordinal_feature]=Impute_Data(train_df[ordinal_feature],'ordinal')
train_df[numerical_feature]=Impute_Data(train_df[numerical_feature],'numerical')

In [19]:
train_df.head()

,MSZoning,Street,LotShape,LandContour,LotConfig,LandSlope,RoofStyle,RoofMatl,MasVnrType,ExterCond,...,TotRmsAbvGrd,ScreenPorch,PoolArea,OverallQual,OverallCond,YearRemodAdd,TotalBsmtSF,GarageCars,MasVnrArea,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,RL,Pave,Reg,Lvl,Inside,Gtl,Gable,CompShg,BrkFace,TA,...,8.0,0.0,0.0,7.0,5.0,2003.0,856.0,2.0,196.0,208500
2,RL,Pave,Reg,Lvl,FR2,Gtl,Gable,CompShg,None,TA,...,6.0,0.0,0.0,6.0,8.0,1976.0,1262.0,2.0,0.0,181500
3,RL,Pave,IR1,Lvl,Inside,Gtl,Gable,CompShg,BrkFace,TA,...,6.0,0.0,0.0,7.0,5.0,2002.0,920.0,2.0,162.0,223500
4,RL,Pave,IR1,Lvl,Corner,Gtl,Gable,CompShg,None,TA,...,7.0,0.0,0.0,7.0,5.0,1970.0,756.0,3.0,0.0,140000
5,RL,Pave,IR1,Lvl,FR2,Gtl,Gable,CompShg,BrkFace,TA,...,9.0,0.0,0.0,8.0,5.0,2000.0,1145.0,3.0,350.0,250000

In [20]:
test_df[categorical_feature]=Impute_Data(test_df[categorical_feature],'categorical')
test_df[ordinal_feature]=Impute_Data(test_df[ordinal_feature],'ordinal')
test_df[numerical_feature]=Impute_Data(test_df[numerical_feature],'numerical')

# **check again for missing value**

In [21]:
train_df.isnull().sum().nlargest(15)

MSZoning       0
Street         0
LotShape       0
LandContour    0
LotConfig      0
LandSlope      0
RoofStyle      0
RoofMatl       0
MasVnrType     0
ExterCond      0
BsmtCond       0
Heating        0
Functional     0
GarageType     0
GarageYrBlt    0
dtype: int64

In [22]:

test_df.isnull().sum().nlargest(15)

MSZoning       0
Street         0
LotShape       0
LandContour    0
LotConfig      0
LandSlope      0
RoofStyle      0
RoofMatl       0
MasVnrType     0
ExterCond      0
BsmtCond       0
Heating        0
Functional     0
GarageType     0
GarageYrBlt    0
dtype: int64

# **Now we should turn object data to numbers ! **

In [23]:
Onehot_Encoding = OneHotEncoder(sparse=False)
features_Onehot_encoded = pd.DataFrame(Onehot_Encoding.fit_transform(train_df[categorical_feature].astype(str) ))
features_Onehot_encoded.columns = Onehot_Encoding.get_feature_names(categorical_feature)
train_df[features_Onehot_encoded.columns] = features_Onehot_encoded
train_df= train_df.drop(train_df[categorical_feature] ,axis =1)
# train_df = train_df.dropna()

In [24]:
print(test_df.shape)
print(train_df.shape)

(1459, 43)
(1460, 207)

In [25]:
Onehot_Encoding = OneHotEncoder(sparse=False)
features_Onehot_encoded = pd.DataFrame(Onehot_Encoding.fit_transform(test_df[categorical_feature].astype(str)))
features_Onehot_encoded.columns = Onehot_Encoding.get_feature_names(categorical_feature)
test_df[features_Onehot_encoded.columns] = features_Onehot_encoded
test_df= test_df.drop(test_df[categorical_feature] ,axis =1)
# test_df = test_df.dropna()

In [26]:
train_df = train_df.fillna(0)
test_df = train_df.fillna(0)

In [27]:

ordinal_encoder = OrdinalEncoder()
ord_encoded_feature = pd.DataFrame(ordinal_encoder.fit_transform(train_df[ordinal_feature]))
train_df[ord_encoded_feature.columns] = ord_encoded_feature
train_df = train_df.drop(train_df[ordinal_feature] ,axis =1)

In [28]:
ordinal_encoder = OrdinalEncoder()
ord_encoded_feature = pd.DataFrame(ordinal_encoder.fit_transform(test_df[ordinal_feature]))
test_df[ord_encoded_feature.columns] = ord_encoded_feature
test_df = test_df.drop(test_df[ordinal_feature] ,axis =1)

# **Now we have to scale the Data**

In [29]:

scaler= StandardScaler()

train_to_scale = train_df.loc[:, train_df.columns != "SalePrice"]

In [30]:
scaled_df_array=scaler.fit_transform(train_to_scale)
scaled_train_df = pd.DataFrame(scaled_df_array, index=train_to_scale.index, columns=train_to_scale.columns)
scaled_train_df['SalePrice']=train_df['SalePrice']

In [31]:
scaled_df_array=scaler.fit_transform(test_df)
scaled_test_df = pd.DataFrame(scaled_df_array, index=test_df.index, columns=test_df.columns)

In [32]:

scaled_train_df.dropna(inplace=True)
scaled_test_df.dropna(inplace=True)

In [33]:
scaled_train_df['SalePrice']

Id
1       208500
2       181500
3       223500
4       140000
5       250000
         ...
1455    185000
1456    175000
1457    210000
1458    266500
1459    142125
Name: SalePrice, Length: 1459, dtype: int64

In [34]:
scaled_train_df.dropna(axis=0, inplace=True)
scaled_test_df.dropna(axis=0, inplace=True)
X=scaled_train_df.drop('SalePrice' , axis=1)
y=scaled_train_df['SalePrice']

# **Now we use GridSerach CV to choose best parameteres for random forest and GradienBoosting model**

In [35]:
warnings.filterwarnings("ignore")
reg = GradientBoostingRegressor()
parameters = {'learning_rate': [0.01,0.02,0.03],
                  'subsample'    : [0.9, 0.5, 0.2, 0.1],
                  'n_estimators' : [100,500,1000],
                  'max_depth'    : [4,6,8]
                 }
grid_GBR = GridSearchCV(estimator=reg, param_grid = parameters, cv = 5, n_jobs=-1)
grid_GBR.fit(X, y)

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

GridSearchCV(cv=5, estimator=GradientBoostingRegressor(), n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.02, 0.03],
                         'max_depth': [4, 6, 8],
                         'n_estimators': [100, 500, 1000],
                         'subsample': [0.9, 0.5, 0.2, 0.1]})

In [36]:
print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_GBR.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_GBR.best_score_)
print("\n The best parameters across ALL searched params:\n",grid_GBR.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 GradientBoostingRegressor(learning_rate=0.01, max_depth=6, n_estimators=1000,
                          subsample=0.9)

 The best score across ALL searched params:
 0.8648471138517733

 The best parameters across ALL searched params:
 {'learning_rate': 0.01, 'max_depth': 6, 'n_estimators': 1000, 'subsample': 0.9}

In [37]:
from sklearn.ensemble import RandomForestRegressor

In [38]:
rnf = RandomForestRegressor()
parameters_rnf = {    'n_estimators' : [100,500,1000],
                       'max_depth'    : [4,6,8]
                 }
grid_rnf = GridSearchCV(estimator=rnf, param_grid = parameters_rnf, cv = 5, n_jobs=-1)
grid_rnf.fit(X, y)
# print("Accuracy: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  FutureWarning,

GridSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'max_depth': [4, 6, 8],
                         'n_estimators': [100, 500, 1000]})

In [39]:
print(" Results from Grid Search " )
print("\n The best estimator across ALL searched params:\n",grid_rnf.best_estimator_)
print("\n The best score across ALL searched params:\n",grid_rnf.best_score_)
print("\n The best parameters across ALL searched params:\n",grid_rnf.best_params_)

 Results from Grid Search

 The best estimator across ALL searched params:
 RandomForestRegressor(max_depth=8)

 The best score across ALL searched params:
 0.8385645136761329

 The best parameters across ALL searched params:
 {'max_depth': 8, 'n_estimators': 100}

In [40]:
test_df.dropna(inplace=True)
X_test=test_df[X.columns]

In [41]:
print(X.shape)
print(y.shape)

(1459, 206)
(1459,)

# Choose the best Parameters and use them to train and test

In [42]:
final_model=GradientBoostingRegressor(learning_rate=0.03, max_depth=6, n_estimators=500,
                          subsample=0.9)
final_model.fit(X,y)
y_pred=final_model.predict(X_test)

In [43]:
y_pred

array([576242.5775397 , 292935.99679066, 552647.51759859, 570002.40773689,
       560759.56013473, 570641.92510527, 282751.91295633, 558538.42189547,
       610386.63155271, 304328.15000325, 286361.1251827 , 565979.66974296,
       300916.17028617, 362143.33070611, 293140.48231054, 346978.41259804,
       292005.87281926, 363125.98974396, 301280.23376401, 288113.6332921 ,
       615905.02976373, 354321.15698729, 367098.2842276 , 292305.16224822,
       301250.29257979, 366699.784853  , 301828.53813616, 287634.85443569,
       289018.65310015, 354688.84622755, 581112.42760974, 352798.79058223,
       366320.69587233, 297262.78789666, 296806.99900633, 612034.68275221,
       353258.48480084, 296193.66806879, 300313.6995932 , 291698.6927407 ,
       298951.37287117, 292480.65876358, 292163.6931253 , 305597.92245802,
       299316.45761874, 285777.237821  , 573097.02302137, 302485.39855328,
       587233.34398583, 297799.16841554, 553168.45680102, 351243.96322251,
       288460.90523284, 305300.30549347, 290863.61418983, 296510.49739568,
       569685.47755453, 614375.20530092, 618964.24685082, 304481.08254263,
       300477.40796167, 597413.20206299, 285437.39067986, 613501.14842087,
       574243.94675301, 604575.37154462, 284943.37323142, 292343.30921506,
       351542.09849523, 564872.92747577, 293228.66583696, 285840.17792548,
       602908.60307078, 292655.30586743, 597746.70695439, 571232.21551461,
       301926.03184293, 557211.58962018, 282555.16511769, 576528.30681377,
       577349.27551253, 298101.38931597, 287818.92618401, 337984.82207077,
       622298.01159443, 612130.28391285, 611572.60493303, 607827.49976619,
       257432.30549339, 225956.96352267, 353222.69571593, 286673.58419922,
       300738.15639726, 574242.22878929, 543977.58452366, 573062.65065863,
       299996.96949643, 294855.46124739, 291832.10176208, 220847.02250151,
       297360.48095087, 597455.45793883, 350062.64654515, 368612.64420292,
       579148.71089292, 602047.91482215, 359025.51833859, 298566.86648201,
       598573.55260196, 298641.89153455, 563633.08994027, 565329.60274535,
       566334.17479548, 287490.76725464, 548956.52950677, 558078.25615626,
       292868.49667246, 351003.03824917, 564648.95436519, 612335.4406205 ,
       299805.55007611, 583747.27769715, 304816.21557373, 293219.76707899,
       371943.31601978, 220922.93721269, 292148.9304925 , 229802.2320349 ,
       560539.98734981, 294002.2091398 , 569071.34846815, 554055.77293824,
       288117.2312999 , 287330.83465925, 305011.86022074, 354547.04673648,
       297901.53696798, 358627.29724232, 573894.04638648, 554449.18966249,
       227322.00454938, 301097.5205419 , 570554.82296873, 296769.23873881,
       296422.09337673, 597220.547417  , 288757.5371186 , 614633.79566249,
       216936.74897146, 580870.57596578, 301142.33172902, 286826.45609757,
       560885.96264984, 298336.03823694, 351402.69670157, 553897.48464207,
       347236.7872666 , 614423.44732165, 566589.78142802, 555607.22191673,
       287632.19114046, 570087.21289307, 299687.65400778, 253907.94527205,
       553285.35823236, 561421.10497049, 307133.76603097, 565458.24081362,
       605999.79193661, 358700.10866689, 287107.16392788, 282630.007895  ,
       553840.50461166, 285471.88429031, 293131.56889404, 286778.48833669,
       576589.18647829, 572502.39997266, 298108.73163085, 355140.13317998,
       558462.13249775, 573849.21124347, 349528.58723931, 594565.45150704,
       597685.52472616, 614416.31346101, 307774.3557656 , 599333.98963709,
       295887.23480656, 313255.81289185, 549827.86630911, 565708.48060935,
       304193.70420346, 610261.7340523 , 303470.59089676, 572145.63155742,
       303326.53153874, 570169.34222158, 564823.97742377, 300746.156266  ,
       375352.28416865, 298391.01992564, 571911.09452762, 294718.73608649,
       568302.18961183, 362866.57023931, 345742.6329056 , 290653.28314702,
       587223.20530565, 295904.85457028, 225183.27812372, 305167.7473957 ,
       568404.61823838, 290653.28314702, 555581.53088024, 294693.50232706,
       297478.86174755, 594954.37112672, 566021.32400981, 286480.85110406,
       362143.12675339, 599834.93517213, 555045.22107202, 297262.78789666,
       297381.15769934, 616883.25702954, 558952.55322985, 558592.75659309,
       299648.995796  , 300779.4630786 , 340611.27123735, 558766.46451451,
       584138.97912364, 300542.25807354, 557676.8073918 , 572233.35490098,
       286480.85110406, 571988.78796558, 371564.47480975, 570405.72871663,
       296443.46308615, 219929.97214384, 582507.25776151, 597413.20206299,
       552150.74643907, 292852.72312174, 620882.24257018, 354565.81098635,
       599605.55960806, 573907.82151888, 251735.40187146, 295869.92943249,
       623516.65508759, 298951.37287117, 288757.5371186 , 617417.11404888,
       571597.89818141, 297292.99097785, 556240.76870716, 350537.61063396,
       283852.94623393, 597114.08963554, 292094.71983731, 300477.40796167,
       342465.05608518, 284844.31160424, 569820.34724613, 566352.82046859,
       289315.72572053, 294250.54610692, 613497.55290573, 288757.5371186 ,
       568783.53909834, 292939.85233846, 299779.0814574 , 608624.3184695 ,
       370674.41710427, 297538.23359267, 382583.10989162, 556000.9079288 ,
       553584.29916791, 298101.38931597, 297318.8957338 , 369794.38546313,
       294765.00481997, 599761.13846298, 553981.7167816 , 223723.0116051 ,
       296678.8445119 , 601763.33954949, 611132.32374647, 541440.09096034,
       551659.084366  , 563568.62153788, 284764.84641245, 300708.23620674,
       574604.39286337, 560279.59911301, 572292.73188801, 352177.98629145,
       294513.81499798, 566589.78142802, 366738.49246048, 300975.86716399,
       607246.35496894, 297817.97248814, 558686.19597289, 564742.31955217,
       286066.71197295, 288397.51575436, 574134.58741291, 301926.03184293,
       564690.40583313, 302607.9941483 , 561518.61019417, 551754.65234969,
       574752.97123304, 614153.44832555, 559244.43468897, 293647.6209814 ,
       611940.58608659, 569544.36468402, 573901.1562895 , 300149.89865468,
       602903.46479481, 288921.71986163, 301965.70125526, 284192.2780999 ,
       591697.7514936 , 581683.63200979, 298933.4219484 , 290684.12299991,
       297041.65714452, 284652.59504866, 560402.01072679, 571613.88387002,
       296971.09081744, 294372.45116825, 296381.5534187 , 303960.78190909,
       597537.04504196, 351950.37808049, 354084.37510921, 297207.99917181,
       552616.82671518, 589418.98111313, 292140.97950519, 298101.38931597,
       577438.35217387, 584620.07111785, 358368.94660752, 314148.05811975,
       552666.83868032, 355895.46086896, 571124.52620514, 291219.74195215,
       293955.13689412, 291987.93420564, 282585.3221457 , 578954.97518738,
       314148.05811975, 566217.74520434, 589413.64412365, 550455.99778503,
       565971.45461682, 554792.83630282, 291565.77139602, 293106.68383672,
       284715.2172426 , 301297.02890155, 594975.21008244, 588459.71989461,
       310776.01581188, 300542.25807354, 596019.57047538, 319459.30327979,
       289629.75436787, 614769.73070323, 282835.92787448, 601857.38112774,
       571597.89818141, 362065.31338712, 592323.79653437, 351819.64961691,
       563807.38482924, 306101.40419458, 569857.56256428, 283314.40168021,
       370481.67747667, 574880.72576486, 563395.91435265, 552508.81073613,
       350586.62726899, 227852.7095511 , 582974.62313892, 303128.63547893,
       303745.29767688, 553711.05449031, 353116.01435826, 570079.21215098,
       298925.74975291, 305878.60973718, 350321.3581304 , 597012.77560148,
       607923.82646667, 306267.69986277, 354730.5858032 , 609708.72144345,
       614389.5761849 , 559321.75122365, 352914.18774522, 300093.66881042,
       297496.81267032, 354159.43855313, 564859.41999804, 304220.24979809,
       560618.78561466, 554475.35767965, 569603.76138606, 298652.13017724,
       286120.17943453, 302336.72894338, 351880.98224862, 560661.56591708,
       294718.73608649, 576280.70538346, 301326.86847166, 302304.66121183,
       282156.66336588, 302867.88305235, 555770.42037741, 564194.07193447,
       564050.93171938, 598198.6896943 , 227510.34479449, 554723.28640485,
       579893.01457451, 354038.02838135, 299837.24765182, 595445.36700336,
       306951.06189428, 235681.37971512, 607654.80213046, 370362.29434497,
       560420.92784059, 344903.50652881, 285884.55735118, 597438.76535764,
       613545.40990822, 573130.08166701, 346849.82950849, 291774.62248992,
       574198.71166086, 597545.59081705, 305689.99523349, 294140.1991336 ,
       593052.77952205, 298858.38729573, 579580.52145449, 565154.22103718,
       573921.96032441, 553113.94107291, 291954.02564696, 553027.93900884,
       240714.90317588, 370378.69034787, 314388.01667882, 571366.25192834,
       355075.04064015, 554433.06282013, 313097.05830338, 615675.11542044,
       282610.78839715, 300712.68562248, 306116.44007106, 310682.66035383,
       300417.08870734, 626249.76218971, 299674.80179401, 282559.48770159,
       290013.762021  , 293761.87391091, 571535.41533501, 281608.12762505,
       303470.59089676, 303226.8465304 , 286099.48904266, 310277.85052904,
       556213.39670677, 297100.05808176, 581749.81956168, 551216.33788914,
       598109.18605985, 299259.61232548, 354726.89241483, 220617.57375938,
       305878.60973718, 570668.99231477, 283725.3094185 , 301761.8490999 ,
       556168.26267258, 576593.46065538, 290362.35632668, 313831.27839075,
       562554.57542867, 616883.25702954, 567377.99571887, 304807.53006745,
       567949.87582653, 296161.28991618, 293195.67736182, 365928.20572712,
       300356.29349325, 301960.66645379, 351948.52271664, 281979.21316129,
       616883.25702954, 617966.2543559 , 571150.44111156, 584157.12895391,
       577481.11211211, 302734.24943144, 572502.39997266, 567050.43938846,
       572634.50023467, 375681.28948565, 286759.70939259, 573459.98036996,
       220302.39894981, 298459.65747177, 286010.14090754, 609621.55844564,
       350112.36324774, 261114.07112804, 597537.04504196, 541083.2659455 ,
       605655.34660984, 291000.75890164, 294205.86035761, 299842.6151102 ,
       296917.67676978, 620150.09005791, 301900.86958675, 283867.48692382,
       547739.03241135, 574348.61538954, 572763.21084676, 290744.38315417,
       300542.25807354, 599834.93517213, 312862.78505326, 290399.71647983,
       372364.50269334, 362508.49251803, 559150.340856  , 342531.51974069,
       312671.76184031, 567109.8360905 , 563807.38482924, 364901.90272353,
       307013.9644626 , 303925.70046013, 225108.08326089, 615834.98091522,
       549360.69201309, 595335.97567239, 617432.39733657, 347444.43601697,
       551009.89389977, 291642.52030286, 298947.29944121, 280977.49929813,
       613200.42754327, 597861.58230207, 556659.3656617 , 552616.82671518,
       616422.76162915, 294203.0726442 , 612345.62236005, 616709.41482187,
       295787.4326013 , 369206.53124243, 216936.74897146, 613368.24564513,
       605825.03485726, 299292.01658313, 293424.83840043, 290090.46017824,
       309693.86747952, 354632.27464186, 567541.64181607, 568567.16822407,
       297923.05064273, 284764.42234643, 341897.60222348, 307209.49654255,
       592203.31110668, 355906.59716191, 296734.98692626, 564659.01619485,
       556240.76870716, 593310.16441751, 572193.92959094, 612863.75646893,
       297901.53696798, 555730.61414545, 301726.16454099, 552747.14916474,
       555241.0744603 , 294877.85517837, 558005.17560382, 298576.31182016,
       571467.35403707, 227135.68711827, 228221.66081604, 282893.27678607,
       550931.798959  , 352441.73180984, 309418.77358256, 558900.743378  ,
       226872.46647593, 555415.49634304, 294982.31582556, 560885.96264984,
       561898.12013472, 349455.12437099, 355303.22384582, 281298.1221074 ,
       556357.68567079, 294055.7024368 , 598050.59401493, 299264.78807743,
       293777.2015778 , 303427.24125781, 303110.35436707, 536225.75820176,
       260381.35051166, 597537.04504196, 256932.98327062, 294346.18716639,
       294513.81499798, 551157.48953919, 566301.3101248 , 570201.76377782,
       288238.35994149, 302498.02940019, 342295.72171526, 304996.68245257,
       586355.62048552, 226401.8294988 , 602158.67152822, 598050.59401493,
       614248.32825977, 595613.56914463, 297381.15769934, 605774.13960909,
       295585.70610522, 581749.81956168, 594369.7353401 , 302484.15240175,
       624746.10229209, 566143.3023445 , 351319.68922053, 300401.31977654,
       289787.03842175, 601534.31282081, 573567.135554  , 294066.0150763 ,
       303694.87221506, 353116.01435826, 554673.2744397 , 556214.08695647,
       299973.48994858, 308340.4511996 , 303470.59089676, 554109.30407255,
       613930.16285858, 341881.29115333, 364304.20534209, 296146.29213535,
       306267.69986277, 567109.8360905 , 288060.15856596, 295871.91429655,
       599346.97718446, 564241.7749911 , 611624.79416823, 572085.81830087,
       288491.64173327, 295634.36287672, 282650.94641471, 581847.35273546,
       569441.43939918, 351205.91703523, 581111.4909919 , 297496.81267032,
       289252.700276  , 305143.49609632, 302468.84395486, 304843.11833287,
       301149.94447407, 341256.94733923, 602819.49394804, 614725.95199811,
       295251.0189745 , 565955.6213377 , 299260.85170579, 289210.28729334,
       594565.45150704, 340081.27784092, 259092.81331715, 575644.25004937,
       303598.97331316, 285210.14770863, 567744.78361738, 369922.39419834,
       581749.81956168, 301900.0758299 , 558082.4921385 , 289132.05090443,
       302142.54993435, 298835.07387034, 303247.75006789, 617556.86708381,
       298705.27475425, 289105.39467772, 298293.10587155, 293355.88816527,
       370244.82674371, 290848.30574294, 285637.66146383, 283400.88542986,
       582270.79212792, 287474.6100062 , 353329.3358372 , 553722.62612373,
       352264.88955884, 598308.62416784, 237021.53096328, 613368.24564513,
       605655.34660984, 301865.77168867, 362113.896664  , 302055.40717801,
       296610.11189904, 567377.99571887, 546574.04746642, 596162.70945165,
       295031.72328204, 584817.42335497, 558301.65833505, 613200.42754327,
       300767.82808569, 605475.00484777, 301367.31248635, 574144.28618221,
       559716.06596941, 555243.00513937, 573512.71007535, 582427.62425076,
       299805.55007611, 302029.95443171, 571163.50801955, 581496.21201441,
       297201.93764777, 369736.05486883, 573352.59428181, 571923.08007484,
       301927.27565318, 569964.78258882, 303427.24125781, 304880.10308852,
       304364.58998329, 294283.60085704, 370706.78108637, 284943.37323142,
       290012.97666204, 299364.07676376, 364833.59529212, 293106.68383672,
       371531.31996129, 571597.89818141, 355112.39961553, 295475.68506121,
       572704.94372728, 311367.82630772, 570989.21313058, 567458.977596  ,
       342465.05608518, 567355.10466284, 280952.75216031, 290601.13277537,
       565164.08527242, 354846.9645788 , 597200.37396762, 621457.26920163,
       350854.41679185, 297016.20992856, 612084.99630459, 555559.57762176,
       572364.28450684, 300733.97462912, 579810.65460887, 604612.73314359,
       288760.68751374, 369604.90601759, 307063.49342412, 557992.75220521,
       290554.44955838, 607047.75249422, 295990.83460645, 295193.37823397,
       355289.25447227, 295633.08203866, 598049.65739709, 355240.2789666 ,
       291260.15723487, 297784.376394  , 283675.77036824, 286480.85110406,
       598318.84797228, 340745.51450391, 597229.10344521, 613837.81949521,
       370765.45026578, 296405.88171531, 220452.30023555, 301524.90667587,
       575546.9824066 , 594536.60749828, 305363.5297155 , 612863.75646893,
       560254.38654298, 304996.68245257, 295904.85457028, 303091.27522894,
       301761.8490999 , 569798.80659244, 357022.28974745, 552187.87593751,
       553168.45680102, 600061.85934059, 294887.18682446, 280517.93204347,
       580335.07621342, 302890.1725861 , 574462.08109106, 301978.61737655,
       626188.17508925, 611562.22484954, 294152.44630995, 370792.89568387,
       555227.12911634, 296625.11780711, 303525.27900416, 291806.70304589,
       298826.00323503, 600061.85934059, 354115.67298161, 556880.71324571,
       599543.95893672, 298165.9363605 , 307040.0141596 , 299901.95225484,
       362863.86073432, 283867.48692382, 368037.00255221, 297091.91249553,
       598152.13723817, 565895.1652191 , 354565.81098635, 550342.00970247,
       354726.89241483, 303642.28668144, 591976.07349413, 551955.26436692,
       297016.20992856, 558810.05979096, 293374.31197992, 294493.06319074,
       292579.86902834, 553878.80324795, 595695.31388074, 584610.3683168 ,
       281099.21528047, 293559.00048783, 285125.60729421, 599559.63421651,
       319357.73235449, 295176.00032297, 588960.95106578, 568376.35972424,
       300313.6995932 , 298310.4638706 , 365013.94044039, 573788.41952983,
       299528.25950679, 604742.95593672, 299253.81049508, 293067.84832103,
       291971.97656972, 300542.25807354, 621525.68116956, 359631.33544612,
       296146.29213535, 282535.15849884, 286852.36085352, 556245.9575573 ,
       300542.25807354, 592897.43573021, 558301.30042808, 300477.40796167,
       312671.76184031, 573523.41924636, 558136.59463122, 586530.86307492,
       308065.40002737, 288989.44854917, 577090.90753049, 301052.54267518,
       558182.41782645, 549861.01948858, 305167.7473957 , 304297.13666934,
       282917.26524953, 303154.7485465 , 604575.37154462, 584965.53296872,
       354942.44061776, 611871.70148926, 308386.27472613, 285425.10752537,
       368574.66102308, 299997.1353444 , 292011.42870025, 350341.82579371,
       298101.38931597, 571597.89818141, 572330.16009269, 596899.65309002,
       291708.52389734, 555607.22191673, 244822.90867976, 362353.07693372,
       299469.50322777, 557992.75220521, 293044.80035924, 285976.47254238,
       611753.36867237, 305127.2760561 , 301285.87153307, 302131.26145523,
       293084.12196857, 557469.57110544, 234438.25652163, 555595.85480401,
       554282.17637631, 302468.84395486, 306964.71147711, 554632.38940948,
       220430.50558056, 553528.35850157, 559876.61876462, 367262.95755117,
       567986.68076969, 612521.19178076, 559267.65481567, 293851.38563509,
       556727.36125695, 295904.85457028, 564742.05660315, 558709.83226312,
       367759.00383629, 354656.16616965, 595837.56868795, 552138.46411391,
       252976.49217074, 297239.43054202, 300312.94385431, 288741.07218168,
       282010.7964498 , 568316.54360911, 365648.84361199, 597537.04504196,
       588022.80903752, 297637.65462439, 596992.40527261, 286043.9625154 ,
       574198.71166086, 606257.38398993, 554149.66537057, 559752.10410262,
       574198.71166086, 614449.44905385, 286981.57694468, 561112.66936406,
       291439.64842479, 371655.9943013 , 354554.46127558, 291071.90075218,
       346996.81075249, 343413.86250707, 282226.15839346, 368851.29588623,
       297172.45743347, 298641.89153455, 312552.76472979, 567463.77637719,
       378835.3719617 , 289367.38836333, 604838.89651815, 287335.93612653,
       589660.05667386, 303263.05851478, 294513.81499798, 571488.68991298,
       287522.55121483, 288967.8681614 , 611042.16732134, 297318.8957338 ,
       302660.56051044, 297496.81267032, 562028.63953963, 287264.65921048,
       301115.47146466, 302045.26287859, 293195.67736182, 299253.81049508,
       553673.98238351, 553992.13228586, 574446.83647746, 567006.7245694 ,
       569836.23479713, 298403.82693988, 342051.41263362, 338632.66322533,
       296917.67676978, 603586.17516569, 551873.19124917, 302223.22025855,
       300538.02551354, 573931.25745184, 299801.9077229 , 560652.44962598,
       294331.23441662, 351897.75372699, 572807.80831494, 297627.82998109,
       352319.76685468, 342273.67773082, 356529.24199075, 369075.88925615,
       576830.50275369, 293029.28146103, 555024.40174029, 295489.07081712,
       297318.8957338 , 564705.7515437 , 553354.49879897, 565762.906088  ,
       306565.0342218 , 354118.86588585, 597438.76535764, 292579.86902834,

In [44]:
submission = pd.DataFrame({'Id': X_test.index, 'SalePrice': y_pred})
submission.to_csv('submission.csv', index=False)