## Spaceship Titanic Prediction with Catboost

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from catboost import CatBoostClassifier
from sklearn.model_selection import StratifiedKFold

## Import datasets

In [2]:
train = pd.read_csv("../input/spaceship-titanic/train.csv")
train_targets = train.pop("Transported")
test = pd.read_csv("../input/spaceship-titanic/test.csv")
data = pd.concat([train, test])
data["Cabin"] = data["Cabin"].replace(np.NAN, data["Cabin"].mode()[0])
data["Deck"] = data["Cabin"].apply(lambda item: str(item).split('/')[0])
data["Num"] = data["Cabin"].apply(lambda item:  str(item).split('/')[1])
data["Side"] = data["Cabin"].apply(lambda item: str(item).split('/')[2])
data.pop("Cabin")
data.pop("PassengerId")
data.pop("Name")
data = pd.get_dummies(data)
train = data.iloc[0:len(train)]
test = data.iloc[len(train):]

In [3]:
data.head()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_False,...,Num_992,Num_993,Num_994,Num_995,Num_996,Num_997,Num_998,Num_999,Side_P,Side_S
0,39.0,0.0,0.0,0.0,0.0,0.0,0,1,0,1,...,0,0,0,0,0,0,0,0,1,0
1,24.0,109.0,9.0,25.0,549.0,44.0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
2,58.0,43.0,3576.0,0.0,6715.0,49.0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
3,33.0,0.0,1283.0,371.0,3329.0,193.0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
4,16.0,303.0,70.0,151.0,565.0,2.0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1

## Model Development

In [4]:
models = []
kfold = StratifiedKFold(7, shuffle=True, random_state=2022)
for index, (train_indices, valid_indices) in enumerate(kfold.split(train, train_targets)):
    x_train = train.iloc[train_indices]
    x_val = train.iloc[valid_indices]
    y_train = train_targets.iloc[train_indices]
    y_val = train_targets.iloc[valid_indices]
    params = {
        'iterations': 10000, 
        'depth': 8, 
        'early_stopping_rounds': 1000,
        'eval_metric': 'Accuracy',
        "verbose": 1000
    }
    ## Create Model
    model = CatBoostClassifier(**params)
    ## Train Model
    model.fit(x_train, y_train, eval_set=(x_val, y_val))
    ## Save Model
    file_path = f"model_{index}.model"
    model.save_model(file_path)
    ## Load Model
    model.load_model(file_path)
    models.append(model)

Learning rate set to 0.019114
0:	learn: 0.7727822	test: 0.7568438	best: 0.7568438 (0)	total: 74ms	remaining: 12m 19s
1000:	learn: 0.8476715	test: 0.7971014	best: 0.8003221 (416)	total: 20.8s	remaining: 3m 7s
Stopped by overfitting detector  (1000 iterations wait)

bestTest = 0.8003220612
bestIteration = 416

Shrink model to first 417 iterations.
Learning rate set to 0.019114
0:	learn: 0.7756006	test: 0.7842190	best: 0.7842190 (0)	total: 22.2ms	remaining: 3m 42s
1000:	learn: 0.8487451	test: 0.7995169	best: 0.8067633 (350)	total: 20.6s	remaining: 3m 5s
Stopped by overfitting detector  (1000 iterations wait)

bestTest = 0.806763285
bestIteration = 350

Shrink model to first 351 iterations.
Learning rate set to 0.019114
0:	learn: 0.7675480	test: 0.7504026	best: 0.7504026 (0)	total: 22.9ms	remaining: 3m 49s
1000:	learn: 0.8471346	test: 0.7987118	best: 0.8027375 (279)	total: 20.7s	remaining: 3m 6s
Stopped by overfitting detector  (1000 iterations wait)

bestTest = 0.8027375201
bestIteration = 279

Shrink model to first 280 iterations.
Learning rate set to 0.019114
0:	learn: 0.7688901	test: 0.7560386	best: 0.7560386 (0)	total: 10.6ms	remaining: 1m 45s
1000:	learn: 0.8484767	test: 0.8051530	best: 0.8123994 (325)	total: 21.6s	remaining: 3m 14s
Stopped by overfitting detector  (1000 iterations wait)

bestTest = 0.8123993559
bestIteration = 325

Shrink model to first 326 iterations.
Learning rate set to 0.019114
0:	learn: 0.7777480	test: 0.7745572	best: 0.7745572 (0)	total: 20.9ms	remaining: 3m 28s
1000:	learn: 0.8483425	test: 0.8035427	best: 0.8075684 (369)	total: 20.6s	remaining: 3m 5s
Stopped by overfitting detector  (1000 iterations wait)

bestTest = 0.807568438
bestIteration = 369

Shrink model to first 370 iterations.
Learning rate set to 0.019114
0:	learn: 0.7808348	test: 0.7858293	best: 0.7858293 (0)	total: 21.2ms	remaining: 3m 31s
1000:	learn: 0.8456583	test: 0.8019324	best: 0.8091787 (210)	total: 21.3s	remaining: 3m 11s
Stopped by overfitting detector  (1000 iterations wait)

bestTest = 0.809178744
bestIteration = 210

Shrink model to first 211 iterations.
Learning rate set to 0.019114
0:	learn: 0.7663714	test: 0.7832393	best: 0.7832393 (0)	total: 21.3ms	remaining: 3m 33s
1000:	learn: 0.8436661	test: 0.8066076	best: 0.8106366 (529)	total: 21.7s	remaining: 3m 15s
Stopped by overfitting detector  (1000 iterations wait)

bestTest = 0.8106365834
bestIteration = 529

Shrink model to first 530 iterations.

## Feature Importance
Let's take a look at feature importance of this dataset.

In [5]:
for fold, model in enumerate(models):
    print("=" * 100)
    print(f"Feature Importance for fold {fold}:")
    print("=" * 100)
    feature_importance = sorted(zip(train.columns, model.get_feature_importance()), reverse=True, key=lambda item: item[1])
    for item in feature_importance[:30]:
        print(item)

====================================================================================================
Feature Importance for fold 0:
====================================================================================================
('Spa', 12.947715078704658)
('VRDeck', 11.727640713490132)
('RoomService', 8.882635531779911)
('CryoSleep_True', 8.029069074840656)
('FoodCourt', 7.937570822071622)
('HomePlanet_Earth', 7.056732349108351)
('HomePlanet_Europa', 4.955946764687835)
('Deck_E', 4.497611603207928)
('Age', 3.9002640412415492)
('ShoppingMall', 3.635486139239815)
('CryoSleep_False', 3.441248648225984)
('Deck_G', 3.2716731816443887)
('HomePlanet_Mars', 2.9795932983881985)
('Side_P', 2.808358556352005)
('Deck_C', 2.6942154011521637)
('Deck_F', 2.5194233235407446)
('Side_S', 2.1457925024584705)
('Destination_TRAPPIST-1e', 1.6973521588756977)
('Destination_55 Cancri e', 1.6510720992749024)
('Deck_B', 1.375760454500273)
('VIP_False', 0.39499109861390863)
('Deck_A', 0.3281605276658719)
('Destination_PSO J318.5-22', 0.2313365020912064)
('VIP_True', 0.17617721612680232)
('Deck_D', 0.14232648574378104)
('Num_981', 0.04904805596916021)
('Num_478', 0.030213095169718377)
('Num_307', 0.02633631919646409)
('Num_648', 0.021267678284563996)
('Num_917', 0.020430189336975258)
====================================================================================================
Feature Importance for fold 1:
====================================================================================================
('Spa', 13.208891818948702)
('VRDeck', 11.510321325039518)
('RoomService', 8.298792165174648)
('HomePlanet_Europa', 7.977779618741034)
('HomePlanet_Earth', 7.912236925650579)
('FoodCourt', 7.852358934034614)
('CryoSleep_True', 7.150159540393538)
('Deck_E', 4.0161519032228945)
('ShoppingMall', 3.8678269529072598)
('Age', 3.864430922396817)
('CryoSleep_False', 3.751499808849069)
('HomePlanet_Mars', 3.0749189558859062)
('Side_S', 2.7430019343805574)
('Deck_F', 2.6257936639967543)
('Deck_C', 2.4807207483789337)
('Destination_TRAPPIST-1e', 2.4638350683205825)
('Side_P', 2.132928297869973)
('Deck_G', 1.7155851381103044)
('Deck_B', 1.1094781226403885)
('Destination_55 Cancri e', 0.9444797812075433)
('Destination_PSO J318.5-22', 0.26737933649464335)
('VIP_False', 0.24346902746606125)
('Deck_A', 0.1781599015781392)
('VIP_True', 0.14836337622100554)
('Deck_D', 0.06149653825388665)
('Num_974', 0.03259732777715898)
('Num_187', 0.020206646690768652)
('Num_917', 0.01494762843860056)
('Num_438', 0.01449717081983375)
('Num_981', 0.01261785370164773)
====================================================================================================
Feature Importance for fold 2:
====================================================================================================
('Spa', 13.357573513546784)
('VRDeck', 12.194308059201724)
('RoomService', 8.55988493427579)
('HomePlanet_Europa', 8.394070501461949)
('FoodCourt', 7.684036627319423)
('CryoSleep_True', 7.514090189751104)
('HomePlanet_Earth', 5.945161467310505)
('HomePlanet_Mars', 3.9709468510698667)
('Deck_E', 3.929285681425304)
('ShoppingMall', 3.703143539345349)
('Age', 3.5089093465279064)
('CryoSleep_False', 3.4385031931200496)
('Deck_C', 3.2749942752023578)
('Deck_F', 2.855702544690181)
('Side_S', 2.4264181507084737)
('Side_P', 2.387739748020908)
('Deck_G', 1.8588555073310933)
('Destination_TRAPPIST-1e', 1.8176154153823283)
('Destination_55 Cancri e', 1.1782158127099607)
('Deck_B', 1.0565850904830816)
('Deck_A', 0.27298520278875715)
('VIP_False', 0.20183608630988512)
('Destination_PSO J318.5-22', 0.10710429480263169)
('VIP_True', 0.09990936717603062)
('Num_981', 0.029207729685363514)
('Num_307', 0.0176067826308688)
('Deck_D', 0.012267212690438376)
('Num_187', 0.011152144762892162)
('Num_178', 0.009982355198811684)
('Num_142', 0.009414718984501557)
====================================================================================================
Feature Importance for fold 3:
====================================================================================================
('Spa', 13.542858138163659)
('VRDeck', 11.523581592381213)
('RoomService', 9.609711043974544)
('HomePlanet_Europa', 7.828398783269278)
('HomePlanet_Earth', 7.282683953683463)
('FoodCourt', 7.2497814902479725)
('CryoSleep_True', 5.7021001048149005)
('Deck_E', 4.627618884954353)
('CryoSleep_False', 4.2171701841042415)
('Deck_C', 3.7562780892450855)
('ShoppingMall', 3.755999597633466)
('HomePlanet_Mars', 3.4251050425160896)
('Age', 3.2446769999597085)
('Deck_F', 2.6721734961218515)
('Side_S', 2.145981833518702)
('Deck_G', 1.8378628934505439)
('Destination_TRAPPIST-1e', 1.819498312494979)
('Side_P', 1.6573591233790022)
('Deck_B', 1.5018045046222264)
('Destination_55 Cancri e', 1.0449457504677935)
('Deck_A', 0.398678195702633)
('Destination_PSO J318.5-22', 0.289265073778313)
('VIP_False', 0.2691942623895317)
('VIP_True', 0.17809871987629636)
('Num_981', 0.04735069355974341)
('Deck_D', 0.040642624993801585)
('Num_307', 0.024398969953005636)
('Num_1023', 0.019888499235287183)
('Num_68', 0.019611286917907433)
('Num_13', 0.015056099954981004)
====================================================================================================
Feature Importance for fold 4:
====================================================================================================
('Spa', 13.89687084938454)
('VRDeck', 11.558252129186522)
('RoomService', 9.09101786251781)
('HomePlanet_Europa', 8.649280174831397)
('FoodCourt', 7.740795129541167)
('CryoSleep_True', 7.219519544376248)
('HomePlanet_Earth', 6.709408122218601)
('Deck_E', 3.9682475243137354)
('Age', 3.9123720907721844)
('ShoppingMall', 3.8814416102182228)
('CryoSleep_False', 3.30940207147367)
('HomePlanet_Mars', 3.2006615099792466)
('Deck_F', 2.603028597712279)
('Deck_C', 2.4550602053124932)
('Side_P', 2.3101489179002512)
('Deck_G', 2.246704152883538)
('Side_S', 2.205496601111605)
('Destination_55 Cancri e', 1.3453224817829994)
('Destination_TRAPPIST-1e', 1.34219743324766)
('Deck_B', 0.7166862225810875)
('Deck_A', 0.32305485378253923)
('VIP_False', 0.27869007000299856)
('Destination_PSO J318.5-22', 0.27637978801035906)
('VIP_True', 0.16976527607566666)
('Deck_D', 0.06424957385549816)
('Num_187', 0.02903489887527963)
('Num_1123', 0.022366053714986026)
('Num_307', 0.022237264798287637)
('Num_68', 0.020535337235026443)
('Num_1023', 0.02009501938127133)
====================================================================================================
Feature Importance for fold 5:
====================================================================================================
('Spa', 13.030673866721683)
('VRDeck', 11.76496723784805)
('RoomService', 8.686845956783735)
('FoodCourt', 8.21639702269482)
('HomePlanet_Europa', 7.512033925667677)
('CryoSleep_True', 7.167619443952767)
('HomePlanet_Earth', 7.043189863957855)
('CryoSleep_False', 4.584489828035363)
('ShoppingMall', 3.6730891800239647)
('Deck_E', 3.6478411961075947)
('Deck_C', 3.4052524099907666)
('HomePlanet_Mars', 3.385401573341887)
('Age', 3.3560476953392624)
('Deck_F', 2.685635468323745)
('Side_P', 2.6697793517167323)
('Deck_G', 1.9082113427860747)
('Side_S', 1.8905785048364896)
('Deck_B', 1.7135331991342322)
('Destination_TRAPPIST-1e', 1.5150912879708722)
('Destination_55 Cancri e', 1.4223611194799821)
('Destination_PSO J318.5-22', 0.20906007136114482)
('VIP_False', 0.18153676778736166)
('VIP_True', 0.0933985188821309)
('Deck_D', 0.08821142245816878)
('Deck_A', 0.026629589496968576)
('Num_734', 0.02458812621833173)
('Num_974', 0.014968116181355254)
('Num_648', 0.010092579090431222)
('Num_981', 0.007262627449934468)
('Num_68', 0.00561115149932037)
====================================================================================================
Feature Importance for fold 6:
====================================================================================================
('Spa', 13.250009121215486)
('VRDeck', 11.770787147924784)
('RoomService', 9.303354252316486)
('FoodCourt', 8.486262186446721)
('HomePlanet_Earth', 7.830557582017717)
('HomePlanet_Europa', 6.560704303963645)
('CryoSleep_True', 5.172751379512729)
('Deck_E', 4.201442756759937)
('ShoppingMall', 3.9586442917328335)
('CryoSleep_False', 3.848112769027085)
('Age', 3.778849849130954)
('Deck_C', 2.8245029836601105)
('Deck_F', 2.7502611609291305)
('Deck_G', 2.57934477968851)
('Side_P', 2.3156494267753747)
('HomePlanet_Mars', 2.173264765720545)
('Side_S', 2.063940430658155)
('Destination_TRAPPIST-1e', 1.88808007865912)
('Destination_55 Cancri e', 1.6672516172299883)
('Deck_B', 1.0138271075362213)
('VIP_False', 0.4722819473325239)
('Destination_PSO J318.5-22', 0.2939098908026383)
('Deck_A', 0.29306065381430796)
('Deck_D', 0.17657759561747652)
('VIP_True', 0.16513455226753151)
('Num_981', 0.07040288922072131)
('Num_307', 0.05943951533377322)
('Num_68', 0.04471547878450104)
('Num_478', 0.04081221907251826)
('Num_648', 0.03291146246663615)

## Submission

In [6]:
def inference(df, models):
    y_pred = np.mean([model.predict_proba(df)[:, 1] for model in models], axis=0)
    y_pred = np.array(y_pred > 0.5, dtype=np.bool_)
    return y_pred

In [7]:
submission = pd.read_csv("../input/spaceship-titanic/sample_submission.csv")
submission["Transported"] = inference(test, models)
submission.to_csv("submission.csv", index=False)
submission.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01        False
2     0019_01         True
3     0021_01         True
4     0023_01         True