In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/breast-cancer-wisconsin-data/data.csv
/kaggle/input/bc-lqv-vectors/bc_vectors.csv

In [2]:
df = pd.read_csv(r'/kaggle/input/breast-cancer-wisconsin-data/data.csv')
vectors = pd.read_csv(r'/kaggle/input/bc-lqv-vectors/bc_vectors.csv')

In [3]:
vectors = vectors.drop('Unnamed: 0' , axis = 1)

In [4]:
vectors

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Tag
0,20.973181,20.876233,129.260631,1051.407209,0.116826,-0.213965,-0.146759,-0.050590,0.092739,-0.021490,...,62.846891,97.349426,955.570099,0.134537,-0.672899,-0.525515,-0.214126,0.763206,-0.104079,B
1,18.462667,-0.285799,111.503401,994.261336,0.048643,-0.166399,-0.171923,-0.059836,0.123893,0.022636,...,-2.900184,111.830280,1028.461489,0.065545,-0.419307,-0.488605,-0.050613,0.120454,-0.002231,B
2,19.008261,-23.990528,118.565524,934.910629,0.099924,0.021390,-0.163683,-0.060979,-0.204205,0.072965,...,-46.941051,129.650501,1068.639213,0.125517,0.219850,-0.326531,-0.102379,-0.174010,0.109272,B
3,18.045075,-0.516528,109.778246,946.828729,-0.091571,-0.219622,-0.246467,-0.117757,0.216279,0.013110,...,-4.003355,135.784927,1068.291170,-0.108294,-0.129007,-0.523627,-0.144443,0.143854,0.036032,B
4,18.997157,47.019326,110.268787,1011.123873,-0.152245,-0.370322,-0.255763,-0.156238,-0.097953,-0.014645,...,60.777805,99.715857,1000.524307,-0.243506,-0.912651,-0.984400,-0.450730,-0.064744,-0.078382,B
5,17.717296,6.729914,113.398642,958.770276,0.104154,0.030106,0.081353,0.097317,0.182841,0.045631,...,18.805301,117.535062,1066.670962,0.148392,-0.031664,0.135889,0.232188,0.343416,0.071768,M
6,17.925898,14.710577,113.837322,956.893434,0.086972,0.049493,-0.007122,0.058885,0.152606,0.045176,...,15.775733,112.784214,1069.158921,0.140113,0.093516,0.176843,0.151303,0.141775,0.061171,M
7,20.403179,15.215089,135.258678,1248.176169,0.146668,0.149452,0.288864,0.169304,0.125906,0.061323,...,17.848865,117.624682,1014.244333,0.247699,0.236043,0.786759,0.271044,0.312207,0.071501,M
8,29.355561,15.768806,197.057465,2692.130207,0.118155,0.146606,0.341092,0.165025,0.154746,0.054181,...,13.435559,177.031226,2181.386266,0.102890,0.071915,0.223966,0.128648,0.123299,0.046363,M
9,18.081798,30.099896,137.046186,782.334372,0.132074,0.749612,0.365041,0.339757,0.600012,0.114885,...,76.012885,224.228751,1168.960941,0.204709,3.686897,2.097917,1.405712,1.481127,0.449816,M

In [5]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [6]:
X = df.drop('diagnosis' , axis = 1)
X = X.drop('id' , axis = 1)
X = X.drop('Unnamed: 32' , axis = 1)
y = df['diagnosis'].tolist()

In [7]:
only_vector = vectors.drop('Tag', axis = 1)
only_vector.shape

(10, 30)

In [8]:
only_vector_orig = only_vector.copy()
print(only_vector_orig.shape)

(10, 30)

In [9]:
from scipy.spatial.distance import pdist, squareform
import time 
pred_list = []

start_time = time.time()

for i in range(len(X)) :
    a = X.iloc[i,:].tolist()
    
    only_vector = only_vector_orig.copy()
    only_vector.loc[only_vector.shape[0]] =a 
   
    distances = pdist(only_vector, metric='euclidean')
    dist_matrix = squareform(distances)
    
    b = np.array(dist_matrix[only_vector.shape[0] -1])[:-1]
    
    vector_number = b.argmin()
    
    prediction  = vectors.iloc[vector_number]['Tag']
    pred_list.append(prediction)
    actual = y[i]
    
end_time = time.time()

In [10]:
diff = (end_time -start_time)*1000
records = len(pred_list)

print('Processing Time per Transaction is ' ,  str(round(diff/records, 5)))

Processing Time per Transaction is  2.06428

In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, pred_list)

array([[349,   8],
       [ 37, 175]])